### ISSUE TITLE
[Bug]: `Request.formData()` never settles on larger payloads

### ISSUE THREAD

**Issue by Trve** [remix-run/remix#972] opened 2021-12-09 16:31 UTC
### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

14.17.5

### Steps to Reproduce

On the client side:
```
const submit = useSubmit();
const data = new FormData();
const data= 'abc'; // some string with 105kB length
data.append('someKey', data);
submit(data, {
	method: 'post',
	action: '/action',
});
```
On the server side:
```
export let action: ActionFunction = async ({ request }) => {
	let formData = await request.formData(); // never settles
	// this code is never reached
	return json('saved!');
};
```

### Expected Behavior

The `request.formData()` should settle with the correctly parsed form data. This should happen within a reasonable amount of time (probably some milliseconds).
This should work with any payload size which is allowed by the specs.

### Actual Behavior

The Promise returned by the `request.formData()` method never settles if the sent payload is (in my case) 105kB or larger. In my case it worked with a payload of ~3kB. I did not test any other payload sizes. But it must be something in between 3 and 105 kilobytes.

**Comment by mmarkell** [comment] 2021-12-13 17:28
+1, I have the same issue

**Comment by mmarkell** [comment] 2021-12-13 17:30
`request.formData()` is hanging for me with a 45KB payload

**Comment by mmarkell** [comment] 2021-12-13 17:41
I'm not sure what it will break in the process, but it seems like a workaround for this issue is the edit @remix-run/node/fetch.js

```
   async formData() {
-    let body = await this.clone().text();
+    const body = await this.text()
+    // Michael -- I don't know what this will break but...it works for now
+    // let body = await this.clone().text();
     return new formData.RemixFormData(body);
   }
```

**Comment by jraoult** [comment] 2022-01-30 11:47
Pretty sure this PR https://github.com/remix-run/remix/pull/1120 fixes this issue @mjackson. you might want to close it then.

**Comment by jraoult** [comment] 2022-01-31 12:55
Updated patch for 1.1.3:

```
diff --git a/fetch.js b/fetch.js
index 5ea85d9e968806a942eea27d1e0ce706d4cb7af6..c0b1173e6c1e66eb2b48779e3a44b357fc8650dd 100644
--- a/fetch.js
+++ b/fetch.js
@@ -104,7 +104,7 @@ class NodeRequest extends nodeFetch.Request {
   }
 
   clone() {
-    return new NodeRequest(this);
+    return this;
   }
 
 }
```

I feel the root cause might be how the request is cloned. I suspect the clone creates a new stream, and the original one is never "consumed" (read from), and it acts weirdly when the data is larger than a certain threshold (maybe the high watermark.)

**Comment by hollandThomas** [comment] 2022-01-31 13:14
FYI this particular piece of code seems to be replaced anyway with a move away from `node-fetch` to `undici` (no idea when it lands though):
https://github.com/remix-run/remix/pull/1687/files#diff-87ec1c3c130fe3481b9f1c542b1d8a53548882d33c73c68b894fd442d606afc0L105

For context, Node itself will include `fetch` on the basis of `undici` soonish
https://github.com/nodejs/node/pull/41749

**Comment by mjackson** [comment] 2022-02-02 18:46
Can you say a bit more about where you were running your app when you observed this behavior? @jacob-ebey has tested the file uploading behavior locally with files > 10GB and hasn't seen any issues.

In any case, we should definitely have some tests that handle large posts to make sure it works.

**Comment by Trve** [comment] 2022-02-02 19:13
I observed this behavior on a Windows 10 machine and was running the art the time latest version of Firefox developer edition.

**Comment by superherointj** [comment] 2022-02-23 21:05
I'm using Linux NixOS, node v17.5.0, and running `npm run dev`. I *think* I can observe this problem. A very larger content on a textarea won't work.

**Comment by machour** [comment] 2023-01-22 09:47
Can't reproduce this anymore on 1.11.1
If this is still failing for you, please open a new bug report and provide a repository or stackblitz showing the issue 🙏🏼

**Closed by machour** 2023-01-22 09:47 UTC
Labels: bug
