### ISSUE TITLE
Dev server crashes after reloading a certain times

### ISSUE THREAD

**Issue by juniorforlife** [remix-run/remix#6680] opened 2023-06-24 04:42 UTC
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Start dev server
2. Make changes and save
3. Hard reload the website
4. Crashes with error
Note: this doesn't happen right away but only after a dozen times of making changes and reloading. However, I've been facing this issue consistently everyday
```
Rebuilt in 110ms
[1] 
[1] <--- Last few GCs --->
[1] 
[1] [80031:0x148008000]  1931613 ms: Mark-sweep (reduce) 2594.5 (2710.1) -> 2594.5 (2672.1) MB, 436.9 / 0.0 ms  (average mu = 0.117, current mu = 0.033) last resort GC in old space requested
[1] [80031:0x148008000]  1932076 ms: Mark-sweep (reduce) 2594.5 (2672.1) -> 2594.4 (2671.9) MB, 462.6 / 0.0 ms  (average mu = 0.060, current mu = 0.000) last resort GC in old space requested
[1] 
[1] 
[1] <--- JS stacktrace --->
[1] 
[1] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[1]  1: 0x103079c84 node::Abort() [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  2: 0x103079e74 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  3: 0x1031be840 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  4: 0x1031be800 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  5: 0x103341d1c v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  6: 0x10334bcf4 v8::internal::Heap::SetUp() [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  7: 0x10331e308 v8::internal::Factory::CodeBuilder::AllocateCode(bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  8: 0x10331dbb8 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1]  9: 0x10331e7c4 v8::internal::Factory::CodeBuilder::Build() [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 10: 0x10388369c v8::internal::RegExpMacroAssemblerARM64::GetCode(v8::internal::Handle<v8::internal::String>) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 11: 0x10362dd54 v8::internal::RegExpCompiler::Assemble(v8::internal::Isolate*, v8::internal::RegExpMacroAssembler*, v8::internal::RegExpNode*, int, v8::internal::Handle<v8::internal::String>) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 12: 0x103647ea8 v8::internal::RegExpImpl::Compile(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool, unsigned int&) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 13: 0x10364768c v8::internal::RegExpImpl::CompileIrregexp(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, bool) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 14: 0x103646e48 v8::internal::RegExpImpl::IrregexpPrepare(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 15: 0x103647150 v8::internal::RegExpImpl::IrregexpExec(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::RegExpMatchInfo>, v8::internal::RegExp::ExecQuirks) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 16: 0x1036662c0 v8::internal::Runtime_RegExpExec(int, unsigned long*, v8::internal::Isolate*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 17: 0x10396a08c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 18: 0x1039c4150 Builtins_RegExpPrototypeTest [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 19: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 20: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 21: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 22: 0x10397cdc8 Builtins_ArrayForEach [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 23: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 24: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 25: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 26: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 27: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 28: 0x10fa8eaec 
[1] 29: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 30: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 31: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 32: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 33: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 34: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 35: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 36: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 37: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 38: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 39: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 40: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 41: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 42: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 43: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 44: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 45: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 46: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 47: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 48: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 49: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 50: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 51: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 52: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 53: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 54: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 55: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 56: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 57: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 58: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 59: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 60: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 61: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 62: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 63: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 64: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 65: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 66: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 67: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 68: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 69: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 70: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 71: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 72: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 73: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 74: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 75: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 76: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 77: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 78: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 79: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 80: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 81: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 82: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 83: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 84: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 85: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 86: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 87: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 88: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 89: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 90: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 91: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 92: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 93: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 94: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 95: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 96: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 97: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 98: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 99: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 100: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 101: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 102: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 103: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 104: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 105: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 106: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 107: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 108: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 109: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 110: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 111: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 112: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 113: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 114: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 115: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 116: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 117: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 118: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 119: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 120: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 121: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 122: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 123: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 124: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 125: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 126: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 127: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 128: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 129: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 130: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 131: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 132: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 133: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 134: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 135: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 136: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 137: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 138: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 139: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 140: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 141: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 142: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 143: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 144: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 145: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 146: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 147: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 148: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 149: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 150: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 151: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 152: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 153: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 154: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 155: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 156: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 157: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 158: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 159: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 160: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 161: 0x1038fdd18 Builtins_InterpreterEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 162: 0x1081096d8 
[1] 163: 0x1038fbb0c Builtins_JSEntryTrampoline [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 164: 0x1038fb7a4 Builtins_JSEntry [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 165: 0x1032ce504 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 166: 0x1032cdb98 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 167: 0x1031db224 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 168: 0x102fc9edc node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 169: 0x102fca2b0 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 170: 0x10302406c node::Environment::CheckImmediate(uv_check_s*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 171: 0x1038e5fa0 uv__run_check [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 172: 0x1038dfcfc uv_run [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 173: 0x102fca6d4 node::SpinEventLoop(node::Environment*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 174: 0x1030b3a90 node::NodeMainInstance::Run(int*, node::Environment*) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 175: 0x1030b3770 node::NodeMainInstance::Run() [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 176: 0x10304de38 node::Start(int, char**) [/Users/juniorforlife/.nvm/versions/node/v16.18.1/bin/node]
[1] 177: 0x194197e50 start [/usr/lib/dyld]
[1] env-cmd -f .env.staging remix dev exited with code SIGABRT
```

### Expected Behavior

No crashes

### Actual Behavior

Crash with error shown above

**Comment by juniorforlife** [comment] 2023-06-24 04:48
```
"dependencies": {
    "@remix-run/node": "^1.17.1",
    "@remix-run/react": "^1.17.1",
    "@remix-run/vercel": "^1.17.1",
    "axios": "^1.3.6",
    "highlight-words": "^1.2.1",
    "i18next": "^22.5.0",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-fs-backend": "^2.1.2",
    "i18next-http-backend": "^2.2.1",
    "isbot": "^3.6.8",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^12.3.1",
    "react-player": "^2.12.0",
    "remix-i18next": "^5.1.1",
    "zustand": "^4.3.8"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.17.1",
    "@remix-run/eslint-config": "^1.17.1",
    "@remix-run/serve": "^1.17.1",
    "@types/react": "^18.0.35",
    "@types/react-dom": "^18.0.11",
    "concurrently": "^8.0.1",
    "cross-env": "^7.0.3",
    "eslint": "^8.38.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.2.7",
    "tailwindcss": "^3.3.1",
    "typescript": "^4.9.5"
  },
  "engines": {
    "node": ">=14"
  }
```

**Comment by pcattori** [comment] 2023-06-26 17:54
This is hardware dependent, so I cannot reproduce locally. Could you provide more details about your memory usage?

How much RAM does your machine have? How much RAM is free/available _before_ you run the Remix dev server? Does memory usage increase predictably every rebuild?

**Comment by juniorforlife** [comment] 2023-07-07 02:09
seems like this problem is gone after I upgraded to 1.18.1

**Comment by pcattori** [comment] 2023-07-07 14:40
Closing, but we can reopen if this comes up again.

**Closed by pcattori** 2023-07-07 14:40 UTC
Labels: package:dev, bug:unverified
