### ISSUE TITLE
[Feature]: Component Level CSS

### ISSUE THREAD

**Issue by Mokshit06** [remix-run/remix#571] opened 2021-11-24 08:25 UTC
### What is the new or updated feature that you are suggesting?

It would be great for Remix to support component level CSS. That way you could import a CSS file in the component's file itself and remix, while generating the `assets.json` file could evaluate which stylesheets are being imported in each route, similar to what it does for js imports to prevent waterfall. These stylesheets could then be rendered in the `Links` component by Remix. This would still prevent the case where all CSS gets bundled into a large file, since esbuild would consider each route as its own separate entry point and each route CSS file will only include the CSS of the components that esbuild thinks are required further down the component tree.component-level

### Why should this feature be included?

The current model suggests importing the CSS file for each route on its respective page and then passing it to the links function. That works fine for apps in which you know which component is being rendered where, but it doesn't prevent you from class name clashes. Imagine a button component that is being used in 2 routes. The way it would work currently is either to add it to the global CSS file which would bloat it for the pages that aren't rendering the button, or create a separate button.css file which would be manually imported in each route that uses it. The issues with this approach are that:-
1. If we were to separate each component's CSS file and load it into the routes that use it, it would require a lot of CSS files to be loaded and it could be difficult to later evaluate which CSS file is being used in which component
2. This wouldn't scale very well as your components won't be aware of where they're getting their CSS from and would also cause a lot of friction, since now whenever I add the `Button` component to another route, I've to make sure to import the `button.css` file in that route. The route approach could work for cases where all your markup is present in the route file itself, but for anything a bit more complex that isn't using an atomic CSS framework like tailwind, I think it could be a problem

**Comment by machour** [comment] 2022-03-18 18:47
Duplicate of #493

**Closed by machour** 2022-03-18 18:47 UTC
Labels: duplicate
