### ISSUE TITLE
Tailwind: FoUC with unstable_createViteServer and unstable_loadViteServerBuild

### ISSUE THREAD

**Issue by manzaloros** [remix-run/remix#8019] opened 2023-11-15 17:40 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Run `npx create-remix@latest --template remix-run/templates/express`.

2. Install Tailwind as per the [instructions here](https://remix.run/docs/en/main/future/vite#enable-tailwind-via-postcss).

3. Use Tailwind to style a `div` on the existing page. It works correctly, with **no flash of unstyled content**.

4. Now, use a custom server as per the [instructions on the same page.](https://remix.run/docs/en/main/future/vite#migrating-from-a-custom-server). 
5. Observe that the page will **now have a flash of unstyled content**.

### Expected Behavior

I expect there to be no flash of unstyled content using a custom server with `unstable_createViteServer` and `unstable_loadViteServerBuild` just like using Vite out of the box.

### Actual Behavior

There is a flash of unstyled content when using a custom server (`unstable_createViteServer` and `unstable_loadViteServerBuild`) and the [instructions from here.](https://remix.run/docs/en/main/future/vite#enable-tailwind-via-postcss)

**Comment by kiliman** [comment] 2023-11-15 17:46
You're probably getting React hydration errors. I recommend updating to the latest React 18.3 canary versions.

You can see an example repo here:

https://github.com/kiliman/remix-vite-2.2.0

**Comment by pcattori** [comment] 2023-11-15 19:27
Duplicate of #7878

**Closed by pcattori** 2023-11-15 19:27 UTC
Labels: bug:unverified
