### ISSUE TITLE
[Bug]: Larger files are not readable via UploadHandler

### ISSUE THREAD

**Issue by Ehesp** [remix-run/remix#1164] opened 2021-12-20 11:54 UTC
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [X] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.1.0

### Steps to Reproduce

Upload a file using the `Form` component.

Add a custom `UploadHandler`:

```ts
export const action: ActionFunction = async ({ request }) => {
  const handler: UploadHandler = async ({ name, stream }) => {
    if (name === 'foo') {
      const buff = await new Promise<Buffer>(async (resolve, reject) => {
        const chunks: any = [];

        stream.on("readable", () => {
          let chunk;
          while (null !== (chunk = stream.read())) {
            console.log('chunk...', chunk);
            chunks.push(chunk);
          }
        });

        stream.on("end", () => {
          console.log('end');
          return resolve(Buffer.concat(chunks));
        });
      });
    }
  }

  const form = await unstable_parseMultipartFormData(request, handler);
  // ..
};
```

### Expected Behavior

The Readable stream should trigger the `end` event once consumed.

### Actual Behavior

For small files (e.g. 10kb) the stream is handled correctly, and the `end` event is called. However, for larger files (90kb fails), a single chunk is logged, but then nothing else happens. The `end` event is never called.

Am I doing something wrong? I just cannot figure this out. The handling of the stream example is even taken from the nodejs docs.

**Comment by ralrom** [comment] 2021-12-20 13:14
I'll add the comment here because it's more relevant to this issue:

I'm having issues uploading larger images. After searching on the Discord server, I found this comment from cmwoodall:

> I've been having the same issue when attempting to upload files... it hangs after the first chunk for files that are greater than one chunk in size. I actually had file uploads working fine in 1.0.6 by backporting the server bits (processMultipartRequest, UploadHandler, etc) and thus figured something else must have changed in the most recent release. After a bit of debugging I think I've found the source of the problem -- a new request.clone() call that happens with callRouteAction() (https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/data.ts#L38). When I comment the request.clone() and pass along the original request everything seems to work great. Not my area of expertise but apparently cloning requests in node-fetch can cause issues (https://github.com/node-fetch/node-fetch#custom-highwatermark) and it looks like the highWaterMark is being set earlier in the request but perhaps doesn't affect subsequent clones 🤷‍♂️

**Comment by Ehesp** [comment] 2021-12-20 13:33
I can confirm removing `request.clone()` fixes this issue. Not sure what impact that has though on anything else.

**Comment by aaronksaunders** [comment] 2021-12-23 20:44
ran into the same issue and the fix recommended by @ralrom solved my issue

**Comment by kimile** [comment] 2021-12-27 20:17
Hey @aaronksaunders, can you share the process that you used to apply that patch? I'm not used to patching dependencies in the project but I'm actually struggling with the same problem

**Comment by jacob-ebey** [comment] 2021-12-27 20:20
> Hey @aaronksaunders, can you share the process that you used to apply that patch? I'm not used to patching dependencies in the project but I'm actually struggling with the same problem

For now, make the single line change required in node_modules/@remix-run/server-runtime/server.js, then run `npx patch-package @remix-run/server-runtime` This will create a patch file in `patches/xxx` Add `npx patch-package` as a post install script.

**Comment by Mad-Kat** [comment] 2021-12-31 13:19
Just so that we have it written down.

I had exactly the same issue with large form-data besides blobs. I have a form that has around 20KB split up in a list and I see exactly the same stuff that you see with the blob and it was fixed the same way.

Thanks for posting it and the solution to it as well.

**Comment by anges244** [comment] 2022-01-05 16:00
> For now, make the single line change required in node_modules/@remix-run/server-runtime/server.js,

Just stumbled upon this problem. Cannot find the request.clone() you guys mention, to patch the file. @aaronksaunders sorry for bothering but what to change exactly there?

**Comment by aaronksaunders** [comment] 2022-01-05 16:12
I made a mistake in the last comment, it is data.js not server.js

line 37 in For now, make the single line change required in **node_modules/@remix-run/server-runtime/data.js,**

```
   try {
     result = await action({
-      request: stripDataParam(stripIndexParam(request.clone())),
+      request: stripDataParam(stripIndexParam(request)),
       context: loadContext,
       params: match.params
     });
```

https://discord.com/channels/770287896669978684/921148525948067850/923329464719536239

**Comment by anges244** [comment] 2022-01-05 16:14
Thank you so much Aaron!

**Comment by timonweb** [comment] 2022-01-14 13:40
just stumbled upon the same issue and the fix solves it, but you can't hack it like that and keep it in *node_modules*, it'd only work in your environment and isn't reproducible. Will this fix go into remix? Is there a PR for it?

**Comment by ralrom** [comment] 2022-01-14 14:09
Hey @timonweb if you look at the answers above, you can use patch-package to apply the fix in your other environments

https://github.com/remix-run/remix/issues/1164#issuecomment-1001735640

**Comment by timonweb** [comment] 2022-01-14 14:25
@ralrom missed that, nice, tx!

**Comment by Ehesp** [comment] 2022-01-14 14:41
Probably worth mentioning I personally haven't made a PR since I'm not sure if there is any underlying consequences of removing the `clone()`. I've not seem it in my own app, but it's not exactly a big one nor important.

**Comment by edmbn** [comment] 2022-01-14 15:50
Any idea to make sure any maintainer read this and checks if solution is valid for a PR?

**Comment by Alazoral** [comment] 2022-02-01 04:41
@aaronksaunders Thanks so much, that really saved my bacon. Definitely think this needs to be patched in, it seems like this would interfere with all kinds of uploads.

**Comment by binajmen** [comment] 2022-02-01 10:19
> Any idea to make sure any maintainer read this and checks if solution is valid for a PR?

Should a PR be created to at least get this patch to the agenda and be challenged? I'm not comfortable with the whole PR process but I'd really appreciate if someone could take care of it 🙏

**Comment by machour** [comment] 2022-03-17 23:49
Fixed by #1766

**Closed by machour** 2022-03-17 23:49 UTC
Labels: bug

**Comment by delivey** [comment] 2023-07-25 11:21
Still running into this issue on a Remix version where `request.clone()` doesn't exist. Any pointers?

**Comment by kiliman** [comment] 2023-07-25 13:49
@delivey Since this issue has been closed for over a year, can you create a new issue with more details? Thanks!
