### ISSUE TITLE
[Bug]: File Upload API is incomplete/not working

### ISSUE THREAD

**Issue by shadyendless** [remix-run/remix#1139] opened 2021-12-18 19:53 UTC
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

The `parseMultipartFormData`, `createMemoryUploadHandler`, and `createFileUploadHandler` are all still behind the `unstable_` prefix. If you attempt to use them in their current state, the route with that action throws an error.

I have created a StackBlitz showcasing this issue, which can be found here: [https://stackblitz.com/edit/node-wg6zks?file=app/routes/index.tsx](https://stackblitz.com/edit/node-wg6zks?file=app/routes/index.tsx)

### Expected Behavior

The `parseMultipartFormData`, `createMemoryUploadHandler`, and `createFileUploadHandler` methods are not behind the `unstable_` prefix, and you are able to upload files and access them inside of the route's action.

### Actual Behavior

Using any of the unstable methods causes the page to error out with the following:

```
TypeError: Cannot read properties of undefined (reading 'root')
    at RemixRoute (https://node-wg6zks--3000.local.webcontainer.io/build/_shared/chunk-TKYDUCAE.js:4711:19)
    at renderWithHooks (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:11068:26)
    at mountIndeterminateComponent (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:13188:21)
    at beginWork (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:13975:22)
    at HTMLUnknownElement.callCallback2 (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:3678:22)
    at Object.invokeGuardedCallbackDev (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:3703:24)
    at invokeGuardedCallback (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:3737:39)
    at beginWork$1 (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:17084:15)
    at performUnitOfWork (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:16315:20)
    at workLoopSync (https://node-wg6zks--3000.local.webcontainer.io/build/entry.client-LCRSCB77.js:16266:13)
```

**Comment by shadyendless** [comment] 2021-12-18 20:34
Following up on this.

I got it to work by moving the `unstable_ createMemoryUploadHandler` into the `ActionFunction`. I am following the pseudo-documentation laid out by @kentcdodds here: https://github.com/remix-run/remix/pull/383#issuecomment-972373927

I am not sure if this API is still supposed to be `unstable_` or not, though, so leaving this open so that it can either be closed or resolved.

**Comment by benwis** [comment] 2021-12-18 21:02
I'll add that the UploadHandler type is not exported from Remix as far as I can tell.

**Comment by ralrom** [comment] 2021-12-19 18:51
I'm having issues uploading larger images. After searching on the Discord server, I found this comment from **cmwoodall**:

> I've been having the same issue when attempting to upload files... it hangs after the first chunk for files that are greater than one chunk in size.  I actually had file uploads working fine in 1.0.6 by backporting the server bits (processMultipartRequest, UploadHandler, etc) and thus figured something else must have changed in the most recent release.  After a bit of debugging I think I've found the source of the problem -- a new request.clone() call that happens with callRouteAction() (https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/data.ts#L38).  When I comment the request.clone() and pass along the original request everything seems to work great.   Not my area of expertise but apparently cloning requests in node-fetch can cause issues (https://github.com/node-fetch/node-fetch#custom-highwatermark) and it looks like the highWaterMark is being set earlier in the request but perhaps doesn't affect subsequent clones 🤷‍♂️

Here's a link to the comment: https://discord.com/channels/770287896669978684/921148525948067850/921926697262141460

**Comment by jansedlon** [comment] 2021-12-19 18:55
> I'm having issues uploading larger images
Just noticed that as well

**Comment by Ehesp** [comment] 2021-12-20 13:23
> @benwis I'll add that the UploadHandler type is not exported from Remix as far as I can tell.

Got a PR up for that https://github.com/remix-run/remix/pull/1133

**Comment by joms** [comment] 2021-12-21 22:36
It also feels like the support for multiple files are lacking: I am uploading multiple files, which works fine. I am also running them through a custom `uploadHandler` to proxy the files to AWS S3, which also works flawlessly. However when returning information from the `uploadHandler`, I only get the result for the last file:

```typescript
const uploadHandler: UploadHandler = async ({ name, stream, mimetype }) => {
    if (name !== "file") {
        stream.resume();
        return;
    }

    const key = crypto.randomUUID();

    const upload = new LibStorage.Upload({
        client: s3Client,
        params: {
            Bucket: "remix-bucket",
            Key: key,
            Body: stream,
            ContentType: mimetype,
        },
        queueSize: 3,
    });

    try {
        await upload.done();
    } catch (error) {
        return JSON.stringify({ success: false, key, error });
    }

    return JSON.stringify({ success: true, key, error: null });
};

const uploadBody = await unstable_parseMultipartFormData(request, uploadHandler);
console.log(Object.fromEntries(uploadBody));
```

This outputs
```javascript
{
  file: '{"success":true,"key":"e35d4128-4391-4aa7-a053-d532e3b4d80a","error":null}'
}
```

What I'd expect is something like
```javascript
{
    file: [
        '{"success":true,"key":"8ec8732e-b26f-4de0-83c2-5cceb5ed5ae6","error":null}',
        '{"success":true,"key":"4a7fb688-746f-4d26-a971-c80908ef5550","error":null}'
    ]
}
```

I've also had some issues submitting files through `useSubmit`. I made this work using a ref connected to the file input, however I haven't tried with multiple files yet.

**Comment by airjp73** [comment] 2021-12-21 22:50
@joms, `Object.fromEntries` is probably the culprit there since all the files have the same name/key. `FormData` supports multiple values for a single key, but `Object.fromEntries` will just take the last one. Does it work if you do this?
```js
const uploadBody = await unstable_parseMultipartFormData(request, uploadHandler);
console.log(uploadBody.getAll('file'));
```

**Comment by joms** [comment] 2021-12-21 22:55
> @joms, `Object.fromEntries` is probably the culprit there since all the files have the same name/key. `FormData` supports multiple values for a single key, but `Object.fromEntries` will just take the last one. Does it work if you do this?

You are absolutely right! That totally did the trick. I know I at some point thought for myself that I should use `uploadBody.getAll` and then the brain just went "nah, go do it with Object.fromEntries in stead!" 🤦

**Comment by binajmen** [comment] 2022-01-31 16:48
I'm going to implement image uploading as well. What is the current status of the situation explained above? Did the patch work in your production environment? Any feedback from your experience I should take into account? 🙏

**Comment by QuentinWidlocher** [comment] 2022-02-01 09:49
> I'm going to implement image uploading as well. What is the current status of the situation explained above? Did the patch work in your production environment? Any feedback from your experience I should take into account? pray

I didn't use the patch but I saw a reply in the Discord thread that said the `.clone()` patch ([seen here](https://github.com/remix-run/remix/issues/1164#issuecomment-1005864530)) actually creates problems down the line so I'd consider waiting for a proper implementation.

That said, I don't think this problem is very high in Remix's backlog unfortunately.

**Comment by joms** [comment] 2022-02-01 10:25
> I'm going to implement image uploading as well. What is the current status of the situation explained above? Did the patch work in your production environment? Any feedback from your experience I should take into account? 🙏

I don't know how prioritised this problem is at the time. Currently I am using a patch in production which works just fine for me. Looking forward to the day this actually is solved in Remix though.

```
// patches/@remix-run+server-runtime+1.1.1.patch
diff --git a/node_modules/@remix-run/server-runtime/data.js b/node_modules/@remix-run/server-runtime/data.js
index 5f1fe2e..60f1b3b 100644
--- a/node_modules/@remix-run/server-runtime/data.js
+++ b/node_modules/@remix-run/server-runtime/data.js
@@ -34,7 +34,7 @@ async function callRouteAction({
 
   try {
     result = await action({
-      request: stripDataParam(stripIndexParam(request.clone())),
+      request: stripDataParam(stripIndexParam(request)),
       context: loadContext,
       params: match.params
     });
```

**Comment by binajmen** [comment] 2022-02-01 10:29
Yes, I'm using the patch too. Works like a charm. Although I'm just worried there is no PR – or is there one? – in order to (1) create awareness on the Remix team side, and (2) get a confirmation there are no side effects by removing `.clone()` from the equation.

Perhaps (most probably?) they are aware of the issue. But having it on the agenda – that is having a pending PR? – wouldn't be a waste of time, isn't it? Unfortunately, I'm not comfortable with the PR process/flow..

**Comment by joms** [comment] 2022-02-01 10:36
> Perhaps (most probably?) they are aware of the issue. But having it on the agenda – that is having a pending PR? – wouldn't be a waste of time, isn't it? Unfortunately, I'm not comfortable with the PR process/flow..

I think they are aware, the problem is I don't think this is the actual solution. I feel like there's more issues down the line, as for instance `.clone()` doesn't work when trying to handle the request before the file which leads me to the biggest issue: 

I haven't been able to handle the request and do the upload based on the request data. Currently I have to do the upload first and then guess what to do with with the file...

**Comment by CanRau** [comment] 2022-02-13 02:26
Also I'm curious about the return shape of custom `uploadHandler` which requires to stringify a custom object as it'd complain that keys from `File` are missing

like in the example from https://github.com/remix-run/remix/issues/1139#issuecomment-999140652

```tsx
return JSON.stringify({ success: true, key, error: null });
```

Is there a reason we can't return custom objects? Have it maybe generic so we can pass in a return type?

**Comment by CanRau** [comment] 2022-02-14 03:32
Uuh of course why didn't I think of this 🤦🏻‍♂️😄
Thanks for explanation 🙏

**Comment by machour** [comment] 2022-04-12 12:44
The original issue reported by @shadyendless was fixed in the documentation in https://github.com/remix-run/remix/pull/2704, so I'm closing this issue.

Feel free to open a new issue if something else is going wrong with files uploads

**Closed by machour** 2022-04-12 12:44 UTC
Labels: bug
