### ISSUE TITLE
remix dev v2 unexpectedly clears the console

### ISSUE THREAD

**Issue by garth** [remix-run/remix#6838] opened 2023-07-14 16:13 UTC
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Running the following command

```
remix dev --no-restart -c "./src/server/index.js"
```

will clear the console right before it outputs

```
💿  remix dev
```

### Expected Behavior

The console should not be cleared.

### Actual Behavior

The console console is cleared, also removing output from other tasks running.

**Comment by pcattori** [comment] 2023-07-14 16:36
Duplicate of #6709

**Closed by pcattori** 2023-07-14 16:36 UTC
Labels: bug:unverified
