### ISSUE TITLE
RemixErrorBoundary caught in infinite crash loop when exception thrown in root handler in browser

### ISSUE THREAD

**Issue by ngbrown** [remix-run/remix#2118] opened 2022-02-24 22:29 UTC
### What version of Remix are you using?

1.2.1

### Steps to Reproduce

Add default error handler in `root.tsx` https://remix.run/docs/en/v1/guides/errors#root-error-boundary

Add code that will throw in the browser in the root `index.tsx`:

```tsx
export default function Index() {
  if (typeof window !== "undefined") {
    (0 as any).missingFunction();
  }

  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <h1>Hi</h1>
    </div>
  );
}
```

### Expected Behavior

Display a blank page and "Oh No" in the title without freezing up the browser tab with endless console errors.

### Actual Behavior

```
entry.client-KIPMOS4E.js:7764 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at appendChildToContainer (http://localhost:3000/build/entry.client-KIPMOS4E.js:7764:24)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:3000/build/entry.client-KIPMOS4E.js:15326:15)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:3000/build/entry.client-KIPMOS4E.js:15333:15)
    at commitPlacement (http://localhost:3000/build/entry.client-KIPMOS4E.js:15313:13)
    at commitMutationEffects (http://localhost:3000/build/entry.client-KIPMOS4E.js:16675:17)
    at HTMLUnknownElement.callCallback2 (http://localhost:3000/build/entry.client-KIPMOS4E.js:3680:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/build/entry.client-KIPMOS4E.js:3705:24)
    at invokeGuardedCallback (http://localhost:3000/build/entry.client-KIPMOS4E.js:3739:39)
    at commitRootImpl (http://localhost:3000/build/entry.client-KIPMOS4E.js:16520:17)
    at unstable_runWithPriority (http://localhost:3000/build/entry.client-KIPMOS4E.js:351:20)
appendChildToContainer @ entry.client-KIPMOS4E.js:7764
insertOrAppendPlacementNodeIntoContainer @ entry.client-KIPMOS4E.js:15326
insertOrAppendPlacementNodeIntoContainer @ entry.client-KIPMOS4E.js:15333
commitPlacement @ entry.client-KIPMOS4E.js:15313
commitMutationEffects @ entry.client-KIPMOS4E.js:16675
callCallback2 @ entry.client-KIPMOS4E.js:3680
invokeGuardedCallbackDev @ entry.client-KIPMOS4E.js:3705
invokeGuardedCallback @ entry.client-KIPMOS4E.js:3739
commitRootImpl @ entry.client-KIPMOS4E.js:16520
unstable_runWithPriority @ entry.client-KIPMOS4E.js:351
runWithPriority$1 @ entry.client-KIPMOS4E.js:8477
commitRoot @ entry.client-KIPMOS4E.js:16441
performSyncWorkOnRoot @ entry.client-KIPMOS4E.js:16006
(anonymous) @ entry.client-KIPMOS4E.js:8517
unstable_runWithPriority @ entry.client-KIPMOS4E.js:351
runWithPriority$1 @ entry.client-KIPMOS4E.js:8477
flushSyncCallbackQueueImpl @ entry.client-KIPMOS4E.js:8513
flushSyncCallbackQueue @ entry.client-KIPMOS4E.js:8503
unbatchedUpdates @ entry.client-KIPMOS4E.js:16084
legacyRenderSubtreeIntoContainer @ entry.client-KIPMOS4E.js:18579
hydrate2 @ entry.client-KIPMOS4E.js:18628
(anonymous) @ entry.client-KIPMOS4E.js:18790
```

```
2entry.client-KIPMOS4E.js:14603 The above error occurred in the <ErrorBoundary> component:

    at ErrorBoundary (http://localhost:3000/build/root-ME527SWU.js:23:26)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:878:5)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:2423:3)
    at Routes2 (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:2406:7)
    at Router (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:218:15)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:953:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:878:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:2303:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-WBC6FA6Y.js:2720:27)

React will try to recreate this component tree from scratch using the error boundary you provided, RemixErrorBoundary.
logCapturedError @ entry.client-KIPMOS4E.js:14603
update.payload @ entry.client-KIPMOS4E.js:14634
getStateFromUpdate @ entry.client-KIPMOS4E.js:9093
processUpdateQueue @ entry.client-KIPMOS4E.js:9192
updateClassInstance @ entry.client-KIPMOS4E.js:9757
updateClassComponent @ entry.client-KIPMOS4E.js:12945
beginWork @ entry.client-KIPMOS4E.js:13993
beginWork$1 @ entry.client-KIPMOS4E.js:17074
performUnitOfWork @ entry.client-KIPMOS4E.js:16317
workLoopSync @ entry.client-KIPMOS4E.js:16268
renderRootSync @ entry.client-KIPMOS4E.js:16243
performSyncWorkOnRoot @ entry.client-KIPMOS4E.js:15983
(anonymous) @ entry.client-KIPMOS4E.js:8517
unstable_runWithPriority @ entry.client-KIPMOS4E.js:351
runWithPriority$1 @ entry.client-KIPMOS4E.js:8477
flushSyncCallbackQueueImpl @ entry.client-KIPMOS4E.js:8513
flushSyncCallbackQueue @ entry.client-KIPMOS4E.js:8503
unbatchedUpdates @ entry.client-KIPMOS4E.js:16084
legacyRenderSubtreeIntoContainer @ entry.client-KIPMOS4E.js:18579
hydrate2 @ entry.client-KIPMOS4E.js:18628
(anonymous) @ entry.client-KIPMOS4E.js:18790
```

![Screenshot - 2022-02-24_15-11-15](https://user-images.githubusercontent.com/228987/155618145-4734fb71-a20d-4e31-bef4-9a21b110cb69.png)

![Screenshot - 2022-02-24_15-11-58](https://user-images.githubusercontent.com/228987/155618155-b2135d17-c0f7-419a-be2e-c083ff4ff480.png)

**Comment by machour** [comment] 2022-03-23 22:00
Duplicate of #1678

**Closed by machour** 2022-03-23 22:00 UTC
Labels: duplicate, bug:unverified
