### ISSUE TITLE
`request.formData()` fails when using an express server with remix

### ISSUE THREAD

**Issue by ryan-snyder** [remix-run/remix#3616] opened 2022-06-30 02:24 UTC
### What version of Remix are you using?

latest

### Steps to Reproduce

1. setup express server to use with remix with `express.urlencoded()` and `express.json()`
2.  create a basic form with an ActionFunction to view the formdata

### Expected Behavior

`request.formData()` returns the data that was submitted to the form. 

### Actual Behavior

formdata is empty when using an express server, since express requests don't conform to the fetch api. 

While I will admit that this is perhaps not a bug, I do think that since we assume that all requests (at least in ActionFunctions) conform to the fetch api that `request.formData()` should work? However, this could be a feature request rather than a bug. 

A possible solution is to adjust the createRequestHandler for express to add formdata?

**Comment by kiliman** [comment] 2022-06-30 14:04
Can you show your code? This should work regardless of adapter. The adapters convert all host-specific request/response to native Request/Response objects for Remix.

```js
export const action: ActionFunction = async ({ request }) => {
  const formData = await request.formData();
  return json({});
};
```

**Comment by ryan-snyder** [comment] 2022-07-01 02:06
Sure. I have a playground setup on a fork of remix. 
For the server I have:

```
const app = express();
app.use(express.static("public"));
app.use(morgan("tiny"));
app.use(express.urlencoded({
  extended: true
}))
app.use(express.json());

const MODE = process.env.NODE_ENV;
const BUILD_DIR = path.join(process.cwd(), "build");

app.all(
  "*",
  MODE === "production"
    ? createRequestHandler({ build: require(BUILD_DIR) })
    : (...args) => {
        purgeRequireCache();
        let requestHandler = createRequestHandler({
          build: require(BUILD_DIR),
          mode: MODE,
        });
        return requestHandler(...args);
      }
);
``` which i just borrowed from the default remix playground template. `express.json()` and `express.urlencoded()` is there because I was testing stuff. Same behaviour with or without.

For remix, my route looks like this:

```
import { ActionFunction } from "@remix-run/node";
import { Form} from "@remix-run/react";

export const action: ActionFunction = async ({ request }) => {
    let formData = await request.formData();
    const name = formData.get('name');
    const desc = formData.get('description');
    console.log(name);
    console.log(desc);
    return { }
  };

export default function Slug() {
    
    return (
        <Form method="post">
            <label><input name="name" type="text" /></label>
            <label><textarea name="description"></textarea></label>
            <button type="submit">Create</button>
        </Form>
    );
}
```
Both name and description are null, and formData is empty.

**Comment by ryan-snyder** [comment] 2022-07-01 02:20
And logging it where the request is converted to a remix request also gives null:

```
 let request = createRemixRequest(req);
      let loadContext = getLoadContext?.(req, res);
      try {
        const formData = await request.formData();
        console.log(formData.get('name'));
      } catch(e) {

      }```

**Comment by ryan-snyder** [comment] 2022-07-01 02:42
I'm not familiar with how remix's web-fetch works but taking a super quick look at the Request constructor, for the body, it does:
```Javascript
const inputBody = init.body != null
			? init.body
			: (isRequest(info) && info.body !== null)
			? clone(info)
			: null;

		// eslint-disable-next-line no-eq-null, eqeqeq
		if (inputBody != null && (method === 'GET' || method === 'HEAD')) {
			throw new TypeError('Request with GET/HEAD method cannot have body');
		}

		super(inputBody, {
			size: init.size || settings.size || 0
		});
```
which is called from `return new NodeRequest(url.href, init);` in `createRemixRequest` where `init.body` is set to the request

But the problem is that an express request doesn't have form data. If you do `request.formData()` on an express request it won't work. 

I could be looking at the wrong places, but I don't see anywhere where the adaptor add's formData to an express request when necessary

**Comment by ryan-snyder** [comment] 2022-07-01 09:24
Also, I'm curious why we set the request body to the entire express request? I guess because depending on how an express server is set up, the express request won't have a body?

```Javascript

if (req.method !== "GET" && req.method !== "HEAD") {
      init.body = req;
  }
```

**Comment by kiliman** [comment] 2022-07-01 15:24
Wow, I'm really not seeing that behavior at all. Can you share the code? This would be a major regression if it didn't work.

**Comment by ryan-snyder** [comment] 2022-07-02 22:24
So I figured out that the problem is using `express.urlencoded` and/or `express.json()` on the express server. 
See https://github.com/ryan-snyder/remix-express-formdata
if you comment out `express.urlencoded` and `express.json()` it works, but with them, it doesn't. 
Not sure if thats expected or...?

**Comment by ryan-snyder** [comment] 2022-07-04 02:10
Correction: it's actually just `express.urlencoded`. I actually can't remember why I had that enabled, I think it was a carryover from my express server before transitioning to remix. If this expected, its fine.

**Comment by kiliman** [comment] 2022-07-04 21:24
Anything on the Express server that reads the body will cause issues since the body can only be read once.

**Comment by diogob** [comment] 2022-07-15 14:51
I have reproduced the issue using the netlify adapter and sending an empty form. Please let me know if I should open a separate issue.
The first item on the stack trace seems to be the same:
```
TypeError: Could not parse content as FormData.
    at toFormData ( ... /@remix-run/web-fetch/src/utils/form-data.js:115:11)
```
I'm using remix 1.6.5, there is [a repo to reproduce the problem](https://github.com/diogob/remix-formdata-empty-form).

**Comment by khowling** [comment] 2022-09-05 21:01
I'm 1hr into remix, excited about the Form handling.  running create-remix with express & following the examples [here](https://remix.run/docs/en/v1/guides/data-writes#html-form-post) hitting empty form Data, that googles to this open issue.  I guess remix is just providing a server route hook but not decorating express's `request`, so we need to install the appropriate middleware & handle the request body rarther than follow the code in the example?

**Comment by sergiodxa** [comment] 2022-09-05 21:49
@khowling `request.formData()` works regardless of the server and you don't need to add any middleware to Express to make it work, actually if you add body-parser to Express it will stop working on Remix because the body of a request can only be read once.

Are you sure your FormData comes empty? If you did `console.log(formData)` and saw in your terminal this `FormData {}` as if it was an empty object, that's expected, FormData is a data structure not a plain object, you need to do `formData.get("the name of an input")` to access the data.

**Comment by flappyBug** [comment] 2022-10-09 10:06
I introduced remix to a legacy express project. The app already has some middleware parsing the incoming stream body globally. It will be great if the express adapter can handle this scenario. One possible solution is to decode the parsed body based on the content-type header, then pass the readable stream from decoded string to the body here.

https://github.com/remix-run/remix/blob/main/packages/remix-express/server.ts#L111-L113

**Comment by RotrixLOL** [comment] 2022-12-11 17:32
> @khowling `request.formData()` works regardless of the server and you don't need to add any middleware to Express to make it work, actually if you add body-parser to Express it will stop working on Remix because the body of a request can only be read once.
> 
> Are you sure your FormData comes empty? If you did `console.log(formData)` and saw in your terminal this `FormData {}` as if it was an empty object, that's expected, FormData is a data structure not a plain object, you need to do `formData.get("the name of an input")` to access the data.

Jeez, thank you very much!

**Comment by brophdawg11** [comment] 2023-05-05 17:19
I'm going to close this out since it's not a bug - the body can only be read once so if an express middleware consumes it first, it will break Remix's ability to consume it.

**Closed by brophdawg11** 2023-05-05 17:19 UTC
Labels: bug:unverified
