### ISSUE TITLE
[Vite plugin] Livereload with Tailwind is not working

### ISSUE THREAD

**Issue by rodolphoasb** [remix-run/remix#7853] opened 2023-11-01 03:39 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Just spin up the Vite example and install Tailwind.

Here's a public repo with the error:
https://github.com/rodolphoasb/vite-remix-tailwind

Here's a video of the error:
https://www.loom.com/share/281c402c46ce42af84f279a4750f8496?sid=e08a36f6-5d9d-4a61-a97a-a05a44f30d18

### Expected Behavior

The live reload should work, updating the new tailwind style.

### Actual Behavior

I need to reload the page to see the new style applied to the project.

**Comment by izznatsir** [comment] 2023-11-01 06:29
I tried it inside a Github Codespace and it works.

**Comment by drobson03** [comment] 2023-11-01 06:45
This seems like a hydration error. When I run the repro repo while having Chrome extensions enabled, I get hydration errors on page load and HMR does not work for Tailwind. Additionally, if I change the text of an element in the index route (and not a className), the generated CSS is removed (even when unchanged) but the actual text still updates.

If I try all this without any extensions loaded/in an incognito window, it works perfectly.

**Comment by rodolphoasb** [comment] 2023-11-01 14:03
@drobson03, you are correct! I think it's more related to hydration, and running it in incognito does workaround the error. Btw, there's no error in the console or terminal.

**Comment by marbemac** [comment] 2023-11-01 20:00
I also couldn't reproduce locally. Are either of you able to narrow down which extension causes the issue? I have react dev tools, so it's not that.

**Comment by drobson03** [comment] 2023-11-01 23:05
For me, it seems to be [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh). The hydration mismatch is happening in `<head>`.

**Comment by rodolphoasb** [comment] 2023-11-01 23:17
For me, it was [Apollo Client Devtools](https://chrome.google.com/webstore/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm)

**Comment by kiliman** [comment] 2023-11-01 23:36
React hydration issues will be fixed in v18.3. If you update to the canary version (stable enough for Next.js), then it will resolve the hydration error.

**Comment by haardikk21** [comment] 2023-11-02 14:10
Had the same issue. It was the [Argent X](https://chrome.google.com/webstore/detail/argent-x/dlcobpjiigpikoobohmabehhmhfoodbb) extension.

**Comment by rodolphoasb** [comment] 2023-11-02 15:55
Additional information, even after having removed the "Apollo Client Devtool" extension, I am still seeing the error, but now it occurs on 70% of the pages, while the rest works normally.

**Comment by hta218** [comment] 2023-11-08 09:07
Confirm that disable extensions temporarily resolve this issue!

**Comment by underfisk** [comment] 2023-11-17 01:32
I do observe the same issue, even after upgrading to `2.3.0`. If the page is running in `incognito` window or chrome extensions are disabled, it works as intended but in a normal workflow it doesn't seem to be

**Comment by RobEasthope** [comment] 2023-12-11 18:36
I'd recommend double checking the console for markup errors. Some Radix UI example markup had a `<button />` nested within a `<button />`.

Fixing that solved the HMR issue entirely 🤷‍♂️

**Comment by underfisk** [comment] 2023-12-11 19:17
> [Bug]: Live Reload not working. #1601

At least on my use case i did not use Radix at all and still observed this, just plain tailwind examples

**Comment by roonie007** [comment] 2024-01-01 00:18
same as @underfisk 

Tailwind integration, with this simple page `_index.tsx`

```tsx
import type { MetaFunction } from '@remix-run/node';

export const meta: MetaFunction = () => {
  return [{ title: 'New Remix App' }, { content: 'Welcome to Remix!', name: 'description' }];
};

export default function Index() {
  return (
    <div>
      <h1 className="text-2xs font-bold underline">Hello world!</h1>
    </div>
  );
}
```

**Comment by JoepKockelkorn** [comment] 2024-01-26 22:10
I'm on 2.5.1 and it's still not working. I'm using SPA mode.

**Comment by pcattori** [comment] 2024-01-26 23:13
We've added a section to [Future > Vite > Troubleshooting](https://remix.run/docs/en/main/future/vite#styles-disappearing-in-development-when-document-remounts) for missing styles due to hydration errors, extensions, etc. tl;dr: it should be fixed in React canary and not something Remix can do anything about.

@JoepKockelkorn if your issue seems the same as #8466 happy to continue discussion there. If not, feel free to open up a separate issue for SPA mode-specific features.

**Closed by pcattori** 2024-01-26 23:13 UTC
Labels: bug:unverified, vite
