### ISSUE TITLE
Server bundle included in monorepo packages

### ISSUE THREAD

**Issue by paul-vd** [remix-run/remix#6302] opened 2023-05-04 13:45 UTC
### What version of Remix are you using?

1.16.x

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone: https://github.com/paul-vd/remix-monorepo-server-bundle-reproduction
2. Install using `pnpm`
3. `cd` into `skeleton` folder (`cd skeleton`) 
4. Run the application `pnpm run dev`

The code the reference is in [`/skeleton/app/routes/_index.tsx`](https://github.com/paul-vd/remix-monorepo-server-bundle-reproduction/blob/main/skeleton/app/routes/_index.tsx)

### Expected Behavior

The [`import { acme as AcmeA } from "@acme/package-a"`](https://github.com/paul-vd/remix-monorepo-server-bundle-reproduction/blob/main/skeleton/app/routes/_index.tsx#LL3C1-L3C49) should be removed from the client bundle, as it does for [`import { test as TestA } from "~/acme-test";`](https://github.com/paul-vd/remix-monorepo-server-bundle-reproduction/blob/main/skeleton/app/routes/_index.tsx#L1)

### Actual Behavior

It is included in the client bundle.

### Example
https://remix-monorepo-server-bundle-reproduction-skeleton.vercel.app/

**Comment by TheRealFlyingCoder** [comment] 2023-07-05 01:45
Just bumping this up, as it's a long standing question I've never really had a solid answer to.

Exact same situation:

i'm running a Monorepo with a global server package `@myapp/serverOnly`

To use it in Remix we have to do the obvious `serverOnly.server.ts` with:

`export * from '@myapp/serverOnly`

But even with that bandaid VSCode will almost ALWAYS prioritise the package import when you aren't looking, and without any warnings / issues 🙄

Is there a solution to excluding a package from the client bundle directly? `serverDependenciesToBundle` was meant to be it I thought but it doesn't seem to work.

**Comment by paul-vd** [comment] 2023-07-05 07:41
> Is there a solution to excluding a package from the client bundle directly? serverDependenciesToBundle was meant to be it I thought but it doesn't seem to work.

Another issue would be with packages/dependencies which have a mix of client/server code, in which case `serverDependenciesToBundle` would not have helped. This is ilistrated in my reproduction repo, where the `.server` in the import method should be used to strip it from the client, but it does not.

**Comment by pcattori** [comment] 2023-08-04 20:45
Duplicate of #6711

**Closed by pcattori** 2023-08-04 20:45 UTC
Labels: package:dev, bug:unverified
