### ISSUE TITLE
Basic Routing Works on Server but not Client

### ISSUE THREAD

**Issue by jdgamble555** [remix-run/remix#9276] opened 2024-04-21 23:00 UTC
### Reproduction

https://remix-firebase-test.vercel.app/about

https://github.com/jdgamble555/remix-firebase-test/tree/master

https://stackblitz.com/github/jdgamble555/remix-firebase-test

The stackblitz seems to work fine. The problem is `ONLY` in production.  You can test this on a local machine by running:

1. `npm run build`
2. `npm run start`
3. Navigate here: http://localhost:3000/about

### System Info

```shell
Pushed to Vercel, Brand new remix - 2.8.1
```

### Used Package Manager

npm

This is a basic app. All I have installed is Tailwind.

### Expected Behavior

It should just display the route as working in the `dev` version.

### Actual Behavior

It says 404 not found, the server loads correctly, but the browser routing is not correct.

**Comment by huijiewei** [comment] 2024-04-22 00:09
override rollup to 4.15.0, this is rollup issue.

**Comment by jdgamble555** [comment] 2024-04-22 01:29
Since rollup is in the core package though, Remix should upgrade their dependencies. But yes, this fixed the problem.

**Comment by brophdawg11** [comment] 2024-04-22 13:54
`rollup` is not in the core package, it's a [nested dependency of `vite`](https://github.com/vitejs/vite/blob/main/packages/vite/package.json#L90).  The rollup folks are looking into this and have a fix open: https://github.com/rollup/rollup/pull/5443#issuecomment-2069501668.

Closing as a duplicate of https://github.com/remix-run/remix/issues/9275

**Closed by brophdawg11** 2024-04-22 13:54 UTC
Labels: bug:unverified
