### ISSUE TITLE
Vite hangs on fresh npm install when using `installGlobals`

### ISSUE THREAD

**Issue by shaqq** [remix-run/remix#9114] opened 2024-03-22 23:17 UTC
### Reproduction

Spin up a remix app using the Cloudflare template, and make sure nothing is installed:

```sh
bunx create-remix@latest --template remix-run/remix/templates/cloudflare
cd my-remix-app
rm -rf node_modules
```

In `vite.config.ts`, add these lines:

```ts
import { installGlobals } from "@remix-run/node";

installGlobals();
```

Try to boot the app using `bun run dev` and you won't get any output. It'll look something like this:

```zsh
➜  my-remix-app git:(main) ✗ bun run dev
$ remix vite:dev



^C
```

Running with `bunx vite dev -d` doesn't seem to show anything helpful either.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 432.41 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - ~/.nodenv/versions/19.5.0/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    bun: 1.0.26 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.3.1
  npmPackages:
    @remix-run/cloudflare: ^2.8.1 => 2.8.1
    @remix-run/cloudflare-pages: ^2.8.1 => 2.8.1
    @remix-run/dev: ^2.8.1 => 2.8.1
    @remix-run/react: ^2.8.1 => 2.8.1
    vite: ^5.1.0 => 5.2.3
```

### Used Package Manager

bun

### Expected Behavior

Vite should boot up and run on localhost

### Actual Behavior

`bunx remix vite:dev` fails to run, and fails silently

**Comment by shaqq** [comment] 2024-03-22 23:19
Curiously, if you install deps without `installGlobals` and add it back in later, Vite still seems to work!

**Comment by shaqq** [comment] 2024-03-26 01:34
`@remix-run/node` is included in [`remix-serve`](https://github.com/remix-run/remix/blob/878440781095205487bc735b535ac8bc78740491/packages/remix-serve/package.json#L19)

I tried this with `npm` and `npx` and ran into the same problem:

<img width="734" alt="image" src="https://github.com/remix-run/remix/assets/1438493/d9fd2ae8-eaaf-4a79-bc86-8b5533d63828">

**Comment by shaqq** [comment] 2024-03-26 01:35
I totally get I don't need to use `installGlobals` here. It just fails without any logs or information as to what to do.

My guess is that `installGlobals` is clobbering something that vite needs.

**Comment by brookslybrand** [comment] 2024-05-22 21:23
There are a few things going on here

- I can't replicate this issue (only difference is I'm on bun 1.1.0)
- You should probably be using Node 18 or 20, not 19, since odd Node versions are experimental and even are stable
- As @brophdawg11 mentioned you shouldn't be using `installGlobals` or `@remix-run/node` with cloudflare

I'm going to go ahead and close this since I can't reproduce and it's not really a use case we want to account for anyway

**Closed by brookslybrand** 2024-05-22 21:23 UTC
Labels: bug:unverified, runtime:bun, template:vite-cloudflare
