### ISSUE TITLE
Error code: SIGILL, Chrome 128 (Aw, snap! Chrome error) Dev mode

### ISSUE THREAD

**Issue by eugeniobet** [remix-run/remix#9908] opened 2024-08-23 09:11 UTC
### Reproduction

Just run the dev server in any Chrome version starting from 128.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 9.30 GB / 15.34 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 128.0.6613.84
  npmPackages:
    @remix-run/css-bundle: latest => 2.7.2 
    @remix-run/dev: latest => 2.7.2 
    @remix-run/node: latest => 2.7.2 
    @remix-run/react: latest => 2.7.2 
    @remix-run/serve: latest => 2.7.2 
    @remix-run/server-runtime: latest => 2.7.2
```

### Used Package Manager

npm

### Expected Behavior

The page to load normally.

### Actual Behavior

We are all experiencing the same issue. Some of us have a "Error code 5" (on a Mac machine), some "Error code 4", me personally I have "SIGILL". Even tried the beta version of Chrome (129) with no luck.
Other browers work fine. Productions build work fine as well.

**Comment by eugeniobet** [comment] 2024-08-23 09:27
I'm actually using remix 2.10.3 not 2.7.2 (as shown in System info, don't know why)

**Comment by brophdawg11** [comment] 2024-08-23 14:50
Could you provide some form of a reproduction?  I'm not seeing any issues  with the dev server or HMR on Chrome 128 and latest Remix on my machine.  Are you doing anything particularly interesting with your app setup?

**Comment by eugeniobet** [comment] 2024-08-23 15:23
Unfortunately I wouldn't know how to make reproducible example. I've just opened this https://issues.chromium.org/issues/361749722 since I suspect it may be related to the browser itself.

**Comment by brophdawg11** [comment] 2024-08-26 14:11
👍 ok - I'm going to close this since it doesn't seem to be related to Remix, but happy to re-open if we discover anything further.

**Closed by brophdawg11** 2024-08-26 14:11 UTC
Labels: package:dev, bug:unverified

**Comment by eugeniobet** [comment] 2024-08-26 15:09
After further investigation, it seems to crash (only on Chrome >= 128) when the function Scripts inside @remix-run/react/dist/esm/components.js gets called. On Firefox (where it works) this gets called multiple times tho.

**Comment by eugeniobet** [comment] 2024-08-26 15:30
I think this is it: https://issues.chromium.org/issues/362055818
It might not strictly be related to Remix, tho I think if Chrome doesn't react swiftly this may impact it.
What do you reckon?

**Comment by brophdawg11** [comment] 2024-08-27 14:04
I'm not sure what you are asking?  Without a reproduction there is not much we can do from our side.  And if it's a bug in Chrome - I'm also unsure what we would be able to do.
