### ISSUE TITLE
HMR Crashes the Node Process when creating new routes

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#5844] opened 2023-03-19 02:59 UTC
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Start a remix app with HMR
Create a route file

### Expected Behavior

I can have a minute to work on making the default export and stuff in that route

### Actual Behavior

The server crashes.

Here's the errors I'm seeing:

```
💿 File created: app/routes/users_+/kody.host.tsx

💿 Rebuilding...

💿 Rebuilt in 768ms

💿 Waiting for http://192.168.115.103:6011...

GET /__REMIX_ASSETS_MANIFEST 200 - - 98.154 ms

💿 http://192.168.115.103:6011 ready in 107ms

/Users/kentcdodds/code/epicweb-dev/web-app-fundamentals/node_modules/@remix-run/dev/dist/hmr.js:33
    let file = config.routes[routeId].file;
                                      ^

TypeError: Cannot read properties of undefined (reading 'file')
    at Object.updates (/Users/kentcdodds/code/epicweb-dev/web-app-fundamentals/node_modules/@remix-run/dev/dist/hmr.js:33:39)
    at onRebuildFinish (/Users/kentcdodds/code/epicweb-dev/web-app-fundamentals/node_modules/@remix-run/dev/dist/devServer2.js:159:27)

Node.js v18.13.0
```

**Comment by pcattori** [comment] 2023-03-19 14:53
Duplicate of #5711

**Closed** 2023-03-19 14:53 UTC
Labels: bug:unverified

**Comment by kentcdodds** [comment] 2023-03-19 15:37
🤦‍♂️ sorry for the noise.
