### ISSUE TITLE
[Bug]: Ctrl+c leaves remix running in the background

### ISSUE THREAD

**Issue by movingelectrons** [remix-run/remix#945] opened 2021-12-08 02:52 UTC
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

start a remix app, 'yarn run dev'

Ctrl+c in terminal to stop it

I'm using wsl, ubuntu, if that matters

### Expected Behavior

shouldn't leave process running, but ps shows that is it still.

### Actual Behavior

shouldn't have to run 'killall -9 remix' after stopping

**Comment by yesmeck** [comment] 2021-12-08 04:06
Duplicate of #752

**Closed** 2022-03-18 00:41 UTC
Labels: bug
