### ISSUE TITLE
SSR not working with the new Vite Cloudflare template on Cloudflare Pages

### ISSUE THREAD

**Issue by shahzaibkhalid** [remix-run/remix#8911] opened 2024-02-27 19:37 UTC
### Reproduction

Go to https://my-remix-app-ab9.pages.dev/ and check console logs.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 92.80 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  Browsers:
    Safari: 17.3.1
  npmPackages:
    @remix-run/cloudflare: ^2.7.2 => 2.7.2 
    @remix-run/cloudflare-pages: ^2.7.2 => 2.7.2 
    @remix-run/dev: ^2.7.2 => 2.7.2 
    @remix-run/react: ^2.7.2 => 2.7.2 
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

pnpm

### Expected Behavior

I created a new app by running the following script:
`npx create-remix@latest --template remix-run/remix/templates/vite-cloudflare` and then just build the app and deployed it to Cloudflare Pages by running the following script:

`npm run deploy` which seems to do `wrangler pages deploy ./build/client`

But after the app is deployed, I'm seeing SSR errors in logs saying the HTML after hydration is not matched with HTML generated on the SSR.

<img width="1190" alt="image" src="https://github.com/remix-run/remix/assets/18225515/a9cabbe1-dceb-436a-9be1-a172f540fd9d">

### Actual Behavior

SSR should work as expected.

**Comment by david-crespo** [comment] 2024-02-27 19:56
I don't see those errors in the console.

**Comment by brophdawg11** [comment] 2024-02-27 20:29
Agreed - that app seems to be SSR-ing properly for me.  I'm going to close this but if you can get the issue reproduced we'd be happy to re-open!

**Closed by brophdawg11** 2024-02-27 20:29 UTC
Labels: bug:unverified

**Comment by shahzaibkhalid** [comment] 2024-02-27 20:57
@brophdawg11 / @david-crespo  Heck, it was because of Adguard injecting some script tags on client side, but SSR still seems to be working. because the document has all the HTML. I wonder if in this case these errors are false positives?

Sorry I'm still pretty new with Remix!

**Comment by brophdawg11** [comment] 2024-02-27 22:14
Ah, yeah that's a common issue in react 18.2 when hydrating the full document.  It should be fixed in the next react release and I think is currently fixed if you use one of the canary versions.  There's an open issue with lots of background on these types of DOM extension hydration issues here: https://github.com/remix-run/remix/issues/4822
