### ISSUE TITLE
saveLoginCookie with Set-Cookie header is not working using defer

### ISSUE THREAD

**Issue by jdnichollsc** [remix-run/remix#5289] opened 2023-01-28 02:43 UTC
### What version of Remix are you using?

1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Create 2 routes
- Create an action to flash a value in a session cookie from the first route while redirecting to the 2nd route:
  ```
  export const action: ActionFunction = async ({ request }) => {
    const {
      saveLoginCookie,
      flashMessage
    } = await getCookieSession(request);
    flashMessage('Welcome to RemixJS');
    return redirect('/route-b',
      {
        headers: {
          'Set-Cookie': await saveLoginCookie(),
        }
      }
    );
  };
  ```
- Get the message saved in the session cookie from the second route and update the cookie to clear the message
  ```
  export const loader = async ({ request }: LoaderArgs) => {
    const {
      getMessage,
      saveLoginCookie
    } = await getCookieSession(request);
  
    return defer({
      message: getMessage(),
    }, {
      headers: {
        'Set-Cookie': await saveLoginCookie(),
      },
    });
  };
  ``` 

### Expected Behavior

As docs says:
> Sets a value in the session that is only valid until the next get(). This can be useful for temporary values, like error messages.

### Actual Behavior

But this is not working, I'm still getting the message every time I reload the page from that second route after that action redirection. It was working before using the `json` method of `@remix-run/node`, but I need to use `defer` from this route and keep the same behavior for this temporary value.

Thanks for your help!

**Comment by sergiodxa** [comment] 2023-01-28 02:50
From what I understand getMessage calls session.get, right?

If that’s the case your issue is that you’re committing the session before reading the key from the session, you need to call session.get and then commit the session, otherwise the session will be committed with the flash unread.

**Comment by jdnichollsc** [comment] 2023-01-28 04:31
Exactly, getMessage is executing session.get internally and that's working correctly with the normal flow using the json reponse, so my question is why is this not working for the defer reponse too? 🤔

**Comment by sergiodxa** [comment] 2023-01-29 03:35
The problem is that now your code is running in a different order

Before
- Get session
- Reas from session 
- Commit session

Now
- Get session
- Commit session 
- Read from session

The last two steps changed, and because you’re committing the session before you read from it (call session.get) it keeps the flash message on the session.

I image that getMessage is async and that’s why you’re using defer, you need to at least ensure session.get runs always before commitSession.

**Comment by jdnichollsc** [comment] 2023-01-29 17:09
> The last two steps changed, and because you’re committing the session before you read from it (call session.get) it keeps the flash message on the session.

I don't think so. Also, I tried moving the **getMessage** before the return and I'm still getting the same message every time I reload the page:

```tsx
export const delay = (timeout: number) => new Promise<void>(resolve => setTimeout(resolve, timeout));
// simulate a slow request
const getOtherData = async () => {
  await delay(7000);
  return {
    items: [1, 2, 3, 4],
  };
}

export const loader = async ({ request }: LoaderArgs) => {
  const {
    getMessage,
    saveLoginCookie
  } = await getLoginSession(
    request
  );

  const message = getMessage(); // Still getting the same flashed message after reloading the page in the Browser (Firefox)
  const otherDataPromise = getOtherData();

  return defer({
    message,
    otherData: otherDataPromise,
  }, {
    headers: {
      'Set-Cookie': await saveLoginCookie(),
    },
  });
};
```

> I imagine that getMessage is async

Nope, I'm using **defer** for another data loaded in this route with a slow request. This is the code of the cookie session for a better DX:

```ts
import { createCookieSessionStorage, redirect } from '@remix-run/node';

const loginInfoStorage = createCookieSessionStorage({
  cookie: {
    name: '_login',
    secure: process.env.NODE_ENV !== 'development',
    secrets: ['SESSION_SECRET'],
    sameSite: 'lax',
    path: '/',
    maxAge: 60 * 60 * 24 * 30, // 30 days
    httpOnly: true,
  },
});

const MESSAGE_KEY = 'message';

async function getLoginSession(request: Request) {
  const session = await loginInfoStorage.getSession(
    request.headers.get('Cookie')
  );
  return {
    getMessage: () => session.get(MESSAGE_KEY) as string | undefined,
    flashMessage: (message: string) => session.flash(MESSAGE_KEY, message),
    saveLoginCookie: () => loginInfoStorage.commitSession(session),
    destroySession: () => loginInfoStorage.destroySession(session)
  };
}
```

As you can see `getMessage` is totally sync, please let me know and thanks for your help! <3

**Comment by zackify** [comment] 2023-02-02 00:34
I have the same issue. it's very obvious. If you just use json instead of defer and remove the deferred promises, you will see the response header for set-cookie in the browser.

With defer, there is no set-cookie header in the response.

**Comment by sergiodxa** [comment] 2023-02-02 17:10
This is probably the reason https://github.com/remix-run/remix/pull/5346

**Comment by jdnichollsc** [comment] 2023-04-18 11:55
Hey folks, can you confirm if this was fixed?

**Comment by jacob-ebey** [comment] 2023-08-22 23:28
Should be fixed, can't reproduce and tests exist to cover the case.

**Closed by jacob-ebey** 2023-08-22 23:28 UTC
Labels: bug:unverified, feat:deferred
