### ISSUE TITLE
npm run dev not working when generating the project using the indie stack

### ISSUE THREAD

**Issue by georgebrianb** [remix-run/remix#3577] opened 2022-06-26 11:11 UTC
### What version of Remix are you using?

latest

### Steps to Reproduce

Following the docs located [here](https://remix.run/docs/en/v1/tutorials/blog#creating-the-project)

1. Copy full command: `npx create-remix --template remix-run/indie-stack blog-tutorial`

2. Run it in either Powershell or Git Bash

- Select Typescript at first prompt
- Select yes when prompted for running `npm isntall` or not 
Wait for it to successfully finish installing the needed requirements.

3. cd into `blog-tutorial/` directory

4. run `npm run dev` 

### Expected Behavior

Local development server spawns at localhost:3000 

### Actual Behavior

Following error is received:

```
georg@DESKTOP $/d/Learning/Web Dev/remix/blog-tutorial
➜  npm run dev

> dev
> run-p dev:*


> dev:css
> npm run generate:css -- --watch


> dev:remix
> cross-env NODE_ENV=development binode --require .\mocks -- @remix-run/dev:remix dev

The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
ERROR: "dev:remix" exited with 1.

```

**Comment by Dookie0107** [comment] 2022-06-27 08:12
I am facing this issue as well

**Comment by machour** [comment] 2022-06-27 09:02
@Dookie0107 are you also on a Windows machine?

**Comment by Dookie0107** [comment] 2022-06-27 09:04
> @Dookie0107 are you also on a Windows machine?

Yup. Using Windows 10.

**Comment by tatomarchioli** [comment] 2022-06-27 12:15
I don't think this is related to remix because I don't use it and I have the same problem when running `npm run dev:ssr` on an Angular project. 
It was working perfectly yesterday, now I won't run at all. 
I'm also on Windows 10.

**Comment by bencollinsuk** [comment] 2022-06-28 20:03
Same with me on Windows 11

**Comment by tatomarchioli** [comment] 2022-06-30 12:07
@Dookie0107 this worked for me too! Thanks for sharing.

**Comment by pcattori** [comment] 2023-01-22 03:57
Closing as this seems like the issue is `npm`-related, and not Remix specific.

**Closed by pcattori** 2023-01-22 03:57 UTC
Labels: bug:unverified

**Comment by wujibear** [comment] 2023-07-12 19:33
is there a list of versions that work? I have a newer version of NPM than that and having the same issue.
Currently on 9.5.1
