### ISSUE TITLE
Remix V1 to V2: This require call is not allowed because the transitive dependency  "..." contains a top-level await

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#7568] opened 2023-10-02 02:10 UTC
### What version of Remix are you using?
- 2.0.1

### Background context
Before I attempted to upgrade to V2, I was on remix version `1.19.0` with all V2 feature flags enabled

### Are all your remix dependencies & dev-dependencies using the same version?
- [X] Yes

## remix.confg.js and tsconfig.json

<details>
<summary>FILE: remix.config.js</summary>

```js
import { createRoutesFromFolders } from '@remix-run/v1-route-convention';

/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverModuleFormat: "esm",
  browserNodeBuiltinsPolyfill: {
    modules: {
      fs: true,
      worker_threads: true,
      process: true,
      "stream/web": true,
      buffer: true,
    }
  },
  routes: (defineRoutes) => {
    // `createRoutesFromFolders` will create routes for all files in the routes directory using the same default conventions as Remix v1.
    return createRoutesFromFolders(defineRoutes, {
      // If you're already using `ignoredRouteFiles` in your Remix config, you can move them to `ignoredFilePatterns` in the plugin's options.
      ignoredFilePatterns: ["**/.*", "**/*.css"],
    });
  },
  
};

```
</details>

<details>
<summary>FILE: tsconfig.json</summary>

```js
{
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["**/*.test.*"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "ES2022",
    "module": "ES2022",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"],
      // ↓ Reason we need to add it here temporarily: https://github.com/wbkd/react-flow/issues/3238
      "reactflow": ["./node_modules/reactflow/dist/esm"],
      "@reactflow/core": ["./node_modules/@reactflow/core/dist/esm"],
      "@reactflow/background": ["./node_modules/@reactflow/background/dist/esm"],
      "@reactflow/controls": ["./node_modules/@reactflow/controls/dist/esm"]
    },

    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}

```
</details>

### Steps to Reproduce
Was starting to upgrade to Remix V2, then I started seeing this error message in my app:
```

❌ [ERROR] Node builtin "node:fs" (imported by "node_modules/fetch-blob/from.js") must be polyfilled for the browser. You can enable this polyfill in your Remix config, e.g. `browserNodeBuiltinsPolyfill: { modules: { fs: true } }` [plugin browser-node-builtins-polyfill-plugin]


❌ [ERROR] Node builtin "worker_threads" (imported by "node_modules/node-domexception/index.js") must be polyfilled for the browser. You can enable this polyfill in your Remix config, e.g. `browserNodeBuiltinsPolyfill: { modules: { worker_threads: true } }` [plugin browser-node-builtins-polyfill-plugin]

❌ [ERROR] Node builtin "node:process" (imported by "node_modules/fetch-blob/streams.cjs") must be polyfilled for the browser. You can enable this polyfill in your Remix config, e.g. `browserNodeBuiltinsPolyfill: { modules: { process: true } }` [plugin browser-node-builtins-polyfill-plugin]


❌ [ERROR] Node builtin "node:stream/web" (imported by "node_modules/fetch-blob/streams.cjs") must be polyfilled for the browser. You can enable this polyfill in your Remix config, e.g. `browserNodeBuiltinsPolyfill: { modules: { "stream/web": true } }` [plugin browser-node-builtins-polyfill-plugin]


❌ [ERROR] Node builtin "buffer" (imported by "node_modules/fetch-blob/streams.cjs") must be polyfilled for the browser. You can enable this polyfill in your Remix config, e.g. `browserNodeBuiltinsPolyfill: { modules: { buffer: true } }` [plugin browser-node-builtins-polyfill-plugin]

```

<br />
<br />

So i added  `browserNodeBuiltinsPolyfill` to my `remix.config.js` per the error message and other error messages:
```ts
// remix.config.js
  browserNodeBuiltinsPolyfill: {
    modules: {
      fs: true,
      worker_threads: true,
      process: true,
      "stream/web": true,
      buffer: true,
    }
  },
```

```
❌ [ERROR] This require call is not allowed because the transitive dependency "node-modules-polyfills:worker_threads" contains a top-level await

    node_modules/node-domexception/index.js:5:39:
      5 │     const { MessageChannel } = require('worker_threads'),
        ╵                                        ~~~~~~~~~~~~~~~~

  The file "node-modules-polyfills-commonjs:worker_threads" imports the file "node-modules-polyfills:worker_threads" here:

    node-modules-polyfills-commonjs:worker_threads:1:14:
      1 │ export * from 'worker_threads'
        ╵               ~~~~~~~~~~~~~~~~

  The top-level await in "node-modules-polyfills:worker_threads" is here:

    node-modules-polyfills:worker_threads:97:49:
      97 │ ...rkerData, environmentData }] = await once(parentPort, 'message'));

❌ [ERROR] This require call is not allowed because the transitive dependency "node-modules-polyfills:worker_threads" contains a top-level await

    node_modules/node-domexception/index.js:5:39:
      5 │     const { MessageChannel } = require('worker_threads'),
        ╵                                        ~~~~~~~~~~~~~~~~

  The file "node-modules-polyfills-commonjs:worker_threads" imports the file "node-modules-polyfills:worker_threads" here:

    node-modules-polyfills-commonjs:worker_threads:1:14:
      1 │ export * from 'worker_threads'
        ╵               ~~~~~~~~~~~~~~~~

  The top-level await in "node-modules-polyfills:worker_threads" is here:

    node-modules-polyfills:worker_threads:97:49:
      97 │ ...rkerData, environmentData }] = await once(parentPort, 'message'));
```

### Expected Behavior

In remix v2, polyfilling should work if the user has added `browserNodeBuiltinsPolyfill` in their `remix.config.js` and the result  should be the same behavior as V1 when the polyfills were added for users

### Actual Behavior

Errors

**Comment by cliffordfajardo** [comment] 2023-10-02 02:27
I tried to set the values of `browserNodeBuiltinsPolyfill` to "empty" and that got me passed the build error 

```ts
// remix.config.js
  browserNodeBuiltinsPolyfill: {
    modules: {
      fs: 'empty',
      worker_threads: 'empty',
      process: 'empty',
      "stream/web": 'empty',
      buffer: 'empty',
    }
  },
```

but I got a new error as soon as I started my app with `npm run dev` and loaded it in the browser

```
2023/10/01 07:24:38 PM] TypeError: stream.getReader is not a function
    at Object.writeReadableStreamToWritable (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/node/dist/stream.js:18:23)
    at sendRemixResponse (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:89:16)
    at <anonymous> (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:42:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
```

**Comment by cliffordfajardo** [comment] 2023-10-02 02:52
Also tried using `serverModuleFormat: "cjs",` and removing `"type": "module",` from package.json yields same errors:

```
❌  [ERROR] This require call is not allowed because the transitive dependency "node-modules-polyfills:worker_threads" contains a top-level await

    node_modules/node-domexception/index.js:5:39:
      5 │     const { MessageChannel } = require('worker_threads'),
        ╵                                        ~~~~~~~~~~~~~~~~

  The file "node-modules-polyfills-commonjs:worker_threads" imports the file "node-modules-polyfills:worker_threads" here:

    node-modules-polyfills-commonjs:worker_threads:1:14:
      1 │ export * from 'worker_threads'
        ╵               ~~~~~~~~~~~~~~~~
```

**Comment by cliffordfajardo** [comment] 2023-10-02 02:59
@markdalgleish - any ideas?
Happy to get on a discord chat / live call

**Comment by cliffordfajardo** [comment] 2023-10-02 03:39
I created a much smaller remix express app and converted it from version 1.19.3 to version 2.0.1 and I'm not getting the same errors as in my real app
https://github.com/cliffordfajardo/remix_express_v1_to_v2_bug_node_polyfill_errors/tree/main


Granted the smaller remix express app is pretty much using stock remix-express, whereas my real app is using lots of other npm packages.


I'm guessing that there maybe file(s) that are referencing nodejs APIs that are making it into the browser build 🤔 

I think the next thing I might do is start going over files which are using node APIs and add `.server.` to them
o man, hundreds of files to sift through 😅

**Comment by cliffordfajardo** [comment] 2023-10-02 04:21
All the files where I was using `node-fetch` I added `.server.` to their name & all the errors went away BUT
now I'm see this error in my browser

```
2023/10/01 09:19:01 PM] TypeError: stream.getReader is not a function
    at Object.writeReadableStreamToWritable (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/node/dist/stream.js:18:23)
    at sendRemixResponse (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:89:16)
    at <anonymous> (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:42:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by brophdawg11** [comment] 2023-10-02 14:32
In v2 you should just use the global `fetch` without any import.  It'll be the default node `fetch` implementation if you do not polyfill via `installGlobals()`, or it'll be the polyfilled version from `@remix-run/web-fetch` if you did call `installGlobals()` in your server.  

Assuming you want to continue using the polyfills, can you remove `node-fetch`, ensure you are calling `installGlobals()` in your Express server, and then see if it works just using `fetch` without any imports?

**Comment by cliffordfajardo** [comment] 2023-10-02 16:18
> In v2 you should just use the global fetch without any import. It'll be the default node fetch implementation if you do not polyfill via installGlobals(),

When I click COMMAND + CLICK into fetch to see the type defs, I'm taken to the type definitions for browser fetch & browser `fetch`'s options dont have things such as `agent` that you can pass to, so typescript complains with errors, which is problematic if you're using typechecking after building the app before merging code 😅 

Video demo (also polyfilled with `installGlobals`)
https://github.com/remix-run/remix/assets/6743796/04dcf147-89b4-4a95-a7b2-a25b1c75645f

**Comment by cliffordfajardo** [comment] 2023-10-02 16:50
I patched `@remix-run/web-fetch/package.json`  file's export field since its having trouble resolving the nodejs one at least on my machine. Basically forcing it to give me the isomorphic version of fetch from [@remix-run/web-fetch/src/fetch.js](https://github.com/remix-run/web-std-io/blob/main/packages/fetch/src/fetch.js#L1)


```ts
//BEFORE
  "exports": {
    ".": {
      "types": "./dist/src/lib.node.d.ts",
      "browser": {
        "require": "./dist/lib.cjs",
        "import": "./src/lib.js"
      },
      "require": "./dist/lib.node.cjs",
      "import": "./src/lib.node.js"
    },


// AFTER:
  "exports": {
    ".": {
      "types": "./dist/src/lib.node.d.ts",
      "default": "./src/fetch.js"
    },
```

but still running into the same error once my code its the browser 🤔 

```sh
TypeError: stream.getReader is not a function
    at Object.writeReadableStreamToWritable (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/node/dist/stream.js:19:23)
    at sendRemixResponse (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:89:16)
    at <anonymous> (/Users/cfajardo/Repos/sdi-infra-fe/sdi-infra-fe/node_modules/@remix-run/express/dist/server.js:42:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by brophdawg11** [comment] 2023-10-02 17:07
> When I click COMMAND + CLICK into fetch to see the type defs, I'm taken to the type definitions for browser fetch & browser fetch's options dont have things such as agent that you can pass to, so typescript complains with errors, which is problematic if you're using typechecking after building the app before merging code 😅

That is currently captured by https://github.com/remix-run/remix/issues/7567#issuecomment-1743147630 - so is this sort of the same root cause?  If so we can close this issue out as a duplicate and figure out the types issue over in #7567.

**Closed** 2023-10-02 17:28 UTC
Labels: bug:unverified, feat:fetch

**Comment by comuneoOrg** [comment] 2024-03-13 12:11
Hey !
for me, solving the problem was adding to the `remix.config.js` with more keys like this:

```
browserNodeBuiltinsPolyfill: {
    modules: {
      util: true, // Provide a JSPM polyfill
      stream: true, // Provide an empty polyfill
      https: true, // Provide an empty polyfill
      url: true, // Provide an empty polyfill
      os: true, // Provide an empty polyfill
      buffer: true, // Provide a JSPM polyfill
      fs: "empty", // Provide an empty polyfill
    },
    globals: {
      Buffer: true,
    }
```

all seems to work
