### ISSUE TITLE
Using Deno doesn't work

### ISSUE THREAD

**Issue by o-t-w** [remix-run/remix#5912] opened 2023-03-25 20:24 UTC
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Run `npx create-remix@latest` and select Deno 
Do an npm install.
run `npm run dev`

### Expected Behavior

It should work

### Actual Behavior

Get error 
```
Error: Is a directory (os error 21), readfile 'public/'
    at async Object.readFile (ext:deno_fs/30_fs.js:695:18)
    at async serveStaticFiles (file:///Users/olliew/code/remixed/my-remix-app/build/index.js:12947:16)
    at async Server.<anonymous> (file:///Users/olliew/code/remixed/my-remix-app/build/index.js:12965:14)
    at async Server.#respond (https://deno.land/std@0.128.0/http/server.ts:298:18)
```

There have been a lot of updates to Deno recently so maybe that caused the issue?
It would be great if there were more docs about using Deno with Remix. There are no resources at all about it at the moment.

**Comment by sstiglitz** [comment] 2023-03-25 20:51
Dupe of #5625

**Comment by machour** [comment] 2023-04-26 07:27
Closing as duplicate

**Closed by machour** 2023-04-26 07:27 UTC
Labels: bug:unverified
