### ISSUE TITLE
Error when using vite with mdx, and navigating from link

### ISSUE THREAD

**Issue by broisnischal** [remix-run/remix#8685] opened 2024-02-05 05:28 UTC
### Reproduction

create the new remix app, with vite plugin either using the cloudflare or without, and addind the @mdx-js/rollup as the markdown plugin and creating the mdx file, and navigating to that link

### System Info

```shell
System:
    OS: Linux 6.5 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 13.19 GB / 22.85 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.7.0 - /usr/local/bin/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
  npmPackages:
    @remix-run/cloudflare: ^2.6.0 => 2.6.0 
    @remix-run/cloudflare-pages: ^2.6.0 => 2.6.0 
    @remix-run/dev: ^2.6.0 => 2.6.0 
    @remix-run/react: ^2.6.0 => 2.6.0 
    vite: ^5.0.0 => 5.0.12
```

### Used Package Manager

npm

### Expected Behavior

When navigating to another mdx link in that should navigate using the mdx rollup plugin, but getting issue of internal server error, 

```sh
[vite] Internal server error: Unexpected token (1:0)
  Plugin: remix-route-exports
  File: /home/nees/newproj/app/routes/blog.mdx:1:0
  1  |  # testing
  ```
  
  

### Actual Behavior

should navigate with no error,

**Comment by pcattori** [comment] 2024-02-07 02:02
We now warn when the MDX plugin comes after the Remix plugin (https://github.com/remix-run/remix/pull/8690)

**Comment by pcattori** [comment] 2024-02-09 04:13
Cannot reproduce, so closing this. If you can share a reproduction, we can reopen.

**Closed by pcattori** 2024-02-09 04:13 UTC
Labels: package:dev, bug:unverified, feat:mdx, vite
