### ISSUE TITLE
entry.server.tsx (jsx) handleDataRequest does not perform anything

### ISSUE THREAD

**Issue by David00154** [remix-run/remix#4962] opened 2022-12-26 13:09 UTC
### What version of Remix are you using?

latest as of 26-12-2022

### Steps to Reproduce

-

### Expected Behavior

the handleDataRequest fuction exported from entry.server.tsx supposed to run before remix calls each route loader function

### Actual Behavior

It does not run

**Comment by machour** [comment] 2022-12-26 13:43
Duplicate of https://github.com/remix-run/remix/issues/4505
TL/DR: It does work, but not on the initial request, only when navigating in SPA mode.

**Closed by machour** 2022-12-26 13:43 UTC
Labels: bug:unverified
