### ISSUE TITLE
useLoaderData type inference broken when returned data has a `data` key

### ISSUE THREAD

**Issue by dmarkow** [remix-run/remix#5211] opened 2023-01-22 19:07 UTC
### What version of Remix are you using?

1.11.1

### Steps to Reproduce

If the object returned from the loader includes a `data` key, the type inference returns only the items nested under that key. So in this case, typescript thinks `useLoaderData` returns just `{item: number}`. The code *works* just fine - `item` and `other` are being destructured properly and displaying on the page, it's just the types that are wrong. If I rename the `data` key to something else, it works fine and typescript returns the full type, e.g. `{myData: {item: number}, other: number}`. This started when `defer` was released.

```typescript
export const loader = async () => {
  return json({
    data: { item: 1 },
    other: 2
  })
}

export default function Index() {
  const { data: { item }, other } = useLoaderData<typeof loader>();

  return <div>Item: {item}, Other: {other}</div>;
}
```

```
> yarn tsc
yarn run v1.22.19
$ /Users/dylan/dev/data-issue/node_modules/.bin/tsc
app/routes/index.tsx:12:11 - error TS2339: Property 'data' does not exist on type 'SerializeDeferred<{ item: number; }>'.

12   const { data: { item }, other } = useLoaderData<typeof loader>();
             ~~~~

app/routes/index.tsx:12:27 - error TS2339: Property 'other' does not exist on type 'SerializeDeferred<{ item: number; }>'.

12   const { data: { item }, other } = useLoaderData<typeof loader>();
                             ~~~~~
```

### Expected Behavior

Type inference should work as it did before, or if `data` is a reserved name, the documentation should say as much.

### Actual Behavior

Typescript infers the wrong types, but the code works fine.

**Comment by emilbryggare** [comment] 2023-01-25 10:56
I've this problem as well with the latest version of Remix. I just wanted to add that it also happens when using useFetcher in actions.

Reproduced this in a minimal repository for you:
https://github.com/emilbryggare/remix-types/

**Comment by CapitaineToinon** [comment] 2023-01-30 21:10
Can confirm this is also a problem with actions, returning POJOs or using the json helper.

**Comment by moishinetzer** [comment] 2023-02-07 02:27
This is still an issue with actions, typed loaders are working for me. 

Meaning, `useActionData<typeof action>()` is inferred completely wrong.

**Comment by balzdur** [comment] 2023-02-14 14:10
To help solve the issue, it comes from this :
```ts
declare type Serialize<T> = IsAny<T> extends true ? any : T extends TypedDeferredData<infer U> ? SerializeDeferred<U> : ...

export declare type TypedDeferredData<Data extends Record<string, unknown>> = Pick<DeferredData, "init"> & {
    data: Data;
};
```

Type narrowing tends to consider every payload with `{data: ..}` to be a "defer" value.

**Comment by ronnylt** [comment] 2023-02-16 07:28
Same issue here:

![image](https://user-images.githubusercontent.com/24546/219296873-78ed2b5e-2783-4892-8ef5-0c574a7a867b.png)

**Comment by raminrez** [comment] 2023-02-21 09:07
This problem still exists !
Any idea how to fix it?

**Comment by michaeldebetaz** [comment] 2023-02-22 07:51
Thanks for reporting the issue! I posted it on the Discord a couple of weeks ago and was late to report it here :)

For debbuging without setting up a whole environment, I would recommend the typescript sandbox. [Here is a gist of the issue](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAggYxsCAOyygHMBnOAXzgDMoIQ4AiAAShRGAA8BaKAK6EA9IQgATFMwDcAKFCRYGOACtyRanQZM2HLn0EixkmfPDR4mAeRS58RACIBDGE831GLdpx78hwjic8U1lZFG5FeCdyREIcOiE8AkI4IPtCAApMDgBHARRyeCoALmwkohIKAEoMWTg4HCJCumgQZ1c4AF5UgHcnYHhc-MKAOlpW9qcMqrqGpvhgQhgUJa6WqDaXJxHSFBgM5kXlpeYZ+uBaOAyjlfhO+5ZxiFPa+vrhYTgOGAEoFLUiFl1ptXKVME9SswAEZOKDMagAGjgKCgDCg5DBLQgkJhAC9mFQqDUPnBAKDks3q31+-3UmUw4i2mIhLBhcMRyNR0AxymZ0Kc+MJxM+gBlyWY0FAAGxsrzeJKpf1UtKB4w2k0xAAtJRLsSwetAJeICUiUWjuYQBBKJUS4CTyW8vntqYrAfTGcpNZadcw9VADUaOabSubLdaSaL6lRZJGwhELHBJLQnBb4LREuk4ABhRiQQi3aYyxqEZppZKTNbWWzlQiTAA8SFQEEuJaIAD5phT7TbhAA9AD8s3lKWDEqjQA).

**Comment by okalil** [comment] 2023-03-18 11:54
That also happened to me using Remix 1.14.0 (cloudflare runtime).

**Comment by huyphamfc** [comment] 2023-03-22 04:21
> This is still an issue with actions, typed loaders are working for me.
> 
> Meaning, `useActionData<typeof action>()` is inferred completely wrong.

To solve this issue, I implement `return json(data)` in the "action" function.

**Comment by mikeybinns** [comment] 2023-04-04 11:29
This still occurs on Remix 1.15, and it also occurs on the `SerializeFrom` type helper, and the `useFetcher<Type>()` generic type.

I also have a [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQKZWAQwDbAF6oBiUEIcAvnAGYlkBEAAlKiMAB4C0UArgHYD0vCABNUdANwAoSTACeYVHAAqqAM4wAjHAC8iSXANx+-OAD0A-PsOruAY1trVALjgweqADRWDwzDEwuCN6GBqqkqDAAFsC8AOYu6hhxUiEhYSAR0XEAotiqqC683CAARugphuSSVTLyiirqAEw6KOhYuATEpAA8DZoAfFLGIRZAA) for testing.

**Comment by bryce-pearce** [comment] 2023-04-08 01:01
here is a code sandbox replication as well

https://codesandbox.io/p/sandbox/confident-feather-x0oe5q?file=%2Fapp%2Froot.tsx&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A31%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A31%7D%5D

**Comment by MichaelDeBoey** [comment] 2023-04-11 22:01
Closed by #5516

**Comment by jcloutier-indeed** [comment] 2023-04-12 14:14
It looks like it resolved the issue for us from what I can see.

**Comment by machour** [comment] 2023-05-01 22:01
1.16.0 is out 🎉

**Closed by machour** 2023-05-01 22:01 UTC
Labels: bug, feat:typescript

**Comment by Darshan562** [comment] 2023-12-20 07:11
> ### What version of Remix are you using?
> 1.11.1
> 
> ### Steps to Reproduce
> If the object returned from the loader includes a `data` key, the type inference returns only the items nested under that key. So in this case, typescript thinks `useLoaderData` returns just `{item: number}`. The code _works_ just fine - `item` and `other` are being destructured properly and displaying on the page, it's just the types that are wrong. If I rename the `data` key to something else, it works fine and typescript returns the full type, e.g. `{myData: {item: number}, other: number}`. This started when `defer` was released.
> 
> ```ts
> export const loader = async () => {
>   return json({
>     data: { item: 1 },
>     other: 2
>   })
> }
> 
> export default function Index() {
>   const { data: { item }, other } = useLoaderData<typeof loader>();
> 
>   return <div>Item: {item}, Other: {other}</div>;
> }
> ```
> 
> ```
> > yarn tsc
> yarn run v1.22.19
> $ /Users/dylan/dev/data-issue/node_modules/.bin/tsc
> app/routes/index.tsx:12:11 - error TS2339: Property 'data' does not exist on type 'SerializeDeferred<{ item: number; }>'.
> 
> 12   const { data: { item }, other } = useLoaderData<typeof loader>();
>              ~~~~
> 
> app/routes/index.tsx:12:27 - error TS2339: Property 'other' does not exist on type 'SerializeDeferred<{ item: number; }>'.
> 
> 12   const { data: { item }, other } = useLoaderData<typeof loader>();
>                              ~~~~~
> ```
> 
> ### Expected Behavior
> Type inference should work as it did before, or if `data` is a reserved name, the documentation should say as much.
> 
> ### Actual Behavior
> Typescript infers the wrong types, but the code works fine.

I face same issue but in my project I use JavaScript instead of TypeScript 

Error:     Property 'filterData' does not exist on type 'unknown'
(https://github.com/remix-run/remix/assets/96987506/f7753cfe-d0bb-4d2a-93c7-504188133d1c)

**Comment by pcattori** [comment] 2023-12-21 00:18
@Darshan562 a bunch of types were improved in 2.1-2.4. If you still have issues after upgrading to those versions, please file a separate issue.
