### ISSUE TITLE
submit multipart/form-data with empty file input, got error on request.formData()

### ISSUE THREAD

**Issue by jacargentina** [remix-run/remix#3570] opened 2022-06-24 23:57 UTC
### What version of Remix are you using?

1.6.1

### Steps to Reproduce

Empty remix app with this route

```tsx
import { ActionFunction } from '@remix-run/node';
import { useSubmit } from '@remix-run/react';
import { useRef } from 'react';

export let action: ActionFunction = async ({ request }) => {
  const fdata = await request.formData();
  console.log(fdata);
  return null;
};

const Comp = () => {
  const submit = useSubmit();
  const formRef = useRef<any>();

  return (
    <>
      <form ref={formRef}>
        <input type="file" name="test" />
      </form>
      <button
        onClick={() => {
          submit(formRef.current, {
            method: 'post',
            encType: 'multipart/form-data',
          });
        }}>
        CLICK SEND WITHOUT FILE. BOOM!
      </button>
    </>
  );
};

export default Comp;
```

Clic the button without any file.

Got this error on the server:

`TypeError: filename is only supported when value is Blob or File`

### Expected Behavior

Simply work.

### Actual Behavior

Gives error.

**Comment by ShMcK** [comment] 2022-06-25 21:24
Same issue. 

Note that the case of an undefined file is not handled in the tests: https://github.com/remix-run/remix/blob/973cd68528c8c58679a5b2d974ae8cefde0db455/packages/remix-server-runtime/__tests__/formData-test.ts

**Comment by machour** [comment] 2022-06-26 10:50
Added a failing test as reproduce case in #3576

**Comment by cwohlman** [comment] 2022-06-28 11:33
I think I have a fix for this in https://github.com/remix-run/web-std-io/pull/12 but wasn't able to test it as I don't have my environment fully set up.

**Comment by mcansh** [comment] 2022-08-02 17:16
with the release of `@remix-run/web-fetch@4.2.0` is this still an issue?

**Comment by machour** [comment] 2022-08-02 18:22
@mcansh seems to be working fine now 🎉 

```
🍺  ~/test-3570 $ yarn dev
yarn run v1.22.19
$ remix dev
Watching Remix app in development mode...
💿 Built in 197ms
Remix App Server started at http://localhost:3000 (http://192.168.1.5:3000)
GET / 200 - - 23.356 ms
FormData {}
POST /?index=&_data=routes%2Findex 200 - - 14.282 ms
FormData {}
POST /?index=&_data=routes%2Findex 200 - - 6.654 ms
FormData {}
```

**Closed** 2022-08-03 08:58 UTC
Labels: bug, feat:forms, feat:fetch
