### ISSUE TITLE
V2 routing root index path issue

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#5216] opened 2023-01-23 03:33 UTC
### What version of Remix are you using?

1.11.0

### Steps to Reproduce

`npx create-remix@latest`

Switch to V2 routing, and run `remix routes`

### Expected Behavior

After the 1.11 update, leaf `index.tsx` routes should be recognised by the routing system (This works with remix-flat-routes).

/routes/index.tsx

`<Route index file="routes/index.tsx" />`

/routes/test/index.tsx

`<Route path="test" file="routes/test/index.tsx" />`

### Actual Behavior

/routes/index.tsx

`<Route path="index" file="routes/index.tsx" />`

/routes/test/index.tsx

`<Route path="test" file="routes/test/index.tsx" />`

**Comment by machour** [comment] 2023-01-23 06:47
Can you check if 1.11.1 works for you?
https://github.com/remix-run/remix/releases/tag/remix%401.11.1

**Comment by Deanmv** [comment] 2023-01-23 10:21
I'm seeing the same issue on 1.11.1 as well.  

If I have `app/routes/_index.tsx` then I get the correct output from `remix routes` of:
`<Route index file="routes/_index.tsx" />`

When changing the filename to `app/routes/index.tsx` then the output of `remix routes` changes to:
`<Route path="index" file="routes/index.tsx" />` 

My content then does not appear at `localhost:3000` 

I've made a repo to reproduce is here - https://github.com/Deanmv/remix-issue-5216

**Comment by kiliman** [comment] 2023-01-23 14:52
@Deanmv index routes in v2 routing must be named `_index.tsx`. Naked `index.tsx` only works as the _route file_ in _flat-folders_ convention.

**flat-files**
`routes/test.tsx` => `/test` layout
`routes/test._index` => `/test/` index route

**flat-folders**
`routes/test/index.tsx` => `/test` layout
`routes/test._index/index.tsx` => `/test/` index route

**Comment by Deanmv** [comment] 2023-01-23 15:05
@kiliman ah, looks like I've misunderstood that then. Ignore me 😄 

Thanks for the example!

**Comment by ianhernandez** [comment] 2023-01-24 01:23
> Routes can also be folders with a conventional `index.tsx` file inside defining the route module. The rest of the files in the folder will not become routes. This allows you to organize your code closer to the routes that use them instead of repeating the feature names across other folders.

[Route File Naming (v2)](https://remix.run/docs/en/v1/file-conventions/route-files-v2) [#folders-for-organization](
https://remix.run/docs/en/v1/file-conventions/route-files-v2#folders-for-organization)

By "Can also" does that mean by opting into the v1 convention? or that you can use index.tsx in a folders with new v2 conventions.

**Comment by machour** [comment] 2023-01-24 07:02
@ianhernandez it's for V2

**Comment by kiliman** [comment] 2023-01-24 14:24
@ianhernandez the "can also" refers to v2 convention, a route can be a `flat-file` or a `flat-folder` (which is basically the route name as the folder name, and `index.tsx` is the route file).

**Comment by jozefmery** [comment] 2023-01-25 00:52
I believe there is still an issue in Remix `v1.11.1` with the `flat-folder` folder convention and index routes.
Consider the following structure (essentially similar example as in the [docs](https://remix.run/docs/en/v1/file-conventions/route-files-v2#folders-for-organization)):   
`routes/_main/index.tsx` -> layout without URL nesting
`routes/_main._index/index.tsx` -> index path with `_main` layout, e.g `localhost/` should map to this
`routes/_main.foo/index.tsx` ->  foo path with `_main` layout, e.g `localhost/foo` should map to this

If I understand everything correctly, this is how the convention should work, but running `remix dev` or `remix routes` yields an error, specifically: `Error: Path undefined defined by route "_main._index/index" conflicts with route "_main/index"`

Chaning to structure to the following:
`routes/_main/index.tsx`
`routes/_main.index/index.tsx`
`routes/_main.foo/index.tsx`
 
fixes the error, and running `remix routes` yield:
`<Routes>
  <Route file="root.tsx">
    <Route index file="routes/_main/index.tsx" />
    <Route path="foo" index file="routes/_main.foo/index.tsx" />
  </Route>
</Routes>
`
which seems correct, but the contents of `routes/_main.index/index.tsx` are not rendered in the `Outlet` of the _main layout. Route `foo` works as expected. Am I missing something ?

**Comment by sturgeonphillip** [comment] 2023-03-29 21:21
Just did the 15 min tutorial with the indie stack and can confirm - had to change `app/routes/_index.tsx` to `app/routes/index.tsx` and then adjust the remix config v2_routeConvention to false.

**Comment by kiliman** [comment] 2023-03-30 13:56
Yes, the transition to v2 routes will be messy, with so many tutorials still showing the old routing convention. Unfortunately, it's not backward compatible.

I have a migration script to go from v1 to v2 (flat routes). It's part of my `remix-flat-routes` package.

**Comment by trylaarsdam** [comment] 2023-03-31 20:29
This needs to be highlighted in the blog tutorial, as it is currently broken. Either a quick fix of switching back to v1 routes or updating the tutorial to v2 routing.

**Comment by machour** [comment] 2023-04-29 11:18
Fixed by #5959

**Closed by machour** 2023-04-29 11:18 UTC
Labels: feat:routing, bug:unverified, v2
