### ISSUE TITLE
[Bug]: myroute.index.tsx failing with conflict

### ISSUE THREAD

**Issue by leon** [remix-run/remix#1422] opened 2022-01-08 16:24 UTC
### Which Remix packages are impacted?

- `remix` (Remix core)

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

try running this

https://github.com/leon/bug-remix-index-route

### Expected Behavior

if having a index.tsx file works inside a route.
placing it outside and using dot notation should work, so you can skip the wrapper

```myroute.index.tsx```

### Actual Behavior

Fails with

```
Path "myroute" defined by route "routes/myroute" conflicts with route "routes/myroute.index"
```

but I don't see why it should fail

**Comment by sergiodxa** [comment] 2022-01-08 20:12
The problem is that routes/articles and routes/articles.index both render on /articles, if you want routes/articles to be the layout of an index and individual article page you should move routes/articles.index to be routes/articles/index.

**Comment by leon** [comment] 2022-01-09 11:16
I want different templates for
/articles

And

/articles/something

And I don't want them to be nested.

How can I achieve this?

**Comment by joe-bell** [comment] 2022-02-16 19:28
Just echoing your concerns – I ran into the same problem today too

**Comment by chaance** [comment] 2022-06-05 15:14
Closing, as this is as-designed. We are working on some alternative routing conventions to reduce nesting, but in the mean time the solution above from @joe-bell is what you're looking for.

**Closed by chaance** 2022-06-05 15:14 UTC
Labels: bug, feat:routing
