### ISSUE TITLE
Assets only imported in resource routes not included in build output

### ISSUE THREAD

**Issue by wKovacs64** [remix-run/remix#3414] opened 2022-06-08 02:37 UTC
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

1. Create a resource route
2. Import an asset (e.g.,  an image)
3. Observe the resulting URL appears correct (includes a hash) 👍 
4. Observe the resulting URL 404s as the asset does not make it into the build directory ☹️ 

Bonus steps:

5. Import the asset into a UI route
6. Observe the asset is now included in the build output

### Expected Behavior

I would expect an asset imported (only) in a resource route to be included in the build output.

### Actual Behavior

The asset is not included in the build output unless it is also imported in a UI route.

**Comment by magnusdr** [comment] 2022-06-12 17:15
I can reproduce this in my project. My current workaround is to put these images in `public/` 🤷‍♂️

**Comment by wKovacs64** [comment] 2022-06-12 17:19
> I can reproduce this in my project. My current workaround is to put these images in `public/` 🤷‍♂️

Unfortunately, that approach doesn't benefit from fingerprinting (no hash for cache-busting), if I understand you correctly. My current workaround is to import them (again) in a UI route. 😕

**Comment by Xiphe** [comment] 2022-08-25 12:05
Gave `v0.0.0-nightly-916caa6-20220726` a shot but the problem seems to persist. 

We can work around this by also importing the assets from within our client bundle. 

```ts
// entry.client.tsx
import { hydrate } from 'react-dom';
import { RemixBrowser } from 'remix';

/* requires are not tree shaken so the imports in that file are considered relevant for the frontend */
require('./routes/my-resouce-route[.]css');

hydrate(<RemixBrowser />, document);
```

When you have server only code in the resource route you want to be more considerate than this, but you get the idea.

**Comment by mcansh** [comment] 2022-08-25 20:30
> Gave `v0.0.0-nightly-916caa6-20220726` a shot but the problem seems to persist.


yeah, the solution is that of #3841

**Comment by Xiphe** [comment] 2022-08-25 21:01
Cool no prob! Thanks for working on this 👍

**Comment by drochag** [comment] 2022-09-28 12:26
Worked like a charm, thank you so much !

**Comment by wKovacs64** [comment] 2022-10-05 03:00
Agreed, that seems to have done it. 👍

**Comment by machour** [comment] 2022-10-20 19:24
Fixed in 1.7.3 🎉

**Closed by machour** 2022-10-20 19:24 UTC
Labels: bug, package:dev

**Comment by manzano78** [comment] 2023-10-31 17:25
@pcattori, FIY this issue reoccurs when we use the unstable vite plugin :) I could reproduce it in one of the latest nightly releases.

**Comment by pcattori** [comment] 2023-10-31 17:29
@manzano78 since this issue tracks the bug for the existing compiler, could you open up a separate issue (maybe linking to this one)?

**Comment by manzano78** [comment] 2023-10-31 19:34
Sure!
