### ISSUE TITLE
Framer motion's full page transitions breaks with remix while using loader in route file

### ISSUE THREAD

**Issue by ImExoOdeex** [remix-run/remix#3625] opened 2022-06-30 18:48 UTC
### What version of Remix are you using?

1.6.3

### Steps to Reproduce

1. Make simple remix app with framer-motion
2. Set up page transtions in root
3. make route that uses loader data,

### Expected Behavior

I expected animation to be compled (exiting from page with loader data).
### Actual Behavior

While exiting from page with loader data, it gives an error `TypeError: Cannot destructure property 'data' of 'useLoaderData(...)' as it is undefined.`. I noticed that loader data delets first off, not allowing animation to complete, so error shows.

All other routes with no loader works completly fine!
[made clean and simple new remix app with framer motion to show](https://github.com/ImExoOdeex/remix-framer-motion)

**Comment by machour** [comment] 2022-07-02 20:47
Could you provide a sample repository reproducing this issue? This would help the team getting on track quickly to see if it can be fixed

**Comment by ImExoOdeex** [comment] 2022-07-02 21:42
I made [one](https://github.com/ImExoOdeex/remix-framer-motion) with loader bug. U can try yourself - change 
`<AnimatePresence exitBeforeEnter>
     <motion.main key={location.key}>
        {outlet}
     </motion.main>
</AnimatePresence>`
to 
`<AnimatePresence exitBeforeEnter>
            {outlet}
</AnimatePresence>`
to remove animations and It'll work fine

**Comment by ImExoOdeex** [comment] 2022-07-02 22:18
Idk, how to name this, but data from loader unmounts before animation is compled, so then data is undefinied, maybe this helps :)

**Comment by jamesilva** [comment] 2022-07-07 19:22
I was having a similar problem after following the [https://github.com/remix-run/remix/tree/main/examples/framer-route-animation](url) example. What I figured out was that with framer motion, the route component that is exiting renders 1 extra time after changing to the next route. If you log `useLocation` in the route that's exiting you'll see that.
![with_framer_console](https://user-images.githubusercontent.com/25672765/177852554-8e4ddf87-4c89-440a-a62f-d421cf0559ca.png)
So, what seems to be happening is that the component is not in the React tree (`isPresent` is from the `useIsPresent()`  hook provided  by Framer Motion) but it is still executing and trying to access useLoaderData() but the routes don't match? I'm a bit over my knowledge here so I'm guessing.
 The way I fixed it for now was moving the `<motion.main key=useLocation().key>`  to each of the route files I want animated instead of the root route:
```jsx
root.tsx: 
(...)
 <AnimatePresence exitBeforeEnter={true}>
      {outlet}
 </AnimatePresence>
(...)

index.tsx: 
<motion.main
      key={location.key}
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
>
(...)
<motion.main/>
```

**Comment by ImExoOdeex** [comment] 2022-07-08 07:10
Thanks for helping @jamesilva, but I did it like you said (moved `motion.div` to route files), but now there are not exit animation :( Did it on my test [repo](https://github.com/ImExoOdeex/remix-framer-motion)

**Comment by machour** [comment] 2022-07-08 23:15
@jamesilva if you feel that the two examples in the repository can be enhanced, don't hesitate to open pull requests 🙏🏼

**Comment by usback** [comment] 2023-03-28 01:15
i have same isusse so i check up example project but same not working exit 

[https://codesandbox.io/s/github/remix-run/examples/tree/main/framer-route-animation]( https://codesandbox.io/s/github/remix-run/examples/tree/main/framer-route-animation)

how to solve this problem ????

**Comment by brophdawg11** [comment] 2023-05-05 17:21
Closing this out because this is not a bug in Remix, which will update stat as you navigate.  You will need to capture that into local state to preserve during the animation - as shown in https://github.com/remix-run/remix/issues/3625#issuecomment-1179178857.

**Closed by brophdawg11** 2023-05-05 17:21 UTC
Labels: bug:unverified
