### ISSUE TITLE
Did not expect server HTML to contain a <script> in <html>.

### ISSUE THREAD

**Issue by ShourovRoy** [remix-run/remix#1176] opened 2021-12-21 10:30 UTC
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

Should not get unusual error for hydrate 

### Expected Behavior

Should not get unusual error for hydrate 

### Actual Behavior

Warning: Did not expect server HTML to contain a <script> in <html>.
head
html
App
RemixRoute@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:3026:20
Routes@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:3010:7
Router2@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:484:13
RemixCatchBoundary@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:1563:28
RemixErrorBoundary@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:1489:5
RemixEntry@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:2906:20
RemixBrowser@http://localhost:3000/build/_shared/chunk-VO4QFITP.js:3387:27 react-dom.development.js:67:29
    React 19
    <anonymous> entry.client.jsx:4

**Comment by wesleybb** [comment] 2021-12-21 10:54
Check this comment https://github.com/remix-run/remix/issues/1077#issuecomment-995986018, might solve your problem.

**Comment by machour** [comment] 2022-03-18 08:22
Duplicate of #1077

**Closed by machour** 2022-03-18 08:22 UTC
Labels: bug
