### ISSUE TITLE
Currently testing out the SPA mode with Remix. I have `react-icons` installed, and by the looks of it the build process for client SPA fails because Vite throws error about CommonJs.

### ISSUE THREAD

**Issue by rayguncertified1** [remix-run/remix#8507] opened 2024-01-13 14:57 UTC
Currently testing out the SPA mode with Remix. I have `react-icons` installed, and by the looks of it the build process for client SPA fails because Vite throws error about CommonJs. 

`import { BiCog, BiHide, BiShowAlt, BiSearchAlt, BiCommentDetail, BiDotsVerticalRounded, BiSolidEditAlt, BiSearch, BiNetworkChart, BiBarChartSquare, BiUserPlus } from "react-icons/bi/index.esm.js";
    ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'BiBarChartSquare' not found. The requested module 'react-icons/bi/index.esm.js' is a CommonJS module
`

_Originally posted by @Abbbdab in https://github.com/remix-run/remix/discussions/8494_

**Comment by miguelc1221** [comment] 2024-01-15 19:28
currently experiencing the same issue with another package. @fluentui/react-components

**Comment by brophdawg11** [comment] 2024-01-16 16:02
This is usually an issue with one of your dependencies not being properly configured.  Please refer to https://remix.run/docs/en/main/future/vite#esm--cjs for tips on troubleshooting the problematic dependency.

In this case it looks like both of these dependencies may not quite be configured correctly:
https://publint.dev/react-icons@5.0.1
https://publint.dev/@fluentui/react-components@9.44.4

Can you provide a reproduction of the issue?  `react-icons` works fine for me in the SPA Mode template:

```sh
npx create-remix@latest --template remix-run/remix/templates/spa -y temp
cd temp
npm install react-icons
```

Then I added `import { Bs8Circle } from "react-icons/bs";` to `root.tsx` and used it in both the component and `HydrateFallback` and `npm run dev`/`npm run build` work/render without issue.

**Comment by aarjithn** [comment] 2024-01-16 23:30
I had the same issue with an internal package, where Vite SPA works but remix with Vite plugin doesn't. 
[vite-plugin-cjs-interop plugin](https://github.com/cyco130/vite-plugin-cjs-interop) fixed it for me.

**Comment by miguelc1221** [comment] 2024-01-17 04:29
@aarjithn thanks tried that plugin but no luck with @fluentui/react-components

**Comment by brophdawg11** [comment] 2024-01-17 17:28
I'm going to close this out because `react-icons` worked in my reproduciton and we don't have a repro of a breaking case.

`@fluentui/react-components` I think just exports things weirdly.  `import { Button } from ...` didn't work but they look to export everything on a named `default` export in ESM so `import { default as Fluent } from ...` works.

**Closed by brophdawg11** 2024-01-17 17:28 UTC
Labels: bug:unverified, feat:spa

**Comment by penx** [comment] 2024-02-22 12:23
I have the same when using remix@2.7.2 and use-query-params@2.2.1

https://stackblitz.com/edit/remix-run-remix-1gqkvs

Related:
- https://github.com/pbeshai/use-query-params/issues/277

**Comment by cliffordfajardo** [comment] 2024-02-22 12:45
In addition to [vite-plugin-cjs-interop plugin](https://github.com/cyco130/vite-plugin-cjs-interop), the Remix team put out a in depth video on how to debug CJS/ESM errors recently demonstrating how to verify if the dependencies you are trying to use are not configured properly (https://youtu.be/jmNuEEtwkD4?si=ny4gMWWihak3Fq3h&t=87) which is useful for creating upstream issue on the package you are trying to use

Video: https://www.youtube.com/watch?v=jmNuEEtwkD4&t=3s
Docs: https://remix.run/docs/en/main/future/vite#esm--cjs
![CleanShot 2024-02-22 at 04 42 15@2x](https://github.com/remix-run/remix/assets/6743796/a21efd4a-7bbe-4a2d-9736-d26e5950b752)
