### ISSUE TITLE
`useTransition` conflicts with React 18 `useTransition` hook

### ISSUE THREAD

**Issue by MunifTanjim** [remix-run/remix#745] opened 2021-11-28 08:22 UTC
# The Problem

The `useTransition` hook's name conflicts with React 18 `useTransition` hook, I think this needs to be changed to something else so that the Remix API stays stable and doesn't change very often.

_Originally posted by @a7med-mahmoud in https://github.com/remix-run/remix/discussions/478_

**Comment by machour** [comment] 2022-03-16 08:58
Duplicate of #478

**Comment by MunifTanjim** [comment] 2022-03-16 09:01
😂 I already mentioned #478 in the description. And that one's a discussion, this one's an issue.

**Comment by machour** [comment] 2022-03-31 14:36
Update: this will likely be changed to `useNavigation()` in v2: https://discord.com/channels/770287896669978684/954403927489662986/959098437792575538

**Comment by ryanflorence** [comment] 2022-03-31 16:52
Unfortunate naming collision indeed!

We're currently going with `useNavigation` over in React Router as we bring over as many Remixism as we can there:

```js
let navigation = useNavigation();
navigation.state
navigation.type
navigation.formData
```

When we update Remix's dependency on the new React Router, we'll deprecate `useTransition` (it'll still work ofc) in favor of `useNavigation`, and in Remix v2, get rid of our `useTransition`.

**Closed by ryanflorence** 2022-03-31 16:52 UTC
