### ISSUE TITLE
[Bug]: Continuous mismatch of stylesheet's "href" on hydration

### ISSUE THREAD

**Issue by silvenon** [remix-run/remix#783] opened 2021-11-29 20:41 UTC
### Which Remix packages are impacted?

Not sure 😅 Probably `@remix-run/react`.

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

1. scaffold a new project with `npx create-remix@latest`, select default options
2. start the development server with `npm run dev`
3. open the app in the browser, and open the developer console
4. change a CSS file, e.g. `global.css`

### Expected Behavior

Expect there not to be any warnings in the console.

### Actual Behavior

`react-dom` outputs a warning because of a `href` mismatch between client and server side rendering. It only goes away after a hard refresh, only to come back as soon as I edit a CSS file again.

```
Warning: Prop `href` did not match. Server: "/build/_assets/global-OTK6YWMW.css" Client: "/build/_assets/global-AXSLNPZT.css"
    at link
    at Links (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:3042:7)
    at head
    at html
    at Document (http://localhost:3000/build/root-DLPFIXPQ.js:66:3)
    at App
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:2905:3)
    at Routes (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:2888:7)
    at Router2 (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:457:21)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:1476:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:1415:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:2785:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-R5U63JRH.js:3467:42)
```

**Comment by kiliman** [comment] 2022-02-22 00:44
Duplicate of #896

**Closed** 2022-02-22 09:28 UTC
Labels: bug
