### ISSUE TITLE
How to use socket.io with remix last version ?

### ISSUE THREAD

**Issue by sostenesapollo** [remix-run/remix#9006] opened 2024-03-07 10:46 UTC
I'm not getting to run with last version, can someone help me ?

**Comment by GOWxx** [comment] 2024-03-07 10:56
Can you provide a minimal reproduction, because we need to know how you are using it, how it failed, what the failure information is, in order to better help you with your specific situation.

**Comment by hilja** [comment] 2024-03-07 16:28
Although this repo is archived I used it as the base on my socket.io setup https://github.com/sergiodxa/remix-socket.io. It doesn't touch Vite at all, so it should be pretty much the same as before.

Points of interest:

https://github.com/sergiodxa/remix-socket.io/blob/809c7a2e7cc2fb04dc3012097aa1d9b8e5731609/server/index.js#L14

https://github.com/sergiodxa/remix-socket.io/blob/809c7a2e7cc2fb04dc3012097aa1d9b8e5731609/server/index.js#L18-L25

https://github.com/sergiodxa/remix-socket.io/blob/809c7a2e7cc2fb04dc3012097aa1d9b8e5731609/app/ws-context.tsx#L5-L7

https://github.com/sergiodxa/remix-socket.io/blob/809c7a2e7cc2fb04dc3012097aa1d9b8e5731609/app/root.tsx#L31-L36

**Comment by brophdawg11** [comment] 2024-03-08 15:01
I'm going to close this out since the linked resources should provide the right guidance and we try to keep the GH Issues limited to bugs in Remix versus Q/A.  If you are still having trouble you can ask for help in the `#help` channel in the [Remix discord](https://rmx.as/discord).  If you find a bug in in Remix using socket.io - please provide a minimal reproduction and we can re-open this issue!

**Closed by brophdawg11** 2024-03-08 15:01 UTC
Labels: bug:unverified
