### ISSUE TITLE
@remix-run/dev v1.16.0 rebuilds do not finish, if a new rebuild starts before the previous one finishes

### ISSUE THREAD

**Issue by Hansenq** [remix-run/remix#6384] opened 2023-05-12 17:56 UTC
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [ ] Yes

I've isolated the issue to `@remix-run/dev@1.16.0`. You can have all other remix packages at 1.16.0 and `@remix-run/dev@1.15.0` and things will work as expected.

### Steps to Reproduce

1. Install a new Remix app using `npx create-remix@latest`. Use minimal default settings; it doesn't matter. I used just the basics, Typescript, and Remix App Server.
2. Ensure your `@remix-run/dev` package in `package.json` is v1.16.0
3. cd into the new remix directory and run `npm run dev`
4. Open a file (such as `root.tsx`), add an inconsequential newline, and save.
5. Look at the dev server output. It should show something like the following: 
```bash
[10:46:03] CS/test-remix-app()%> npm run dev                                                                                                                      [23-05-12]?127

> dev
> remix dev

💿 Building...
💿 Rebuilt in 698ms
Remix App Server started at http://localhost:3000 (http://172.20.34.75:3000)
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 Rebuilt in 238ms
```
6. Repeat step 4 **twice or more**, in **extremely rapid** succession. You want to trigger the next rebuild before the previous rebuild finishes. Note that if you have a fast computer, rebuilding be much faster--mine is a 2016 Macbook so rebuilds take at least 200ms. If you're successful, the dev server output should show the following: 
```bash
[10:46:03] CS/test-remix-app()%> npm run dev                                                                                                                      [23-05-12]?127

> dev
> remix dev

💿 Building...
💿 Rebuilt in 698ms
Remix App Server started at http://localhost:3000 (http://172.20.34.75:3000)
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 Rebuilt in 238ms
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 File changed: app/root.tsx
💿 Rebuilding...
```

Note how those three rebuilds will never succeed. You have to restart the devserver to continue. 

### Expected Behavior

In v1.15.0 of the `@remix-run/dev`, this issue does not happen. Triggering a rebuild before the previous one finishes shows the following output: 
```bash
web:dev: Remix App Server started at http://localhost:3000 (http://172.20.34.75:3000)
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 Rebuilt in 545ms
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 Rebuilt in 2.7s
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 File changed: app/root.tsx
web:dev: 💿 Rebuilding...
web:dev: 💿 Rebuilt in 2.8s
web:dev: 💿 Rebuilt in 2.7s
web:dev: 💿 Rebuilt in 1.5s
web:dev: 💿 Rebuilt in 1.2s
```

### Actual Behavior

Rebuilds triggered by hot reloads before the previous rebuild finishes are causing all rebuilds to hang indefinitely. We get the following output from the dev server: 
```bash
Remix App Server started at http://localhost:3000 (http://172.20.34.75:3000)
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 Rebuilt in 238ms
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 File changed: app/root.tsx
💿 Rebuilding...
💿 File changed: app/root.tsx
💿 Rebuilding...
```

**Comment by pcattori** [comment] 2023-05-15 15:38
Duplicate of https://github.com/remix-run/remix/issues/6285

**Closed by pcattori** 2023-05-15 15:38 UTC
Labels: package:dev, bug:unverified
