### ISSUE TITLE
SerializeFrom has problems resolving Generic Types

### ISSUE THREAD

**Issue by barrymay** [remix-run/remix#4626] opened 2022-11-17 14:15 UTC
### What version of Remix are you using?

1.7.5

### Steps to Reproduce

Hi!    This may be a feature request, but I feel that myself and some other folks may be running into this because of a change 
between 1.7.3 and 1.7.4 around the (corrected) typing of useFetcher.

When using useFetcher (which now has a hard dependency on SerializeFrom in its function output) it would be really helpful to be able to pass down a type from the calling function... but SerializeFrom appears to eliminate properties in the Generic type.

Here I'm trying to create a Discriminated Union for successes and failures: (simplified for clarity)
```ts
import { useFetcher } from "@remix-run/react";
type FetcherSuccessResult<TSuccess> = {
  type: "success";
  successData: TSuccess;
};

function useValueFromFetcher<TData>() {
  const testFetcher = useFetcher<FetcherSuccessResult<unknown>>();
  if (testFetcher && testFetcher.data?.successData) { // PASS
    console.log("Gets here!")
  }

  const testFetcher2 = useFetcher<FetcherSuccessResult<any>>();
  if (testFetcher2 && testFetcher2.data?.successData) { // PASS
    console.log("Gets here!")
  }

  const testFetcher3 = useFetcher<FetcherSuccessResult<{foo: 'bar'}>>();
  if (testFetcher3 && testFetcher3.data?.successData) { // PASS
    console.log("Gets here!")
  }

  const testFetcher4 = useFetcher<FetcherSuccessResult<TData>>();
  // TS ERROR - Property 'successData' does not exist on type 'SerializeObject<UndefinedToOptional<FetcherSuccessResult<TData>>>
  if (testFetcher4 && testFetcher4.data?.successData) { 
    console.log("Fails to TS compile")
  }
}
```

Thanks, and keep up the great work!

### Expected Behavior

No TS Errors would show in the example above, and `testFetcher4.data?.successData` would return the value
```ts
{
  type: "success";
  successData: TData;
}
```

### Actual Behavior

See the example above - testFetcher4 throws the TS error shown

**Comment by kiliman** [comment] 2022-11-17 19:03
Yes, I'm seeing the same issue. The `SerializeObject<UndefinedToOption<T>>` wrapper around the `useLoaderData/fetcher.data` return type makes it really hard to correctly type any inner props.

**Comment by bmaycc** [comment] 2022-11-18 04:51
One workaround I've got working for now is basically to undo the output serialization.  

While it won't handle the useFetcher<typeof loader/action> behavior which was the main reason for the 1.7.4 change,  I can pass in the expected SerializeFrom-based expectation into TData and things resolve as desired.

```ts
export function useFetcherNoSerialize<
  TData = any
>(): FetcherWithComponents<TData> {
  return useFetcher<TData>() as FetcherWithComponents<TData>;
}
```

**Comment by barrymay** [comment] 2022-11-18 04:52
One workaround I've got working for now is basically to undo the output serialization.  

While it won't handle the useFetcher<typeof loader/action> behavior which was the main reason for the 1.7.4 change,  I can pass in the expected SerializeFrom-based expectation into TData and things resolve as desired.

```ts
export function useFetcherNoSerialize<
  TData = any
>(): FetcherWithComponents<TData> {
  return useFetcher<TData>() as FetcherWithComponents<TData>;
}
```

**Comment by politicker** [comment] 2022-12-08 01:35
getting this too. some type information is lost when wrapped in ` SerializeObject<UndefinedToOptional<>>`

**Comment by JeffBeltran** [comment] 2023-02-01 22:48
i spent way to long to find this was my cause of a typescript issue. Thought my problem was with my discriminated union.

what ended up fixing my issue was to swap out the `useLoaderData` hook with @kiliman package https://github.com/kiliman/remix-typedjson

hopefully this helps someone else

**Comment by pcattori** [comment] 2023-08-04 20:21
Duplicate of #6632

**Closed by pcattori** 2023-08-04 20:21 UTC
Labels: bug, feat:typescript
