### ISSUE TITLE
unstable_dev - never get event.type = "HMR"

### ISSUE THREAD

**Issue by rlesniak** [remix-run/remix#5861] opened 2023-03-21 13:25 UTC
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Clone template repo: https://github.com/pcattori/remix-hmr-example
Update package.json to reflect 1.14.3
Run `npm run dev`

### Expected Behavior

Working HMR 

### Actual Behavior

Socket events stops at this logs:
![image](https://user-images.githubusercontent.com/13970783/226618883-b6b6bf84-b718-4d34-8f9c-23771c4be8cb.png)
So no `event.type === "HMR"` event, thus no events like `[HMR] Updated accepted by` etc

VIDEO:

https://user-images.githubusercontent.com/13970783/226619539-3f2b776e-b44f-47ae-9d1c-9f07ab99401a.mov

**Comment by rlesniak** [comment] 2023-03-31 08:08
bump

**Comment by machour** [comment] 2023-04-26 21:21
@rlesniak could you please test on 1.16.0-pre.0? Seems to be working fine on my side

**Comment by pcattori** [comment] 2023-06-14 21:06
`unstable_dev` architecture has changed in 1.16 and 1.17. Closing as this isn't reproducible on recent versions.

**Closed by pcattori** 2023-06-14 21:06 UTC
Labels: package:dev, bug:unverified
