### ISSUE TITLE
Remix polyfills `crypto` in browser bundle

### ISSUE THREAD

**Issue by grinkus-adapt** [remix-run/remix#7095] opened 2023-08-07 13:01 UTC
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone and run [Remix repro repo](https://github.com/grinkus-adapt/typesense-remix).
2. Go to the "Typesense Search" page or navigate to `/typesense-search`.
3. Check the largest bundle chunk, see it's at about 1.7 MB (extracted)
4. Clone and run [Next.js repro repo](https://github.com/grinkus-adapt/typesense-next).
5. Go to the "Typesense Search" page or navigate to `/typesense-search`.
6. Check the bundle chunk that is responsible for the same code, see it's at about 150 kB (extracted)

### Expected Behavior

As outlined in https://github.com/typesense/typesense-instantsearch-adapter/issues/180, it seems that Remix polyfills `crypto` (based on what it seems like when [analyzing](https://esbuild.github.io/analyze/) [the metafile](https://raw.githubusercontent.com/grinkus-adapt/typesense-remix/main/_metafiles/metafile.js.json)).

I assume that the `browser` value in `package.json` of the library that uses `crypto` in this case is being ignored in Remix, although I think it should be a signal that `crypto` is not supposed to be polyfilled in the browser (although I'm not sure how that's supposed to work if not polyfilled, so maybe I'm making a wrong assumption here).

![image](https://github.com/remix-run/remix/assets/12794717/dbe446c2-cc6f-4cba-856a-1dca935424be)

In any case, I expect the bundle to be much smaller than the currently-resulting 1.7 MB and I can't work out why that happens.

### Actual Behavior

The resulting bundle is 1.7 MB, when it, in my opinion, should be smaller -- I'm basing this assumption on Next.js handing it in such a way that the bundle is at about 150 kB (or 450 kB, depending on what's included in comparison).

This is the search page on Remix:

![image](https://github.com/grinkus-adapt/typesense-remix/assets/12794717/d2eaf026-0ce2-4160-a21e-c1577e2bdc6c)

For comparison, this is the same page, but on Next.js:

![image](https://github.com/grinkus-adapt/typesense-next/assets/12794717/d4efa7e6-c032-477d-8bab-c7913f478002)

**Comment by kiliman** [comment] 2023-08-07 15:26
Currently, Remix has a config setting [`serverNodeBuiltinsPolyfill`](https://remix.run/docs/en/1.19.2/file-conventions/remix-config#servernodebuiltinspolyfill), but this only applies to the server bundle. Unfortunately, they don't have one for the client bundle.

Here's a patch that will prevent the `crypto` package from being bundled.

`patches/@remix-run+dev+1.19.2.patch`
```diff
diff --git a/node_modules/@remix-run/dev/dist/compiler/js/compiler.js b/node_modules/@remix-run/dev/dist/compiler/js/compiler.js
index bb93d52..e7710bc 100644
--- a/node_modules/@remix-run/dev/dist/compiler/js/compiler.js
+++ b/node_modules/@remix-run/dev/dist/compiler/js/compiler.js
@@ -92,7 +92,7 @@ const createEsbuildConfig = (ctx, refs) => {
     sideEffects: false
   }), mdx.mdxPlugin(ctx), emptyModules.emptyModulesPlugin(ctx, /\.server(\.[jt]sx?)?$/), emptyModules.emptyModulesPlugin(ctx, /^@remix-run\/(deno|cloudflare|node)(\/.*)?$/, {
     includeNodeModules: true
-  }), esbuildPluginsNodeModulesPolyfill.nodeModulesPolyfillPlugin(), external.externalPlugin(/^node:.*/, {
+  }), esbuildPluginsNodeModulesPolyfill.nodeModulesPolyfillPlugin({modules:{crypto: false}}), external.externalPlugin(/^node:.*/, {
     sideEffects: false
   })];
   if (ctx.options.mode === "development" && ctx.config.future.v2_dev) {
```

## Before
<img width="1068" alt="image" src="https://github.com/remix-run/remix/assets/47168/c2693e42-2b32-44b6-af66-cd04a2b8cc46">
<img width="1003" alt="image" src="https://github.com/remix-run/remix/assets/47168/99d828b7-415e-4a82-80e3-595ab7541be3">

## After
<img width="1054" alt="image" src="https://github.com/remix-run/remix/assets/47168/793476b1-e805-4813-a6c8-393a8af8fa97">

**Comment by grinkus-adapt** [comment] 2023-08-07 16:53
> patches/@remix-run+dev+1.19.2.patch

This patch breaks the client-side functionality though.

![image](https://github.com/remix-run/remix/assets/12794717/6399f711-7c05-4e77-bdc5-297c549bd8fa)

It seems that Next.js version somehow tree-shakes the crypto package and only bundles the method from it that's used in the library.

**Comment by kiliman** [comment] 2023-08-07 18:04
Ah, I see. Here's a patch for `typesense` that replaces `crypto` with `crypto-js`.

`patches/typesense+1.5.4.patch`

```diff
diff --git a/node_modules/typesense/dist/typesense.js b/node_modules/typesense/dist/typesense.js
index b2c32ab..1d25093 100644
--- a/node_modules/typesense/dist/typesense.js
+++ b/node_modules/typesense/dist/typesense.js
@@ -7853,7 +7853,7 @@ Object.defineProperty(exports, "__esModule", {
   value: true
 });
 
-var crypto_1 = require("crypto");
+var crypto_1 = require("crypto-js");
 
 var RESOURCEPATH = '/keys';
 
@@ -7889,7 +7889,7 @@ function () {
     // Note: only a key generated with the `documents:search` action will be
     // accepted by the server, when usined with the search endpoint.
     var paramsJSON = JSON.stringify(parameters);
-    var digest = Buffer.from((0, crypto_1.createHmac)('sha256', searchKey).update(paramsJSON).digest('base64'));
+    var digest = Buffer.from((0, crypto_1.HmacSHA256)(paramsJSON, searchKey).toString(CryptoJS.enc.Base64));
     var keyPrefix = searchKey.substr(0, 4);
     var rawScopedKey = "".concat(digest).concat(keyPrefix).concat(paramsJSON);
     return Buffer.from(rawScopedKey).toString('base64');
```

<img width="1377" alt="image" src="https://github.com/remix-run/remix/assets/47168/a81c11a8-6b3f-4755-a36c-74ae24d78637">

**Comment by markdalgleish** [comment] 2023-08-23 02:38
Turns out this is because polyfills aren't taking into account the [`browser` field in `package.json`](https://github.com/defunctzombie/package-browser-field-spec) (which @grinkus-adapt pointed to in the `typesense` package). I've opened a PR to fix this upstream: https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/pull/150

**Comment by markdalgleish** [comment] 2023-08-23 03:09
I've tested the fix from my PR linked above and the file size of the `typesense-search` chunk in dev has gone from 585kb down to 41.3kb.

**Comment by imranbarbhuiya** [comment] 2023-08-23 10:21
Can u update `esbuild-plugins-node-modules-polyfill` to [v1.4.1](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/releases/tag/v1.4.1) using `override` or `resolution` and check if it works now without any patch

**Comment by markdalgleish** [comment] 2023-08-23 20:26
@imranbarbhuiya I get the following error when upgrading. Since a polyfill is no longer being resolved, `crypto` is now being marked as external in the Remix client build so the import is left in the generated code and fails at runtime.

<img width="877" alt="Screenshot 2023-08-24 at 6 22 26 am" src="https://github.com/remix-run/remix/assets/696693/dafd673a-757c-41a7-86e1-ef1b03d5d190">

This is caused by Remix's esbuild config but I'm hoping we can roll back part of the change until the next major version of your plugin so that it doesn't break Remix v1 consumers. I'm prepping a PR for you now.

**Comment by markdalgleish** [comment] 2023-08-24 20:02
This is now fixed in [`esbuild-plugins-node-modules-polyfill` v1.5](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/releases/tag/v1.5.0). If you ensure your project is resolving this version, you'll see crypto is no longer included in the browser bundle.

**Closed by markdalgleish** 2023-08-24 20:02 UTC
Labels: bug, package:dev, external

**Comment by grinkus-adapt** [comment] 2023-09-11 13:00
> @grinkus-adapt This is now fixed in [`esbuild-plugins-node-modules-polyfill` v1.5](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill/releases/tag/v1.5.0). If you ensure your project is resolving this version, you'll see crypto is no longer included in the browser bundle.

Indeed, `v1.5` _does_ fix the issue. Thank you!
