### ISSUE TITLE
1.16.0 / 1.16.1 / 1.17.0 : Horrible reload experience with historic dev server

### ISSUE THREAD

**Issue by raskyer** [remix-run/remix#6560] opened 2023-06-07 17:31 UTC
### What version of Remix are you using?

1.17.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Have a window
- Install remix 1.16.0 / 1.16.1 or 1.17.0
- Make some change, save, make some other change, save (without waiting the first rebuilt to stop)
- Wait ...

Precision : Use the historic dev server and not the new one.

### Expected Behavior

The dev server reloads correctly under a manageable and ok time 

### Actual Behavior

It reloads but sometimes get stucks, sometimes throws 10 errors in console (No routes matched location "/build/_shared/chunk-MVBW4HBB.js"), sometimes takes up to 10 seconds to fully reload, sometimes requires to restart completly the server because it fails in loop.

That's a terrible step backward compared to 1.15.0 and is unmanageable to work with in dev for real world project.

**Comment by raskyer** [comment] 2023-06-07 17:48
It seems that unstable_dev is not better on load times (but since it's unstable, that's fine) : 
![image](https://github.com/remix-run/remix/assets/16725289/ed4d1c48-9b1d-4225-8211-a01f216bd8b4)

For successive changes, new dev server is better (it canceled correctly the app and dev server without issue or multiple errors) but it's very long : 
![image](https://github.com/remix-run/remix/assets/16725289/c928e832-a336-4aa6-a547-27ce6736d088)

**Comment by raskyer** [comment] 2023-06-07 21:11
To have an iso repo, it will be hard since it's for a client, but I can have the same result with a newly created repository with createRemix.

For my remix.config.js : 
```
const { createRoutesFromFolders } = require('@remix-run/v1-route-convention');

/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  serverDependenciesToBundle: ['marked', 'p-pipe'],
  future: {
    v2_meta: true,
    v2_errorBoundary: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
    v2_headers: true,
  },
  routes(defineRoutes) {
    return createRoutesFromFolders(defineRoutes);
  },
};
```

package.json scripts : 
```
"scripts": {
    "build": "remix build",
    "build:sourcemap": "remix build --sourcemap",
    "dev": "remix dev",
    "start": "remix-serve build"
  },
```

**Comment by pcattori** [comment] 2023-06-08 12:44
Other users have had significant slowdowns due to slow CSS compilation.

#6535 may (partially or entirely) address this.

**Comment by lili21** [comment] 2023-06-09 05:39
I ran into similar issue. https://github.com/remix-run/remix/discussions/6539

I upgrade from deferred to latest version, the (re)building time has increased about 4 times.

**Comment by pcattori** [comment] 2023-06-15 18:27
v1.17.1 just released which includes a couple perf improvements for the CSS compilation

**Comment by samadadi** [comment] 2023-06-15 19:51
I am using remix 1.17.1 with tailwind with 10 routes and almost 30 components and it takes 3 seconds just to update a single component. This is horrible. My laptop has 2.5GHz cpu with  4 core 8G ram.

**Comment by pcattori** [comment] 2023-06-15 20:00
> I am using remix 1.17.1 with tailwind with 10 routes and almost 30 components and it takes 3 seconds just to update a single component. This is horrible. My laptop has 2.5GHz cpu with 4 core and 8G ram.

@samadadi can you provide a reproduction?

**Comment by pcattori** [comment] 2023-06-15 20:04
> To have an iso repo, it will be hard since it's for a client, but I can have the same result with a newly created repository with createRemix.

@raskyer can you specify how you created that newly created repo? Which template did you use?

**Comment by samadadi** [comment] 2023-06-15 22:03
> @samadadi can you provide a reproduction?

Since actual project has more private data I can't publish it. But I cloned remix-tailwind example from remix repository and change some settings and updated `package.json` file and add more than 10 routes that is similar to my actual project. But the result is almost the same even in this simple project. It almost took 2 seconds to rebuild a single route file.
Repository: [https://github.com/samadadi/remix-tailwind-boilerplate](https://github.com/samadadi/remix-tailwind-boilerplate)

![Screenshot from 2023-06-16 01-07-39](https://github.com/remix-run/remix/assets/18693428/32e23202-2e99-4504-949f-f3765307c91a)

**Comment by pcattori** [comment] 2023-06-17 01:45
@samadadi Did some perf profiling. Looks like your app is bound by CSS compilation time. I did notice that the browser JS compilation was also slow. I tracked it down to the polyfills we do for the browser. Removing them sped up the JS part of the compilation from ~450ms to ~30ms (15x faster). Definitely something we can look to optimize, though not sure how much low hanging fruit there will be there.

<img width="709" alt="Screenshot 2023-06-16 at 9 43 29 PM" src="https://github.com/remix-run/remix/assets/1477317/6084147c-1dc5-4cd9-91c0-1cbf6c72cf33">

👆first run is normal, second run is with browser js polyfills disabled.

**Comment by pcattori** [comment] 2023-06-17 03:03
@raskyer have you tried using [path imports as described in MUI docs](https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports)? You could verify if that has any effect on treeshaking my checking the contents of the chunks in `public/build` or just your `build/index.js`.

You could also try using `esm` as your [server module format](https://remix.run/docs/en/1.17.1/file-conventions/remix-config#servermoduleformat) since CJS (I _think_) cannot be treeshaken.

**Comment by samadadi** [comment] 2023-06-17 08:47
@pcattori How can i profile my remix app? I appreciate if you help or provide a tutorial link.

**Comment by raskyer** [comment] 2023-06-17 16:34
@pcattori 
https://github.com/raskyer/remix-issue

The issue comes from : @mui/icons-material without a doubt.
Mui itself do not really take so long but when icons are added ...

![image](https://github.com/remix-run/remix/assets/16725289/7387c813-fff5-4732-bd18-740c797b4bee)

**Comment by raskyer** [comment] 2023-06-17 16:36
I think my client project is worst since it has more routes, more styles, components, etc ... but this major dump from just importing icons is probably one good step to fix

**Comment by raskyer** [comment] 2023-06-17 16:37
Here is the same project without the single import of icons : 
![image](https://github.com/remix-run/remix/assets/16725289/bc8efe14-733a-40c9-8b87-89ece3005bce)

**Comment by juniorforlife** [comment] 2023-06-18 14:43
I have the same issue with Tailwind. The app breaks a couple times a day for no reason while I'm making changes. I have to restart the server again. It happens on all browsers. Another issue is on Firefox, CSS doesn't get updated unless I specifically hit the reload button

**Comment by pcattori** [comment] 2023-06-18 15:01
> I have the same issue with Tailwind. The app's CSS breaks a couple times a day for no reason while I'm making changes. I have to restart the server again. It happens on all browsers. Another issue is on Firefox, CSS doesn't get updated unless I specifically hit the reload button

This discussion is about performance. Sounds like what you are experiencing is a different issue. If you are able to share a reproduction in a separate issue, I'd be happy to take a look.

**Comment by juniorforlife** [comment] 2023-06-18 15:49
@pcattori sure. I'll create a repo with screen recording tomorrow

**Comment by markdalgleish** [comment] 2023-06-19 21:56
@raysker Other than icons, I was able to further improve rebuild speeds by rewriting the other MUI imports in `root.tsx`.

```diff
-import {
-  CssBaseline,
-  unstable_useEnhancedEffect as useEnhancedEffect,
-  type ThemeOptions,
-  createTheme,
-} from "@mui/material";
+import type { ThemeOptions } from "@mui/material";
+import createTheme from "@mui/material/styles/createTheme";
+import useEnhancedEffect from "@mui/material/utils/useEnhancedEffect";
+import CssBaseline from "@mui/material/CssBaseline";
```

**Comment by raskyer** [comment] 2023-06-19 22:00
@markdalgleish Remix do not tree shake those ? It is surprising to see such a slowdown by importing the lib with ease (it's the prefered way to import things by Mui docs itself).

Or maybe Mui is misleading ? It will be a big refactoring to do in my client app to transform all those imports.

**Comment by markdalgleish** [comment] 2023-06-19 22:04
They should get tree shaken but the bundler will still walk the source code, and in the case of a component library like MUI that's quite a lot.

**Comment by pcattori** [comment] 2023-06-21 01:02
@samadadi some perf improvements just landed.

## before (1.17.1)

<img width="857" alt="Screenshot 2023-06-20 at 8 59 15 PM" src="https://github.com/remix-run/remix/assets/1477317/1fc89d83-0efc-4775-8644-9b02cca6869f">

👆 ~650ms build and ~400ms rebuilds

## after (`dev` branch + some inflight PRs)

Includes https://github.com/remix-run/remix/pull/6653

<img width="876" alt="Screenshot 2023-06-20 at 9 00 26 PM" src="https://github.com/remix-run/remix/assets/1477317/e2e2e409-669a-4d5b-a0e2-e160ba55ac1a">
 👆 ~180ms build and ~90ms rebuilds

**Comment by TheRealFlyingCoder** [comment] 2023-06-21 03:58
@pcattori Do we have any ways of profiling / logging out detailed metrics for the build to locate problem packages / areas?

**Comment by pcattori** [comment] 2023-06-21 04:12
> @pcattori Do we have any ways of profiling / logging out detailed metrics for the build to locate problem packages / areas?
> 
> Switching over to the nightly build, i'm still working with a 21.8s build time 👀
> 
> EDIT: After building once, it only takes 10s the second time, if I run dev I get 3-4s rebuilds which is still quite slow

We just merged a bunch of performance improvements today that aren't yet in `nightly`. You can try again tomorrow to see if you got any perf improvements.

**Comment by pcattori** [comment] 2023-06-26 17:51
Closing this as 1.18.0 was released including performance fixes/improvements that target all of the reproductions in this issue. If you have poor perf in your app, please open a separate issue.

**Closed by pcattori** 2023-06-26 17:51 UTC
Labels: package:dev, bug:unverified

**Comment by lili21** [comment] 2023-07-04 04:17
> @raskyer Other than icons, I was able to further improve rebuild speeds by rewriting the other MUI imports in `root.tsx`.
> 
> ```diff
> -import {
> -  CssBaseline,
> -  unstable_useEnhancedEffect as useEnhancedEffect,
> -  type ThemeOptions,
> -  createTheme,
> -} from "@mui/material";
> +import type { ThemeOptions } from "@mui/material";
> +import createTheme from "@mui/material/styles/createTheme";
> +import useEnhancedEffect from "@mui/material/utils/useEnhancedEffect";
> +import CssBaseline from "@mui/material/CssBaseline";
> ```

can we provide a config to do this automatically? like [modularizeImports](https://nextjs.org/docs/architecture/nextjs-compiler#modularize-imports)
