### ISSUE TITLE
Await loop rendering, when using fetcher.submit or revalidate

### ISSUE THREAD

**Issue by wmdmomo** [remix-run/remix#7809] opened 2023-10-29 13:19 UTC
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

`list, list2` is the value of defer, wrap it with `useMemo  Promise.all([list, list2])`
When using `fetcher.submit` or `revalidate`, there will be a problem of repeated page rendering.

Log information has been added to the Await component to help troubleshoot problems. When using fetcher.submit or revalidate, it is found that `await step4` , `await step9` ,`render again`are being printed in a loop
Below is my code

``` typescript
export default function Index() {
  const { list, list2 } = useLoaderData<typeof loader>();
  const { revalidate } = useRevalidator();
  const { submit, load } = useFetcher();
  const promise = useMemo(() => Promise.all([list, list2]), [list, list2]);

  console.log('render again');
  return (
    <div>
      <h1 onClick={() => load('/api/adjust')}>fetcher.load click</h1>
      <h1
        onClick={() => submit(null, { action: '/api/adjust', method: 'post' })}
      >
        fetcher.submit click
      </h1>
      <h1 onClick={revalidate}>revalidate click</h1>
      <Suspense fallback={<div>fallback</div>}>
        <Await resolve={promise}>
          {([list, list2]) => {
            return (
              <>
                {list?.map((item) => (
                  <div key={item.name} style={{ color: 'red' }}>
                    {item?.name}
                  </div>
                ))}
                {list2?.map((item) => (
                  <div key={item.name} style={{ color: 'yellowgreen' }}>
                    {item?.name}
                  </div>
                ))}
              </>
            );
          }}
        </Await>
      </Suspense>
    </div>
  );
}
```

The following is the source code of the Await component. I added some log statements
``` typescript
if (!(resolve instanceof Promise)) {
      // Didn't get a promise - provide as a resolved promise
      status = AwaitRenderStatus.success;
      promise = Promise.resolve();
      Object.defineProperty(promise, "_tracked", {
        get: () => true
      });
      Object.defineProperty(promise, "_data", {
        get: () => resolve
      });
      console.log('await step 1')
    } else if (this.state.error) {
      // Caught a render error, provide it as a rejected promise
      status = AwaitRenderStatus.error;
      let renderError = this.state.error;
      promise = Promise.reject().catch(() => {}); // Avoid unhandled rejection warnings
      Object.defineProperty(promise, "_tracked", {
        get: () => true
      });
      Object.defineProperty(promise, "_error", {
        get: () => renderError
      });
      console.log('await step 2')
    } else if (resolve._tracked) {
      // Already tracked promise - check contents
      promise = resolve;
      status = promise._error !== undefined ? AwaitRenderStatus.error : promise._data !== undefined ? AwaitRenderStatus.success : AwaitRenderStatus.pending;
      console.log('await step 3')
    } else {
      // Raw (untracked) promise - track it
      status = AwaitRenderStatus.pending;
      Object.defineProperty(resolve, "_tracked", {
        get: () => true
      });
      promise = resolve.then(data => Object.defineProperty(resolve, "_data", {
        get: () => data
      }), error => Object.defineProperty(resolve, "_error", {
        get: () => error
      }));
      console.log('await step 4')
    }
    if (status === AwaitRenderStatus.error && promise._error instanceof AbortedDeferredError) {
      // Freeze the UI by throwing a never resolved promise
      console.log('await step 5')
      throw neverSettledPromise;
    }
    if (status === AwaitRenderStatus.error && !errorElement) {
      // No errorElement, throw to the nearest route-level error boundary
      console.log('await step 6')
      throw promise._error;
    }
    if (status === AwaitRenderStatus.error) {
      // Render via our errorElement
      console.log('await step 7')
      return /*#__PURE__*/React.createElement(AwaitContext.Provider, {
        value: promise,
        children: errorElement
      });
    }
    if (status === AwaitRenderStatus.success) {
      // Render children with resolved value
      console.log('await step 8')
      return /*#__PURE__*/React.createElement(AwaitContext.Provider, {
        value: promise,
        children: children
      });
    }
    console.log('await step 9')
    // Throw to the suspense boundary
    throw promise;
```

### Expected Behavior

There should be no loop rendering issues

### Actual Behavior

When using fetcher.submit or revalidate, it is found that` await step4 , await step9 ,render again`are being printed in a loop

https://github.com/remix-run/remix/assets/43945660/1d8f1521-ab16-48de-8601-36a8dfa2aa1a

**Comment by brophdawg11** [comment] 2023-10-30 15:01
I believe this is a duplicate of https://github.com/remix-run/remix/issues/7392.  From an initial investigation it seemed the `useMemo` behavior wasn't working right even though it looked like the promise instances were stable aross re-renders.  I'm going to close this out and we can continue digging in over there.

**Closed by brophdawg11** 2023-10-30 15:01 UTC
Labels: bug:unverified
