### ISSUE TITLE
some browser extensions prevent css render 

### ISSUE THREAD

**Issue by HossamMarey** [remix-run/remix#5020] opened 2023-01-06 15:28 UTC
### What version of Remix are you using?

1.9.0

### Steps to Reproduce

This happens with chrome extensions like 'Fair AdBlocker' and 'Grammer & Spell Checker' 
so i have tried it with the default configuration and this throw errors in development and production

those errors disappear when disable all extensions 

### Expected Behavior

no errors

### Actual Behavior

errors in  production (vercel deployment)
![image](https://user-images.githubusercontent.com/16583413/211043068-09aed343-afce-4a17-a9c5-3bdd95aed69c.png)

errors in development 
![image](https://user-images.githubusercontent.com/16583413/211043267-184c8bbf-29a2-4550-956c-63e615485c07.png)

**Comment by OnurGvnc** [comment] 2023-01-10 10:16
+1

related:
- https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code
- https://github.com/remix-run/remix/issues/4822
- https://github.com/remix-run/remix/discussions/4902
- https://github.com/remix-run/remix/issues/4651

**Comment by OnurGvnc** [comment] 2023-01-13 10:15
I was able to resolve my issue by invoking [`removeInjectedHtmlForReactHydration()`](https://gist.github.com/OnurGvnc/31f03f0d5237b78224aa083493fda645) prior to executing `hydrateRoot()`.
https://gist.github.com/OnurGvnc/31f03f0d5237b78224aa083493fda645

**Comment by clgeoio** [comment] 2023-01-24 23:32
I have created a discussion for this issue: https://github.com/remix-run/remix/discussions/5244

**Comment by brophdawg11** [comment] 2023-08-09 19:32
Duplicate of https://github.com/remix-run/remix/issues/4822

**Closed by brophdawg11** 2023-08-09 19:32 UTC
Labels: bug:unverified, hydration
