### ISSUE TITLE
Cookie serialize function failes to serialize emojis (not sure this is a bug)

### ISSUE THREAD

**Issue by iamrane** [remix-run/remix#1962] opened 2022-02-15 08:38 UTC
### What version of Remix are you using?

1.1.3

### Steps to Reproduce

in app/cookies.js

```js
import { createCookie } from "remix";

export const userPrefs = createCookie("user-prefs", {
  maxAge: 604_800 // one week
});
```

in app/routes/index.js
```js
import { userPrefs } from "~/cookies";

export async function loader({ request }) {
  const cookieHeader = request.headers.get("Cookie");
  const cookie =
    (await userPrefs.parse(cookieHeader)) || {};
  return { showBanner: cookie.showBanner };
}

export async function action({ request }) {
  const cookieHeader = request.headers.get("Cookie");
  const cookie =
    (await userPrefs.parse(cookieHeader)) || {};
  cookie.showBanner = '😀';
  
  return redirect("/", {
    headers: {
      "Set-Cookie": await userPrefs.serialize(cookie)
    }
  });
}
```

### Expected Behavior

After submit i expect cookie = { showBanner: '😀'' } in the loader function.

### Actual Behavior

After submit cookie = {};

If I change 😀 to 'hello' it works like a charm.

I know this is maybe not your top prio haha

**Comment by merelinguist** [comment] 2022-02-15 14:01
What browser are you using?

**Comment by iamrane** [comment] 2022-02-15 14:03
Ah yeah, Version 98.0.4758.80
On MacOS 12.1

**Comment by confix** [comment] 2022-02-17 17:36
Duplicate of https://github.com/remix-run/remix/issues/1282?

**Comment by machour** [comment] 2022-03-17 21:52
Tracked in #1282

**Closed by machour** 2022-03-17 21:52 UTC
Labels: bug
