### ISSUE TITLE
Cloudflare worker adapter is not passing the platform context to the Remix application

### ISSUE THREAD

**Issue by dario-piotrowicz** [remix-run/remix#5655] opened 2023-03-03 22:28 UTC
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a standard Remix application by choosing the Cloudflare worker adaptor, add a loader like the following to your index.tsx:
```ts
export async function loader({ request, context, params }: DataFunctionArgs) {
  const contextKeys = Object.keys(context).join(", ");

  return {
    contextKeys,
  };
}
```

In the component itself log out the value:
```ts
export default function Index() {
  const data = useLoaderData<ReturnType<typeof loader>>();

  useEffect(() => {
    console.log({ data });
  }, [data]);
```

Add a Cloudflare binding to your wrangler.toml file, for example a [KV binding](https://developers.cloudflare.com/workers/runtime-apis/kv/#kv-bindings):
```toml
[[kv_namespaces]]
  binding = "MY_KV"
  id = "..."
```

Finally deploy your application

### Expected Behavior

when you access your application via your browser you should see "KV" being included in the contextKeys (or you should have an `env` which in turn would include the `MY_KV` field)

### Actual Behavior

There isn't any `MY_KV` field, nor a way to access your KV binding

**Comment by dario-piotrowicz** [comment] 2023-03-03 22:30
I think that the issue is just that the adaptor is missing an appropriate  `getLoadContext` here:

https://github.com/remix-run/remix/blob/3d3079bfd5d18ab9efe8e3e79935939cfdfb7e11/templates/cloudflare-workers/server.js#L6

**Comment by dario-piotrowicz** [comment] 2023-03-03 22:32
(PS: less relevant but also Cloudflare's ctx values such as `waitUntil` are not accessible either)

**Comment by johtso** [comment] 2023-03-04 01:51
You might find this project useful as a reference: https://github.com/Girish21/remix-cloudflare-workers-template

**Comment by huw** [comment] 2023-03-04 03:13
This is the intended behaviour IIRC, it’s up to the user to define their own `getLoadContext` escape hatch to pass through the context values they want available. The adapter supports this fine, I guess you’re asking for the `cloudflare-workers` template to define `getLoadContext` by default?

**Comment by dario-piotrowicz** [comment] 2023-03-04 13:34
@huw yeah you're totally right (thanks a lot for clarifying and sorry about getting it wrong), to be honest I thought that the template I linked was just used internally and not exposed to the developer (making the context unacessible) but it actually is, so you can indeed just add your own `getLoadContext` :sweat: 

Moreover the adapter here is using the service worker syntax so it is putting the env bindings in the global scope, so they are indeed available there anyways

<details>

<summary>Example</summary>

for example this works fine:
```ts
declare const MY_KV: KVNamespace;

export async function loader({ request }: DataFunctionArgs) {
  return {
    MY_ITEMS: JSON.stringify(await MY_KV.list()),
  };
}

```

</details>

There is a chance that the developer can need to access things that aren't added to the global scope as [`waitUntil`](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil) but in that case it should be easy enough to provide their own `getLoadContext` as you mention.

So I think that I'd be ok to just close this issue as I misunderstood Remix implementation, but I can also update it to provide a default `getLoadContext` as that could also be valuable maybe? What do you think @huw?

**Comment by huw** [comment] 2023-03-05 07:38
Yeah, because of the way Remix is bundled it’s preferable to pass the variables through `getLoadContext` regardless of whether you’re on Service Workers or ESM.

The issue with setting a default `getLoadContext` will be typing it. The idiomatic way to type `AppLoadContext` is to override it in a `.d.ts` file, which is going to be tricky to share with the `Environment` parameter (in ESM) or global scope declaration (in Service Workers). Unless you have a clever solution to that it’s probably best for the user to add and type it themselves?

**Comment by dario-piotrowicz** [comment] 2023-03-06 12:21
I think that for esm workers we could specify the the return type of `getLoadContext` contains `Env` and `ExecutionContext` type variables, the same that are used in the worker itself:
![Screenshot 2023-03-06 at 12 13 06](https://user-images.githubusercontent.com/61631103/223107457-9da39b50-6235-41f9-bdd9-906b750ea6ab.png)

then we could have a `.d.ts` file which contains the Env type which can be tweaked by the developer, that could work for esm workers right? (anyways we don't even have an esm adaptor at the moment 😓)

but regarding service-worker workers we could sort of emulate that for `ExecutionContext`, but taking bindings from the global scope it's indeed going to be tricky....

**Comment by jaitaiwan** [comment] 2023-03-17 12:29
I just wanted to note that I was starting a new project with the cloudflare-pages template; using the instructions provided by [this course](https://egghead.io/courses/build-a-realtime-chat-app-with-remix-and-supabase-d36e2618) to setup supabase with remix. The instructions talked about adding env vars, and the env vars section took me to using `.dev.vars` to see variables automatically passed in. I have had the same issue where they exist in the root loader and then when using `useLoaderData` they're undefined.

Because I'm using the template, I'm not really sure what the options are for solving this, even having read the above.

**Comment by dario-piotrowicz** [comment] 2023-03-17 17:48
Which section of the course was instructing to set the env vars?

If you're using the pages adaptor then you should get your env variables from `contex`  (provided in your action or loader parameter)

Could you share your code maybe?

**Comment by jaitaiwan** [comment] 2023-03-18 02:49
It's [lesson five](https://egghead.io/lessons/github-implement-authentication-for-supabase-with-oauth-and-github). So with that one they're recommending using `process.env` there which [according to the docs](https://remix.run/docs/en/1.14.3/guides/envvars#md-local-development) doesn't exist in cloudflare pages so you replace process.env with context, and put the variables in `.dev.vars` instead of `.env`.

So using the code from the tutorial, this:
```
export const loader = async ({}: LoaderArgs) => {
  const env = {
    SUPABASE_URL: process.env.SUPABASE_URL!,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY!,
  };

  return json({ env });
};
```

becomes this:
```
export const loader = async ({ context }: LoaderArgs) => {
  const env = {
    SUPABASE_URL: context.SUPABASE_URL!,
    SUPABASE_ANON_KEY: context.SUPABASE_ANON_KEY!,
  };

  return json({ env });
};
```

And in the root component which uses the following code:
```
const { env } = useLoaderData<typeof loader>();
```

`env` is empty, but context in the loader has the correct variables.

**Comment by dario-piotrowicz** [comment] 2023-03-20 23:09
I'm not sure, your code does look correct to me.... did you try passing something else (list a constant string) in the `env` to see if that does anything?

**Comment by jaitaiwan** [comment] 2023-03-21 04:12
@dario-piotrowicz I can give it a go. I already moved on to using vercel instead of cloudflare pages, so I'll try with a new project and let you know.

**Comment by brophdawg11** [comment] 2023-05-04 19:51
Closing per https://github.com/remix-run/remix/issues/5655#issuecomment-1454742058

**Closed by brophdawg11** 2023-05-04 19:51 UTC
Labels: adapter:cloudflare-workers, bug:unverified
