### ISSUE TITLE
Application crashes on unhandled promise rejection in deferred data

### ISSUE THREAD

**Issue by merthanmerter** [remix-run/remix#9340] opened 2024-04-29 20:02 UTC
### Reproduction

When an error is thrown in the deferred data, the application crashes with an unhandled promise rejection error. Returning an error response instead does not signal an error to the Await element.

**Concern:**
Using `process.on('unhandledRejection', (reason, promise) => -1);` in entry.server as a workaround doesn't seem like a best practice.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 3.05 GB / 15.82 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.0.0 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.0.26 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (117.0.2045.36)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/css-bundle: ^2.9.1 => 2.9.1 
    @remix-run/dev: ^2.9.1 => 2.9.1 
    @remix-run/express: ^2.9.1 => 2.9.1 
    @remix-run/node: ^2.9.1 => 2.9.1 
    @remix-run/react: ^2.9.1 => 2.9.1 
    @remix-run/serve: ^2.9.1 => 2.9.1 
    vite: ^5.2.10 => 5.2.10
```

### Used Package Manager

npm

### Expected Behavior

The application should handle errors in deferred data gracefully without crashing.

### Actual Behavior

Currently, when an error is thrown in deferred data, the application crashes due to an unhandled promise rejection, showing the following error message:

```shell
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Response>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by merthanmerter** [comment] 2024-04-29 20:05
Actual code:

```ts
export async function getFilesByParent(request: Request, params: Params) {
  try {
    const db = await tenantDb({ request, permissions: [UserPermissions.GetFiles] });

    const { parentId, parentType } = parentSchema.parse(params);
    const id = await http.parser.id(parentId);

    return await db.query.files
      .findMany({ where: and(eq(files.parentId, id), eq(files.parentType, parentType)) })
      .execute();
  } catch (err) {
    throw jsonErrorResponse(err);
  }
}
```

```ts
export async function parseId(value: string | undefined) {
  return await idSchema.parseAsync(value).catch(() => {
    throw http.err.NotAcceptable('Invalid id!');
  });
}
```

**Comment by brophdawg11** [comment] 2024-04-30 13:26
I think this is a duplicate of https://github.com/remix-run/remix/issues/9178 and IIRC in that case the issue was that the promise was rejecting _before_ being handed to `defer`.  `defer` will handle rejected promises if they reject after `defer` is called because it wires up a `.catch` handler internally.  So there wasn't anything Remix can do because it's crashing in the raw node process before the `defer` is invoked.

**Comment by merthanmerter** [comment] 2024-04-30 14:29
> I think this is a duplicate of #9178 and IIRC in that case the issue was that the promise was rejecting _before_ being handed to `defer`. `defer` will handle rejected promises if they reject after `defer` is called because it wires up a `.catch` handler internally. So there wasn't anything Remix can do because it's crashing in the raw node process before the `defer` is invoked.

Ok, then this seems to be the correct workaround, or maybe using custom server for api endpoints. (?)

> This is standard node behavior on unhandled promise rejections. As of Node 16 (I think) they started terminating the process if left unhandled. `defer` will handle the rejections _if it has been wired up prior to the rejection_. But in this case, specifically you create a promise that Remix knows nothing about, and it rejects before you hand it off to `defer`, and because it's unhandled it terminates the process.
> 
> A quick workaround is to just hand the promise to defer at creation time, but the true fix is to add a [handler for unhandled rejections](https://nodejs.org/api/process.html#event-unhandledrejection) which will prevent the server from terminating. You could add something like this in your `entry.server.tsx` or express server:
> 
> ```js
> process.on("unhandledRejection", (reason: string, p: Promise<any>) => {
>   console.error("Unhandled Rejection at:", p, "reason:", reason);
> });
> ```

**Comment by brophdawg11** [comment] 2024-04-30 20:17
> ps: this makes defer completely useless imo.

This is unhelpful and quite frankly pretty rude for a piece of software you get to use _completely free_.

What exactly do you expect `defer` to do if the node process crashes _before your code even calls `defer`_?  As discussed in the linked issue, this is not specific or related to Remix - https://github.com/remix-run/remix/issues/9178#issuecomment-2032430025:

> Just to completely rule out Remix, I also made [a repro using Express](https://stackblitz.com/edit/stackblitz-starters-qw192k?description=&file=pages%2Findex.html,index.js&title=Express%20Starter), and it crashes in the same way.

We'd appreciate it if you'd try to be a bit more thoughtful in your future issues and responses.

**Closed by brophdawg11** 2024-04-30 20:17 UTC
Labels: bug:unverified, feat:deferred

**Comment by merthanmerter** [comment] 2024-04-30 23:54
> > ps: this makes defer completely useless imo.
> 
> This is unhelpful and quite frankly pretty rude for a piece of software you get to use _completely free_.
> 
> What exactly do you expect `defer` to do if the node process crashes _before your code even calls `defer`_? As discussed in the linked issue, this is not specific or related to Remix - [#9178 (comment)](https://github.com/remix-run/remix/issues/9178#issuecomment-2032430025):
> 
> > Just to completely rule out Remix, I also made [a repro using Express](https://stackblitz.com/edit/stackblitz-starters-qw192k?description=&file=pages%2Findex.html,index.js&title=Express%20Starter), and it crashes in the same way.
> 
> We'd appreciate it if you'd try to be a bit more thoughtful in your future issues and responses.

My intention wasn't to be rude. I was just pointing out my opinion. I just don't agree this should be the default behaviour [#9178 ](https://github.com/remix-run/remix/issues/9178#issuecomment-2034678456) Sorry that I did it for a software "I use for free". Maybe I should just not use a software I can't criticize then.
