### ISSUE TITLE
Remix's <Form> doesn't respect <button> formMethod attribute

### ISSUE THREAD

**Issue by tarngerine** [remix-run/remix#4337] opened 2022-10-06 22:00 UTC
### What version of Remix are you using?

1.7.2

### Steps to Reproduce

Reproduction: https://codesandbox.io/s/silly-currying-qpb8iu?file=/app/root.jsx

1. Click Get for Remix Form, see console log -> GET
2. Click Get for Regular form, see console log -> GET
3. Click Post for Regular form, see console log -> POST
4. Click Post for Remix Form, see console log -> GET. **This is wrong**

### Expected Behavior

Remix's `<Form>` should respect the child `<button>`'s `formMethod` attribute, allowing multiple buttons with different formMethods inside one form

### Actual Behavior

Remix Form ignores formMethod and treats all buttons as GET

**Comment by machour** [comment] 2022-10-13 19:09
Fixed by #4053

**Comment by machour** [comment] 2022-10-20 19:18
Released in 1.7.3 🎉

**Closed by machour** 2022-10-20 19:18 UTC
Labels: bug, feat:forms, awaiting release

**Comment by maxschwarzmueller** [comment] 2022-10-24 15:11
This new release breaks the `method` prop of `<Form>` though. Is that an intended change?

This code will now lead to a `POST` request being sent, instead of a `DELETE` request:

```jsx
<Form method="delete">
  <button>Delete</button>
</Form>
```

This action would therefore fail / not work as intended:

```js
export function action({request}) {
  if (request.method === 'DELETE') {
    // do stuff, delete something...
    return redirect('/');
  }
}
```

You would instead have to write this code to make it work:

```jsx
<Form method="delete">
  <button formMethod="delete">Delete</button>
</Form>
```

This is not very intuitive and probably not how it should work. Especially since the [docs state](https://remix.run/docs/en/v1/api/remix#form-method): 
> "This determines the HTTP verb to be used: get, post, put, patch, delete."

**Comment by machour** [comment] 2022-10-25 04:08
@maxschwarzmueller if that's the case, then it's totally unintentional. Could you fill in a new issue, or better, a PR with a failing test? (See instructions when opening an issue)

**Comment by maxschwarzmueller** [comment] 2022-10-25 07:38
Sure, I opened #4412 with a failing test.
I also opened #4413 with a possible fix
