### ISSUE TITLE
Remix V1 to V2: `Module '"@remix-run/node"' has no exported member 'fetch'.ts(2305)`

### ISSUE THREAD

**Issue by cliffordfajardo** [remix-run/remix#7567] opened 2023-10-02 00:10 UTC
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Was starting to upgrade to Remix V2, then I started seeing this error message in my app:

```ts
import { fetch } from "@remix-run/node"; // ❌Module '"@remix-run/node"' has no exported member 'fetch'.ts(2305)

import { Response } from "@remix-run/node"; // ❌Module '"@remix-run/node"' has no exported member 'Response
```

I know this is because `fetch` export was removed the `@remix-run/node` package per this PR  #7293 

### Question
**Is the only way to reliably get proper `fetch` typing for `fetch` on the server/nodejs to import it?**

`installGlobals` doesn't help because when I COMMAND + CLICK into `fetch` implementation, I am taken to this type definition file located here:

```
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts
```

The browser implementation of `fetch` obviously doesnt have types for passing things like `agent` & other nodejs specif stuff to `fetch`'s request options object.

For example, in my remix app, we need to pass a custom agent to our fetch

```ts
const response = await fetch(`example.com`, {
    method: "GET",
    headers: {
      "Content-type": "application/json",
    },
    agent: new https.Agent({ rejectUnauthorized: false, requestCert: false }), // <----🟡
  });
   return await response.json();
};
```

**Comment by cliffordfajardo** [comment] 2023-10-02 00:33
Should `fetch` be re-exported back from `@remix-run/node`?

I think that would be nice, and users won't need to go install `node-fetch` to be able to pass nodejs specific options (ex: `agent`) to the `fetch`'s request options

**Comment by cliffordfajardo** [comment] 2023-10-02 00:44
Tried using  `import { fetch } from "@remix-run/web-fetch";` but when I run `npm run build` in my v2 project, now getting lots of errors:

```
❌ [ERROR] No matching export in "node_modules/@remix-run/web-fetch/src/lib.js" for import "fetch"

    app/apps/@dwdm-ui/services/server/getAllDCMetroDevices/getAllDCMetroDevices.ts:3:9:
      3 │ import { fetch } from "@remix-run/web-fetch";
```
![CleanShot 2023-10-01 at 17 44 03](https://github.com/remix-run/remix/assets/6743796/c11b9a73-f04a-4751-be8b-edbb66f193cb)

**Comment by cliffordfajardo** [comment] 2023-10-02 01:04
I think the temp solution is for me to install `node-fetch` 😢 ahh extra dependency

**Comment by brophdawg11** [comment] 2023-10-02 14:40
Importing from the global namespace is by design in v2 as we want to lean more into the platform/built-ins.  If `fetch` were stable in node 18 we would have completely dropped our polyfills.  However, since it's still experimental we have kept them but we don't export them so you still use the polyfilled global.  The idea being that eventually when you _are_ ready to use the built-in - you just remove `installGlobals()` and you don't have to go change a ton of imports.  This also means that if we find type discrepancies between native node `fetch` and our package - it's something we need to address to get our polyfill in line with the native behavior/spec.

It looks we need to dig into the typings and see what our options are there for differences between node `fetch` and the types in `lib.dom`.  Thank you for the reference above on the differences!

**Comment by brophdawg11** [comment] 2023-10-02 17:04
That would be incorrect though if they don't call `installGlobals`...

**Comment by ericallam** [comment] 2023-11-10 17:20
@brophdawg11 there are also inconsistencies around `installGlobals()`, specifically when the custom server *does not* call install globals and `remix-serve` is used in development (then remix will call `installGlobals` for you).

**Comment by brophdawg11** [comment] 2024-09-13 20:24
I'm going to close this out because we're adopting the native `undici` fetch.  The recommendation now is that if you are on Node 20+, you should just remove `installGlobals`.  If you are on Node 18, you can use [`installGlobals({ nativeFetch: true })`](https://remix.run/docs/en/main/guides/single-fetch#enabling-single-fetch) to opt-into `undici` instead of the Remix web fetch polyfill.

**Closed by brophdawg11** 2024-09-13 20:24 UTC
Labels: feat:typescript, bug:unverified, feat:fetch
