### ISSUE TITLE
remix-serve is incompatible with serverModuleFormat:esm

### ISSUE THREAD

**Issue by danestves** [remix-run/remix#6272] opened 2023-05-02 01:22 UTC
### What version of Remix are you using?

v1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Set the `serverModuleFormat` to `esm` and run the server

### Expected Behavior

Run without any issues

### Actual Behavior

Getting the `SyntaxError: Cannot use import statement outside a module` from the `build/index.js`

![](https://user-images.githubusercontent.com/31737273/235559478-0cfd08eb-c5fa-45cd-bdb9-7f3f5b0d7000.png)

![](https://user-images.githubusercontent.com/31737273/235559844-65a02d7d-3973-4b28-94a6-f4e97b00a687.png)

**Comment by herecydev** [comment] 2023-05-02 07:28
Can also confirm this seems broken. If you add `type: module` to the package.json and converting remix.config,js to ES module doesn't work either as `@remix-run/serve` uses require() to get the build.

**Comment by jakarlse88** [comment] 2023-05-05 12:36
Same issue here on `1.16.0`. Setting `serverModuleFormat` to `esm`, I receive:

```
GET / 500 - - 1.453 ms
/Users/<USERNAME>/source/hahaha/main/app/api/index.js:12
import { PassThrough } from "stream";
^^^^^^

SyntaxError: Cannot use import statement outside a module
     at Object.compileFunction (node:vm:360:18)
     at wrapSafe (node:internal/modules/cjs/loader:1119:15)
     at Module._compile (node:internal/modules/cjs/loader:1155:27)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
     at Module.load (node:internal/modules/cjs/loader:1069:32)
     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
     at Module.require (node:internal/modules/cjs/loader:1093:19)
     at require (node:internal/modules/cjs/helpers:108:18)
     at /Users/<USERNAME>/source/hahaha/node_modules/.pnpm/@remix-run+serve@1.16.0/node_modules/@remix-run/serve/dist/index.js:43:17
     at Layer.handle [as handle_request] (/Users/<USERNAME>/source/hahaha/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by tcschiller** [comment] 2023-05-14 03:50
> Can also confirm this seems broken. If you add type: module to the package.json and converting remix.config,js to ES module doesn't work either as @remix-run/serve uses require() to get the build.

Confirmed, I think, on my end too. I did what I can only assume are the required changes:

* changed `serverModuleFormat` to `esm`
* added `type: module` to my `package.json`
* changed `remix.config.js` to ES module

_Plus_, I added `@remix-run/serve` to the `serverDependenciesToBundle` array, just for good measure, and still I get the error about `require()` in the serve code.

**Comment by willopez** [comment] 2023-05-16 00:23
yup, this is broken for me too, using the nightly version of Remix

**Comment by oliverjam** [comment] 2023-05-19 11:34
Yeah ESM is totally broken for me too, same issue with `@remix-run/serve` using `require` to import the build.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/oli/Code/my-app/build/index.js from /Users/oli/Code/my-app/node_modules/@remix-run/serve/dist/index.js not supported.
Instead change the require of /Users/oli/Code/my-app/build/index.js in /Users/oli/Code/my-app/node_modules/@remix-run/serve/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at /Users/oli/Code/my-app/node_modules/@remix-run/serve/dist/index.js:43:17
```

This is with a super minimal setup, nothing but `type: module` in `package.json` and `serverModuleFormat: esm` in `remix.config.js`. Using Remix 1.16.1

**Comment by muco-rolle** [comment] 2023-05-20 14:38
The same for me with Remix `1.16.1` anyone was able to find a fix for this?

**Comment by connorb08** [comment] 2023-05-20 17:13
> The same for me with Remix `1.16.1` anyone was able to find a fix for this?

Only fix I could find was changing serverModuleFormat back to cjs in remix config

**Comment by Industrial** [comment] 2023-05-27 16:30
I'm trying to use PureScript in Remix but can't because it can only produce ES Modules. It has no options for CJS, since that's an old format.

**Comment by alexbu92** [comment] 2023-05-30 10:12
> 

Add it to your server dependencies: https://remix.run/docs/en/1.16.1/pages/gotchas#importing-esm-packages

**Comment by Industrial** [comment] 2023-05-30 11:10
I did that. I have a PNPM monorepo with `packages/ui` which packages `@code9/todo-ui` which is written in PureScript and produces a JS file that is an ESM.

Then in `apps/web` (Remix application) I use that module and I have it included in the server dependencies:

```js
serverDependenciesToBundle: ['react-movable', '@code9/todo-ui']
```

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/tom/Code/code9/node/test-astro-solid/packages/ui/dist/index.js from /home/tom/Code/code9/node/test-astro-solid/apps/web/build/index.js not supported.
Instead change the require of /home/tom/Code/code9/node/test-astro-solid/packages/ui/dist/index.js in /home/tom/Code/code9/node/test-astro-solid/apps/web/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/tom/Code/code9/node/test-astro-solid/apps/web/build/index.js:287:19)
    at /home/tom/Code/code9/node/test-astro-solid/node_modules/.pnpm/@remix-run+serve@1.16.1/node_modules/@remix-run/serve/dist/index.js:43:17
```

**Comment by quinn** [comment] 2023-07-26 19:31
getting this error when trying to use the template: " The template could not be verified. Please double check that the template is a valid GitHub repository and that the filepath points to a directory in the repo and try again."

**Comment by brophdawg11** [comment] 2023-08-01 15:50
That branch has been merged to `dev`, you can now run 

```
npx create-remix --template https://github.com/remix-run/remix/tree/dev/templates/express
```

You may also need to install `@remix-run/serve` as a `devDependency` in the created app.

**Comment by jacob-ebey** [comment] 2023-08-07 17:53
remix-serve has been updated as part of this PR, but I'm having trouble with windows CI: https://github.com/remix-run/remix/pull/6949

**Closed** 2023-08-10 00:32 UTC
Labels: package:serve, v2

**Comment by wolfiecoder** [comment] 2023-08-10 19:54
@jacob-ebey just tried upgrading all my `@remix-run/*` dependencies to the `nightly` tag. However, I'm still seeing the `[ERR_REQUIRE_ESM]` issue :/.

**Comment by cjbland** [comment] 2024-01-14 18:11
> `@remix-run/serve` is not compatible with `serverModuleFormat: "esm"` in v1 because that would be a breaking change. Once v2 is released, it will be compatible with `serverModuleFormat: "esm"`.
> 
> For now, if you are using `@remix-run/serve` you should set `serverModuleFormat: "cjs"` in your `remix.config.js` to explicitly indicate your app setting which will silence the warning and ensure your app is able to upgrade to v2 without issues.

So does this mean in a v1 app that uses `@remix-run/serve` we cannot opt into the v2 "esm" format?
