### ISSUE TITLE
When parent route loads data using `useFetcher`, all child routes/components that use `useFetcher` gets re-rendered

### ISSUE THREAD

**Issue by hasanayan** [remix-run/remix#9528] opened 2024-05-30 20:39 UTC
### Reproduction

https://stackblitz.com/edit/remix-run-remix-ncybyj?file=app%2Froutes%2Fparent.child._index.tsx

The repro opens at `/parent/child` route. Parent route calls `useFetcher().load` every few seconds. Child route does not make any load calls but calls `useFetcher`. Whenever parent route gets re-rended, the child route/component that uses `useFetcher` gets re-rendered, too.

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.5.2 - /usr/local/bin/npm
    pnpm: 9.1.3 - /usr/local/bin/pnpm
    bun: 1.1.10 - ~/#####REDACTED#####/node_modules/.bin/bun
    Watchman: 2024.04.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.4.1
```

### Used Package Manager

npm

### Expected Behavior

calling `useFetcher` should trigger a re-render only when its data changes

### Actual Behavior

When a parent route/component calls `useFetcher.load` all child components/routes that use `useFetcher` gets re-rendered.

**Comment by nullndr** [comment] 2024-06-05 06:39
I have this issue as well.

In my case when I submit `fetcher.submi({}, { method: "POST" });` the whole route hierarchy gets revalidated.

**Comment by hasanayan** [comment] 2024-06-05 07:05
I'm not sure, it might make sense to revalidate the whole hierarchy, but what I reported is true even when all the routes' `shouldRevalidate` returns `false`

**Comment by nullndr** [comment] 2024-06-05 07:17
> it might make sense to revalidate the whole hierarchy

Not with a `useFetcher()`, since I use it in a place where the [URL does not change](https://remix.run/docs/en/main/discussion/form-vs-fetcher#form-vs-fetcher).

I simply use the `POST` method because I need to pass to my `action` some data in JSON.

**Comment by brophdawg11** [comment] 2024-06-06 18:38
Fetchers are managed through a single `Map` so when one updates they all update.  This is working as designed so I'm going to close this out, but feel free to write up a proposal in the Disscussions tab in the React Router repo if you'd like to propose a change to the fetcher behavior.

**Closed by brophdawg11** 2024-06-06 18:38 UTC
Labels: feat:routing, bug:unverified
