### ISSUE TITLE
HTTP2 Pseudo headers get rejected by Remix [\w Vite]

### ISSUE THREAD

**Issue by kazdegroot** [remix-run/remix#7867] opened 2023-11-01 22:32 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Use Vite plugin
2. Enable https for Vite, by setting `{ server: { https: true } }` 
3. Make sure there is something like a cert configured; e.g. using `vite-plugin-mkcert`
4. Start dev server
5. Visit site

### Expected Behavior

Site works

### Actual Behavior

Site throws the following error:

```
Unexpected Server Error

TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":authority"]
```

HTTPS in Vite will include HTTP2 by default, but also setting the `server.proxy` option (e.g. to `{}`), will fallback to just TLS. Everything works fine then.

**Comment by manzaloros** [comment] 2023-11-07 21:43
Hi, I'm having this same issue:

```
TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":authority"]
```

```
// vite.config.ts
import { unstable_vitePlugin as remix } from '@remix-run/dev';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import { SERVER_OPTION_KEY, SERVER_OPTION_CERT } from './setup-app-config.js';

export default defineConfig({
  plugins: [
    remix({
      ignoredRouteFiles: ['**/.*'],
      serverModuleFormat: 'esm',
      future: {},
    }),
    /*
      needed so Vite knows about tsconfig paths:
    */
    tsconfigPaths(),
  ],
  server: {
    port: 18267,
    https: {
      key: SERVER_OPTION_KEY,
      cert: SERVER_OPTION_CERT,
      rejectUnauthorized: false,
      requestCert: false,
    },
  },
});

```

**Comment by hi-ogawa** [comment] 2023-11-18 04:16
Thanks for raising the issue and providing contexts.
I investigated further based on a simple reproduction https://github.com/hi-ogawa/remix-reproduction-7867.

I think the issue goes like:
- vite dev server includes http2 pseudo headers when delegating a request to remix middleware,
- remix vite plugin injects polyfills for `Request`, `Headers`, etc... based on `@remix-run/web-fetch` package https://github.com/remix-run/remix/blob/f7062e43079fba6edb3fd04642fb8cba3ba09c67/packages/remix-dev/vite/node/adapter.ts#L12
- remix re-instantiates `Request` object with original headers when executing loader https://github.com/remix-run/remix/blob/f7062e43079fba6edb3fd04642fb8cba3ba09c67/packages/remix-server-runtime/data.ts#L127
- however `@remix-run/web-fetch` doesn't allow pseudo header such as `:authority`

Two solution/workaround I came up with are: 1. remove node polyfill https://github.com/hi-ogawa/remix-reproduction-7867/pull/1 or 2: filter out pseudo headers https://github.com/hi-ogawa/remix-reproduction-7867/pull/2

Interesting to note that, node's builtin `Headers` (since node 18) accept pseudo headers, but it throws in browser:

```txt
//// node repl
$ node
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> new Headers({ ":method": "GET" })
HeadersList {
  cookies: null,
  [Symbol(headers map)]: Map(1) { ':method' => { name: ':method', value: 'GET' } },
  [Symbol(headers map sorted)]: null
}

//// browser devtools
> new Headers({ ":method": "GET" })
VM109:1 Uncaught TypeError: Failed to construct 'Headers': Invalid name
    at <anonymous>:1:1
```

There are other issues due to remix injecting `Request` polyfills https://github.com/remix-run/remix/issues/7819#issuecomment-1788319813, so eventually removing polyfill would be a robust solution, but as a short term workaround, I'll put together a PR based on 2nd approach.

**Comment by pcattori** [comment] 2023-12-14 17:42
Fixed by https://github.com/remix-run/remix/pull/8062 and https://github.com/remix-run/web-std-io/pull/55

**Closed by pcattori** 2023-12-14 17:42 UTC
Labels: bug:unverified, vite

**Comment by BrandonNoad** [comment] 2024-04-19 15:20
> A workaround for this issue is enabling `server.proxy` in `vite.config`, which will downgrade vite server to http/1.1.
> 
> ```ts
> server: {
> 	proxy: {
> 		// ...
> 	},
> },
> ```

I ran into a similar issue when I switched to Remix Vite with the Cloudflare dev proxy and had to use the `proxy: {}` workaround above to solve it. I'm using v2.8.1 of all the Remix packages.
