### ISSUE TITLE
 SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by imcvampire** [remix-run/remix#5570] opened 2023-02-25 17:00 UTC
### What version of Remix are you using?

1.12.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Using `serverDependenciesToBundle` doesn't help.

1. Install and use `@lifi/widget` 
2. There is an error 
```
<svg width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 ^

SyntaxError: Unexpected token '<'
```

### Expected Behavior

No error 

### Actual Behavior

Error: 

``` 
<svg width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 ^

SyntaxError: Unexpected token '<'
```

**Comment by machour** [comment] 2023-02-25 17:51
Duplicate of #1909

**Closed by machour** 2023-02-25 17:51 UTC
Labels: bug:unverified
