### ISSUE TITLE
[Bug]: App crash on fast browser navigation

### ISSUE THREAD

**Issue by axel-xitaso** [remix-run/remix#1757] opened 2022-02-01 10:47 UTC
### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16.0.0

### Steps to Reproduce

1. Create a new Remix app with `npx create-remix@latest`.
2. Choose the Remix dev server.
3. Install dependencies using `yarn install`.
4. Next to `app/routes/index.tsx`, add `app/routes/other.tsx` with a component that simply renders `<>Other</>`
5. In `app/routes/index.tsx`, add `<Link to="/other">Other</Link>` somewhere, with `import { Link } from "remix";`.
6. Run your app using `yarn dev` or `yarn start`; the error happens for both dev and prod builds.
7. Open your browser and create a new browser tab (the bug happens with both Firefox and Chrome).
8. Go to your app's URL.
9. Click the link to `Other`.
10. Click the browser back button two times. The tab should now show your browser's default UI for new tabs.
11. Now very quickly click the browser's forward button twice.
12. The app should now crash. If it doesn't you didn't click the forward button fast enough.

### Expected Behavior

The page content should be displayed without any errors.

### Actual Behavior

In the simple repo above, the app crashes and there is the following stack trace in the dev console. In my real app in a production build, this issue then causes #1678, basically making the entire browser tab unresponsive.

```
components.js:470 Uncaught TypeError: Cannot read properties of undefined (reading 'meta')
    at Meta (components.js:470:21)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
    at workLoopSync (react-dom.development.js:22707:5)
Meta @ components.js:470
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
scheduleUpdateOnFiber @ react-dom.development.js:21881
updateContainer @ react-dom.development.js:25482
(anonymous) @ react-dom.development.js:26021
unbatchedUpdates @ react-dom.development.js:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
hydrate2 @ react-dom.development.js:26086
(anonymous) @ entry.client.tsx:4```

**Comment by revelt** [comment] 2022-02-02 21:02
https://github.com/remix-run/remix/issues/1618 might be related to this

**Comment by axel-habermaier** [comment] 2022-02-20 18:30
This seems to be caused by a race condition in the Remix code.

As far as I understand, the `loadRouteModule` function in `routeModules.ts` loads the JavaScript file related to a route and then adds an entry to the `routeModules` cache.

The `Meta` component uses this cache to do its thing.

If you're doing the browser navigation slowly, everything works as expected: `loadRouteModule` loads the JS file, updates the cache and only then does `Meta` try to use it. If you're fast, however, `loadRouteModule` hasn't even been called yet, hence the JS file is not downloaded,  `routeModules` cache not updated, but `Meta` tries to access it anyway, resulting in the observed crash.

I'm not yet sure how to fix this.

**Comment by axel-habermaier** [comment] 2022-02-20 18:49
After further experimentation, it is quite clear that React Router immediately wants to render `app/routes/other.tsx` (the second route in the repo case above), completely skipping rendering the first route. But the second route's loader hasn't been executed yet.

**Comment by tomslutsky** [comment] 2022-05-08 07:12
I just faced the same issue.
Did someone found a solution for that?

**Comment by F1ow** [comment] 2022-05-16 09:13
Same here:

components.js:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'meta')
    at Meta (components.js:502:21)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateFunctionComponent (react-dom.development.js:17356:20)
    at beginWork (react-dom.development.js:19063:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
    at workLoopSync (react-dom.development.js:22707:5)
```

links.js
```
Uncaught TypeError: Cannot read properties of undefined (reading 'links')
    at links.js:26:37
    at Array.map (<anonymous>)
    at getLinksForMatches (links.js:22:29)
    at components.js:391:35
    at updateMemo (react-dom.development.js:15867:19)
    at Object.useMemo (react-dom.development.js:16413:16)
    at Object.useMemo (react.development.js:1532:21)
    at Links (components.js:391:21)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateFunctionComponent (react-dom.development.js:17356:20)
```

components:js:
```
Uncaught TypeError: Cannot destructure property 'default' of 'routeModules[id]' as it is undefined.
    at RemixRoute (components.js:179:14)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateFunctionComponent (react-dom.development.js:17356:20)
    at beginWork (react-dom.development.js:19063:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
    at workLoopSync (react-dom.development.js:22707:5)
```

**Comment by designbyadrian** [comment] 2022-05-25 10:49
I'm also getting a `components.js:176 Uncaught TypeError: Cannot destructure property 'default' of 'routeModules[id]' as it is undefined. at RemixRoute (components.js:176:14)`, but having a hard time telling _when._ Still investigating.

**Comment by Manuelbaun** [comment] 2022-07-09 19:18
@F1ow thank you so much, i had the same issue, and also rendered Script twice!
The team could maybe add some errors, when used the Script tag more the once?

**Comment by seyaobey-dev** [comment] 2022-07-31 22:29
Facing same issue with latest `@remix-run/react`

**Comment by FlickDUB** [comment] 2022-09-07 13:45
Same. The error appears on the first hydration with a quick navigation to another page (in my case, a nested one).

**Comment by nabeelpkl** [comment] 2022-11-16 09:30
any update on this?

**Comment by n8agrin** [comment] 2022-11-23 19:18
I'm running into this as well.

A trivial repro is:

1. clone the remix repository and create the default playground app.
2. cd to playground/<app> start it
3. open localhost:3000, in chrome set your network speed to fast 3g
4. click the "signup" link
5. click back twice, so you're on the default chrome page (no url loaded)
6. click browser forward button once, and before entry.client.tsx loads, click forward again
7. url should now be localhost:3000/join
8. 💥 app crashes

hypothesis:
1. routeModules is loaded from the the root route
2. when entry.client.tsx finishes loading it tries to load the route module for `/join` which is not part of the routeModules map and it blows up

hypothetical fix: 
1. before running any client code, ensure the route module for the given route is loaded

**Comment by elledienne** [comment] 2022-11-24 14:58
Running into the same issue caused by fast navigation between pages

**Comment by daxaxelrod** [comment] 2023-01-03 20:12
Any ideas? I don't have a duplicate <Script /> or another other top level tag. Occurred when I was showing off remix to my boss 😅

**Comment by n8agrin** [comment] 2023-01-20 23:44
Crafted a PR that demonstrates a repro case for this issue: https://github.com/remix-run/remix/pull/5166

cc/ @jacob-ebey

**Comment by brophdawg11** [comment] 2023-01-23 21:39
I think I'm gonna call this the [goldilocks](https://en.wikipedia.org/wiki/Goldilocks_and_the_Three_Bears) bug.  It's not just an issue of clicking too fast, or too slow.  It seems to happen if you click forward, then wait _just the right_ amount of time for the modules to start loading for `index.tsx` and then click the forward button a second time _during_ the index chunk loads. 

I could never reproduce it normally, but once I turned on network throttling and waited long enough to see the `.js` files start loading I could reproduce it.

I believe this is what's happening:

* Forward click - Remix renders `/` (index route) on the server
  * Remix sends back the proper modules for entry-client and the index route
  * Network requests go out for entry-client and index
* While they are loading, second forward click
  * `popstate` is ignored since we haven't finished loading the chunks yet and therefore haven't instantiated our client side router and it's `popstate` listener
  * Once the chunks load and go to hydrate, it attempts to hydrate `/other` since that's the current URL

A few off-the-cuff options:
1. Easier fix - track the URL at page load and if it's not the same at hydration start (once JS chunks have loaded) we force a hard reload of `/other`
2. Harder fix - same detection, but instead of a hard reload we use the manifest to kick off loads for the `/other` chunks and delay hydration until they complete.  That introduces the case for the same issue on a third click, so that would have to do the check each time the new "initial" route chunks load.

I prefer 1 :)

**Comment by n8agrin** [comment] 2023-03-02 01:52
@brophdawg11 any chance there is an update on this? We're still running into the issue which causes the app to sometimes arbitrarily crash:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/6043/222310268-45238fcb-69bb-4526-be48-be71baea15c0.png">

**Comment by n8agrin** [comment] 2023-05-16 18:09
Added a PR with suggested fix here: https://github.com/remix-run/remix/pull/6409

**Comment by armando-herastang** [comment] 2023-05-23 15:59
Having issues with this as well.

**Comment by brophdawg11** [comment] 2023-06-14 21:39
This is fixed by #6409 and should be available once the next release goes out (should be `1.18.0`)

**Closed by brophdawg11** 2023-06-14 21:39 UTC
Labels: bug, awaiting release, hydration

**Comment by brophdawg11** [comment] 2024-08-16 20:26
I did some digging back into this today after we made the change in #9695 and reverted it because it caused some other regressions.  I was going to try to dig in and see if there was a better fix than the URL check we are currently doing which has some false positives (https://github.com/remix-run/remix/issues/8872, https://github.com/remix-run/remix/issues/7529) and was having trouble reproducing it.

> In my real app in a production build, this issue then causes https://github.com/remix-run/remix/issues/1678,

Reading through #1678 though I had forgotten that this looping was only an issue in React 17, and React 18 did not go into an hydration loop.  That was the underlying reason we aimed to fix this - because the infinite loop React got into was problematic, not so much the fact that a hydration error occurred.  Now that Remix v2 requires React 18, the looping issue is gone.

So, it seems that at this point, the original looping issue from OP here is no longer a concern in Remix v2.  And the fix we have in had some false positive edge cases that cause a loop of it's own.  So our fix, applied to React 18, introduces a potential loop which is worse than the actual non-looping hydration error which is fixed by a reload.

So I'm inclined to remove this URL check and, if desired, we can potentially look for a more appropriate fix as part of https://github.com/remix-run/remix/issues/7080.  But honestly I think the hydration errors that may occur if we did remove this check are likely less of an issue than the current loops we get into from false-positives.

**Comment by brophdawg11** [comment] 2024-08-20 19:16
FYI we just merged https://github.com/remix-run/remix/pull/9890 to remove the hydration check originally added in `1.18.0` (for https://github.com/remix-run/remix/issues/1757).  Details are in the #9890 changeset and the comment above.

@jacob-ebey and I then spent a while reproducing the issue on various versions of Remix (back to 1.17.0) and React (17 and 18) and from what we can tell, current Remix `2.11.2` no longer has the original issue any longer.  I am pretty confident it's the usage of React Router's `route.lazy` as suspected in https://github.com/remix-run/remix/issues/7080#issuecomment-1688451561 and the presence of `HydrateFallback` in Remix these days.  I also think that as part of the fog of war implementation we had to make all accesses to the `routeModulesCache` defensive since modules are not guaranteed to be in there and that eliminated some of the client-side rendering errors that triggered the error boundaries in the first place.

When you SSR `/` and then try to hydrate against something else (`/page`), Remix realizes it doesn't have the right modules/data to initialize and runs the `route.lazy` implementation for the missing routes.  This causes the client side router to try to hydrated with the default root `HydrateFallback` (or your own if you happened to have one).  This doesn't match what got SSR'd so you get a React hydration error and `There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.` which then replaces the SSR'd content with the default `HydrateFallback`.  Then once the proper modules load and `route.lazy` resolves, the client side switches over to the proper page contents.
