### ISSUE TITLE
Remix Link to="#" Bug

### ISSUE THREAD

**Issue by bd8993** [remix-run/remix#5898] opened 2023-03-24 15:58 UTC
### What version of Remix are you using?

"^1.14.3"

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a page, Have a Link to="#" anywhere on the page, once clicked the loaders are re-run causing loading states to run and useNavigation() to believe something new is happening as useNavigation().state !== "idle" anymore. 

Initially I just thought this was how things went, but according to Ryan on the Remix Discord, this is a bug that shouldn't happen. I have a [minimum reproduction](https://stackblitz.com/edit/remix-sq7mu7?file=app%2Froot.tsx,app%2Froutes%2FNext.tsx,package.json) repo on stackblitz

Click to Next Page, then on /Next route there is a Link to="#" that you can see re-runs the loader that waits for 2 seconds, and console.logs to confirm that loader has been hit again.

### Expected Behavior

Expected to just navigate towards "#Headers" with an Id or do nothing if no header is present.

### Actual Behavior

Loaders are re-run causing root loading states (if any) to fire

**Comment by Brocktho** [comment] 2023-04-25 15:45
Updated simpler example better showcasing the issue:
[Minimum Reproduction](https://stackblitz.com/edit/remix-sq7mu7?file=app/routes/index.tsx)

**Comment by brophdawg11** [comment] 2023-04-27 15:11
Could you folks try this locally?  I've seen codesandbox do some funky things with the URL and hide things (i.e., I don't see the hash even after clicking nor does it actually scroll to the hash).

When I run this reproduction in a local remix app, I get the following behavior:

* Load `http://localhost:3000`
* Click `Link to Header`
* Navigates to the hash and _does not call loaders_ because this is a "hash change only" link ✅
* URL is now `http://localhost:3000/#Header`
* If I then click `Link to Header` _again_, it _does call the loaders_ because we assume a link to the exact current URL is the same as a clicking the reload button which re-runs everything.

**Comment by bd8993** [comment] 2023-04-27 15:29
So I did look at a local repo with this, It does work as described. I guess the question I have now is how to approach purposefully dead/disabled links. Previously I'd just update the link href to "#" since that didn't cause any redirect or extra fetch or anything, however because of how the Link tag works, link to="#" on a freshly navigated route _appears_ to be asking for a page reload.

Is the suggest solution to do: instead of Link to="#" instead be to="javascript:void(0)"

**Comment by brophdawg11** [comment] 2023-04-27 17:25
This is merged in RR but we already started the RR 6.11/Remix 1.16 release so this will make it into the next Remix release after 1.16.0.

**Comment by machour** [comment] 2023-05-17 20:18
Should be fixed by 1.16.1, please advise if it's not the case.

**Closed by machour** 2023-05-17 20:18 UTC
Labels: bug, feat:routing, awaiting release
