### ISSUE TITLE
Broken node polyfill on Cloudflare Pages

### ISSUE THREAD

**Issue by aaronadamsCA** [remix-run/remix#6825] opened 2023-07-13 13:27 UTC
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone repository https://github.com/aaronadamsCA/remix-issue-node-polyfills.
1. Run `remix dev`.

### Expected Behavior

Works the same as v1.17.0.

### Actual Behavior

When I use library [`sanitize-html`](https://www.npmjs.com/package/sanitize-html), this results in the inclusion of polyfill `"node-modules-polyfills-commonjs:tty"`, which crashes the Cloudflare Workers runtime.

This is similar to, but different from, the error reported in #6665.

<details><summary>Local dev using Wrangler v3.2.0</summary>

First a warning:

```
▲ [WARNING] Duplicate key "constants" in object literal [duplicate-object-key]

    functions/[[path]].js:30299:6:
      30299 │       constants,
            ╵       ~~~~~~~~~

  The original key "constants" is here:

    functions/[[path]].js:30298:6:
      30298 │       constants: { F_OK, R_OK, W_OK, X_OK },
            ╵       ~~~~~~~~~
```

Then an error:

```
service core:user:worker: Uncaught TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'
  at fa523uyfx1e.js:16968:28 in node-modules-polyfills-commonjs:tty
  at fa523uyfx1e.js:82:50
  at fa523uyfx1e.js:16976:15 in node_modules/picocolors/picocolors.js
  at fa523uyfx1e.js:82:50
  at fa523uyfx1e.js:17185:16 in node_modules/postcss/lib/css-syntax-error.js
  at fa523uyfx1e.js:82:50
  at fa523uyfx1e.js:31987:26 in node_modules/postcss/lib/postcss.js
  at fa523uyfx1e.js:82:50
  at fa523uyfx1e.js:32044:229 in node_modules/sanitize-html/index.js

✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

</details>

**Comment by aaronadamsCA** [comment] 2023-07-13 17:28
Apologies if this ends up being a dupe of #6665, but given there was a change introduced in `1.18.1-pre.2` + this error message is now happening in a different place, I took this to likely be a new issue.

**Comment by MichaelDeBoey** [comment] 2023-07-13 17:32
Duplicate of #6665

**Closed by MichaelDeBoey** 2023-07-13 17:32 UTC
Labels: bug:unverified
