### ISSUE TITLE
Blog tutorial at Loading data does not import from right modules 

### ISSUE THREAD

**Issue by wanradt** [remix-run/remix#2823] opened 2022-04-15 20:26 UTC
### What version of Remix are you using?

1.3.5

### Steps to Reproduce

https://remix.run/docs/en/v1/tutorials/blog#loading-data

has:

`import { Link, json, useLoaderData } from "remix";`

### Expected Behavior

I expected it to work fine, but for every imported function I got on console error:

```
✘ [ERROR] No matching export in "node_modules/remix/esm/index.js" for import "Link"

    app/routes/posts/index.tsx:1:9:
      1 │ import { Link, json, useLoaderData } from "remix";

```

### Actual Behavior

Actual **solution** for me was importing like that:

```
import { json } from "@remix-run/node";
import { Link, useLoaderData } from "@remix-run/react";
```

**Comment by silvenon** [comment] 2022-04-16 12:13
Not a bug, read the [release notes for v1.4.0](https://github.com/remix-run/remix/releases/tag/v1.4.0).

**Comment by silvenon** [comment] 2022-04-16 12:16
Oh, but you're right that the docs need to be updated in the relevant places.

**Comment by machour** [comment] 2022-09-02 22:48
This have been fixed in docs

**Closed by machour** 2022-09-02 22:48 UTC
Labels: documentation, bug:unverified
