### ISSUE TITLE
Automatic change in tsconfig make remix stop working in nx mono repo

### ISSUE THREAD

**Issue by npirotte** [remix-run/remix#3174] opened 2022-05-12 14:00 UTC
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

1. Create a mono repo with nx
2. Within that mono repo create a remix app
3. Create a module with some components
4. change TS config of the remix app so aliases are correctly resolved
5. import the component in the remix app
6. start the app (nx dev app)

### Expected Behavior

Remix app start, component is properly resolved, tsconfig doesn't change

### Actual Behavior

remix add path property to remix app ts config

```
"paths": {
     "~/*": ["./app/*"]
 },
```

This override the existing path configuration, overriting the property value coming from the base project tsconfig:
```
{
  "extends": "../../tsconfig.base.json",
  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2019"],
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "target": "ES2019",
    "strict": true,
    // Remix takes care of building everything in `remix build`.
    "noEmit": true,
    "paths": {
         "~/*": ["./app/*"]
     },
  }
}
```

The only workaround is to manually sync the paths from tsconfig.base.json to remix app tsconfig each time we add a new modules, which is can be quite annoying and error prone.

I get the value of such a feature, but it would be nice either to be able, somehow, to switch it off, or to properly support typescript by taking into account `extends` property.

**Comment by MichaelDeBoey** [comment] 2022-05-12 14:36
Duplicate of #3010, which is fixed by #2961

**Closed as completed by MichaelDeBoey** 2022-05-12 14:36 UTC
Labels: bug, duplicate
