### ISSUE TITLE
Changing routes quickly sometimes leads to errors finding routes

### ISSUE THREAD

**Issue by kentcdodds** [remix-run/remix#7080] opened 2023-08-05 19:29 UTC
### What version of Remix are you using?

1.19.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Got this from https://github.com/kentcdodds/kentcdodds.com/issues/473

1. go to [blog page](https://kentcdodds.com/blog)
2. Open **useEffect vs useLayoutEffect** [article](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect)
3. scroll down and open visit course [link](https://epicreact.dev/)
4. go back in browser history very quickly (click twice quickly on the go back button)
5. you should find yourself in the blog page
6. instead error appears

### Expected Behavior

The `/blog` route should be shown

### Actual Behavior

You get an error (I have an error boundary but it's not shown):

```
TypeError: Cannot read properties of undefined (reading 'links')
    at https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:9:330
    at Array.map (<anonymous>)
    at _n (https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:9:284)
    at https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:14:2535
    at Object.useMemo (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:6:25719)
    at r.useMemo (https://kentcdodds.com/build/_shared/chunk-52ROR7N5.js:1:6137)
    at Qo (https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js:14:2523)
    at du (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:6:19466)
    at Ba (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:8:43659)
    at Ua (https://kentcdodds.com/build/_shared/chunk-Y6UZ2JHA.js:8:39459)
```

6 total relevant errors appear in the console
![image](https://github.com/kentcdodds/kentcdodds.com/assets/34947993/90f2670a-ac45-4b47-93ea-a1ef4435efce)
![image](https://github.com/kentcdodds/kentcdodds.com/assets/34947993/21049367-5e92-4b6c-9b45-5367020b08b7)

**Comment by hichemfantar** [comment] 2023-08-05 21:10
I just wanted to mention that this doesn't always happen, even when quickly switching routes.
It may be some kind of race condition.

**Comment by brophdawg11** [comment] 2023-08-21 20:17
@kentcdodds are you sure you're on `1.19.2`?  I'm seeing `1.17.1` in the sourcemaps and also in the preserved comments at the bottom of the bundles files: https://kentcdodds.com/build/_shared/chunk-NA3JZD7E.js

<img width="681" alt="Screenshot 2023-08-21 at 4 11 47 PM" src="https://github.com/remix-run/remix/assets/1609022/13ceb342-d4b6-4c15-b3a8-1becb6cecf04">

<img width="673" alt="Screenshot 2023-08-21 at 4 13 40 PM" src="https://github.com/remix-run/remix/assets/1609022/e42a55d2-a633-40bb-9283-3ea1ec268aa6">

This sounds like https://github.com/remix-run/remix/issues/1757 which was fixed in `1.18.0`, so if you are on `1.17.1` this would make sense showing up on these fast back button navigations.  The underlying issue is described in more detail [here](https://github.com/remix-run/remix/issues/1757#issuecomment-1401023829) and the fix we went with was just trying to detect this URL mismatch and doing a browser reload.

**Comment by kentcdodds** [comment] 2023-08-21 23:19
Oh man, I apologize for my lazy issue filing 🤦‍♂️ I can't remember my state of mind when I opened this issue, but I apologize for not double-checking that I was upgraded before opening this. Sorry for the wild goose chase. Thank you for fixing it!

I've just upgraded (thanks for `npx upgrade-remix`!!) and it's now *extremely* difficult to reproduce this issue. I have to hit forward/backward in random orders over and over again very rapidly to have it show up. I'm not sure what could be causing this, but like I said, it's very difficult to reproduce and users won't be behaving this way normally so I think this is safe to close, but I'll leave that to you.

**Comment by brophdawg11** [comment] 2023-08-22 15:36
Well drat - I wish _"extremely difficult"_ was instead _"impossible"_ 😂 , so I guess there's still some path that can hit it. I'll keep it open for now but won't put it high on the priority list since if it does happen a simple refresh oughta get the user back to a working state.

I have a small hope/hunch that https://github.com/remix-run/remix/pull/7133 might allow us to fix this in a better manner without the forced reload since we could rely on `lazy` to load the modules for the new URL - and just delay hydration.  I'll loop back and see if that helps once we land that.

**Comment by anthonymartinovic-eiq** [comment] 2023-12-14 15:23
Are there any updates for this issue? We're currently running on version `2.1.0` and are dealing with the same error for one particular route.

Unfortunately I've been unable to find a consistent way to reproduce this error, it's happening seemingly at random.

**Comment by brophdawg11** [comment] 2024-08-20 19:18
Please see details in https://github.com/remix-run/remix/issues/1757#issuecomment-2299585123 but we think this is no longer an issue in current versions of Remix so I'm going to close it out.  Please re-open with reproduction steps if anyone comes across this again!

**Closed by brophdawg11** 2024-08-20 19:18 UTC
Labels: feat:routing, bug:unverified
