### ISSUE TITLE
[Bug]: Cannot use @ character to start the route

### ISSUE THREAD

**Issue by alexluong** [remix-run/remix#947] opened 2021-12-08 06:20 UTC
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

Setup these routes

- `routes/a.tsx`
- `routes/a@.tsx`
- `routes/@.tsx`
- `routes/@a.tsx`

### Expected Behavior

Remix creates 4 pages

- `/a`
- `/a@`
- `/@`
- `/@a`

### Actual Behavior

Remix only creates 2 out of those 4 pages

- `/a`
- `/a@`
- `/@` --> not created
- `/@a` --> not created

**Comment by soungrong** [comment] 2021-12-10 12:53
Duplicate of #846

**Closed** 2022-03-22 18:08 UTC
Labels: bug, feat:routing
