### ISSUE TITLE
Broken polyfill on Cloudflare Pages after `1.17.1` upgrade

### ISSUE THREAD

**Issue by aaronadamsCA** [remix-run/remix#6665] opened 2023-06-22 12:22 UTC
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone repository https://github.com/aaronadamsCA/remix-issue-node-polyfills.
1. Run `remix dev` or deploy to Cloudflare Pages.

### Expected Behavior

Works the same as v1.17.0.

### Actual Behavior

When I use library [`sanitize-html`](https://www.npmjs.com/package/sanitize-html), this results in the inclusion of polyfill `"node-modules-polyfills-commonjs:tty"`, which crashes the Cloudflare Workers runtime.

<details><summary>Local dev using Wrangler v2.20.0</summary>

First a warning:

```
▲ [WARNING] Duplicate key "constants" in object literal [duplicate-object-key]

    functions/[[path]].js:30122:6:
      30122 │       constants,
            ╵       ~~~~~~~~~

  The original key "constants" is here:

    functions/[[path]].js:30121:6:
      30121 │       constants: { F_OK, R_OK, W_OK, X_OK },
            ╵       ~~~~~~~~~
```

Then an error:

```
/workspaces/remix-issue-6665/functions/[[path]].js:17285
        module.exports[k4] = polyfill[k4];
                       ^
TypeError: Cannot assign to read only property 'ReadStream' of object '[object Object]'
    at node-modules-polyfills-commonjs:tty (/workspaces/remix-issue-6665/functions/[[path]].js:17285:24)
    at /workspaces/remix-issue-6665/functions/[[path]].js:10:46
    at node_modules/picocolors/picocolors.js (/workspaces/remix-issue-6665/functions/[[path]].js:17295:15)
    at /workspaces/remix-issue-6665/functions/[[path]].js:10:46
    at node_modules/postcss/lib/css-syntax-error.js (/workspaces/remix-issue-6665/functions/[[path]].js:17510:16)
    at /workspaces/remix-issue-6665/functions/[[path]].js:10:46
    at node_modules/postcss/lib/postcss.js (/workspaces/remix-issue-6665/functions/[[path]].js:31823:26)
    at /workspaces/remix-issue-6665/functions/[[path]].js:10:46
    at node_modules/sanitize-html/index.js (/workspaces/remix-issue-6665/functions/[[path]].js:31882:229)
    at /workspaces/remix-issue-6665/functions/[[path]].js:10:46
```

</details>

<details><summary>Deploying to Cloudflare Pages results in "this deployment failed" with no details</summary>

<img width="1010" alt="image" src="https://github.com/remix-run/remix/assets/1505561/62dce2c8-eb3a-4e8a-9ae2-2bb65d41ac79">

</details>

**Comment by acidio** [comment] 2023-06-22 14:08
FYI, I was getting this issue in version 1.7.1, I downgraded to 1.7.0 but still got the same problem.

**Comment by acidio** [comment] 2023-06-22 14:12
FYI, I downgraded to 1.7.0 but the issue remains, maybe this is related to another dependency that was updated? 🤔

**Comment by aaronadamsCA** [comment] 2023-06-22 17:01
My rollback to 1.17.0 fixed the issue with no other changes.

However another project with a very similar setup upgraded to v1.17.1 without issue, so there is definitely more to this. I'll try to find the contributing factor.

**Comment by acidio** [comment] 2023-06-22 17:40
In my case it's a brand new app, I can't compare what modules were updated from 1.7.0 to 1.7.1, but I also only got this issue when I added `import { json } from '@remix-run/node'` to use on an `action`, which I believe is related to `"node-modules-polyfills-commonjs:tty"` as you mentioned.

**Comment by aaronadamsCA** [comment] 2023-06-22 17:57
Our small API app still worked post-upgrade despite including `import { json } from "@remix-run/cloudflare"`.

It doesn't use navigation-related imports like `redirect`, `useNavigation`, `useSearchParams`, and `Link`.

You may wish to try importing from `"@remix-run/cloudflare"` if you're developing for Cloudflare. On my side, if nobody else chimes in with more info, I'll try to figure out the minimal reproduction.

**Comment by acidio** [comment] 2023-06-22 18:55
You're right, I should import it from `"@remix-run/cloudflare"` 🤦 
That works, thanks for the tip.

**Comment by silence48** [comment] 2023-06-23 00:15
I am getting the same issue and i don't have any imports from @remix-run/node...

💿 Rebuilt in 1.2s
▲ [WARNING] Duplicate key "constants" in object literal [duplicate-object-key]

    functions/[[path]].js:44234:6:
      44234 │       constants,
            ╵       ~~~~~~~~~

  The original key "constants" is here:

    functions/[[path]].js:44233:6:
      44233 │       constants: { F_OK, R_OK, W_OK, X_OK },
            ╵       ~~~~~~~~~

▲ [WARNING] Duplicate key "constants" in object literal [duplicate-object-key]

    functions/[[path]].js:44234:6:
      44234 │       constants,
            ╵       ~~~~~~~~~

  The original key "constants" is here:
```
    functions/[[path]].js:44233:6:
▲ [WARNING] 1 warning(s) when compiling Worker.
```

**Comment by silence48** [comment] 2023-06-23 00:23
sorry i was on 1.17.1 i had ^1.16.1 in my package.json.  I pinned it to 1.16.1 and the bugs went away.  I have nothing requiring the /node i always use @remix-run/cloudflare

**Comment by markdalgleish** [comment] 2023-06-23 00:55
@aaronadamsCA I followed your reproduction steps and I'm not seeing the local dev issue you described. Could you share a minimal repro?

**Comment by aaronadamsCA** [comment] 2023-06-23 12:38
[`sanitize-html`](https://www.npmjs.com/package/sanitize-html) appears to be the package causing the `"node-modules-polyfills-commonjs:tty"` polyfill to be included. I am guessing this polyfill being broken on Cloudflare Pages may wind up being an upstream issue.

I am putting together a minimal reproduction now.

**Comment by aaronadamsCA** [comment] 2023-06-23 13:14
Very minimal reproduction:

https://github.com/aaronadamsCA/remix-issue-6665

This crashes on `remix dev`.

**Comment by markdalgleish** [comment] 2023-06-26 06:44
I've raised a couple of PRs against [esbuild-plugins-node-modules-polyfill](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill) to address this issue.

**Comment by markdalgleish** [comment] 2023-07-14 01:01
I tried this against `1.19.0-pre.0` and I was able to get it to work, but only if I made the following changes:

1) Provided a `process` global polyfill in `server.ts`:

```ts
import process from 'node:process';
globalThis.process = process;
```

Then I needed to move the import of `sanitize-html` into the component body as a `require` call rather than a top-level import:

```ts
export default function Index() {
  const sanitizeHtml = require('sanitize-html'); // Ugh

  return (
    <div
      dangerouslySetInnerHTML={{
        __html: sanitizeHtml("<p>Hello world</p>"),
      }}
    ></div>
  );
}

```

This seems to be because `sanitize-html` uses PostCSS under the hood and for some reason a file watcher is set up and the polyfill immediately calls `setTimeout`, but you're only allowed to do this within the scope of a request, not at the top level.

This feels like a pretty big hack to me though. You might want to look for a lighter-weight alternative to `sanitize-html` since it seems a bit heavy for Cloudflare.

**Comment by aaronadamsCA** [comment] 2023-07-14 17:06
Can we maybe get this issue reopened for now until we can figure out a resolution?

You won't get any disagreement on my part that `sanitize-html` is quite heavy, but I'm not sure it's going to be easy to replace. Right now I'd prefer to get it working again if possible.

With your help, here's what I think I know so far, please correct anything that isn't right:

- In `v1.17.1`, Remix changed Node polyfill libraries to fix a handful of other issues. The new `node-modules-polyfills:tty` was breaking, leading to our initial error. You fixed this upstream (thank you!).

- As part of this change `process` was no longer polyfilled. #6696 would have added this back in `v1.18.1`, but this change was reverted prior to release.

- You suggested I try to polyfill `process` in `server.ts`, but this doesn't work. The `process` global isn't polyfilled, so I still get `Uncaught ReferenceError: process is not defined`.

  - Yes I could potentially `require()` the library into the front end to get around this, but unlike the minimal repro we do want to run this on the server side.

- If I patch `@remix-run/dev` myself to enable the new `process` polyfill myself, now I get an error in the new `node-modules-polyfills:fs`:

  ```
  service core:user:worker: Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and generating random values, can only be performed while handling a request.
    at et82e18l7nb.js:44634:24 in FSWatcher2._this._persist
    at et82e18l7nb.js:44649:140 in FSWatcher2.start
    at et82e18l7nb.js:44465:22 in Volume2.watch
    at et82e18l7nb.js:44716:7 in watchStdo
    at et82e18l7nb.js:46887:5 in node-modules-polyfills:fs
    at et82e18l7nb.js:79:56
    at et82e18l7nb.js:47114:5 in node-modules-polyfills-commonjs:fs
    at et82e18l7nb.js:79:56
    at et82e18l7nb.js:47122:135 in ../../node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/previous-map.js
    at et82e18l7nb.js:82:50
  ```

  - This is because _the polyfill itself_ is setting up file watchers (!) which Cloudflare Workers does not seem to like:

    ```js
    var e5, t4, n5, r5, i4, s3, y2, e22, t22, n22, r23, o22, l22, s22, f22, a22, T2, t32, e32, o32, n32, r32, l32, t$1, o$1, n$1, e$1, r$1, c32, u32, i32, t$2, i$1, o$2, u$1, f32, a32, s32, p32, y22, l$1, d22, m22, h32, j, A, Q, X, Y, ee, te, re, ne, ie, Se, Ee, _extend, callbackify, debuglog, deprecate, format3, inherits, inspect, isArray, isBoolean, isBuffer, isDate, isError, isFunction, isNull, isNullOrUndefined, isNumber, isObject, isPrimitive, isRegExp, isString, isSymbol, isUndefined, log, promisify, types, TextEncoder2, TextDecoder2, exports4, _dewExec4, _global3, process4, r$13, t$13, e$22, n$22, o$23, a$12, h$12, a$1$1, e$1$1, n$1$1, i$12, o$1$1, j2, Y2, e42, n42, o42, u42, e$12, s4, i42, exports$2$1, _dewExec$2$1, exports$1$1, _dewExec$1$1, exports$g, _dewExec$g, buffer, exports$f, _dewExec$f, exports$e, _dewExec$e, exports$d, _dewExec$d, exports$c, _dewExec$c, exports$b, _dewExec$b, exports$a, _dewExec$a, exports$9, _dewExec$9, _global$2, exports$8, _dewExec$8, _global$1, exports$7, _dewExec$7, exports$6, _dewExec$6, exports$5, _dewExec$5, exports$4, _dewExec$4, exports$3, _dewExec$3, _global22, exports$2, _dewExec$2, exports$13, _dewExec$1, exports23, _dewExec23, r52, t5, e$13, r$12, n8, o8, c7, l7, i7, a7, u7, f7, p7, s6, y4, b3, g3, h5, $2, j3, w3, r$2, e$2, o$13, n$13, a$1, c$13, l$13, u$13, f$12, t$12, f$22, e$3, l$2, t$22, n$2, o$22, r$3, e$4, o$3, t$3, n$3, y$1, a$22, i$13, d4, f$3, u$22, A3, l$3, v4, P3, c$2, t$4, p$1, o$4, i$2, a$3, l$4, r$4, n$4, i$3, o$5, c$3, f$4, u$3, s$12, a$4, l$5, p$2, m4, N3, e$5, i$4, n$5, t$5, u$4, a$5, m$1, o$6, s$2, f$5, c$4, a$6, u$5, l$6, g$1, h$1, y$2, b$1, v$1, d$1, E3, w$1, S3, j$1, O3, x3, q2, R3, A$1, k3, _32, T4, P$1, I3, D3, F3, N$1, L3, M3, X2, Z2, $$1, et, AssertionError, deepEqual, deepStrictEqual, doesNotReject, doesNotThrow, equal, fail, ifError, notDeepEqual, notDeepStrictEqual, notEqual, notStrictEqual, ok, rejects, strict, strictEqual, throws, _extend2, callbackify2, debuglog2, deprecate2, format22, inherits2, inspect2, isArray2, isBoolean2, isBuffer2, isDate2, isError2, isFunction2, isNull2, isNullOrUndefined2, isNumber2, isObject2, isPrimitive2, isRegExp2, isString2, isSymbol2, isUndefined2, log2, promisify2, types2, TextEncoder22, TextDecoder3, exports$122, _dewExec33, exports33, _makeLong2, basename2, delimiter2, dirname2, extname2, format32, isAbsolute2, join2, normalize2, parse4, posix2, relative2, resolve3, sep2, win322, EventEmitter, defaultMaxListeners, init, listenerCount, on2, once2, exports$132, _dewExec42, _global32, exports42, Readable, Writable, Duplex, Transform, PassThrough, finished, pipeline, Stream, promises, t6, o52, n52, e6, r6, c5, s5, u5, a5, d5, h6, p5, n6, r7, t7, o6, h7, e8, a6, o7, n7, i6, l6, p6, c6, u6, f6, m5, v5, g4, y5, b4, exports5, _dewExec5, path2, processPlatform$12, CHAR_BACKWARD_SLASH$12, CHAR_FORWARD_SLASH$12, CHAR_LOWERCASE_A$12, CHAR_LOWERCASE_Z$12, isWindows$12, forwardSlashRegEx$12, percentRegEx$12, backslashRegEx$12, newlineRegEx$12, carriageReturnRegEx$12, tabRegEx$12, processPlatform2, Url2, format4, resolve22, resolveObject2, parse22, _URL2, CHAR_BACKWARD_SLASH2, CHAR_FORWARD_SLASH2, CHAR_LOWERCASE_A2, CHAR_LOWERCASE_Z2, isWindows2, forwardSlashRegEx2, percentRegEx2, backslashRegEx2, newlineRegEx2, carriageReturnRegEx2, tabRegEx2, exports$32, _dewExec$22, exports$22, _dewExec$12, exports$14, _dewExec6, exports6, Buffer2, INSPECT_MAX_BYTES, kMaxLength, exports$h, _dewExec$f2, exports$g2, _dewExec$e2, exports$f2, _dewExec$d2, exports$e2, _dewExec$c2, exports$d2, _dewExec$b2, _global$3, exports$c2, _dewExec$a2, exports$b2, _dewExec$92, exports$a2, _dewExec$82, _global$22, exports$92, _dewExec$72, exports$82, _dewExec$62, exports$72, _dewExec$52, _global$12, exports$62, _dewExec$42, exports$52, _dewExec$32, exports$42, _dewExec$23, _global4, exports$33, _dewExec$13, exports$23, _dewExec7, exports$15, exports7, vol, createFsFromVolume, fs, appendFile, appendFileSync, access, accessSync, chown, chownSync, chmod, chmodSync, close, closeSync, copyFile, copyFileSync, cp, cpSync, createReadStream, createWriteStream, exists, existsSync, fchown, fchownSync, fchmod, fchmodSync, fdatasync, fdatasyncSync, fstat, fstatSync, fsync, fsyncSync, ftruncate, ftruncateSync, futimes, futimesSync, lchown, lchownSync, lchmod, lchmodSync, link, linkSync, lstat, lstatSync, mkdir, mkdirSync, mkdtemp, mkdtempSync, open, openSync, opendir, opendirSync, readdir, readdirSync, read, readSync, readv, readvSync, readFile, readFileSync, readlink, readlinkSync, realpath, realpathSync, rename, renameSync, rm, rmSync, rmdir, rmdirSync, stat, statSync, symlink, symlinkSync, truncate, truncateSync, unwatchFile, unlink, unlinkSync, utimes, utimesSync, watch, watchFile, writeFile, writeFileSync, write, writeSync, writev, writevSync, Dir, Dirent, Stats, ReadStream2, WriteStream2, FileReadStream, FileWriteStream, _toUnixTimestamp, F_OK, R_OK, W_OK, X_OK, constants, promises2, init_fs = __esm({
      "node-modules-polyfills:fs"() {
        // ...
        watchStdo("/dev/stdout", 1, console.log);
        watchStdo("/dev/stderr", 2, console.error);
        // ...
      }
    });
    ```

Let me know what you think. IMO some ideal goals would be:

- `node-modules-polyfills:fs` shouldn't create file watchers on load.
- There should be some easy way to re-enable a global `process` polyfill.

**Comment by markdalgleish** [comment] 2023-07-17 04:02
I dug into the`fs` issue and figured out why this wasn't happening with the older polyfill setup. In [esbuild-plugin-polyfill-node](https://github.com/cyco130/esbuild-plugin-polyfill-node) it's actually configured to provide an empty module for `fs` by default, among others: https://github.com/cyco130/esbuild-plugin-polyfill-node/blob/9afcb6abaf9062a15daaffce9a14e478b365139c/src/index.ts#L143-L149. Since it's using the same JSPM polyfills, I can actually reproduce the issue with the older polyfill setup if I enable the `fs` polyfill.

In order to get us back to a similar setup for you, I might need to add support for empty polyfills upstream.

**Comment by aaronadamsCA** [comment] 2023-07-17 16:18
@markdalgleish Great find, thank you! That led me to look further into the underlying polyfill; patching out [these two lines](https://github.com/jspm/jspm-core/blob/209cd168383d76215445c79001b9f45568dd92df/src-browser/fs.js#L22-L23) in it worked around the issue, so I agree that passing an empty polyfill will work around the problem.

(I don't understand why an `fs` polyfill would watch devices on load. Maybe that's worth reporting as an upstream compatibility problem with `workerd`.)

The general ability for Remix apps to "officially" opt into/out of specific polyfills seems like it could be a good long-term solution for all of these ecosystem challenges. If I could set `serverNodePolyfillsOptions` in my config and have it passed through to the server compiler, I don't think I'd need to patch anything.

Until then, with your help I've got a two-patch workaround that lets me get back onto Remix latest, so thanks again!

<details><summary><code>@jspm__core@2.0.1.patch</code></summary>

```patch
diff --git a/nodelibs/browser/fs.js b/nodelibs/browser/fs.js
index c234dc5d07c5ac6df817477bfbaaf9f563f37375..092933de60123809a68ee641a69c1fcd2542e47d 100644
--- a/nodelibs/browser/fs.js
+++ b/nodelibs/browser/fs.js
@@ -4411,19 +4411,6 @@ vol.releasedFds = [2, 1, 0];
 vol.openSync('/dev/stdin', 'w');
 vol.openSync('/dev/stdout', 'r');
 vol.openSync('/dev/stderr', 'r');
-watchStdo('/dev/stdout', 1, console.log);
-watchStdo('/dev/stderr', 2, console.error);
-function watchStdo(path, fd, listener) {
-  let oldSize = 0;
-  const decoder = new TextDecoder();
-  vol.watch(path, 'utf8', () => {
-    const { size } = vol.fstatSync(fd);
-    const buf = Buffer.alloc(size - oldSize);
-    vol.readSync(fd, buf, 0, buf.length, oldSize);
-    oldSize = size;
-    listener(decoder.decode(buf, { stream: true }));
-  });
-}
 
 const fs = createFsFromVolume(vol);
```

</details>

<details><summary><code>@remix-run__dev@1.18.1.patch</code></summary>

```patch
diff --git a/dist/compiler/server/compiler.js b/dist/compiler/server/compiler.js
index a5143271bd5f30487d7f2b052ce9b37229add46c..880317346c3753ab85760d33d75860498dd84620 100644
--- a/dist/compiler/server/compiler.js
+++ b/dist/compiler/server/compiler.js
@@ -72,7 +72,11 @@ const createEsbuildConfig = (ctx, refs) => {
     sideEffects: false
   })];
   if (ctx.config.serverPlatform !== "node") {
-    plugins.unshift(esbuildPluginsNodeModulesPolyfill.nodeModulesPolyfillPlugin());
+    plugins.unshift(esbuildPluginsNodeModulesPolyfill.nodeModulesPolyfillPlugin({
+      globals: {
+        process: true
+      }
+    }));
   }
   return {
     absWorkingDir: ctx.config.rootDirectory,
```

</details>

**Comment by markdalgleish** [comment] 2023-07-18 03:49
@aaronadamsCA Relating to your issue around globals, have you tried adding this to `app.root.tsx` in your minimal repro?

```ts
import process from 'node:process';
globalThis.process = process;
```

I realise I posted earlier that I added this to `server.ts` but I might have got that wrong. Moving this to `app/root.tsx` seems to work for me. We're trying to avoid adding further API for polyfills so I'm hoping this issue with globals can be solved on your end.

**Closed** 2023-07-18 12:22 UTC
Labels: adapter:cloudflare-pages, bug:unverified

**Comment by aaronadamsCA** [comment] 2023-07-18 17:14
@markdalgleish Thank you for the help and the update. I've managed to update [the reproduction repository](https://github.com/aaronadamsCA/remix-issue-node-polyfills) so that it works correctly without any patched packages. 🙌

Some quick observations:

- It's still unfortunate that the `process` global is polyfilled in `root.jsx`, while the `process` module is polyfilled in `remix.config.js`. I understand the desire to avoid _adding_ API for polyfills, but I'd argue that accepting `serverNodeBuiltinsPolyfill.globals` would _remove_ API for polyfills, since there would no longer be separate polyfill APIs for globals vs. modules. Hopefully you'll still consider this.

- When I set `fs: "empty"`, this unexpectedly removed default polyfills [that I had to restore myself](https://github.com/aaronadamsCA/remix-issue-node-polyfills/blob/4b96025efb0f1ba75c0293cdfc1d63afaa0ad1d3/remix.config.js#L11-L19). I expected my config to be merged with the default - pass `false` to disable a default polyfill, `true` to enable a non-default one, etc. Just worth noting.

  ```
  serverNodeBuiltinsPolyfill: {
    modules: {
      fs: "empty",
      path: true,
      process: true,
      tty: true,
      url: true,
    },
  },
  ```

**Comment by meoyawn** [comment] 2023-07-19 21:46
tried 1.19.0

with
```js
serverNodeBuiltinsPolyfill: {
  modules: {
    fs: "empty",
    buffer: "empty",
    "fs/promises": "empty",
  },
},
```

but it still errors when `gray-matter` calls `Buffer.from`:

https://github.com/jonschlinkert/gray-matter/blob/master/lib/utils.js#L36

`Buffer is not defined`

**Comment by markdalgleish** [comment] 2023-07-19 23:00
You'll need to add the `Buffer` constructor it to the global environment somewhere at the root of your app:

```ts
import { Buffer } from 'buffer';
globalThis.Buffer = Buffer;
```

Note that this won't work if you've set the `buffer` polyfill to `"empty"`, like in your config snippet.
