### ISSUE TITLE
return type of useLoaderData is missing properties.

### ISSUE THREAD

**Issue by MoSattler** [remix-run/remix#7462] opened 2023-09-18 11:02 UTC
### What version of Remix are you using?

2.0.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```tsx
export const loader = () => {
  return json({
    willBeForgotten: { name: "forgotten" },
    willBeRemembered: { anythingButName: "remembered" },
  });
};

export default function Index() {
  // TYPEERROR: Property 'willBeForgotten' does not exist on type 'JsonifyObject<{ willBeRemembered: string }>'
  const { willBeForgotten, willBeRemembered } = useLoaderData<typeof loader>();
  return <div />
}
```

### Expected Behavior

When returning an object from the loader in the shape of `{ name: string}`, typescript passes. Both fields (`willBeForgotten` and `willBeRemembered`) are being returned from `useLoaderData`.

### Actual Behavior

`willBeForgotten` is not returned from `useLoaderData`

**Comment by pcattori** [comment] 2023-09-18 18:54
This looks like a bug in `type-fest`: https://tsplay.dev/wgK54w

**Comment by MichaelDeBoey** [comment] 2023-09-18 20:19
Duplicate of #7246

**Closed by MichaelDeBoey** 2023-09-18 20:19 UTC
Labels: bug, feat:typescript, external

**Comment by MichaelDeBoey** [comment] 2023-09-18 21:05
@MoSattler I did some further investigation on this some time ago and posted in the `type-fest` issue my findings: https://github.com/sindresorhus/type-fest/issues/667#issuecomment-1692247637

**Comment by kevinbailey25** [comment] 2023-09-18 22:05
@MoSattler we are also having the same issue. Anytime we have an object with a single key called `name`... in our case tenant: `{ name: 'tenant name', address: {...} }`

**Comment by kevinbailey25** [comment] 2023-09-18 22:26
@MoSattler I went down WAY TOO many rabbit holes and have a temp solution until that issue gets fixed...

The issue is any object that has a `name` property and all other properties can be optional (aka undefined), it will assume it's a function and stripe it out. 

We have a `tenant` object that has a `name: string` then several other fields that all happen to be undefined. As long as we add an extra prop like `json({ tenant: { ...tenant, fix: true }})` it will work. Very annoying, but until that issue (https://github.com/sindresorhus/type-fest/issues/657) gets fixed... ya

**Comment by dperetti** [comment] 2023-12-30 11:40
Still happening in Remix 2.4.1
<img width="825" alt="image" src="https://github.com/remix-run/remix/assets/845612/1796f9aa-5e74-41db-b174-bce3c4b23d36">

**Comment by kiliman** [comment] 2023-12-30 15:07
This is one of the main reasons I created `remix-typedjson`. Too many weird edge cases with the JSON type conversion. 

https://github.com/kiliman/remix-typedjson
