### ISSUE TITLE
[Bug]: "Warning: Did not expect server HTML to contain a <script> in <html>."

### ISSUE THREAD

**Issue by timscodebase** [remix-run/remix#1463] opened 2022-01-11 21:41 UTC
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

v17.3.0

### Steps to Reproduce

1. clone git@github.com:leveluptuts/remix-for-everyone.git
1. open 8HittingAnApi
1. npm i
1. npm run dev

See console in browser

### Expected Behavior

no error

### Actual Behavior

"Warning: Did not expect server HTML to contain a <script> in <html>."

**Comment by yesmeck** [comment] 2022-01-12 10:01
Most probably caused by chrome extension, see https://github.com/remix-run/remix/issues/1077#issuecomment-995986018

**Comment by ccssmnn** [comment] 2022-01-22 13:21
I cannot reproduce this error.

Running node v16.13.1, Chrome 97, Safari 15.2, Sizzy 57.

**Comment by revelt** [comment] 2022-02-02 21:10
@timscodebase please confirm which browser are you testing on and, can you recreate the issue with all the plugins disabled

**Comment by adamlbunch** [comment] 2022-02-04 23:21
If you go into incognito mode and it stops, then it's likely an issue with one of your extensions. I had this issue specifically when using the Yoroi Cardano Wallet extension which injects itself into localhost

**Comment by machour** [comment] 2022-03-18 09:32
Duplicate of #1077

**Closed by machour** 2022-03-18 09:32 UTC
Labels: bug

**Comment by Crazyloon** [comment] 2022-06-03 03:42
Adobe Experience Cloud Debugger was causing this issue for me. Disabled it and the error message went away.
