### ISSUE TITLE
[template issue]: express + typescript `server.ts` with `node`

### ISSUE THREAD

**Issue by paul-vd** [remix-run/remix#6161] opened 2023-04-25 09:30 UTC
### What version of Remix are you using?

latest

### Template

https://github.com/remix-run/remix/tree/main/templates/express

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Run the create-remix script with `npx create-remix@latest`
   ```
   $ npx create-remix@latest
   ? Where would you like to create your app? prototype
   ? What type of app do you want to create? Just the basics
   ? Where do you want to deploy? Express Server
   ? TypeScript or JavaScript? TypeScript
   ? Do you want me to run `npm install`? Yes
   ```
2. Run the Dev or Start command `npm run dev`
   ```bash
   $ npm run dev

   > start
   > cross-env NODE_ENV=production node ./server.js
 
   node:internal/modules/cjs/loader:1078
     throw err;
     ^
 
   Error: Cannot find module '/home/paul/Projects/prototype/server.js'
       at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
       at Module._load (node:internal/modules/cjs/loader:920:27)
       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
       at node:internal/main/run_main_module:23:47 {
     code: 'MODULE_NOT_FOUND',
     requireStack: []
   }
   ```

### Expected Behavior

It should start a development or production server

### Actual Behavior

It fails because it is trying to start `server.js` while there is only `server.ts`
```bash
   node:internal/modules/cjs/loader:1078
     throw err;
     ^
 
   Error: Cannot find module '/home/paul/Projects/prototype/server.js'
       at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
       at Module._load (node:internal/modules/cjs/loader:920:27)
       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
       at node:internal/main/run_main_module:23:47 {
     code: 'MODULE_NOT_FOUND',
     requireStack: []
   }
```

### Suggestion
When using typescript server, use `ts-node` for `start` script, and update all the `server.js` instances to `server.ts` in the scripts.

**Comment by machour** [comment] 2023-04-25 15:55
Duplicate of #6119

**Closed by machour** 2023-04-25 15:55 UTC
Labels: template: bug, template:express
