### ISSUE TITLE
No loader is configured for ".png" files

### ISSUE THREAD

**Issue by michael-wolfenden** [remix-run/remix#8605] opened 2024-01-26 09:49 UTC
### Reproduction

1) Create a new cloudflare-pages project
> pnpm dlx create-remix@latest --template remix-run/remix/templates/cloudflare-pages

2) Copy a png to `\app\routes`
3) Import the png in `\app\routes\_index.tsx`

```tsx
import type { MetaFunction } from "@remix-run/cloudflare";

// 👇
import wave from './wave.png'

export const meta: MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.8" }}>
      <h1>Welcome to Remix</h1>
      <ul>
        <li>
          <a
            target="_blank"
            href="https://remix.run/tutorials/blog"
            rel="noreferrer"
          >
            15m Quickstart Blog Tutorial
          </a>
        </li>
        <li>
          <a
            target="_blank"
            href="https://remix.run/tutorials/jokes"
            rel="noreferrer"
          >
            Deep Dive Jokes App Tutorial
          </a>
        </li>
        <li>
          <a target="_blank" href="https://remix.run/docs" rel="noreferrer">
            Remix Docs
          </a>
        </li>
      </ul>
    </div>
  );
}
```

4) Run `pnpm dev`

```
❯ pnpm dev

> my-remix-app@ dev C:\dev\my-remix-app
> remix dev --manual -c "npm run start"


 💿  remix dev

 info  building...
✘ [ERROR] Build failed with 1 error:
error: No loader is configured for ".png" files: app/routes/wave.png [plugin browser-route-module]
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 17.10 GB / 31.73 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\pnpm\node.EXE
    npm: 10.2.4 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/cloudflare: ^2.5.1 => 2.5.1
    @remix-run/cloudflare-pages: ^2.5.1 => 2.5.1
    @remix-run/css-bundle: ^2.5.1 => 2.5.1
    @remix-run/dev: ^2.5.1 => 2.5.1
    @remix-run/react: ^2.5.1 => 2.5.1
```

### Used Package Manager

pnpm

### Expected Behavior

To be able to import image assets as per the docs -> https://remix.run/docs/en/main/file-conventions/asset-imports

### Actual Behavior

`error: No loader is configured for ".png"`

**Comment by brookslybrand** [comment] 2024-05-22 19:22
Hi @michael-wolfenden, thanks for sharing and for all the info

This is actually not a bug, the error message that says

> error: No loader is configured for ".png" files: app/routes/wave.png [plugin browser-route-module]

is saying that it doesn't know what to do with a `.png` file for a route. If you want to import an asset like you're doing, you just need to move it outside of the `routes/` directory. [The `routes/` directory has a special meaning in Remix](https://remix.run/docs/en/main/file-conventions/routes#route-file-naming).

I'm going to go ahead and close this issue since there's no actual bug. Please reach out if my answer doesn't clarify how you can properly import an image

**Closed by brookslybrand** 2024-05-22 19:22 UTC
Labels: bug:unverified, template:cloudflare-pages, runtime:cloudflare
