### ISSUE TITLE
Error: invariant.js "Missing output for entry point"

### ISSUE THREAD

**Issue by obillwan** [remix-run/remix#5754] opened 2023-03-10 04:03 UTC
### What version of Remix are you using?

1.14.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. run "npx create-remix@latest"
2. Choose all of the defaults (ie. "Just the basics", etc ...)
3. Run "npm run dev"

### Expected Behavior

I expected to see this in the terminal "Remix App Server started at http://localhost:3000"

### Actual Behavior

Instead, the terminal showed 

"The following error is a bug in Remix; please open an issue! https://github.com/remix-run/remix/issues/new

C:\Users\Berry\React\work-journal\node_modules\@remix-run\dev\dist\invariant.js:18
    throw new Error(message);
          ^
Error: Missing output for entry point
    at Object.invariant [as default] (C:\Users\Berry\React\work-journal\node_modules\@remix-run\dev\dist\invariant.js:18:11)    
    at Object.compile (C:\Users\Berry\React\work-journal\node_modules\@remix-run\dev\dist\compiler\compileBrowser.js:257:20)"

**Comment by machour** [comment] 2023-03-10 06:50
Duplicate of #5737

**Closed by machour** 2023-03-10 06:50 UTC
Labels: bug:unverified
