### ISSUE TITLE
yjs throws error when using @remix-run/dev 1.16.0

### ISSUE THREAD

**Issue by anton-g** [remix-run/remix#6290] opened 2023-05-03 08:00 UTC
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Version 1.16.0 of `@remix-run/dev` breaks `yjs`. It works fine for 1.15.0 of `@remix-run/dev`.

I didn't know how to add a test for this specific case, but here's a CodeSandbox with reproduction: https://codesandbox.io/p/github/anton-g/remix-yjs-error/main

Steps to recreate from scratch:
```sh
➜ npx create-remix@latest
? Where would you like to create your app? ./yjs-example
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment
targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes

➜ npm i yjs
```

Add the following to the top of `_index.js`:
```js
import * as Y from 'yjs'

const ydoc = new Y.Doc()
```

Run the app (`npm run dev`) and refresh the page.

### Expected Behavior

New yjs Doc created successfully on page load.

### Actual Behavior

Client crashes with error:
```
caught TypeError: Cannot read properties of undefined (reading 'isTTY')
    at environment.js:125:30
```

**Comment by pcattori** [comment] 2023-05-03 14:38
@anton-g what future flags do you have enabled in `remix.config.js`?

**Comment by anton-g** [comment] 2023-05-07 11:54
> @anton-g what future flags do you have enabled in `remix.config.js`?

Just the defaults from create-remix:

```
  future: {
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
```

Turning them off doesn't seem to make a difference.

**Comment by MichaelDeBoey** [comment] 2023-06-08 18:43
We just published version `1.17.1-pre.0` which includes #6562 (a possible fix). If you'd like to take it for a test run please try it out and let us know what you think!

**Comment by MichaelDeBoey** [comment] 2023-06-10 18:41
@anton-g Closing this as I can't reproduce this locally (tried with 1.15, 1.16 & 1.17) & the CodeSandbox you linked is working fine as well

**Closed by MichaelDeBoey** 2023-06-10 18:41 UTC
Labels: package:dev, bug:unverified

**Comment by anton-g** [comment] 2023-06-12 09:24
@anton-g Tried with 1.17.1-pre.0 and seems to be working now! Great job! 🙌

**Comment by MichaelDeBoey** [comment] 2023-06-12 21:03
@anton-g to be clear: when trying to reproduce this, it was already working in 1.15
