### ISSUE TITLE
hmr rebuilding has race condition occasionally resulting in SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by ngbrown** [remix-run/remix#6831] opened 2023-07-13 22:57 UTC
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Install Remix with Express template (using ESM as is the default)
2. Add enough code that the resulting server module is about 1.4 MiB in size?
3. Run `npm run dev`. (I'm running in Linux docker container, `node:16-bullseye-slim` with the `procps` package installed for the `ps` command that the dev server uses)
4. Make repeated edits in a route component.

### Expected Behavior

I would expect hmr to keep working.

```
[info] rebuilding... (~ app/routes/workshop.vertical-gauge._index/route.tsx)
[info] rebuilt (642ms)
[info] app server ready (55ms)
[info] hmr
[info] rebuilding... (~ app/routes/workshop.vertical-gauge._index/route.tsx)
[info] rebuilt (626ms)
[info] app server ready (80ms)
[info] hmr
[info] rebuilding... (~ app/routes/workshop.vertical-gauge._index/route.tsx)
[info] rebuilt (627ms)
[info] app server ready (62ms)
[info] hmr
```

Lines repeat as long as edits are being made

### Actual Behavior

Instead, I sometimes get this, and there wasn't a syntax error in the source file being changed.

```
[info] rebuilding... (~ app/routes/workshop.vertical-gauge._index/route.tsx)
[info] rebuilt (597ms)
SyntaxError: Unexpected end of input
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at link (node:internal/modules/esm/module_job:67:21)
```

At this point, reloading the browser doesn't work (browser says connection is reset, `NS_ERROR_NET_RESET`), I have to restart the Remix development server to reload and continue making edits.

**Comment by ngbrown** [comment] 2023-07-14 18:51
I've tried other node versions: `node:18-bullseye-slim` and `node:20-bullseye-slim`. All had the same error.

There's a similar stack trace raised in the node.js repo: https://github.com/nodejs/node/issues/42890, where it seems to have something to do with importing `data:` URIs.

**Comment by pcattori** [comment] 2023-08-04 21:03
Duplicate of #6919

**Closed by pcattori** 2023-08-04 21:03 UTC
Labels: package:dev, bug:unverified, feat:dx
