### ISSUE TITLE
BUG: when use google translate -> "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

### ISSUE THREAD

**Issue by zAndrey95** [remix-run/remix#3807] opened 2022-07-20 10:55 UTC
### What version of Remix are you using?

Main site https://remix.run/

### Steps to Reproduce

1. Go to [https://remix.run/](remix)
2. Click to google translate page -> change another language
3. Scroll to block with example (website veiw)
4. Scroll up or down 
5. Get error

`DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### Expected Behavior

All working, not crashed

### Actual Behavior

Crashed

**Comment by machour** [comment] 2022-07-20 11:22
Duplicate of #2943

**Closed by machour** 2022-07-20 11:22 UTC
Labels: bug:unverified
