### ISSUE TITLE
Not able to initiate new project

### ISSUE THREAD

**Issue by fullyDeepak** [remix-run/remix#10309] opened 2024-12-08 20:10 UTC
### Reproduction

![image](https://github.com/user-attachments/assets/c071aefb-ae4d-4b1a-a615-57cabb116945)

### System Info

```shell
System:
  OS: Linux 6.11 Fedora Linux 41 (Workstation Edition)
  CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Memory: 8.89 GB / 15.46 GB
  Container: Yes
  Shell: 5.9 - /usr/bin/zsh
Binaries:
  Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
  npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
  pnpm: 9.14.4 - ~/.local/share/pnpm/pnpm
Browsers:
  Brave Browser: 131.1.73.91
```

### Used Package Manager

npm

### Expected Behavior

It should initiate a project.

### Actual Behavior

Not able to initiate a project.

**Comment by ksamirdev** [comment] 2024-12-09 07:43
+1

**Comment by scorder96** [comment] 2024-12-09 08:22
Duplicate of #10299 
Related PR is #10300 

### Workaround 
Install **create-remix** and **fs-extra** as local dependency, then call it via `npx create-remix`.
`npm i create-remix fs-extra`
`npx create-remix`

**Closed** 2024-12-09 15:00 UTC
Labels: bug:unverified
