### ISSUE TITLE
Button value doesn't get passed to action when using Remix <Form /> component

### ISSUE THREAD

**Issue by ErickTamayo** [remix-run/remix#162] opened 2021-05-13 22:05 UTC
When using a form to perform an action without inputs (e.g. log out a user) using the `<Form />`:

```jsx
<Form method="post" action="/me">
  <button name="actionId" value="sign-out" type="submit">
    Sign Out
  </button>
</Form>;
```

The action in Remix doesn't receive the button value at all.

```js
  const text = await request.text();
  const params = new URLSearchParams(text);
  const entries = Object.fromEntries(params); // entries is an empty object
```

---

On the other hand, if I replace the `<Form/>` for a regular `<form />`

```jsx
<form method="post" action="/projects">
  <button name="actionId" value="sign-out" type="submit">
    Sign Out
  </button>
</form>;

```

```js
  const text = await request.text();
  const params = new URLSearchParams(text);
  const entries = Object.fromEntries(params); // { actionId: 'sign-out' }
```

**Comment by andrelandgraf** [comment] 2022-01-31 05:32
I think this is a duplicate of #101  and can be closed!

**Comment by machour** [comment] 2022-03-17 21:51
Should be fixed now, if not, please open a new issue with a failing code sample 🙏🏼

**Closed by machour** 2022-03-17 21:51 UTC
