### ISSUE TITLE
[Bug]: font files are not moved to `_assets` directory on build

### ISSUE THREAD

**Issue by ties-v** [remix-run/remix#1153] opened 2021-12-19 14:44 UTC
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.18.1

### Steps to Reproduce

[Example on stackblitz.com](https://stackblitz.com/github/ties-v/remix-with-fontsource?devtoolsheight=33)

1. Run `yarn create remix` to create a new remix project. 
2. Install a fontsource package in this project, e.g: `yarn add @fontsource/aguafina-script`
3. Create the main style sheet: [(source)](https://github.com/ties-v/remix-with-fontsource/blob/c73c2a610b2597acd34c84e07da5a7f0f0174db6/app/styles/main.css#L1)
```css
/* app/styles/main.css */
body { font-family: "Aguafina Script"; }
```
4. Add the font style sheet and the main style sheet to `root.tsx`: [(source)](https://github.com/ties-v/remix-with-fontsource/blob/c73c2a610b2597acd34c84e07da5a7f0f0174db6/app/root.tsx#L11-L23)
```tsx
// ...
import fontStyleUrl from "@fontsource/aguafina-script/index.css";
import mainStyleUrl from "~/styles/main.css";

export let links: LinksFunction = () => {
  return [
    { rel: "stylesheet", href: fontStyleUrl },
    { rel: "stylesheet", href: mainStyleUrl }
  ]
}
// ...
```
5. Run the development server: `yarn dev` and visit the page in you browser.

### Expected Behavior

Font files (*.woff or *.woff2) from the fontsource package are copied to the `_assets` folder. Also, the compiled version of the fontsource css points to these font files.

### Actual Behavior

Font files are not copied to the `_assets` folder. Browser receives HTTP 404 when trying to load the font.
![image](https://user-images.githubusercontent.com/1744962/146679034-e259161d-03a3-4da8-beb2-49685d9ea880.png)

**Comment by ties-v** [comment] 2021-12-19 14:45
Related: https://github.com/remix-run/remix/issues/185#issuecomment-985869723

**Comment by synaptiko** [comment] 2022-02-05 17:16
Using the local font from npm is one of the methods described in MUI's docs: https://mui.com/components/typography/#install-with-npm

I would expect this to work out of the box with Remix.

**Comment by akbo** [comment] 2022-03-02 14:27
I found the following workaround on the Remix Discord (credit goes to @kiliman): https://discord.com/channels/770287896669978684/940920958540197889/941007998388690985

For those who don't want to / can't follow the Discord link, add this to your `package.json` to copy the font files to the bulid folder (change `poppins` to the name of the font you use):
```
"build": "remix build && npm run install:fonts",
"postinstall": "remix setup node && npm run install:fonts",
"install:fonts": "rsync -r node_modules/@fontsource/poppins/files/ public/build/_assets/files/"
```

**Comment by melloware** [comment] 2022-06-27 18:21
If you are using [PrimeIcons ](https://github.com/primefaces/primeicons)with [PrimeReact](https://primefaces.org/primereact/setup/) then the script is...

```
"build": "remix build && npm run install:fonts",
"postinstall": "remix setup node && npm run install:fonts",
"install:fonts": "rsync -r node_modules/primeicons/fonts/ public/build/_assets/files/"
```

**Comment by cdev-enter** [comment] 2022-07-12 15:45
Copying font files manually does not work with the latest version (1.6.4) anymore. Font file references are now cache busted.

Is there a way to disable cache busting for css or make remix copy the font files?

**Comment by mcansh** [comment] 2022-07-22 18:47
looking into this a bit, looks like esbuild doesn't copy imports/urls from `.css` files if the loader is set to 'file'

**Comment by mcansh** [comment] 2022-07-22 19:41
i did manage to get this working using `postcss` as a interim step in the build process

```js
const path = require("node:path");
const fse = require("fs-extra");

module.exports = {
  plugins: {
    "postcss-import": {},
    "postcss-url": {
      url: (asset) => {
        let { absolutePath } = asset;
        let basename = path.basename(absolutePath);
        let outDir = path.join(
          __dirname,
          "public",
          "build",
          "_assets",
          "fonts"
        );
        let destpath = path.join(outDir, basename);
        if (!fse.pathExistsSync(destpath)) {
          fse.copySync(absolutePath, destpath);
        }
        return "/" + path.join("build", "_assets", "fonts", basename);
      },
    },
  },
};
```

```css /styles/index.css
@import "@fontsource/aguafina-script/index.css";
```

using `npm-run-all` to run both remix and postcss in one tab

```json /package.json
"scripts": {
  "dev:css": "postcss ./styles/index.css --output ./app/styles/index.css --watch",
  "dev:remix": "remix dev",
  "dev": "run-p dev:*"
}

```js /app/routes/root.jsx
import fontStyleUrl from './styles/index.css';
```

**Comment by mrmartineau** [comment] 2022-08-24 16:30
> ```
> "build": "remix build && npm run install:fonts",
> "postinstall": "remix setup node && npm run install:fonts",
> "install:fonts": "copyfiles -u 3 "./node_modules/primeicons/fonts/*" ./public/build/_assets/fonts/",
> ```

So this method works when running `remix build` but does not when running `remix dev`. For some reason when running `remix dev` there are two `build` directories generated: one in the `public` directory and another in the root of the repo (which looks like a duplicate of the directory in the `public` directory..).

My fix for this was to add a `prestart` script like so:

```
"prestart": "npm run install:fonts",
"start": "remix dev"
```

if you use `npm run dev` instead, it would look like this:

```
"predev": "npm run install:fonts",
"dev": "remix dev"
```

**Comment by domino2** [comment] 2022-08-30 03:29
I think this should be handled by the framework and not by developers using the remix.
I was wondering, so I had a look and the loader for the css is actually a `"file"` type also mentioned in the https://github.com/remix-run/remix/issues/185#issuecomment-1007139460.
After change to `"css"` as esbuild should to cover it I see this in the console.

```
Remix App Server started at http://localhost:3001 (http://172.20.10.2:3001)
GET / 200 - - 143.124 ms
GET /[object%20Object] 404 - - 9.569 ms
```

Otherwise I see 
```
...
GET /build/_assets/fonts/primeicons.ttf 404 - - 6.513 ms
GET /build/_assets/fonts/primeicons.woff 404 - - 5.325 ms
```

I think that esbuild has some problem here or it is used on way which doesn't allow to parse css properly.

**Comment by mcansh** [comment] 2022-08-30 18:02
> I think this should be handled by the framework and not by developers using the remix.

definitely, i took a quick look at this a bit ago - never opened an issue on esbuild yet, but looks like if you use a `file` loader on a css file it doesn't copy over the `url()` assets in that file

**Comment by mcansh** [comment] 2022-08-30 18:39
looks like this is what we need to do: https://github.com/evanw/esbuild/issues/1757#issuecomment-963133064 looking into it :)

**Comment by KingSora** [comment] 2022-09-03 18:01
@mcansh I've created a plugin which (hopefully) does the job.. I've tried to touch as less as possible and recycle as many build optons as possible #4130

**Comment by mcansh** [comment] 2022-09-06 18:35
> @mcansh I've created a plugin which (hopefully) does the job.. I've tried to touch as less as possible and recycle as many build options as possible #4130

awesome! i'm gonna pull this and check it out ❤️

**Comment by ayuhito** [comment] 2022-09-07 11:28
We're actually [rebuilding the Fontsource website](https://github.com/fontsource/fontsource/issues/558) with Remix so this is huge. Thank you so much for giving up your time for this @mcansh and @KingSora!

**Comment by machour** [comment] 2022-10-20 19:21
Fixed in 1.7.3, thank you @KingSora  🎉

**Closed by machour** 2022-10-20 19:21 UTC
Labels: bug

**Comment by sergioarieljuarez** [comment] 2022-10-30 17:47
> copyfiles

Hi Friends !!!
In my case, the development server sources did not load...
I share in this answer my solution (in Remix App FullStack Framework):
________________________________________
// in your root project:
1. ) add "copyfiles" library in your project:
`yarn add copyfiles`
[copyfiles library docs link](https://www.npmjs.com/package/copyfiles)
________________________________________
// in your package.json file allocated in your root project:
2. ) add "dev:fonts" script in your package.json
For example in my case:
```
...previus lines
"dev": "run-p dev:*",
"dev:css": "npm run generate:css -- --watch",
"dev:remix": "cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev",
"dev:fonts": "rsync -r public/fonts/ public/build/_assets/fonts/",
...next lines
```
________________________________________
// in your css file to load in your route:
3) add your @font-face css rules in your css file loaded from your route:
For example in my case: 
```
@font-face {
    font-family: 'ChekoFontBold';
    src: local('ChekoFont-Bold'),
    url('fonts/Cheko Fonts/Web/ChekoFont/ChekoFont-Bold.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
    url('fonts/Cheko Fonts/Web/ChekoFont/ChekoFont-Bold.woff') format('woff'), /* Modern Browsers */
    url('fonts/Cheko Fonts/Web/ChekoFont/ChekoFont-Bold.ttf') format('truetype'), /* Safari, Android, iOS */
    url('fonts/Cheko Fonts/Web/ChekoFont/ChekoFont-Bold.svg#BloggerSans') format('svg'); /* Legacy iOS */
    font-style: normal;
    font-weight: normal;
    text-rendering: optimizeLegibility;
}

.section-title {
    font-family: "ChekoFontBold" !important;
    text-align: center;
    font-size: 2rem !important;
}
```
________________________________________
// in your css file to load in your route:
4) add your rule css className in your tsx or jsx file loaded from your route:
For example in my case: 
```
import React from 'react';

export default function About() {
    return (<div className={`section`}>
	<h1 className={`section-title`}>{"Good luck !"}</h1>
</div>);
}
```

Its worked for me !! 
Good luck !

**Comment by machour** [comment] 2022-10-30 19:57
@sergioarieljuarez if 1.7.3 didn't work for you here, please open a new issue and provide a public repository reproducing the problem 🙏

**Comment by universse** [comment] 2022-11-19 12:40
hi, any tip on how to get the url for the hashed font file referenced in the css file? I'm trying to preload the font via route module's `links` function, but esbuild throws an error when importing the font file from node_modules.

**Comment by machour** [comment] 2022-11-19 13:04
@universse please ask questions in the Discussions tab.
