### ISSUE TITLE
[Bug] :  'npm run dev' not working as expected : "Error: Missing output for entry point on"

### ISSUE THREAD

**Issue by adedotxn** [remix-run/remix#5737] opened 2023-03-09 10:24 UTC
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce
```
> git clone <new repo>
> cd <new repo>
> npx create-remix@latest
> npm run dev
```
### Expected Behavior

Open up a local development server as expected

### Actual Behavior

![Screenshot (3203)](https://user-images.githubusercontent.com/74747245/223993472-8447a652-d011-41dc-8335-0ab19778a39b.png)

```
> remix dev

The following error is a bug in Remix; please open an issue! https://github.com/remix-run/remix/issues/new


C:\Users\del\Desktop\dev\side-projects\wordplaylist\tut\node_modules\@remix-run\dev\dist\invariant.js:18
    throw new Error(message);
          ^
Error: Missing output for entry point
    at Object.invariant [as default] (C:\Users\del\Desktop\dev\side-projects\wordplaylist\tut\node_modules\@remix-run\dev\dist\invariant.js:18:11)
    at Object.createAssetsManifest (C:\Users\del\Desktop\dev\side-projects\wordplaylist\tut\node_modules\@remix-run\dev\dist\compiler\assets.js:91:23)
    at Object.compile (C:\Users\del\Desktop\dev\side-projects\wordplaylist\tut\node_modules\@remix-run\dev\dist\compiler\compileBrowser.js:256:20)
```

**Comment by obillwan** [comment] 2023-03-12 03:23
@machour - why was this bug closed?  I'm getting the same bug.

**Comment by adedotxn** [comment] 2023-03-12 06:43
> @machour / @adedotxn - Can either of you explain why was this bug closed? I'm getting the same bug. Is this being worked on? Thank you.

This issue is still open. I think machour closed his when he found out it's a duplicate.
I have no idea if this bug is being worked on but to get around this bug/error, I had to Install a [remix template ](https://remix.guide/templates) instead, specifically [this one by colbywhite](https://remix.guide/resources/932EYHid67BP?list=templates) , and deleted the code/files/packages I didn't need.

I think the bug might be an issue with just the latest version of Remix.

**Comment by pcattori** [comment] 2023-08-04 20:02
Duplicate of #6418 , not reproducible on 1.19.2

**Closed by pcattori** 2023-08-04 20:02 UTC
Labels: package:dev, bug:unverified
