### ISSUE TITLE
"unstable_dev" not working on Windows

### ISSUE THREAD

**Issue by trevor-hackett** [remix-run/remix#6308] opened 2023-05-04 19:10 UTC
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On a Windows machine, create a new Remix app with `unstable_dev` enabled. (ex: `npx create-remix@latest --template https://github.com/remix-run/remix/tree/templates_v2_dev/templates/remix my-app`)

Run the app. (`npm run dev`)

### Expected Behavior

Dev server and app server runs successfully

### Actual Behavior

App server fails to run with these logs:

```
> dev
> remix dev

💿 Building...
💿 Built in 508ms
Waiting for app server (13c89a7f)
> remix-serve build\index.js
Remix dev server ready
'remix-serve' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pcattori** [comment] 2023-05-05 00:02
@trevor-hackett do you have `@remix-run/serve` installed and `remix-serve` within `node_modules/bin`?

**Comment by trevor-hackett** [comment] 2023-05-05 02:48
Yes. `@remix-run/serve` is installed and I do see `remix-serve` inside `node_modules/.bin`

After adding the test script, the app server starts up by itself.

Here's the two scripts run one after the other:

```
PS D:\dev\my-app22> npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 531ms
Waiting for app server (b0701266)
> remix-serve build\index.js
Remix dev server ready
'remix-serve' is not recognized as an internal or external command,
operable program or batch file.
Terminate batch job (Y/N)? y

PS D:\dev\my-app22> npm run test

> test
> remix-serve ./build

Remix App Server started at http://localhost:3000 (http://192.168.169.228:3000)
```

It might be worth mentioning that if I turn off `unstable_dev` it runs without issue.

This only happens on Windows from what I can tell. On the same machine running in WSL (Ubuntu) it works without any issues.

**Comment by pcattori** [comment] 2023-05-05 03:13
Probably caused by unnormalized path separator here: https://github.com/remix-run/remix/blob/dev/packages/remix-dev/devServer_unstable/index.ts#L32

**Comment by pcattori** [comment] 2023-05-05 03:20
Potentially fixed by #6310

**Comment by pcattori** [comment] 2023-05-05 03:31
@trevor-hackett to verify that the PATH is the cause of the issue, could you try:

```json
{
  "scripts": {
    "test": "echo $PATH",
  }
}
```

**Comment by trevor-hackett** [comment] 2023-05-05 03:52
I poked around at the the code in that file and changing the `:` to `;` on this line fixed the issue for me.

https://github.com/remix-run/remix/blob/f5ef1ac8f0f01770a28f86ad11f3cbeade540452/packages/remix-dev/devServer_unstable/index.ts#L73

I logged out that path and it was the only path that wasn't separated by a `;`

This is what the path variable being passed to `execa.command()` looked like:

```
D:\dev\my-app22\node_modules\.bin:D:\dev\my-app22\node_modules\.bin;C:\Users\trevor\AppData\Roaming\npm\node_modules\pnpm\dist\node-gyp-bin;C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.4.0_x64__8wekyb3d8bbwe;C:\Python311\Scripts\;C:\Python311\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Users\trevor\AppData\Local\pnpm;C:\Users\trevor\scoop\shims;C:\Users\trevor\AppData\Local\Microsoft\WindowsApps;C:\Users\trevor\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\trevor\.dotnet\tools;C:\Users\trevor\AppData\Roaming\npm;C:\Users\trevor\AppData\Local\gitkraken\bin;C:\Users\trevor\AppData\Local\GitHubDesktop\bin
```

I don't know if that "fix" would work outside of Windows.

**Comment by pcattori** [comment] 2023-05-05 04:12
Conditionally joining PATH with `;` on Windows and `:` on all other OSs: #6312

**Closed** 2023-05-06 07:06 UTC
Labels: package:dev, bug:unverified

**Comment by jgentes** [comment] 2023-06-08 13:55
I can confirm this fix worked 👍
