### ISSUE TITLE
<Scripts crossOrigin /> doesn't work for when hosting the app's JS assets on a different CDN server

### ISSUE THREAD

**Issue by ranjithkumar-n** [remix-run/remix#3572] opened 2022-06-25 01:02 UTC
### What version of Remix are you using?

1.6.1

### Steps to Reproduce

Try to host public/build assets in a CDN by passing the right CDN prefix to `publicPath` in your remix.config.js

Sample: remix.config.js

<img width="470" alt="image" src="https://user-images.githubusercontent.com/63418450/175752333-edba4a98-f12d-48c9-b010-7b503b271df5.png">

And now when the scripts are loaded via `<Scripts crossOrigin/>` in `root.tsx` file, the scripts fail to load with `CORS Error`

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/63418450/175752082-f7e68e3b-37c9-43cb-b154-f1291e0682c4.png">

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/63418450/175752104-949ee062-d51d-499d-9a96-66bc2094c647.png">

As per the docs here https://remix.run/docs/en/v1/api/remix#meta-links-scripts, the above settings should work when scripts are hosted on another server than the app, screenshot of the docs below

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/63418450/175752019-9043b82c-d487-48b3-be9d-e3aecd3ac873.png">

### Expected Behavior

`<Scripts crossOrigin />` should work when assets are hosted in an external CDN server.

If possible add props to `<Scripts />` component to add scripts as plain scrips instead of module

### Actual Behavior

When using `<Scripts crossOrigin />` to add CDN based JS files the JS files fail to load with CORS error

**Comment by kennethvdberghe** [comment] 2022-06-27 16:48
Are you sure you have configured the CDN correctly to allow other origins to fetch these resources? Since the error is stating `No 'Access-Control-Allow-Origin' header is present.` I think this is the reason for the browser blocking you to fetch the resources from the CDN coming from qaa.priceline.com.

**Comment by ranjithkumar-n** [comment] 2022-07-25 22:40
@kennethvdberghe sorry for the late response, so I inspected the HTML, the <Scripts /> component seems to render `link` tag with rel set to `modulepreload`

Like this below,
`<link rel="modulepreload" href="https://assets.pclncdn.com/web/partner-pages/ccffcd2c6e/bundle.c23ea32b87e6b15a417d.js"></link>`

**Comment by brophdawg11** [comment] 2023-08-08 20:30
I'm going to close this out since I can't reproduce and it seems to be an error due to a mismatching CORS header on your asset server.  If you can provide a minimal reproduction, please feel free to re-open!

To test, I created a new Remix express app (`npx create-remix@latest`) and set `publicPath: "http://localhost:8888/assets"`.

Then I created an asset Express server to serve from the `public/build/` directory on port 8888 at the path `/assets`:

```js
import express from "express";

const app = express();
app.use(
  "/assets",
  express.static("public/build", { immutable: true, maxAge: "1y" })
);

app.listen(8888, async () => {
  console.log(`Asset server listening on port 8888`);
});
```

This produced your error above - both with and without `crossOrigin=""` on `<Scripts />`:

```
Access to script at 'http://localhost:8888/assets/entry.client-ZNK7YNKG.js' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

To remedy the error, I just added the indicated header to my asset server:

```js
app.use(
  "/assets",
  (req, res, next) => {
    res.setHeader("Access-Control-Allow-Origin", "*");
    next();
  },
  express.static("public/build", { immutable: true, maxAge: "1y" })
);
```

Then the remix app works fine loading assets from my pseudo-CDN.

**Closed by brophdawg11** 2023-08-08 20:30 UTC
Labels: bug:unverified, renderer:react
