### ISSUE TITLE
Unable to run Remix on monorepo

### ISSUE THREAD

**Issue by nachoaldamav** [remix-run/remix#4177] opened 2022-09-12 10:55 UTC
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

Create monorepo with turbo
`npx create-turbo@latest`

Create Remix app inside apps folder
```bash
cd apps
npx create-remix
```

### Expected Behavior

Work inside monorepo.

### Actual Behavior

When running npm install (doesn't matter if i do it in the root of the monorepo or in the remix app) and npm run dev gives the following errors.
```bash
[1] Watching Remix app in development mode...
[0] Done in 170ms.
[1] The path "framer-motion" is imported in app/components/graph.tsx but "framer-motion" was not found in your node_modules. Did you forget to install it?
[1] 💿 Built in 498ms
[1] Remix App Server started at http://localhost:3000 (http://172.26.131.88:3000)
[1] Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
[1] 1. You might have mismatching versions of React and the renderer (such as React DOM)
[1] 2. You might be breaking the Rules of Hooks
[1] 3. You might have more than one copy of React in the same app
[1] See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by nachoaldamav** [comment] 2022-09-12 11:09
I've copied the folder outside of the monorepo and it works, so it's a problem related to the monorepos.

**Comment by machour** [comment] 2022-09-12 19:31
Duplicate of #4106

**Closed by machour** 2022-09-12 19:31 UTC
Labels: bug:unverified
