### ISSUE TITLE
Transferring to Express from app server, but keeps running app server with no errors

### ISSUE THREAD

**Issue by ddm50** [remix-run/remix#7585] opened 2023-10-03 22:51 UTC
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've no real way to reproduce this. I was on 1.13, switched to 1.19.3 before trying to go to Express. Used rmx-cli ejact-ras function, thought it worked. Didn't do much. Whatever I did it would keep running remix app server, it seems to totally ignore the arguments and does not output errors of any kind. I tried uninstalling node_modules but nothing. I've been having this issue for 2 days now and no one has a clue as to what is the issue.

 
`   "dev": "remix dev --manual -c \"npm run dev:node\"",
    "dev:node": "nodemon --require dotenv/config ./server.js --watch ./server.js",

const fs =require('fs');

const { createRequestHandler } = require( "@remix-run/express");
const { broadcastDevReady, installGlobals } =require( "@remix-run/node");
const chokidar = require( "chokidar");
const compression = require("compression");
const express = require( "express");
const morgan = require( "morgan");
const sourceMapSupport = require( "source-map-support)

sourceMapSupport.install();
installGlobals();

const BUILD_PATH = "./build/index.js";
/**
 * @type { import('@remix-run/node').ServerBuild | Promise<import('@remix-run/node').ServerBuild> }
 */
let build = await import(BUILD_PATH);

const app = express();

app.use(compression());

// http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header
app.disable("x-powered-by");

// Remix fingerprints its assets so we can cache forever.
app.use(
    "/build",
    express.static("public/build", { immutable: true, maxAge: "1y" })
);

// Everything else (like favicon.ico) is cached for an hour. You may want to be
// more aggressive with this caching.
app.use(express.static("public", { maxAge: "1h" }));

app.use(morgan("tiny"));

app.all(
    "*",
    process.env.NODE_ENV === "development"
        ? createDevRequestHandler()
        : createRequestHandler({
          build,
          mode: process.env.NODE_ENV,
        })
);

const port = process.env.PORT || 3000;
app.listen(port, async () => {
  console.log(`Express server listening on port ${port}`);

  if (process.env.NODE_ENV === "development") {
    broadcastDevReady(build);
  }
});

function createDevRequestHandler() {
  const watcher = chokidar.watch(BUILD_PATH, { ignoreInitial: true });

  watcher.on("all", async () => {
    // 1. purge require cache && load updated server build
    const stat = fs.statSync(BUILD_PATH);
    build = import(BUILD_PATH + "?t=" + stat.mtimeMs);
    // 2. tell dev server that this app server is now ready
    broadcastDevReady(await build);
  });

  return async (req, res, next) => {
    try {
      //
      return createRequestHandler({
        build: await build,
        mode: "development",
      })(req, res, next);
    } catch (error) {
      next(error);
    }
  };
}
`

### Expected Behavior

To run Express instead of Remix App Server

### Actual Behavior

Runs Remix App Server, does not care for any arguments put. You can put server.js or a random name, it just doesn't care. I thought it'd be some simple process but its anything but. I thought the issue may be that I was on 1.13, but that is all gone, I reinstalled node_modules, removed any kind of build files.

**Comment by kiliman** [comment] 2023-10-03 23:26
The `eject-ras` script simply copies the Remix express templates and updates package.json. However, it tries not to overwrite files.

The main thing to ensure that you're using launching the correct server is to verify that _package.json_ `"dev"` command is correct. If you look at the actual template file, you'll see that it explicitly runs `node server.js` which is the express server file.

You may also want to double-check your _remix.config.js_ file that it matches the template, especially since you upgraded from an older version of Remix.

Finally, did you run `npm install` after you ejected? That is needed so the correct packages are installed.

https://github.com/remix-run/remix/blob/a20ae7fb0727212ac52bdc687513c61851ac4014/templates/express/package.json#L5-L10

https://github.com/remix-run/remix/tree/main/templates/express

**Comment by ddm50** [comment] 2023-10-04 00:22
> The `eject-ras` script simply copies the Remix express templates and updates package.json. However, it tries not to overwrite files.
> 
> The main thing to ensure that you're launching the correct server is to verify that the _package.json_ `"dev"` command is valid. If you look at the actual template file, you'll see that it explicitly runs `node server.js`, which is the express server file.
> 
> You may also want to double-check that your _remix.config.js_ file matches the template, especially since you upgraded from an older version of Remix.
> 
> Finally, did you run `npm install` after you ejected? That is needed so the correct packages are installed.
> 
> https://github.com/remix-run/remix/blob/a20ae7fb0727212ac52bdc687513c61851ac4014/templates/express/package.json#L5-L10
> 
> https://github.com/remix-run/remix/tree/main/templates/express

Hi, thanks for the reply. Unfortunately this doesn't do anything. I did do npm install. Even tried it just now. 
The config is the same. There's really nothing different. I thought maybe serverModuleFormat could be it, but switched to esm from cjs, and nothing. I'd create a repo but it is a bigger project and not really comfortable with it. 

Nothing I do affects what remix dev does. It does whatever it wants, doesn't show any errors when I put that -c "node server.js" argument.

**Comment by cliffordfajardo** [comment] 2023-10-04 17:54
@ddm50 - I recommend the following for debuggin:

1. Create a fresh remix express app and choose the express template
```
```

**Comment by ddm50** [comment] 2023-10-09 13:51
There's absolutely no difference. It just doesn't work.

**Comment by ddm50** [comment] 2023-10-09 22:22
It would appear this issue is related with v2_dev flag, if it's not set to true it doesn't care about the arguments. Perhaps it does care, but I assume unless set it uses older arguments that are not known to me. A bit surprised someone wouldn't have pointed this out but all's well that ends well I guess. 


![image](https://github.com/remix-run/remix/assets/82258474/47402e67-179e-4492-92e2-4ec2183569ef)
Now remains this issue for me

**Comment by pcattori** [comment] 2023-10-10 14:12
@ddm50 the root cause it `esbuild`'s compilation of the server, which only supports top-level `await` when the target is set to `node16` or newer. But Remix v1 supports Node 14, so we couldn't make that change as it would have been breaking. This is fixed in Remix v2 (https://github.com/remix-run/remix/pull/7292/files) since v2 supports Node 18+ (and dropped official support for Node 14)

**Closed by pcattori** 2023-10-10 14:12 UTC
Labels: bug:unverified
