### ISSUE TITLE
Not able to deploy on Fly via Docker: `top-level await` error

### ISSUE THREAD

**Issue by binajmen** [remix-run/remix#6357] opened 2023-05-09 13:09 UTC
### What version of Remix are you using?

v1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Deploy to Fly using Docker

### Expected Behavior

Build should succeed

### Actual Behavior

Build step is failing:

```
#17 [build 6/6] RUN npm run build
#17 14.11 ✘ [ERROR] This require call is not allowed because the imported file "node_modules/@jspm/core/nodelibs/browser/worker_threads.js" contains a top-level await
#17 14.11 
#17 14.11     node_modules/@prisma/client/runtime/index.js:13:8230:
#17 14.11       13 │ ...ssageOnPort:LR}=require("worker_threads"),xR=["GET","HEAD","POS...
#17 14.11          ╵                            ~~~~~~~~~~~~~~~~
#17 14.11 
#17 14.11   The top-level await in "node_modules/@jspm/core/nodelibs/browser/worker_threads.js" is here:
#17 14.11 
#17 14.11     node_modules/@jspm/core/nodelibs/browser/worker_threads.js:97:49:
#17 14.11       97 │ ...rkerData, environmentData }] = await once(parentPort, 'message'));
#17 14.11          ╵                                   ~~~~~
#17 14.11 
#17 14.11 
#17 14.11 ✘ [ERROR] This require call is not allowed because the imported file "node_modules/@jspm/core/nodelibs/browser/worker_threads.js" contains a top-level await
#17 14.11 
#17 14.11     node_modules/@prisma/client/runtime/index.js:56:58637:
#17 14.11       56 │ ...MessagePort:SU}=require("worker_threads"),uA,WA=class extends E...
#17 14.11          ╵                            ~~~~~~~~~~~~~~~~
#17 14.11 
#17 14.11   The top-level await in "node_modules/@jspm/core/nodelibs/browser/worker_threads.js" is here:
#17 14.11 
#17 14.11     node_modules/@jspm/core/nodelibs/browser/worker_threads.js:97:49:
#17 14.11       97 │ ...rkerData, environmentData }] = await once(parentPort, 'message'));
#17 14.11          ╵                                   ~~~~~
#17 14.11 
#17 14.11 
#17 14.15 ERROR: "build:remix" exited with 1.
```

**Comment by nakleiderer** [comment] 2023-05-17 14:24
I was able to circumvent the issue with an npm override:
```
"overrides": {
    "@remix-run/dev": {
      "esbuild-plugin-polyfill-node": "0.1.0"
    }
  }
```

**Comment by nakleiderer** [comment] 2023-05-17 19:45
Just saw Remix 1.16.1 dropped and gave it a shot, but receiving the same errors. I have two apps with the same error now, so maybe I can figure out a reproduction. This affects the production build and the dev builds.

**Comment by bvkimball** [comment] 2023-05-17 20:22
Here are the relevant deps...  i can add devDeps if you want.

https://gist.github.com/bvkimball/5f93ed2ad2f81fbd8279c71641860200

I use a mono-repo similar to this, but not the same: https://github.com/NoQuarterTeam/boilerplate

I am in the process of cleaning this up now too so i will remove any unused deps and let you know

I think its prisma or zenstack for me that is causeing it.

**Comment by nakleiderer** [comment] 2023-05-17 20:41
This is what appears we have in common (devDependencies doesn't account for your project):
```
Common dependencies:
@prisma/client
@remix-run/server-runtime
tiny-invariant
zod



Common devDependencies:
@faker-js/faker
@tailwindcss/aspect-ratio
@tailwindcss/forms
@tailwindcss/typography
@types/eslint
@types/node
@types/nprogress
@typescript-eslint/eslint-plugin
@vitest/coverage-c8
esbuild
eslint-config-prettier
eslint-plugin-tailwindcss
msw
prettier
prisma
tailwindcss
tsconfig-paths
vite-tsconfig-paths
vitest
```

**Comment by nakleiderer** [comment] 2023-05-17 21:28
It looks like something is causing `@remix/dev` to bundle the `esbuild-plugin-polyfill-node`. Still no luck on my end figuring out what is triggering it to load.

**Comment by nakleiderer** [comment] 2023-05-17 21:51
Probably not helpful, but removing this line makes everything work again: https://github.com/remix-run/remix/blob/cb7a4e8fd2f3f6cf6840672905a7bf8e032849c7/packages/remix-dev/compiler/js/compiler.ts#L148

**Comment by nakleiderer** [comment] 2023-05-18 13:42
I one of my projects, I had a resource route that imported a library with node library usage. When I put that dependency behind a `.server.ts` file, I was able to build. This is very unexpected since it was a resource route (only exports a loader).

I also had to update a Sentry import from `import { BrowserTracing } from "@sentry/tracing";` to use `import * as Sentry from "@sentry/remix";` as `new Sentry.BrowserTracing()` but this may have been because I updated my Sentry dependencies and might not be related to the actual issues here.

I found I had more luck update remix version-by-version instead of leaping from 1.13 > 1.16.1 directly. I was able to get better error messages for issues along the way, fix them, then upgrade to the next version.

**Comment by bvkimball** [comment] 2023-05-18 18:17
Ok, thank you for all the help....  I deleted everything in my routes until it was just and index, root, and entry.x files
For me it seems it is an my `session.server.ts` which i moved into a "package" in my monorepo then imported poorly.

I basically couldn't narrow it down to just one thing... but basically if my mono-repo packages bleed any node dep than it borked.  Basically treeshaking was working or i missed something.

for me i re-exported all my monorepo packages in a file like `utils/[package].server`

```ts
export * from `@monorepo/[package]`;
```

i wish i could just mark packages as server only.

**Comment by bvkimball** [comment] 2023-05-19 13:35
I really figured it what caused it for my repo.

I include `zod` schemas in the same package that my "server-side" business logic exists.  but i also use that `zod` schema to do form validation on client & server-side.

I assumed that the `zod` schema would be "tree-shaken" out of the package, but this doesn't seem to be the case.  I am using `serverDependenciesToBundle` feature too.

There are several other issues listing this in issues now:
https://github.com/remix-run/remix/issues/6318
https://github.com/remix-run/remix/issues/6302

**Comment by onemen** [comment] 2023-05-22 11:26
did any of you use `"chalk": "^5.2.0"`

with `"chalk": "^4.1.2"` i don't see this error `"node_modules/@jspm/core/nodelibs/browser/worker_threads.js"`

**Comment by fiws** [comment] 2023-05-22 14:13
I had the same problem and solved it by migrating some deprecated `@prisma/client/runtime` imports in my app to `@prisma/client/runtime/library`.


If you get this during startup:

```
imports from "@prisma/client/runtime" are deprecated.
Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"
```

It might also work for you.

**Comment by znycheporuk** [comment] 2023-07-06 10:55
I had a similar issue, setting target to node18 fixed an issue


`remix,config.js`

<img width="513" alt="image" src="https://github.com/remix-run/remix/assets/42861377/e3f227df-f405-4b87-b482-d17cd82e10cc">

**Comment by markdalgleish** [comment] 2023-08-15 03:50
It looks like there's a few solutions here:

- Migrate to `@prisma/client/runtime/library`, as @fiws said, as this doesn't appear to call `require("worker_threads")`.
- If that doesn't work (or if you're hitting this error another way), you can move `require("worker_threads")` or any imports of packages/modules calling this into a `*.server.ts` file so that Remix won't include the code in the client module graph. Note that tree-shaking doesn't fix this problem because this error happens during an earlier phase of the build process.

It might be worth raising this as an issue upstream against [esbuild-plugins-node-modules-polyfill](https://github.com/imranbarbhuiya/esbuild-plugins-node-modules-polyfill) since that plugin could potentially stub out `"worker_threads"` with an empty module in a CJS context rather than breaking the build, but this might need to be configurable via plugin options.

I'm closing this for now, but if this doesn't help address your problem, could you please open a new, more specific issue with a reproduction?

**Closed by markdalgleish** 2023-08-15 03:50 UTC
Labels: package:dev, bug:unverified, template:fly
