### ISSUE TITLE
`.server` imports erroring with build command (Vite - Nightly)

### ISSUE THREAD

**Issue by mmachatschek** [remix-run/remix#7818] opened 2023-10-30 12:33 UTC
### What version of Remix are you using?

nightly (2.2.0-pre.0)

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Clone the repo https://github.com/mmachatschek/vite-server-only-code
2. run `npm install`
3. run `npm run build`
4. see the error in the console

### Expected Behavior

The build doesn't fail with `.server` imports

### Actual Behavior

Using any imports with `.server` suffix will make the vite build command fail (dev command works as expected)

Error Log in console:

```
"helloWorld" is not exported by "app/feature/hello-world.server.ts", imported by "app/routes/api.json.ts".
file: /Users/markus/vite-server-only-code/app/routes/api.json.ts:2:9
1: import { json } from '@remix-run/node';
2: import { helloWorld } from '~/feature/hello-world.server';
            ^
3:
4: export const action = () => {
error during build:
RollupError: "helloWorld" is not exported by "app/feature/hello-world.server.ts", imported by "app/routes/api.json.ts".
    at error (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at CallExpression.bind (file:///Users/markus/vite-server-only-code/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
```

**Comment by pcattori** [comment] 2023-10-30 14:48
Duplicate of https://github.com/remix-run/remix/issues/7795

**Closed** 2023-10-30 14:50 UTC
Labels: bug:unverified, vite
