### ISSUE TITLE
Error console  WebSocket connection to 'ws://localhost:59765/socket' failed:  Remix dev asset server web socket error:

### ISSUE THREAD

**Issue by hakimLyon** [remix-run/remix#3197] opened 2022-05-15 07:55 UTC
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

- ``` npm run dev  ```
- Check the console in Chrome's inspector in few minutes 

### Expected Behavior

No errors Remix dev asset server web socket error

### Actual Behavior

```sh
WebSocket connection to 'ws://localhost:59765/socket' failed: 
(anonyme) @ valider:30
valider:42 Remix dev asset server web socket error:
valider:43 EventisTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'ws://localhost:59765/socket', readyState: 3, bufferedAmount: 0, onopen: null, onerror: ƒ, …}defaultPrevented: falseeventPhase: 0path: []returnValue: truesrcElement: WebSocket {url: 'ws://localhost:59765/socket', readyState: 3, bufferedAmount: 0, onopen: null, onerror: ƒ, …}target: WebSocket {url: 'ws://localhost:59765/socket', readyState: 3, bufferedAmount: 0, onopen: null, onerror: ƒ, …}timeStamp: 1082.7000002861023type: "error"[[Prototype]]: Event
ws.onerror @ valider:43


```

**Comment by machour** [comment] 2022-05-15 17:29
Duplicate of #3193

**Closed by machour** 2022-05-15 17:29 UTC
Labels: bug:unverified
