### ISSUE TITLE
Error: [remix] dest already exists.

### ISSUE THREAD

**Issue by danestves** [remix-run/remix#8813] opened 2024-02-20 22:46 UTC
### Reproduction

Using this template 👉 https://github.com/kiliman/remix-vite-template that doesn't differ very much from the official one 👉 https://github.com/remix-run/remix/tree/main/templates/vite-express

It gives the following error when running `remix vite:build`:

![](https://github.com/remix-run/remix/assets/31737273/2fa9e2c5-d4f0-4a5d-83bb-4d62abe9716c)

This only happens to me after upgrading to `2.7.0` of Remix

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    bun: 1.0.28 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
```

### Used Package Manager

npm

### Expected Behavior

Build normally like the previous version (2.6.0)

### Actual Behavior

Breaking the builds

**Comment by danestves** [comment] 2024-02-20 22:48
Same error from this issue reported too 👉 https://github.com/remix-run/remix/issues/8814 I'm using CSS URLs too

**Comment by wKovacs64** [comment] 2024-02-20 22:55
Closed my issue as a dupe.

For reference, this broke in `@remix-run/dev@2.7.0-pre.2` and carried through to 2.7.0 stable (it was fine in `@remix-run/dev@2.7.0-pre.1`).

**Comment by pajasevi** [comment] 2024-02-20 23:30
Can confirm that I am experiencing the same issue but my build fails with different fatal error when I try to remove `?url`.
```sh
vite v5.1.3 building for production...
✓ 95 modules transformed.
x Build failed in 392ms
Error [RollupError]: "default" is not exported by "app/tailwind.css", imported by "app/root.tsx".
file: /Users/pavelsevcik/WebstormProjects/samourai-fees/app/root.tsx:7:7
5: import robotoFlex from "@fontsource-variable/roboto-flex/index.css?url";
6: 
7: import styles from "./tailwind.css";
```

**Comment by markdalgleish** [comment] 2024-02-21 01:02
Thanks for raising this. I've found the problem, I should have a fix ready soon.

**Comment by markdalgleish** [comment] 2024-02-21 01:27
@pajasevi Your issue is expected when removing ?url from the CSS import since Vite won't provide a default export anymore.

**Comment by robertjpayne** [comment] 2024-02-21 01:48
@markdalgleish this issue also occurs if you add extra entry points that are css files to the vite pipeline via plugins:

e.g.:

```
function extraEntryPoints(): PluginOption {
  return {
    name: "extra-entry-points",
    apply: "build",
    config(config, { command }) {
      if (command !== "build") {
        return;
      }

      return {
        build: {
          rollupOptions: {
            input: ["app/entry.inter.css"],
          },
        },
      };
    },
  };
}
```

**Comment by markdalgleish** [comment] 2024-02-21 02:23
@robertjpayne Ah, that's interesting. If the build passes, how would that extra CSS file be part of your Remix app?

**Comment by robertjpayne** [comment] 2024-02-21 02:24
@markdalgleish it just gets processed as it's own entry point so it gets put into the assets folder and added to the vite manifest. It was working in 2.6.0 and earlier.

**Comment by eavonius** [comment] 2024-02-21 03:38
This just bit me too. Excited about the vite support!

**Comment by ccentrella** [comment] 2024-02-21 04:19
Yeah, I'm experiencing same issue. It happens with any css file that is imported using `Links` if using `?url` which is required for Vite.

```
import anything from "./anyfile.css?url";

export const links: LinksFunction = () => [
    { rel: "stylesheet", href: anything }
];
```

**Comment by markdalgleish** [comment] 2024-02-21 04:48
@robertjpayne Thanks for sharing that repro. I've just confirmed that the PR fixing this issue also fixes your issue: https://github.com/remix-run/remix/pull/8829

**Comment by Lenghak** [comment] 2024-02-21 04:56
H! Please don't mind me cause I am new to this, but how do you find out that the error causes by the css import with `url`?

**Comment by ccentrella** [comment] 2024-02-21 05:14
@Lenghak Because if you remove the `?url` the error goes away :). It takes a bit of trial and error but basically I'll have a hypothesis for what might be causing the issue. If it isn't the issue, I'll keep trying different possibilities trying to isolate the problem further.

**Comment by Lenghak** [comment] 2024-02-21 06:06
Right, sir. So it does require some experiences in order to come up with some hypothesizes or even have a sense to suspect where the error could be. I, personally, wouldn't think that the it comes from the CSS cause the error shows entirely different message. Thank you for your explanation sir, I really appreciate it.

**Comment by markdalgleish** [comment] 2024-02-21 08:10
This is fixed by https://github.com/remix-run/remix/pull/8829, it'll be out in the next patch release.

**Closed** 2024-02-21 16:48 UTC
Labels: bug, vite

**Comment by markdalgleish** [comment] 2024-02-21 19:56
@danestves @robertjpayne Can you please confirm that v2.7.2 fixes your issue?

**Comment by wKovacs64** [comment] 2024-02-21 20:05
@markdalgleish It fixed it, thank you. ❤️

**Comment by pajasevi** [comment] 2024-02-21 20:59
I can confirm this is fixed for me as well. Thank you guys.

**Comment by danestves** [comment] 2024-02-21 21:37
Fixed thanks!

**Comment by eugeniobet** [comment] 2024-06-05 14:53
works up until 2.9.1, seems to be back with 2.9.2
