### ISSUE TITLE
Missing output for entry point

### ISSUE THREAD

**Issue by rlumsden** [remix-run/remix#7876] opened 2023-11-02 14:52 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Follow the steps on the [quick start guide](https://remix.run/docs/en/main/start/quickstart):

mkdir my-remix-app
cd my-remix-app

# install runtime dependencies
npm i @remix-run/node @remix-run/react @remix-run/serve isbot react react-dom

# install dev dependencies
npm i -D @remix-run/dev

mkdir app
touch app/root.jsx

paste into root.jsx:
```
import {
  Links,
  Meta,
  Outlet,
  Scripts,
} from "@remix-run/react";

export default function App() {
  return (
    <html>
      <head>
        <link
          rel="icon"
          href="data:image/x-icon;base64,AA"
        />
        <Meta />
        <Links />
      </head>
      <body>
        <h1>Hello world!</h1>
        <Outlet />

        <Scripts />
      </body>
    </html>
  );
}
```

npx remix build

### Expected Behavior

You should now see a build/ folder (the server version of your app) and public/build folder (the browser version) with some build artifacts in them.

### Actual Behavior

info  building... (NODE_ENV=production)
The following error is a bug in Remix; please open an issue! https://github.com/remix-run/remix/issues/new
Missing output for entry point

**Comment by lumsden-digital** [comment] 2023-11-02 14:53
Sorry about the formatting of the root.jsx file!

**Comment by brophdawg11** [comment] 2023-11-03 14:21
Can you provide a repository with a reproduction?  

Running the steps above worked ok for me (I did have to run `npm init -y` in the app directory before running the `npm install` commands though).  I'll get that fixed in the docs, but otherwise it worked ok.

If you want to you could also just use the existing template by running `npx create-remix@latest`, that will avoid you needing to run the individual steps.

**Comment by lumsden-digital** [comment] 2023-11-03 17:59
Hi @brophdawg11,

I did originally try npx create-remix@latest, however I had a different issue with this, seemingly related to NPM (I had to create an empty npm directory in /users/[user]/AppData/Roaming) hence attempting to build manually.

Just to double check I reproduced the previous steps and again got the same result:

![image](https://github.com/remix-run/remix/assets/59280121/10d5f3a4-2349-4946-8ac9-ca3e9a085dcf)

However when I pushed up the repository: [https://github.com/lumsden-digital/my-remix-app](url), then cloned it locally and tried again, it built successfully! I can't imagine what the difference is that is making the original not work.

**Comment by gyotov** [comment] 2023-12-19 08:22
@rlumsden I had the same issue using Node v21. Switched to Node v18.12.0 and it worked.
Hope that helps.

**Comment by brophdawg11** [comment] 2023-12-19 15:35
It sounds like this might have been a one-off local issue since it worked on a fresh clone.

Also, FWIW if this was a node 21 issue, Remix doesn't technically support that since we support [active/maintenance](https://remix.run/docs/en/main/other-api/node#version-support) LTS versions so it should work on Node 18 and 20 currently.  If that's the case and anyone wants to dig in and look for a root cause we would happily accept a PR that fixes it though!

I'm going to close this since it doesn't sound like we have a reproduction on Node 18/20

**Closed by brophdawg11** 2023-12-19 15:35 UTC
Labels: package:dev, bug:unverified

**Comment by gyotov** [comment] 2024-01-16 07:57
@rlumsden I've encountered the same issue. Tried different node/npm versions with no success: 21.6.0, 21.4.0, 20.0.0, 18.12.0.
I've discovered that the issue only exist in the VS Code terminal. In GitBash it works as expected. Hope this helps.

Cheers

**Comment by nc1z** [comment] 2024-01-19 12:59
Using 2.3.1, able to repro on git bash. Had to switch to windows powershell to avoid the bug.
