### ISSUE TITLE
Add `useScrollRestoration`

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#186] opened 2021-05-25 14:35 UTC
Browsers have built-in scroll restoration for both document transitions and history push/pop events. However, for history events the behavior is *synchronous*: as soon as the event fires, the browser tries to restore the scroll position. This means your data on both pop *and push* events needs to be synchronous as well. This is, of course, not realistic.

These are all typical bugs around scroll position with client routed SPAs

1. The scroll position stays at the bottom of a new page after a link is clicked
2. The scroll position changes to the top of the old page before the data loads for the new page (this one really freaks me out)
3. The scroll position goes to the top on every history event, instead of restoring to the position it was at that entry in the stack

Additionally, one day React's rendering itself will be asynchronous with concurrent mode, so even if you solve the data case (you can't though) the browser would restore scroll before the new page is ready causing bug (2) on pop events.

In order to have automatic scroll restoration with async transitions we need to once again emulate the browser's behavior with document transitions, which is to wait for the next page to be ready before restoring scroll positions.

## window Scroll

This will scroll to the top on push events and restore scroll position on window on pop events:

```tsx
export function Root() {
  useScrollRestoration()
}
```

If you want to stop scroll restoration, pass it `false`

```tsx
export function Root() {
  useScrollRestoration(false)
}
```

This is useful when you have an outlet that is changing a small part of the UI and don't want the page scrolling up and down as the user moves through it, a couple example are Tabs and Multi-step "Wizards". Can use `handle` and `useMatches` to turn off scroll restoration:

```tsx
let matches = useMatches();
let shouldManageScroll = !(matches.some(match => match.handle.scroll === false));
useScrollRestoration(shouldManageScroll)
```

## Scroll Containers

Sometimes your UI has large scrollable containers instead of window that need their position restored. For that we have `useElementScrollRestoration`.

```tsx
export function Root() {
  let ref = useRef<HTMLDivElement>(null);
  useElementScrollRestoration(ref)
  return (
    <>
      <div>Sidebar</div>
      <div ref={ref} style={{ overflow: "scroll" }}>
        <Outlet/>
      </div>
    </>
  )
}
```

And same thing, can pass a boolean to prevent the behavior:

```tsx
useElementScrollrestoration(ref, false);
```

## Restoring by URL instead of location

Some SPAs restore scroll by URL instead of location. This is not how browsers work, but in some apps it makes sense. For example, twitter.com restores scroll position of your home feed whether it's a push or pop event and it's a solid UX (though personally I'd expect it to go to the top for a push, restore for a pop, but I'm sure user research could go against my preference).

For this we could add a bit different API with a config object since we have a couple options now besides just "shouldRestore" from earlier.

```tsx
// default behavior, always restore
useScrollRestoration();

// stop restoring
useScrollRestoration({ restore: false });

// Give the developer a very sharp knife, when the same key is passed in later,
// we'll restore to that key's position, regardless of the location/url
useScrollRestoration({ key });

// restore by location (browser behavior)
useScrollRestoration({ key: location.key });

// restore by url (twitter.com behavior)
useScrollRestoration({ key: location.pathname });

// don't restore for the paths under "/wizard"
useScrollRestoration({
  key: location.pathname.startsWith('/wizard') ? 'wizard' : location.key
});

// put the route modules in charge:
let matches = useMatches();
// default to location key
let scrollKey = location.key;
for (let match of matches) {
  if (match.handle.scrollKey) {
    scrollKey = match.handle.scrollKey
  }
}

useScrollRestoration({ key });
```

`key` is so powerful, we might get away with not needing the `restore` option and just have `useScrollRestoration(key?)`

**Comment by wladiston** [comment] 2022-02-07 18:23
The current <ScrollRestoration /> component also does't support conditional scroll depending on the link you click.
This is very useful for those modals scenarios where you want to keep the current background page on the same place.

Next.js has a nice way to implement this:
https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page

For now, I've just made a copy of the current component and added a condition before the `window.scrollTo(0, 0);`

```ts
if (
  location.state &&
  typeof location.state === "object" &&
  (location.state as { scroll: boolean }).scroll === false
) {
  return;
}
```

And in my link I only set a state

```tsx
<Link to="cart" state={{scroll: false}}>my link</Link>
```

Not sure this is an appropriate solution, that's why I haven't submitted a PR.

**Comment by TomerAberbach** [comment] 2022-02-26 00:27
I'm also encountering some scrolling issues.

I have some code using `useSearchParams`. I have the following requirements:
1. When I call `setSearchParams(newSearchParams, { replace: true })` I want the scroll position to remain where it was
2. When navigating to a new page I want the scroll position to reset to the top

If I use `<ScrollRestoration />`, then 1 doesn't work, but 2 does. If I don't use `<ScrollRestoration />`, then 1 works, but 2 doesn't 🙃

**Comment by TomerAberbach** [comment] 2022-02-26 00:38
@wladiston's solution worked for me! 😄

**Comment by chaance** [comment] 2022-03-18 19:54
Closing this since we've already added the feature, but if you are experiencing bugs please open a new issue so we can prioritize better!

**Closed by chaance** 2022-03-18 19:54 UTC

**Comment by machour** [comment] 2022-03-19 17:22
@chaance AFAIK, `useScrollRestoration()` is not available, and we still need a way to enable/disable scroll restoration in user land.

Can this be re-opened?

**Comment by gzaripov** [comment] 2022-03-21 13:33
I would like to see @wladiston solution merged in Remix. I have a simple case where I need to show modal when user clicks the button, I use modal route for that, when I show it using `navigate('/landing/register')` I have page scrolled to top 😞.

**Comment by kiliman** [comment] 2022-03-21 15:40
Both Ryan and Kent have posted code for `useScrollRestoration` here in the comments. I'm not sure if it was intended to be added in Remix core.

**Comment by efkann** [comment] 2022-03-24 01:07
I also found myself using @wladiston's solution when navigating back and forward between routes including dialogs which worked perfectly.

**Comment by arnaudambro** [comment] 2022-05-16 05:11
@efkann @TomerAberbach @wladiston 
It seems you found a solution to prevent the scroll to top to happen, but I don't see how to implement it ?


> For now, I've just made a copy of the current component and added a condition before the `window.scrollTo(0, 0);`
> 
> ```ts
> if (
>   location.state &&
>   typeof location.state === "object" &&
>   (location.state as { scroll: boolean }).scroll === false
> ) {
>   return;
> }
> ```
> 

Where/how do you write this code ?

If I go to see `node_modules/react-router-dom/index.js` before I extend the Link component, I see

```

/**
 * The public API for rendering a history-aware <a>.
 */
const Link = /*#__PURE__*/forwardRef(function LinkWithRef(_ref4, ref) {
  let {
    onClick,
    reloadDocument,
    replace = false,
    state,
    target,
    to
  } = _ref4,
      rest = _objectWithoutPropertiesLoose(_ref4, _excluded);

  let href = useHref(to);
  let internalOnClick = useLinkClickHandler(to, {
    replace,
    state,
    target
  });

  function handleClick(event) {
    if (onClick) onClick(event);

    if (!event.defaultPrevented && !reloadDocument) {
      internalOnClick(event);
    }
  }

  return (
    /*#__PURE__*/
    // eslint-disable-next-line jsx-a11y/anchor-has-content
    createElement("a", _extends({}, rest, {
      href: href,
      onClick: handleClick,
      ref: ref,
      target: target
    }))
  );
});
```

I don't see where to insert your code there... 🥸


> I would like to see @wladiston solution merged in Remix. I have a simple case where I need to show modal when user clicks the button, I use modal route for that, when I show it using `navigate('/landing/register')` I have page scrolled to top 😞.

This is exactly my use case !

**Comment by wladiston** [comment] 2022-05-16 23:23
@arnaudambro you have to basically duplicate this file

https://github.com/remix-run/remix/blob/main/packages/remix-react/scroll-restoration.tsx

And add that snippet in. Then just replace the <ScrollRestoration/> on your root.tsx for your new one 😉

**Comment by arnaudambro** [comment] 2022-05-17 19:47
cool !
what I did is patching the file instead, before a change comes (maybe)

- I made the change manually in `/node_modules/@remix-run/react/esm/scroll-restoration.js` like you advised
- I ran `npx patch-package @remix-run/react`
the output is the file located in `/patches/@remix-run+react+1.4.3.patch`
```
diff --git a/node_modules/@remix-run/react/esm/scroll-restoration.js b/node_modules/@remix-run/react/esm/scroll-restoration.js
index 2ec020c..33e77c5 100644
--- a/node_modules/@remix-run/react/esm/scroll-restoration.js
+++ b/node_modules/@remix-run/react/esm/scroll-restoration.js
@@ -126,6 +126,15 @@ function useScrollRestoration() {
       } // otherwise go to the top on new locations


+      if (
+        location.state &&
+        typeof location.state === "object" &&
+        (location.state.scroll === false)
+      ) {
+        return;
+      }
+
       window.scrollTo(0, 0);
     }, [location]);
   }
```

then I updated the `postinstall` script this way: `    "postinstall": "remix setup node && npx patch-package"`

and here it goes ! 🥂

thanks for the tip, it works very well

**Comment by dani-mp** [comment] 2022-05-19 15:46
I had to use this patch today as well. Mentioning here in case it's useful for the maintainers, because AFAIK there's no public API solution in place, right?

**Comment by machour** [comment] 2022-05-19 15:53
@dani-mp The best thing would be to open a [new discussion](https://github.com/remix-run/remix/discussions/new) to bring  the subject back to life.

**Comment by ryym** [comment] 2022-07-08 00:18
The solution https://github.com/remix-run/remix/issues/186#issuecomment-1031778216 worked for me too, thank you!
Instead of patching the original `ScrollRestoration` component, I just wrapped it for now. It seems working.

```tsx
function ConditionalScrollRestoration() {
  const location = useLocation();
  if (
    location.state != null &&
    typeof location.state === "object" &&
    (location.state as { scroll: boolean }).scroll === false
  ) {
    return null;
  }
  return <ScrollRestoration />;
}
```

**Comment by bill-kerr** [comment] 2022-07-09 16:08
> 



> The solution [#186 (comment)](https://github.com/remix-run/remix/issues/186#issuecomment-1031778216) worked for me too, thank you! Instead of patching the original `ScrollRestoration` component, I just wrapped it for now. It seems working.
> 
> ```tsx
> function ConditionalScrollRestoration() {
>   const location = useLocation();
>   if (
>     location.state != null &&
>     typeof location.state === "object" &&
>     (location.state as { scroll: boolean }).scroll === false
>   ) {
>     return null;
>   }
>   return <ScrollRestoration />;
> }
> ```

I am getting hydration mismatch errors on React 18 (on refresh) with this approach. I had to copy the file and patch `useScrollRestoration` to avoid it.

**Comment by shenders13** [comment] 2022-08-07 23:49
Is there a way to preserve scroll height on Remix's Link tag? I know [Inertia](https://inertiajs.com/scroll-management) does something like this:

```tsx
import { Link } from '@inertiajs/inertia-react'
<Link preserveScroll href="/">Home</Link>
```

Would be super handy

**Comment by tavoyne** [comment] 2022-08-15 15:54
> I am getting hydration mismatch errors on React 18 (on refresh) with this approach. I had to copy the file and patch `useScrollRestoration` to avoid it.

To fix that, you can slightly alter the behavior and always return `<ScrollRestoration />` in case it's a first render.

```tsx
function ConditionalScrollRestoration() {
  const isFirstRenderRef = useRef(true);
  const location = useLocation();

  useEffect(() => {
    isFirstRenderRef.current = false;
  }, []);

  if (
    !isFirstRenderRef.current &&
    location.state != null &&
    typeof location.state === "object" &&
    (location.state as { scroll: boolean }).scroll === false
  ) {
    return null;
  }

  return <ScrollRestoration />;
}
```

Hacky, but temporary: soon the `resetScroll` prop (https://twitter.com/ryanflorence/status/1527775882797907969).

**Comment by arnaudambro** [comment] 2022-09-27 20:14
@ryanflorence  is `preventScrollReset` working on remix yet ?

https://reactrouter.com/en/main/components/link#preventscrollreset

**Comment by n1ghtmare** [comment] 2022-10-21 15:37
The solution by @tavoyne doesn't seem to work for me. Did anyone make it work for them?

**Comment by Mange** [comment] 2022-10-24 21:11
> The solution by @tavoyne doesn't seem to work for me. Did anyone make it work for them?

Worked for me.

**Comment by dani-mp** [comment] 2022-12-19 15:32
I tried using `navigate('.', { replace: true, preventScrollReset: true })` in Remix 1.9 still doesn't work for me.

I had to use the custom `ConditionalScrollRestoration` component mentioned above.

**Comment by xiamuguizhi** [comment] 2023-11-12 02:46
I had a problem with the very upstairs reply today.

Thank you very much for your solutions as well.

The solution is now available on the official website, thank you very much:

https://remix.run/docs/en/main/components/scroll-restoration


This component will emulate the browser's scroll restoration on location changes after [loader](https://remix.run/docs/en/main/route/loader)s have completed. This ensures the scroll position is restored to the right spot, at the right time, even across domains.

You should only render one of these, right before the [<Scripts/>](https://remix.run/docs/en/main/components/scripts) component.

```js

import {
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";

export default function Root() {
  return (
    <html>
      <body>
        {/* ... */}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

```
