### ISSUE TITLE
vite template doesn't start (dev server origin not set)

### ISSUE THREAD

**Issue by rolandleth** [remix-run/remix#9080] opened 2024-03-19 13:24 UTC
### Reproduction

- run `npx create-remix@latest --template remix-run/remix/templates/vite vite-template-demo`
- either manually install packages, or let the template do it
- run `npm run build`
- run `npm run start`
- observe it fail

<img width="1025" alt="2024-03-19 at 3 22 55 PM" src="https://github.com/remix-run/remix/assets/1858700/445f32a9-ff00-4f3c-9cd8-fe2bde968dc5">

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.91 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 4.1.1 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.4
  npmPackages:
    @remix-run/dev: ^2.8.1 => 2.8.1 
    @remix-run/express: ^2.8.1 => 2.8.1 
    @remix-run/node: ^2.8.1 => 2.8.1 
    @remix-run/react: ^2.8.1 => 2.8.1 
    vite: ^5.1.6 => 5.1.6
```

### Used Package Manager

npm

### Expected Behavior

To run.

### Actual Behavior

Throws an error.

**Comment by pcattori** [comment] 2024-03-19 19:35
I could not reproduce this locally. Closing, but happy to reopen if you can provide a repro in stackblitz or in a github repo link.

**Closed by pcattori** 2024-03-19 19:35 UTC
Labels: bug:unverified

**Comment by rolandleth** [comment] 2024-03-20 05:49
@pcattori Sure, added the repo here: https://github.com/rolandleth/vite-template-demo

It really is just `npx create-remix@latest --template remix-run/remix/templates/vite vite-template-demo`, install, build, start 🙁

If you'll still can't reproduce, maybe you have any tips I can try to debug on my end?

**Comment by pcattori** [comment] 2024-03-20 14:33
`REMIX_DEV_ORIGIN` is only relevant for the classic Remix compiler (the esbuild-based one, not the Vite plugin), so seems like you might be running the old compiler by accident somehow.

**Comment by rolandleth** [comment] 2024-03-20 15:38
@pcattori That's strange, any idea why the same code might work for you, but not for me and why I might get the old compiler running? I'm definitely using `npm`; even `yarn` behaves the same, both v1 and berry (as expected, I guess).

Anything I could try to shed some more light on this? I tried with the versions that come with the template, I also tried upgrading them all, same result.

<img width="773" alt="2024-03-20 at 5 37 17 PM" src="https://github.com/remix-run/remix/assets/1858700/2f77aee4-0599-4f2a-ba7f-d362fb6bc432">

**Comment by pcattori** [comment] 2024-03-20 15:51
If using `remix-serve`, then you should be using `remix vite:dev` as your `dev` script. Which means the _only_ script using `remix-serve` should be `start`. Notably, that script (`start`) should not be running in development mode. If you run `remix-serve` with `NODE_ENV=development` it will try to do the classic compiler dev flow, which is what requires REMIX_DEV_ORIGIN and `/ping`. So my guess is that for some reason you have the `NODE_ENV` env var set to `development` when running `remix-serve`.

**Comment by rolandleth** [comment] 2024-03-21 07:06
> If using `remix-serve`, then you should be using `remix vite:dev` as your `dev` script. Which means the only script using `remix-serve` should be `start`

That is correct.

> So my guess is that for some reason you have the `NODE_ENV` env var set to `development` when running `remix-serve`.

That is also correct, changing the start script to `NODE_ENV=production remix-serve ./build/server/index.js` works, thanks for your help!

Would it be a good idea to change it in the template too, just in case others have `NODE_ENV=development` as the default? And also because running `remix-serve` on dev causes issues anyway and the production is usually the desired result.
