### ISSUE TITLE
CSS Bundle does not work when deployed to Vercel

### ISSUE THREAD

**Issue by dantman** [remix-run/remix#6688] opened 2023-06-26 05:42 UTC
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I've included a git repo where I have done the following:
https://github.com/dantman/remix-vercel-css-bundled-modules-bug

1. Run `npx create-remix@latest`
2. Select Just the basics, Vercel, TypeScript
3. Verify that `root.tsx` contains `...(cssBundleHref ? [{ rel: "stylesheet", href: cssBundleHref }] : []),` (css-bundle is pre-configured in the default template)
4. Add CSS using an import that depends on the css-bundle 
5. Verify your CSS works locally in `npm run dev`
6. Deploy to Vercel
7. Check that your CSS is working on the deployed Vercel site

### Expected Behavior

Expected Vercel deployment to have same CSS as seen locally.

### Actual Behavior

Bundled CSS and module CSS files that load when run in the dev server do not work when deployed to Vercel.
![image](https://github.com/remix-run/remix/assets/53399/a9c5e25a-af12-4f68-83fa-c1ddee5589c5)

Local: Run `npm run dev` using https://github.com/dantman/remix-vercel-css-bundled-modules-bug
Vercel Deployment: https://remix-vercel-css-bundled-modules-bug-git-stock-dantman.vercel.app/

**Comment by dantman** [comment] 2023-06-26 05:43
From what I can tell it seems like `cssBundleHref` is not defined when deployed to Vercel.

**Comment by markdalgleish** [comment] 2023-06-28 05:27
Looks like this is an issue on the Vercel side due to their Remix-specific build process. I'm currently reaching out to get it resolved. In the meantime I've verified that you should be able to fix this by rolling back to v1.17.0.

**Comment by markdalgleish** [comment] 2023-08-07 07:26
As noted above, this issue is currently fixed in the latest version.

Since this issue is caused by a version mismatch between `@remix-run/css-bundle` and Vercel's custom fork of `@remix-run/dev` which they only run in CI, I recently merged a PR that will go out in Remix v2 that decouples these two packages to avoid this issue re-emerging in the future: https://github.com/remix-run/remix/pull/6982.

**Closed by markdalgleish** 2023-08-07 07:26 UTC
Labels: bug:unverified, package:css-bundle
