### ISSUE TITLE
SerializeFrom with nested 'data' props replaces parent entries causing type loss

### ISSUE THREAD

**Issue by milamer** [remix-run/remix#5288] opened 2023-01-27 23:20 UTC
### What version of Remix are you using?

1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

When using the SerializeFrom function to convert a nested data object to a serialized version, any nested data props within the object will replace all entries of the parent. This results in the parent object having the type of the nested data object, rather than preserving the original type of the parent. This can lead to unexpected behavior and loss of information.

An example of this issue can be seen in the following code:

```ts
type NestedDataObject = {
  value: string
  // can also be deeper nested
  data: {
    test: string
  }
}

type SerializedData = SerializeFrom<NestedDataObject>

// SerializedData has the entries of data
const TestImpl: SerializedData = {
  test: 'test',
}
```

### Expected Behavior

In the example above, the SerializedData type should have both value and data entries.

### Actual Behavior

It only has the entries of data.

**Comment by machour** [comment] 2023-01-28 00:05
Duplicate of #5211

**Closed by machour** 2023-01-28 00:05 UTC
Labels: bug:unverified
