### ISSUE TITLE
Application Error – TypeError: Failed to Fetch

### ISSUE THREAD

**Issue by kevinreber** [remix-run/remix#7188] opened 2023-08-17 18:51 UTC
### What version of Remix are you using?

1.19.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have an interval setup that refetches the most recent data for one of our routes using a `useRevalidator()`. It works as expected about 90% of the time, but once in awhile will break things and return a `TypeError: Failed to fetch`

Here is a snippet of how we are setting up our interval below
```tsx
import { useRevalidator } from "@remix-run/react";

const THIRTY_SECONDS_IN_MS = 30 * 1000;

const PageComponent = () => {
  const revalidator = useRevalidator();

  /**
   * @description
   * Refetch page data data every 30 seconds
   */
  React.useEffect(() => {
    const interval = setInterval(() => {
      if (document.visibilityState === "visible") {
        revalidator.revalidate();
      }
    }, THIRTY_SECONDS_IN_MS);

    return () => clearInterval(interval);
  }, []);

}
```

References used to create this interval:
- Refresh Route Data API: https://github.com/remix-run/remix/discussions/1996#discussioncomment-4731905
- `useFetcher` vs `useRevalidator` Discussion: https://github.com/remix-run/remix/issues/6587#issuecomment-1590076789

### Expected Behavior

Have our `loader` fetch the most recent data without throwing any `Errors`

### Actual Behavior
Most of the time our `useRevalidator()` interval works as expected, but when something breaks we receive  an **Application Error** 
```
TypeError: Failed to fetch
    at https://localhost:15037/build/_shared/chunk-I5HQNNDB.js:7698:10
    at fetchData (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:7317:24)
    at https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:7569:26
    at runHandler (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:2497:26)
    at callLoaderOrAction (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:2536:22)
    at https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:1651:70
    at Array.map (<anonymous>)
    at callLoadersAndMaybeResolveData (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:1651:55)
    at handleLoaders (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:1302:15)
    at startNavigation (https://localhost:15037/build/_shared/chunk-JO3TXGFA.js:1165:15)
```
<img width="1738" alt="image" src="https://github.com/remix-run/remix/assets/42260999/8473c31b-d0e6-48b7-b9f0-93926558bdfb">

**Comment by brophdawg11** [comment] 2023-08-18 15:17
Do you have any more information on the fetch error?  What does the network tab show?  Did the app lose internet connection briefly?  Unfortunately, `fetch`-thrown errors trigger error boundaries currently, and when it's a `useRevalidator` - it ends up usually going to the top-most error boundary.  You can add a boundary to your top-level route to improve the UI and give the user a link back to the current location - but until https://github.com/remix-run/react-router/discussions/10013 is implemented that might be the best you can do.  https://github.com/remix-run/react-router/discussions/10013 should hopefully add the same `onError` callbacks to `useRevalidator`

**Comment by kevinreber** [comment] 2023-08-21 15:42
hey @brophdawg11 the network does look like it fails for some reason (screenshot) not exactly sure why this happens in multiple environments though (dev/staging/prod) 🤔 
![CleanShot 2023-08-21 at 08 28 23](https://github.com/remix-run/remix/assets/42260999/db08c112-105e-47c1-acf8-419494ed05fa)

As a work around I have done as you suggested and added an `Error Boundary` to improve the UI/UX. Appreciate the help and extra context 🙏 😄

**Comment by brophdawg11** [comment] 2023-08-21 20:54
Thank you for the screenshot.  If it's a network error then it's expected behavior for the error boundary to fire at the moment until the above-mentioned proposals are considered/inmplemented.  I don't know if it would help but you could potentially check against [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) as well before kicking off the revalidation.

I'm going to close this out but please keep an eye on those proposals.

**Closed by brophdawg11** 2023-08-21 20:54 UTC
Labels: feat:routing, bug:unverified

**Comment by seanmoghadam** [comment] 2024-03-27 21:02
Can confirm, we face the same issue in all our environments. Happens randomly. 
Error boundary is in place but it's unclear why it's happening. Will share some insights in the next days.

**Comment by rickykissoon** [comment] 2024-07-22 19:14
> Can confirm, we face the same issue in all our environments. Happens randomly. Error boundary is in place but it's unclear why it's happening. Will share some insights in the next days.

Any updates on this issue? I'm currently facing the same thing and having a hard time tracking down the cause.

**Comment by nick-potts** [comment] 2024-07-28 09:30
Also facing this. Now checking against navigator.onLine, but its not ideal having to remember to do this in every place.

**Comment by brophdawg11** [comment] 2024-07-29 14:39
Another thing you can do now that [client data](https://remix.run/docs/en/main/guides/client-data) has shipped is catch these errors in a `clientLoader` and return them as data to avoid triggering the error boundary:

```js
export async function loader() {
  return { ok: true, ... };
}

export async function clientLoader({ serverLoader }) {
  try {
    let data = await serverLoader(); // Call the server loader
    return data;
  } catch (e) {
    // fetch() failures would throw to here - returning them as data lets you show a contextual error message
    // You could also leverage a client cache to return/show the stale data from the last execution
    return { ok: false, error: }
  }
}
```

**Comment by parisholley** [comment] 2024-10-29 06:31
I was running into this problem and figured out it was due to having an old reference to useRevalidator. `useInterval` in my before is from `usehooks-ts` library.

**before (broken)**
```typescript
  const revalidator = useRevalidator();

  useInterval(() => {
    if (revalidator.state === "idle") {
      revalidator.revalidate();
    }
  }, 5000);
```

**after (working)**
```typescript
  const interval = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (interval.current) {
      clearInterval(interval.current);
    }
    
    interval.current = setInterval(() => {
      if (revalidator.state === 'idle') {
        revalidator.revalidate();
      }
    }, 5000);
  }, [revalidator]);
```
