### ISSUE TITLE
Invalid 404 after page reload and "back" nav

### ISSUE THREAD

**Issue by nicholaschiang** [remix-run/remix#2106] opened 2022-02-23 20:51 UTC
### What version of Remix are you using?

1.2.2

### Steps to Reproduce

Follow the instructions from the [introduction tutorial](https://remix.run/docs/en/v1/tutorials/blog) until you have:

```
nchiang@eevee ~/repos/my-remix-app (master) $ tree app/
app/
├── entry.client.tsx
├── entry.server.tsx
├── post.ts
├── root.tsx
└── routes
    ├── index.tsx
    └── posts
        └── index.tsx

2 directories, 6 files
```

Make sure that you don't yet have a page for each individual post (i.e. going to `/posts/my-first-post` should—correctly—result in a 404). Then:
1. `yarn && yarn dev`
2. Open up `http://localhost:3000` in Firefox (I'm not sure if this bug appears in Chromium-based browsers; I only tested with Firefox)
3. Click on the "Posts" link to go to `http://localhost:3000/posts` client-side
4. Click on one of the post links to go to, for example, `http://localhost:3000/posts/my-first-post`
5. Reload the page
6. See (correct) 404
7. Click the "back" button in your browser to navigate back to `http://localhost:3000/posts`
8. See (incorrect) 404 when there should instead be the "Posts" page

### Expected Behavior

Navigating back from a 404 page to a page that exists shouldn't result in a 404 but should instead simply show the page that exists correctly.

### Actual Behavior

See steps to reproduce.

**Comment by machour** [comment] 2022-03-17 22:29
Thank you for reporting this. It seems like a duplicate of #776, so let's track it there.

**Closed by machour** 2022-03-17 22:29 UTC
Labels: bug
