### ISSUE TITLE
Adding `//` to the end of the root route throws an Internal Server Error

### ISSUE THREAD

**Issue by krall12** [remix-run/remix#4422] opened 2022-10-26 14:04 UTC
### What version of Remix are you using?

1.7.3

### Steps to Reproduce

Spin up a new remix project from scratch. Just the basics. Remix Server. JavaScript. 

Start the dev server and visit the browser at `localhost:3000//`. 

Also, for fun check out `https://remix.run//`

### Expected Behavior

I would expect this to not error. Ideally it would redirect back to the root route. 

### Actual Behavior

On production: An `Internal Server Error` is thrown that doesn't get caught by Error Boundaries. 

On development: An `Invalid URL` error is thrown that also doesn't get caught by Error Boundaries. 
```
TypeError: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at createRemixRequest (/Users/bkrall/content/remix-bug-server-error-on-route/node_modules/@remix-run/express/dist/server.js:67:13)
    at /Users/bkrall/content/remix-bug-server-error-on-route/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/bkrall/content/remix-bug-server-error-on-route/node_modules/@remix-run/serve/dist/index.js:48:7
    at Layer.handle [as handle_request] (/Users/bkrall/content/remix-bug-server-error-on-route/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bkrall/content/remix-bug-server-error-on-route/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/bkrall/content/remix-bug-server-error-on-route/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/bkrall/content/remix-bug-server-error-on-route/node_modules/express/lib/router/route.js:140:7)
```

**Comment by brophdawg11** [comment] 2023-02-15 14:54
This is fixed in Remix 1.13.0 - we aren't doing any redirecting but instead are ensuring our adapters can correctly generate a URL with these trailing slashes.  It would still be up to the app to detect and redirect in a loader (or eventually in [middleware](https://github.com/orgs/remix-run/projects/5?pane=issue&itemId=13430611) once that lands).

**Closed by brophdawg11** 2023-02-15 14:54 UTC
Labels: bug, adapter:architect, adapter:vercel, adapter:express, adapter:netlify, awaiting release

**Comment by Hansenq** [comment] 2023-02-26 07:46
@brophdawg11 I just filed [an issue](https://github.com/remix-run/remix/issues/5573) with the `<Link>` component improperly handling URLs in Webkit browsers that occur in Remix 1.13.0. The issue _must_ be a regression (it would be insane if this behavior existed for more than a week, since it means all links are broken on Webkit browsers). The commit that fixes this issue looks likely to be the culprit; any chance you could double check that it didn't cause a regression? Thanks!

**Comment by lili21** [comment] 2024-03-01 08:58
I ran into similar issue. I'm trying to deploy the remix app to our company cloud service. it works locally. what should I look at first? below is the error message

```
TypeError: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at createRemixRequest (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/@remix-run+express@2.6.0_express@4.18.2_typescript@5.3.3/node_modules/@remix-run/express/dist/server.js:74:13)
    at /opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/@remix-run+express@2.6.0_express@4.18.2_typescript@5.3.3/node_modules/@remix-run/express/dist/server.js:39:21
    at Layer.handle [as handle_request] (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at next (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
    at next (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
    at next (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
    at next (/opt/bytefaas/toutiao/app/gdserver/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
```

**Comment by lili21** [comment] 2024-03-01 09:48
After some dig in, I found the issue
In our could service, `resolveHost` is `[fdbd:dc01:b:90::28]:dc01`, which isn't a valid URL. 

the source code
https://github.com/remix-run/remix/blob/2228ec33f6964bb5bf1373cd4f41cdff4a134301/packages/remix-express/server.ts#L96-L98
