### ISSUE TITLE
v1.15 breaks route v2 convention

### ISSUE THREAD

**Issue by buzinas** [remix-run/remix#6257] opened 2023-05-01 00:04 UTC
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On v1.14.3 we could nest folders when using route v2 convention:

```
routes/_layout/route.tsx
routes/_layout/_index/route.tsx
```

Reproducible folder setup working on v1.14.3: https://stackblitz.com/edit/remix-run-remix-u7t3ez

On v1.15.0 it doesn't work, unless you use dots on the folder name instead, eg:

```
routes/_layout/route.tsx
routes/_layout._index/route.tsx
```

Reproducible folder setup not working on v1.15.0: https://stackblitz.com/edit/remix-run-remix-tdwjmj
Reproducible alternative folder setup working on v1.15.0: https://stackblitz.com/edit/remix-run-remix-mrxhbz

Was this an intended breaking change? And if so, why?

### Expected Behavior

Route `routes/_layout/_index/route.tsx` should render on v1.15 (on v1.14 it does).

### Actual Behavior

Route `routes/_layout/_index/route.tsx` doesn't render, but `routes/_layout._index/route.tsx` does.

**Comment by machour** [comment] 2023-05-01 00:17
CCed @mcansh that have been working on the v2 routes convention, and will be able to tell if that was intentional or not.

As a reminder, v2 routes is **opt in** and still work in progress, so you can expect some breaking changes here and there while we're polishing it. Thank you for baring with us 🙏🏼

**Comment by mcansh** [comment] 2023-05-01 00:46
this was a bug in pre 1.15 behavior as we unintentionally recursively checked `routes`

**Comment by buzinas** [comment] 2023-05-01 00:57
That’s really sad to hear, since the biggest advantage of v2 convention was the ability to colocate the routes and their components, and having to use dots just creates a huge flat folder that is super hard to navigate.

What was your intention when you made this proposal @ryanflorence?

Also @mcansh, what’s wrong with recursively checking folders? What’s better on v15 that makes this change worth?

**Comment by kiliman** [comment] 2023-05-01 14:49
The `remix-flat-routes` package supports nested folders. 

Basically, treat `/` as `.` If it ends in `/route.tsx`, treat it as `.tsx`. It simply converts the `folder` route into a `flat-file` route.
```
a/route.tsx => a.tsx
a/b/route.tsx => a.b/route.tsx => a.b.tsx
a/b.c/d/route.tsx => a.b.c.d/route => a.b.c.d.tsx
```
```
❯ tree app/routes
app/routes
└── _layout
    ├── _index
    │   └── route.tsx
    └── route.tsx
```
```ts
❯ npx remix routes
<Routes>
  <Route file="root.tsx">
    <Route file="routes/_layout/route.tsx">
      <Route index file="routes/_layout/_index/route.tsx" />
    </Route>
  </Route>
</Routes>
```

**Comment by bluefire2121** [comment] 2023-05-03 18:19
Doesn't this regression break the recommendation on Scaling as shown in the docs?

`Scaling
Our general recommendation for scale is to make every route a folder and put the modules used exclusively by that route in the folder, then put the shared modules outside of routes folder elsewhere. This has a couple benefits:

Easy to identify shared modules, so tread lightly when changing them
Easy to organize and refactor the modules for a specific route without creating "file organization fatigue" and cluttering up other parts of the app`

**Comment by mcansh** [comment] 2023-05-03 18:24
> Doesn't this regression break the recommendation on Scaling as shown in the docs?

`routes/_layout/_index/route.tsx` was never meant to work where as `routes/_layout._index/route.tsx` does and was not called out in the docs. you can still colocate files in `routes/_layout._index`

```
❯ tree app/routes
app/routes
└── _layout._index
    ├── route.tsx
    └── image.png
    └── header.tsx
```

**Comment by buzinas** [comment] 2023-05-03 18:58
You can colocate, but you end up with lot of flat folders since you can’t really nest. Nesting folders and colocating the logic was the only advantage of route v2 for me, so I don’t really get what’s the goal now.

What’s the drawback of allowing nesting? And what’s the advantage of disallowing it?

**Comment by StevenBendell** [comment] 2023-05-30 12:59
Is there any follow up on this?
I have adopted the same route/folder pattern as @buzinas and found it to be a clean solution for co locating code. Currently holding out on upgrading from v1.14.3 . If the logic isn't planned to include this in the future then would I would look to use killman's package

**Comment by joshboley** [comment] 2023-06-14 15:45
I agree with @buzinas and @StevenBendell and had done the same.  This is subjective, but I would argue that disallowing a nested structure makes it more difficult for the developer to easily understand the loader hierarchy.

@mcansh would there be any harm in just allowing both flat and nested as was the case before v1.15.0?

**Comment by brophdawg11** [comment] 2023-06-22 19:50
> you end up with lot of flat folders since you can’t really nest

This is exactly the idea of v2 "flat routes".  Some folks prefer flat (including us).  Some prefer nested.  Some prefer to implement their own `routes` function 😉 

> disallowing a nested structure makes it more difficult for the developer to easily understand the loader hierarchy.

Nothing is disallowed - the v1 convention is [available through the `@remix-run/v1-route-convention` package](https://remix.run/docs/en/1.17.1/pages/v2#upgrading-without-changing-files).

I'm going to close this because this was a bug fix in `1.15.0` - v2 "flat routes" is specifically designed to flatten your `routes` folder away from the heavily nested folder structures that you ended up with when using the original/v1/nested convention.  It was never intended for `routes/_layout/_index/route.tsx` to be valid using the v2 convention.

We understand and agree this is **highly subjective and preferential** which is why we provide 2 basic conventions and then given you full control to develop your own via `remix.config.js` `routes`.  As @kiliman has shown with his excellent `remix-flat-routes` package - you can go above and beyond if neither the v1 or v2 convention suffices for your needs.

**Closed by brophdawg11** 2023-06-22 19:50 UTC
Labels: feat:routing, bug:unverified

**Comment by buzinas** [comment] 2023-06-22 22:22
Totally fine if you prefer flat, but the original RFC has multiple comments mentioning the ability to nest and colocate as part of v2 – which was the main selling point for many people and basically the comments with the most upvotes there as well.

Again, totally fine if this wasn't the intention in the first place, but I'd love if I could have an answer to a very simple question I asked twice that got unanswered here: what's the advantage of disabling nesting and what's the drawback of allowing it?

**Comment by brophdawg11** [comment] 2023-06-23 14:31
I see nothing in the `Justification` section of https://github.com/remix-run/remix/discussions/4482 about being able to nest folders within one another.

> what's the advantage of disabling nesting

We think flat routes provides a simpler approach for the majority of Remix apps.  Can't please everyone but we think this is a better default for small to medium sized apps.  Neither convention is particularly good for large scale apps and we expect most of them will use `remix.config.js` `routes` to do something more advanced tailored to their app.

The reason it is no longer in the repo is that we only want one convention in the primary repo.  Not 2 implementations, 2 sets of tests, 2 sets of docs, etc.  We're a small team and the maintenance overhead is non-negligible.  The v1 implementation now lives in a separate repo and is considered feature complete.

> what's the drawback of allowing it?

None, we are just allowing it in a separate package for the same reasons above.
