### ISSUE TITLE
A hybrid EJS – CommonJS module is being imported as CommonJS

### ISSUE THREAD

**Issue by leduyquang753** [remix-run/remix#9181] opened 2024-04-02 03:36 UTC
### Reproduction

https://stackblitz.com/edit/remix-run-remix-cx78kz?file=app%2Froot.tsx

1. Use the default template from `remix-create`.
2. Try to `import` stuff from `@fluentui/react-components` like in `app\root.tsx`.

### System Info

```shell
System:
	OS: Windows 11 10.0.22631
	CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Memory: 8.72 GB / 19.78 GB
Binaries:
	Node: 21.7.1 - C:\Program Files\NodeJS\node.EXE
	Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
	npm: 10.5.0 - C:\Program Files\NodeJS\npm.CMD
Browsers:
	Edge: Chromium (123.0.2420.65)
	Internet Explorer: 11.0.22621.1
npmPackages:
	@remix-run/dev: ^2.8.1 => 2.8.1
	@remix-run/node: ^2.8.1 => 2.8.1
	@remix-run/react: ^2.8.1 => 2.8.1
	@remix-run/serve: ^2.8.1 => 2.8.1
	vite: ^5.1.0 => 5.2.7
```

### Used Package Manager

npm

### Expected Behavior

The module is imported as ESM and the imports successful.

### Actual Behavior

The module is imported as CommonJS and the imports failed.

**Comment by alcpereira** [comment] 2024-04-02 12:26
This seems to be an issue with `@fluentui/react-components`, see [here](https://github.com/microsoft/fluentui/issues/30634#issuecomment-2005149989).

**Comment by brophdawg11** [comment] 2024-04-02 13:36
Closing this in favor of https://github.com/microsoft/fluentui/issues/30634#issuecomment-2005149989 - please let us know if that does not end up being the root cause and we can re-open if this is indeed a Remix issue.

**Closed by brophdawg11** 2024-04-02 13:36 UTC
Labels: bug:unverified
