### ISSUE TITLE
useFetcher will reload the page with 【@remix-run/react vision 1.4.0】

### ISSUE THREAD

**Issue by xingxinglieo** [remix-run/remix#2850] opened 2022-04-19 02:21 UTC
### What version of Remix are you using?

@remix-run/react vision 1.4.0

### Steps to Reproduce

```
 // in hook 
  const fetcher = useFetcher()
  const compile = (code: string) => {
    fetcher.submit({ code }, { method: 'post', action: '/compile' })
  }
```
after the response back, the page will reload.

**but it's normal in @remix-run/react vision 1.1.1 !**

### Expected Behavior

return the json in res and page doesn't reload

### Actual Behavior

page reload

**Comment by chaance** [comment] 2022-04-19 02:23
Hello.

I cannot reproduce this bug with the information given. Closing for now but let me know if you can provide a reproduction of the bug with https://remix.new

**Closed by chaance** 2022-04-19 02:23 UTC
Labels: bug:unverified

**Comment by mwood23** [comment] 2022-04-21 04:32
@chaance  This could be me misunderstanding how things work but I'm seeing my page reload on submit of useFetcher too. It causes all the images to render again and janks the page.

https://user-images.githubusercontent.com/13633613/164372518-53865f25-d45a-402f-a532-86aed9045664.mp4

Link: https://stackblitz.com/edit/node-1vlj5i?file=app/routes/index.tsx

**Comment by chaance** [comment] 2022-04-22 03:47
Hmm, not sure why off hand but you were using an old version of `@remix-run/dev` in that example, and upgrading it fixed the issue. https://stackblitz.com/edit/node-cw71zb?file=package.json
