### ISSUE TITLE
Basic example Remix 1.3.3 project fails to render with "Error: Invalid hook call" error message

### ISSUE THREAD

**Issue by dstrekelj** [remix-run/remix#2509] opened 2022-03-26 20:04 UTC
### What version of Remix are you using?

1.3.3

### Steps to Reproduce

**Environment:**
- macOS Monterey 12.1
- Node 16.4.2
- NPM 8.5.0
- Chrome 99

**Steps to reproduce:**
Start a new Remix project using `npx create-remix@latest ./apps/website` (this was done as part of a Turborepo monorepo setup where the `apps/` directory contains a Strapi admin app, hence the path).

Select the following options:

```
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix if you're unsure, it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```

Change into the project directory (`./apps/website` in this case) and run `npm run dev`.

Open http://localhost:3000 in Chrome.

### Expected Behavior

I expected to see the default Remix template application homepage.

### Actual Behavior

I saw the following error in the terminal and the browser:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/user/project/node_modules/react/cjs/react.development.js:1465:13)
    at Object.useMemo (/Users/user/project/node_modules/react/cjs/react.development.js:1520:20)
    at RemixEntry (/Users/user/project/node_modules/@remix-run/react/components.js:69:39)
    at processChild (/Users/user/project/apps/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/user/project/apps/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/user/project/apps/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/user/project/apps/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/user/project/apps/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at handleRequest (/Users/user/project/apps/website/app/entry.server.tsx:11:16)
    at handleDocumentRequest (/Users/user/project/node_modules/@remix-run/server-runtime/server.js:407:20)
```

**Note:** Downgrading to Remix 1.3.2 seems to have fixed the issue. I'm currently not able to dig deeper to see what changed between versions to cause this issue.

**Comment by jacob-ebey** [comment] 2022-04-01 19:02
Seems like the build is resolving multiple versions of React. Can you copy the project out of the turborepo and see if you can install and run it standalone? It's probably a dependency resolution / linking issue with turborepo.

**Comment by wingy3181** [comment] 2022-04-07 07:19
Interestingly I got the same issue in `examples/routes-gen`  (which doesn't have an `.nvmrc` file) when using node 16.13.0 and then i  switched to node 14 and then it worked....

Obviously that doesn't address the root cause but maybe try that too?

**Comment by justLuiz** [comment] 2022-05-11 19:00
try upgrading your react and react-dom to 18.1.0

**Closed** 2022-05-21 20:08 UTC
Labels: needs-response, bug:unverified

**Comment by jayphelps** [comment] 2022-05-29 03:39
Wanted to chime in that upgrading react/react-dom to 18.1.0 solved the problem for me.
