### ISSUE TITLE
create-remix with indie stack template breaks when choosing JavaScript because prisma/seed.ts is now prisma/seed.js

### ISSUE THREAD

**Issue by Kilian** [remix-run/remix#2998] opened 2022-04-27 12:24 UTC
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Follow the blog tutorial: https://remix.run/docs/en/v1/tutorials/blog and choose for JavaScript instead of TypeScript (using Node 14, though I don't know if that's relevant here)

The issue seems to be mentioned here as well: https://github.com/remix-run/remix/issues/2714#issuecomment-1106774296

### Expected Behavior

The setup succeeds and I can learn how to use Remix. 

### Actual Behavior

The setup breaks because it tries to find a file called prisma/seed.ts, but there is only a prisma/seed.js file:

```bash
Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module './seed.ts'
Require stack:
- /home/kilian/Workspace/personal/remix/blog-tutorial2/prisma/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at requireResolveNonCached (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:489:16)
    at getProjectSearchDir (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:459:40)
    at phase3 (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:263:27)
    at bootstrap (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:44:30)
    at main (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/home/kilian/Workspace/personal/remix/blog-tutorial2/node_modules/ts-node/dist/bin.js:519:5)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kilian/Workspace/personal/remix/blog-tutorial2/prisma/imaginaryUncacheableRequireResolveScript'
  ]
}

An error occured while running the seed command:
Error: Command failed with exit code 1: ts-node --require tsconfig-paths/register prisma/seed.ts
```

When choosing the TypeScript variant, things work as ecpected.

**Comment by MichaelDeBoey** [comment] 2022-04-27 12:38
Duplicate of #2781

**Closed by MichaelDeBoey** 2022-04-27 12:38 UTC
Labels: bug:unverified
