### ISSUE TITLE
Remix dev asset server web socket error

### ISSUE THREAD

**Issue by gonghaibo** [remix-run/remix#2958] opened 2022-04-22 02:25 UTC
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

1.npm i create-remix mydemo
2.remix dev
3.Modify or add files in routes
4.chrome error(Remix dev asset server web socket error:)

![image](https://user-images.githubusercontent.com/36252719/164583992-9aff78aa-373a-49b6-b45e-bcc9a61d2076.png)

### Expected Behavior

Automatically refresh the page to match the new route.
To fix this I had to reboot.

### Actual Behavior

![image](https://user-images.githubusercontent.com/36252719/164583992-9aff78aa-373a-49b6-b45e-bcc9a61d2076.png)

**Comment by LukasCornille** [comment] 2022-04-25 18:54
Hey, I had the same issue.

Deleting my package-lock & node_modules however, fixed the issue for me. Hope this is the case for you as well!

**Comment by gonghaibo** [comment] 2022-04-26 05:44
> Hey, I had the same issue.
> 
> Deleting my package-lock & node_modules however, fixed the issue for me. Hope this is the case for you as well!

#1601 
Thanks, but your workaround didn't work for me. I found a similar question.

**Comment by TimoWestland** [comment] 2022-05-01 12:46
Been having this issue as well since upgrading to v1.4.3. Re-installing dependencies did not work for me either.

**Comment by sillypoise** [comment] 2022-05-04 16:55
Same bug has been happening to me as well since v1.4.3. Can reproduce the bug just as OP described.

**Comment by leimantas** [comment] 2022-05-17 15:24
I have same problem. 
Latest Safari. No extensions.
After reloading vscode - it works for some time. 

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/46538777/168848334-503e10b3-e048-4631-8d2d-3c7984a1c190.png">

**Comment by MichaelDeBoey** [comment] 2022-05-17 19:22
Closed by #3206

**Closed by MichaelDeBoey** 2022-05-17 19:22 UTC
Labels: bug:unverified

**Comment by apisandipas** [comment] 2022-05-24 15:15
Hello, I am on 1.5.1 and I'm getting this exact issue. I am running Firefox 100.1 with all extensions disabled.

**Comment by xanderberkein** [comment] 2022-05-24 16:29
For anyone still having this issue after 1.5.0, try adding

```js
devServerPort: 8002
``` 

to `remix.config.js`.

**Comment by nicholaschiang** [comment] 2022-05-29 01:32
@xanderberkein could you put that into all of the Remix stacks configurations? I ran into this issue when using the Blues stack...

**Comment by Vikaskumargd** [comment] 2022-05-29 18:17
issue is still there

![image](https://user-images.githubusercontent.com/7469181/170885443-fcd7e784-9131-4679-a84b-35bd7255ade1.png)

**Comment by decanTyme** [comment] 2022-05-29 20:03
> For anyone still having this issue after 1.5.0, try adding
> 
> ```js
> devServerPort: 8002
> ```
> 
> to `remix.config.js`.

Thanks, this worked wonders with https://github.com/remix-run/remix/issues/2485, getting really tired manually reloading for every change (even on 1.5.1). Though I'm confused, this should be fixed internally, right? Because the TS docs on `devServerPort` is kinda misleading the way it is if we had to be explicit everytime.

![image](https://user-images.githubusercontent.com/74456102/170889096-f8844352-3037-4465-b170-e128a83b3a9f.png)

**Comment by kiliman** [comment] 2022-05-30 16:47
Yes this is an issue with templates that don’t use Remix App Server. Because `remix watch` and Express are separate processes they don’t share the `REMIX_DEV_SERVER_WS_PORT` environment variable that defines the random port used by Remix. The solution is to hard code the port in *remix.config*

See the following issue for more detail. 

https://github.com/remix-run/remix/issues/3314

**Comment by kmocorro** [comment] 2022-05-30 19:40
Adding to _remix.config.js_ solves the issue. 
`devServerPort: 8002,`

I wonder why all of a sudden LiveReload doesn't work whilst the app was still working prior refactoring the code to components structure.

**Comment by russc** [comment] 2022-06-05 19:36
In addition to @kmocorro's comment about `devServerPort`, if you are using netlify dev some of the default exports in _remix.config.js_ get commented out. Uncommenting them fixed this issue for me.

**Comment by hakimLyon** [comment] 2022-06-10 04:02
Thanks, for me this issue fixed  on v1.5.1 💯.

**Comment by bursteways** [comment] 2022-12-30 02:10
I had a CORS plugin that was enabled. Turning this `OFF` allowed the websocket to LiveReload again.

**Comment by TreyOverton** [comment] 2023-07-17 15:42
I am adding this comment well after a generally accepted solution just in case the following is the actual problem for some people who are still struggling.

One of the devs on my team was experiencing this error with Remix v1.18, even when setting up a fresh Remix app. Nobody else on the team seemed to have this issue. All the various solutions suggested did not work. One difference was that he was on Windows 10 while everyone else was on Windows 11.

We finally discovered this article:
https://blog.deanosim.net/windows-10-winnat-and-why-your-programs-cant-listen-on-certain-ports/

He followed the advice, which I replicate here in case the link goes away.

> After many hours of research I discovered the Wonders of Windows NAT Driver (WINNAT) and that in a Windows update in 2018 they snuck in a feature that allows WINNAT to reserve ports for Windows use (even if Windows 10 isn't actually using them) so that no other programs on your computer can use these ports.

Then use these commands to stop WINNAT, exclude port 8002 from being secretly reserved, restart WINNAT. This is apparently durable such that after reboot, the protection from Windows reserving the port remains.

```
net stop winnat

netsh int ipv4 add excludedportrange protocol=tcp startport=8002 numberofports=1

net start winnat
```

If you are using a port other than 8002, use that instead. If the random ports sometimes get blocked and sometimes not, it could be you are running up against some reserved ports. Locking in port 8002 and then doing this would presumably solve it.

This may not be the solution generally, but it is what we found explicitly worked along with a clear reason why. Best of luck!

**Comment by mildrenben** [comment] 2023-10-03 12:09
For anyone running into this in 2023, the `devServerPort` in `remix.config.js` was renamed. You should now use:
```
module.exports = {
  ...otherConfig,
  dev: {
    port: 8002
  }
};
```

**Comment by smittal-qb** [comment] 2023-10-04 20:49
Is the solution still working for remix V2? i can't seem to get it to work

**Comment by smittal-qb** [comment] 2023-10-04 20:50
> For anyone running into this in 2023, the `devServerPort` in `remix.config.js` was renamed. You should now use:
> 
> ```
> module.exports = {
>   ...otherConfig,
>   dev: {
>     port: 8002
>   }
> };
> ```

Is this working for remix V2

**Comment by YuraGB** [comment] 2023-10-19 16:48
Ok. guys.
My  project uses this package.json: 

`  "dependencies": {
    "@nextui-org/react": "^2.1.13",
    "@prisma/client": "^5.4.2",
    "@remix-run/css-bundle": "^2.0.1",
    "@remix-run/express": "^2.1.0",
    "@remix-run/node": "^2.0.1",
    "@remix-run/react": "^2.0.1",
    "@remix-run/serve": "^2.0.1",
    "bcryptjs": "^2.4.3",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "express": "^4.18.2",
    "framer-motion": "^10.16.4",
    "isbot": "^3.6.8",
    "morgan": "^1.10.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "remix": "^2.1.0",
    "remix-auth": "^3.6.0",
    "remix-auth-form": "^1.4.0",
    "socket.io": "^4.7.2"
  },
  "devDependencies": {
    "@remix-run/dev": "^2.0.1",
    "@remix-run/eslint-config": "^2.0.1",
    "@types/bcryptjs": "^2.4.4",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@types/socket.io-client": "^3.0.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.38.0",
    "nodemon": "^3.0.1",
    "prisma": "^5.4.2",
    "socket.io-client": "^4.7.2",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.1.6"
  },`

I don't use any dev ports in remix-config
I don't use any port prop  in  <LiveReload /> component.
I don't use "remix watch" command because it's hard to catch what port it will be  using if 3000 will be not available
You must understand that almost all examples of remix + socket io are  old  and uses outdated version of packages 
So, you need to configure the io server

`const io = new Server(httpServer, {
    transports: [
        'polling',
    ],
    cors: {
        origin: "http://localhost:3000",
        credentials: true,
    },
});`

![image](https://github.com/remix-run/remix/assets/26120957/0e1ad303-5a83-47d0-bb7c-866df384bc26)
![image](https://github.com/remix-run/remix/assets/26120957/e1e01a54-4827-4d16-9a59-efd72edae1e8)
![image](https://github.com/remix-run/remix/assets/26120957/c4230747-9788-439f-b881-2975251d4940)

**Comment by deadcoder0904** [comment] 2024-03-10 12:06
any solutions for docker?
