### ISSUE TITLE
create-remix CLI 404ing for template url to branch

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/remix#8151] opened 2023-11-27 17:33 UTC
### Reproduction

As noted in [this PR](https://github.com/remix-run/remix/pull/8149), I would expect the following to work

```shellscript
npx create-remix@latest --template https://github.com/remix-run/remix/tree/brooks/remix-tutorial-template/templates/remix-tutorial
```

For some reason it doesn't. I can confirm that using a file path did work, which is how I ended up testing the template. However, the file path doesn't have the branch name in the path, so not a 1-to-1 comparison

### System Info

```shell
npx 9.6.7
```

### Used Package Manager

npm

### Expected Behavior

Expected it to clone the template

### Actual Behavior

It did not, it 404'd with this message 

> ▲  Oh no! There was a problem fetching the file from GitHub. The request responded with a 404 status. Please try again later.

**Comment by brophdawg11** [comment] 2023-11-27 18:43
Yeah this looks like it doesn't work for branches with slashes in the name at the moment, since it splits by slash and grabs one URL segment for the branch :/

https://github.com/remix-run/remix/blob/374d28c97ed897a7afd87cc44eeb5a9cc49476c3/packages/create-remix/copy-template.ts#L437

I'm not sure offhand if/how we want to fix this.  Part of the original design of `create-remix` is to avoid having to talk to github multiple times to determine if the URL you passed is valid or what type it is.  So short of taking one slash section at a time until we find a valid branch (i.e., what if the branch is `brophdawg11/fix/something`), there's not a great way to know if the branch is more than one URL segment.

We could potentially consider leaning into the shorthand notation and adding a `branch` flag, but it's not necessarily a good thing to enlarge the API surface like that:

```
npx create-remix@latest --template remix-run/remix/templates/remix-tutorial --branch brooks/remix-tutorial-template
```

**Comment by brophdawg11** [comment] 2023-12-07 18:11
I'm going to close this out for now since it's not a bug per-se.  I added a note to the docs in 7c6392295f1f50eb3083826189d74087bdbe2e53

**Closed by brophdawg11** 2023-12-07 18:11 UTC
Labels: package:create-remix, bug:unverified
