### ISSUE TITLE
[Bug]: Warning: Did not expect server HTML to contain a <div> in <html>.

### ISSUE THREAD

**Issue by shadyendless** [remix-run/remix#1158] opened 2021-12-19 21:03 UTC
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14

### Steps to Reproduce

- Install the [10ten Japanese Reader](https://github.com/birchill/10ten-ja-reader) extension
- Run `npx create-remix@latest <project-name>`
- Choose any template
- Install the dependencies
- Run `cd <project-name> && npm run dev`
- Open the browser console

### Expected Behavior

The expected behavior is that the console window is empty.

### Actual Behavior

The following error is displayed:
```
Warning: Did not expect server HTML to contain a <div> in <html>.
    at html
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:3022:3)
    at Routes (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:3010:7)
    at Router2 (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:478:21)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:1564:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:1489:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:2907:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-XXZOVCAU.js:3314:27)
```

**Comment by shadyendless** [comment] 2021-12-19 21:06
I am not sure if anything can be done about fixing this issue, but I discussed with @jacob-ebey about starting a new area in the documentation that lists extensions that may cause this error to appear.

The code for the above-mentioned extension is open source, so it may be possible to look at it and see what may be causing it or to submit a PR modifying its behavior to avoid this in the future, though simply calling it out may be sufficient enough.

**Comment by Glup3** [comment] 2021-12-20 19:29
https://github.com/remix-run/remix/issues/1077#issuecomment-995986018

**Comment by pablen** [comment] 2022-01-08 18:04
In my case it was the Apollo Client Devtools extension triggering the error.

**Comment by machour** [comment] 2022-03-18 01:07
Duplicate of #1077

**Closed by machour** 2022-03-18 01:07 UTC
Labels: bug
