### ISSUE TITLE
[ERROR] Could not resolve "fs/promises"

### ISSUE THREAD

**Issue by archraziel88** [remix-run/remix#3103] opened 2022-05-05 14:57 UTC
### What version of Remix are you using?

Remix - Cloudflare workers @ latest

### Steps to Reproduce

Hello,
i'm trying to learn react and remix altogheter, I came across an error, trying to pass a multipart form from frontend to backend via form and action. As i try to import unstable_createMemoryUploadHandler it throws an error related to FS/Promises
``` node_modules/@remix-run/node/upload/fileUploadHandler.js:17:23:
17 │ var promises = require('fs/promises'); 

The package "fs/promises" wasn't found on the file system but is built into node. 
Are you trying to bundle for node? 
You can use "platform: 'node'" to do that, which will remove this error.


Build failed with 1 error:
node_modules/@remix-run/node/upload/fileUploadHandler.js:17:23: ERROR: Could not resolve "fs/promises"

```
So basically I don't understand if I'm doing something wrong. As I could understand on cloudflare workers I have to rely on their services, and so no storage and so no fileUpload, i'm trying to use the stream to get the file posted with the request to pass it to supabase via service role key. 

Any idea what am I missing?

### Expected Behavior

Should create a uploaderHandle to pass to 
```
export const action: ActionFunction = async ({
  request,
}) => {
  const uploadHandler = unstable_createMemoryUploadHandler({
    maxFileSize: 500_000,
  });
  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const file = formData.get("avatar");

  // file is a "File" (https://mdn.io/File) polyfilled for node
  // ... etc
```

### Actual Behavior

``` node_modules/@remix-run/node/upload/fileUploadHandler.js:17:23:
17 │ var promises = require('fs/promises'); 

The package "fs/promises" wasn't found on the file system but is built into node. 
Are you trying to bundle for node? 
You can use "platform: 'node'" to do that, which will remove this error.


Build failed with 1 error:
node_modules/@remix-run/node/upload/fileUploadHandler.js:17:23: ERROR: Could not resolve "fs/promises"

```

**Comment by top16Dev** [comment] 2022-05-07 05:36
Did you solve it?

**Comment by archraziel88** [comment] 2022-05-07 08:26
> Did you solve it?

nope. tried a lil' more, as i was trying to figure out how this works, ended up trying setting up a edge function (working on supabase) to overcome the limit. 

I couldn't figure out how to go on, and reverted back to next at the moment :)

**Comment by roblingle** [comment] 2022-05-09 15:44
Same issue. Cloudflare Worker + Typescript
node 17.8.0
npm 8.5.5

Regarding `You can use "platform: 'node'" to do that, which will remove this error.`, is this an option I could pass through to esbuild?

**Comment by kiliman** [comment] 2022-05-09 16:36
You can't use node APIs with Cloudflare. They don't even have a file system.

**Comment by ptim** [comment] 2022-05-13 03:40
I had this issue when trying to "re-platform" a default remix app to  cloudflare pages in a [monorepo created with nx](https://www.npmjs.com/package/@nrwl/remix) `npx create-nx-workspace@latest nx --preset=@nrwl/remix --project=remix-nx`. There were no imports of node APIs in the app code.

I think the issue was that the nx template uses the 'default' remix platform @ v1.0.6, and the imports were from 'remix' rather than '@remix-run/*'. Updating all these references resolved the issue for me:

- ❌ `import { Link } from 'remix';`
- ✅ `import { Link } from "@remix-run/react";`

Red herring: I noticed along the way `npx remix setup cloudflare` and ran that, but I don't think that resolved the issue.

**Comment by ptim** [comment] 2022-06-21 03:25
> Anyone who was able to solve this?

Works for me with the adjustments [I mentioned above](https://github.com/remix-run/remix/issues/3103#issuecomment-1125627098) @mcmxcdev 👍

**Comment by mcmxcdev** [comment] 2022-06-21 16:19
> Works for me with the adjustments [I mentioned above](https://github.com/remix-run/remix/issues/3103#issuecomment-1125627098) @mcmxcdev +1

Thank you Tim, but we already use the new imports rather than the deprecated ones. We also don't use `fs-extra`, so no clue where to start. 

One way to solve this would be to patch away the line failing the CI run with https://www.npmjs.com/package/patch-package I guess.

**Comment by RaquelFilipaMendes** [comment] 2022-08-19 17:04
I have the same error, with the remix-i18next. Has anyone had the same problem?

**Comment by sibasishm** [comment] 2022-09-18 19:34
It's happening for me as well, but in `remix-run/node` Any resolution? 

<img width="278" alt="Screenshot 2022-09-18 at 23 05 00" src="https://user-images.githubusercontent.com/16509307/190925174-b912ed81-3f4b-49de-86bb-f719891587b2.png">

**Comment by matt416** [comment] 2022-11-04 12:57
In my case, I was getting this error because I was trying to import from the wrong package,

in `entry.client.jsx` I had

`import { RemixBrowser } from "@remix-run/node";`

which should have been

`import { RemixBrowser } from "@remix-run/react";`

I assume this could happen with other incorrect imports as well

**Comment by lili21** [comment] 2022-11-09 08:02
same issue here. I'm trying to use `defer` in cloudflare worker.

**Comment by seancwalsh** [comment] 2022-11-10 11:28
For me, the problem was caused by `createCookie` from `@remix-run/node`. I can't remember why, but I think I read somewhere that this must not be in a route file. So moving this to another file fixed the issue.

**Comment by tyteen4a03** [comment] 2022-11-12 02:41
Same error here, no idea what the cause is.

**Comment by mxp-qk** [comment] 2022-11-26 22:12
Same issu for me, in my case this is due to importing anything (redirect, json) from `@remix-run/node` in a yarn PNP monorepo. I didn't find a way around it but to use `new Response (...)`

**Comment by shubumpc91** [comment] 2022-12-12 16:22
I was facing the same issue.

Solution that worked for me : moved **createCookie** helper to **.server** file

**Comment by jacob-ebey** [comment] 2023-01-12 00:15
This should be resolved. Anyone experiencing this should try upgrading to 0.0.0-experimental-2f4891673.

**Comment by BillBrower-Shopify** [comment] 2023-02-01 18:51
@jacob-ebey Is this fixed in v1.12.0?

**Comment by Coco-rb2** [comment] 2023-03-09 07:41
> 

TS2305: Module '"@remix-run/cloudflare"' has no exported member 'Response'.
did you get this error ?

**Comment by jgentes** [comment] 2023-03-26 02:21
I ended up switching
```js
import { LinksFunction, MetaFunction } from '@remix-run/node'
```
to
```js
import { LinksFunction, MetaFunction } from '@remix-run/cloudflare'
```

**Comment by felpsio** [comment] 2023-04-27 04:05
I'm having the same problem with node v16.13.0. Had to use `remix-run/cloudflare`. We definitely need a better solution for this, I lost a long time trying to find better solutions

**Comment by markdalgleish** [comment] 2023-08-21 02:12
There is now a polyfill for `fs/promises` when building for non-Node platforms, but as others have said, you should be using `@remix-run/cloudflare` which doesn't depend on Node built-ins and therefore doesn't need any polyfills.

Note that in the upcoming Remix v2 you'll need to explicitly enable any polyfills via the [serverNodeBuiltinsPolyfill option](https://remix.run/docs/en/main/file-conventions/remix-config#servernodebuiltinspolyfill).

**Closed by markdalgleish** 2023-08-21 02:12 UTC
Labels: adapter:cloudflare-workers, bug:unverified
