### ISSUE TITLE
[Bug]: The demo text did not render properly

### ISSUE THREAD

**Issue by lie5860** [remix-run/remix#805] opened 2021-11-30 12:43 UTC
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0

### Steps to Reproduce

url: http://localhost:3000/demos/params
click "And this will be 401 Unauthorized"

### Expected Behavior

It should show "Looks like you tried to visit a page that you do not have access to. Maybe ask the webmaster (hello@remix.run) for access."

### Actual Behavior

not show

**Comment by MichaelDeBoey** [comment] 2021-11-30 13:23
Duplicate of #625

**Closed** 2022-03-18 08:17 UTC
Labels: bug, documentation
