### ISSUE TITLE
Dynamic Route 404 if url segment has special characters.

### ISSUE THREAD

**Issue by xHomu** [remix-run/remix#4585] opened 2022-11-12 18:04 UTC
### What version of Remix are you using?

1.7.4

### Steps to Reproduce

[Stack Blitz Example](https://stackblitz.com/edit/node-7m5upb?file=app%2Froutes%2F%24userid%2F%24projectname%2F%24.tsx)

1. Declare a dynamic route file route/$route.tsx.
2. Try to access URL with special characters, such as @: /@testroute.

### Expected Behavior

Valid URI should parse as dynamic parameter.

### Actual Behavior

Page returns 404.

**Comment by xHomu** [comment] 2022-11-12 18:14
Is this due to @ being a reserved character?

https://developers.google.com/maps/url-encoding

**Comment by machour** [comment] 2022-11-12 20:08
Duplicate of #846

**Closed by machour** 2022-11-12 20:08 UTC
Labels: bug:unverified
