### ISSUE TITLE
A compilation error occurred while changing serverModuleFormat to esm.

### ISSUE THREAD

**Issue by mitamac** [remix-run/remix#6534] opened 2023-06-05 03:16 UTC
### What version of Remix are you using?

latest

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- pnpm dlx create-remix remix
- ![image](https://github.com/remix-run/remix/assets/56892264/1487968c-de38-4d91-8be1-cb8b31b432b9)
- Change serverModuleFormat to esm
- ![image](https://github.com/remix-run/remix/assets/56892264/9a2b5793-74ce-474f-a59b-8ab9436848c2)

### Expected Behavior

I want it to work

### Actual Behavior

- ![image](https://github.com/remix-run/remix/assets/56892264/7385f40f-c5c2-4908-b1e6-445db1ad9cda)

**Comment by brophdawg11** [comment] 2023-06-06 14:19
Duplicate of #6272

**Closed by brophdawg11** 2023-06-06 14:19 UTC
Labels: bug:unverified
