### ISSUE TITLE
useFetcher's type loses generic properties

### ISSUE THREAD

**Issue by AsaAyers** [remix-run/remix#6632] opened 2023-06-17 14:32 UTC
### What version of Remix are you using?

1.17.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

This isn't a runtime problem, you can copy/paste this code into a project and you'll see a TypeScript error where I left a comment.

```
type ValidTypes = 'A' | 'B'
type DataForType<T extends ValidTypes> = T extends 'A' ? { a: string } : { b: number }
export function ExampleComponent<T extends ValidTypes>(props: { type: T }) {
  const stringFetcher = useFetcher<{
    type: string
  }>()
  const unionFetcher = useFetcher<{
    type: 'A' | 'B'
  }>()
  const typeFetcher = useFetcher<{
    type: ValidTypes
  }>()
  const genericFetcher = useFetcher<{
    // type demonstrates the issue with minimal code
    type: T
    // data demonstrates the issue with real code. I have a component that needs
    // to be composed with other components and using generics I can ensure all
    // the types match. Except when I got to here, the property ends up getting
    // lost from the result.
    data: DataForType<T>
  }>()

  const a = stringFetcher.data?.type
  const b = unionFetcher.data?.type
  const c = typeFetcher.data?.type
  // Either SerializeObject or UndefinedToOptional cause
  // generic properties to become lost.
  const d = genericFetcher.data?.type

  return null
}
```

### Expected Behavior

I expected to be able to use `genericFetcher` like I would any of the others. 

### Actual Behavior

I think the type system is looking at `T extends ValidTypes` and that somehow doesn't infer down to a JSON serializable type. We know looking at it that `ValidTypes` is a union of strings, but that's getting lost somewhere.

I understand this could be some limitation in TypeScript. If you have any thoughts on a more specific explanataion or where the problem might be, I can investigate and see if I can resolve it.

<img width="749" alt="image" src="https://github.com/remix-run/remix/assets/324999/24aed760-4141-499f-9b24-49eab208cbea">
<img width="893" alt="image" src="https://github.com/remix-run/remix/assets/324999/56675280-7309-450c-9c6c-6ca789f72e80">

**Comment by pcattori** [comment] 2023-06-18 17:42
Seems like this is a Typescript issue with filtering keys for generic types. Here's a [minimal reproduction in a Typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAaghgGwJYBMAq4IGcoF4oDkAggVAD6EBCBAUKJFACJzBwBiA9gE4aQA8aKBAAewCADsUOeMnSYsAPjxRBIsZJzFSAfigBvKHABcULMC5JxAcygBfKCYMAjE+ICuAWycQudmnUwoNiQEMS4AaQgQLAEhUQkpKA4nACsIAGNgJXw9GigoAHoC0wB3ODAoEoALJHSqqGRxaCQcdI4PDwkxFCgqn2hgDlMIAb6oFCQAM0n+8XSIGgBIAG1IkChLKABrKI5JlQBdEzRVqIO49US3SQhJywge3SaANx8HKDWAbjzC4tP1zY7EB7Q4mL40WzLIEgtAHb4BBjBUI+ADyqQywFiagSOGSaUy2X0S3+G3E212+wACrUtgIADRBEJhNYxNAKBRHFT-OEQ+EICDAKD7fBY+IaWCIVC8bAKAAUwGOAEo8Epcvl6NBmKxlFr2NxpQIFD8NVAAMrANzTZQGMyWyYmXV+dWBAAayiRYTR+Mx5rtRvy-MFwhMbpy9jgODg4hAP2EADpbdMIUA).

**Comment by pcattori** [comment] 2023-07-03 15:52
Closing as this seems to be a limitation with TS, not Remix.

**Closed by pcattori** 2023-07-03 15:52 UTC
Labels: feat:typescript, bug:unverified
