### ISSUE TITLE
Remix + Styled Components practicably not production ready

### ISSUE THREAD

**Issue by Xiphe** [remix-run/remix#5159] opened 2023-01-20 14:21 UTC
### What version of Remix are you using?

v1.11.0

### Steps to Reproduce

This is not per-se a remix bug but a conceptual incompatibility between apps that manage the whole document (like remix) and styled-components (at the current state). 

I therefore opened an issue on their side: https://github.com/styled-components/styled-components/issues/3924 including steps to reproduce.

I'm opening this issue here to raise awareness. Maybe of the team want's to jump on it or maybe you have another idea how to work around it.

### Expected Behavior

Since hydration errors can be randomly introduced by any browser extension my app has to be able to fully recover from those.

### Actual Behavior

The problem is that when any hydration error happens in production ALL styled-component styles are just gone 🕳️

**Comment by machour** [comment] 2023-01-20 14:35
Closing as duplicate of https://github.com/remix-run/remix/issues/5144 which provides more details 👍🏼

**Closed by machour** 2023-01-20 14:35 UTC
Labels: bug:unverified
