### ISSUE TITLE
Vite: Issues adding and navigating to new routes

### ISSUE THREAD

**Issue by dmarkow** [remix-run/remix#7894] opened 2023-11-03 14:33 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- `vite dev`
- Link to a new route that doesn't exist yet, e.g. `/foo`, which adds the link via HMR.
- Create the new route, e.g. `app/routes/foo.tsx`
- Click the link

There are a couple things that can happen:
- If you have a splat route that could match the new route, e.g. `app/routes/$.tsx`, and it has no loader, the splat route gets rendered as if the new route doesn't exist.
- If you have a splat route which has its own loader, an ErrorBoundary is triggered with a server error of `Error: Route "routes/$" does not match URL "/foo"` when running the loader -- makes sense, as the request to the server for this loader triggers an update of `pluginConfig`, so the server knows about the new route even though the client doesn't.
- If you don't have a matching splat route, Remix throws a 404

This only affects adding new routes, not renaming existing ones. In all 3 situations, a full reload in the browser pulls up the new page. Vite doesn't do anything when a new file is added as far as I can tell, so the hard reload is required to get the remix plugin to notice the new route.

### Expected Behavior

Adding new routes should do something via HMR so the client side knows about the new routes.

### Actual Behavior

Adding new routes does not notify the client, so the client decides the new route does not exist.

**Comment by kiliman** [comment] 2023-11-03 15:43
Interesting. I get different results based on the sequence.

### works
* Add new route and save
* Add `<Link>` to new route and save
* Click on link
* 🎉 Yay!

### doesn't work
* Add `<Link>` to new route and save
* Add new route and save
* Click on link
* 😭 Boo!

So what I think is happening is that when you update the route with the `<Link>`, it's getting the updated route config, so clien-side routing works properly.

However, if you add the route **after** updating the `<Link>` route, it's not getting the updated route config, so it returns _route not found_.

**Comment by dmarkow** [comment] 2023-11-03 18:35
@kiliman Sorry, you're right! I got those two steps mixed up, fixing now.

**Comment by pcattori** [comment] 2024-01-31 21:16
Looks like this was fixed in #8164 . Can't reproduce anymore on v2.5.1

https://github.com/remix-run/remix/assets/1477317/12747f8e-71f2-4c6f-94e8-3a7962c46765

**Closed by pcattori** 2024-01-31 21:16 UTC
Labels: bug:unverified, vite
