### ISSUE TITLE
Remix crashes with web-fetch 4.3.2/1.8.2

### ISSUE THREAD

**Issue by tarngerine** [remix-run/remix#4993] opened 2023-01-03 17:52 UTC
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

See sandbox: https://codesandbox.io/p/sandbox/solitary-wave-1l0skr
Failing test PR: https://github.com/remix-run/remix/pull/4994

1. Observe exit code 1 (remix crashes, premature close error) when fetcher loads from /load.tsx route, which calls fetch from a Google drive URL
2. Go to load.tsx, uncomment the import that uses web-fetch 4.3.1
3. Remix no longer crashes

### Expected Behavior

web-fetch's fetch should work, without crashing remix, returning a valid HTML result

### Actual Behavior

remix crashes, exit code 1

```
/project/sandbox/node_modules/@remix-run/node/node_modules/@remix-run/web-fetch/src/fetch.js:342
                                const error = Object.assign(new Error('Premature close'), {
                                ^
Error: Premature close
    at TLSSocket.onSocketClose (/project/sandbox/node_modules/@remix-run/node/node_modules/@remix-run/web-fetch/src/fetch.js:342:33)
    at TLSSocket.emit (node:events:525:35)
    at node:net:757:14
    at TCP.done (node:_tls_wrap:584:7)
error Command failed with exit code 1.
```

### Related issues:

https://github.com/remix-run/remix/issues/4737

**Comment by cliffordfajardo** [comment] 2023-01-03 19:45
This codesandbox URL you shared  doesn't seem to work; I've had this challenge when using their newer codesandbox environments 😅 

Any way you could copy code into this  stackblitz template below?
- Remix Stackblitz 1.8.2 template: https://stackblitz.com/edit/node-nrd9zz

**Comment by tarngerine** [comment] 2023-01-03 20:16
Hi, can you explain what you mean by the codesandbox doesn't work? It is supposed to show an error that is the bug I am reporting:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/1629901/210434251-db8db9f7-96b4-4255-ac0e-a87ab90cbb9b.png">

once you go into load.tsx and uncomment the 4.3.1 web-fetch import, and hit the refresh icon "restart task" on the dev pane, then it will display the site:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/1629901/210434366-498a0b82-839e-4763-9443-2dc24b610ac0.png">

**Comment by tarngerine** [comment] 2023-01-03 20:17
Unfortunately i cannot repro this issue in Stackblitz, it has its own issues with fetching, guessing from CORS bc it's webcontainer?

**Comment by tarngerine** [comment] 2023-01-03 20:28
Here's a failing test PR if that helps: https://github.com/remix-run/remix/pull/4994

**Comment by cliffordfajardo** [comment] 2023-01-04 00:56
> Hi, can you explain what you mean by the codesandbox doesn't work?
My bad, i should have been more specific; 
when I try to view the codesandbox URL you shared I see this error & do no have access to view the code in the images you shared
 
![CleanShot 2023-01-03 at 16 54 58@2x](https://user-images.githubusercontent.com/6743796/210465193-26b6cd56-e13b-4bea-8150-aefda02dfc0d.png)

**Comment by tarngerine** [comment] 2023-01-13 18:09
Here's a failing test PR if that helps: https://github.com/remix-run/remix/pull/4994

**Comment by nicksrandall** [comment] 2023-01-20 17:18
@jacob-ebey Is the failing test enough? Anything else we can do to help get this fixed?

**Comment by gigobyte** [comment] 2023-02-07 16:16
I have an `action` that starts a `setInterval` that calls fetch and for me this reproduces the error every few requests. Luckily reverting `@remix-run/web-fetch` back to 4.3.1 fixes the issue.

**Comment by donavon** [comment] 2023-02-07 23:37
I'm having the same issue. I just closed #5385 as it's a dupe of this issue.

If you need to temporary workaround (it works for me), you can use the diff I posted there with [patch-package](https://www.npmjs.com/package/patch-package). No guarantees, but it seems to work until we get a proper fix (all I do is suppress the error).

**Comment by donavon** [comment] 2023-02-07 23:57
@tarngerine Just to confirm, I can see your sandbox properly failing with 4.3.2

**Comment by donavon** [comment] 2023-02-07 23:59
FYI... Here's the diff between 4.3.1 and 4.3.2

## fetch.js

```diff
diff --git a/src/fetch.js b/src/fetch.js
index v4.3.1..v4.3.2 100644
--- a/src/fetch.js
+++ b/src/fetch.js
@@ -346,13 +346,8 @@
 			}
 		};
 
-		socket.prependListener('close', onSocketClose);
-
-		request.on('abort', () => {
-			socket.removeListener('close', onSocketClose);
-		});
-
-		socket.on('data', buf => {
+		/** @param {Buffer} buf */
+		const onData = buf => {
 			properLastChunkReceived = Buffer.compare(buf.slice(-5), LAST_CHUNK) === 0;
 
 			// Sometimes final 0-length chunk and end of message code are in separate packets
@@ -364,6 +359,14 @@
 			}
 
 			previousChunk = buf;
+		};
+
+		socket.prependListener('close', onSocketClose);
+		socket.on('data', onData);
+
+		request.on('close', () => {
+			socket.removeListener('close', onSocketClose);
+			socket.removeListener('data', onData);
 		});
 	});
 }
```

## request.js

```diff
diff --git a/src/request.js b/src/request.js
index v4.3.1..v4.3.2 100644
--- a/src/request.js
+++ b/src/request.js
@@ -38,6 +38,7 @@
  * @property {string} method
  * @property {RequestRedirect} redirect
  * @property {globalThis.Headers} headers
+ * @property {RequestCredentials} credentials
  * @property {URL} parsedURL
  * @property {AbortSignal|null} signal
  * 
@@ -135,6 +136,7 @@
 			method,
 			redirect: init.redirect || input.redirect || 'follow',
 			headers,
+			credentials: init.credentials || 'same-origin',
 			parsedURL,
 			signal: signal || null
 		};
@@ -169,7 +171,7 @@
 	 */
 
 	get credentials() {
-		return "same-origin"
+		return this[INTERNALS].credentials
 	}
 
 	/**
```

**Comment by donavon** [comment] 2023-02-08 01:57
The only issue with reverting back to 4.3.1 is that 4.3.2 was there to fix a memory leak (see https://github.com/remix-run/web-std-io/commit/3b9b38446d186230a94d5481ba12ae4289d8809e).

**Comment by donavon** [comment] 2023-02-08 02:39
PR created with a possible fix: https://github.com/remix-run/web-std-io/pull/29

Plz review

**Comment by donavon** [comment] 2023-02-19 14:45
I'm surprised that something that crashes Remix isn't getting any attention.

**Comment by zabirauf** [comment] 2023-04-21 07:20
FWIW, I also came here to report similar issue. I have also run into it often but it's not consistent.

**Comment by IgnisDa** [comment] 2023-06-19 16:34
The error does not occur if you have `connection: keep-alive` in the headers. I think axios sets that automatically.

**Closed** 2023-08-01 19:42 UTC
Labels: bug:unverified, feat:fetch

**Comment by brophdawg11** [comment] 2023-08-01 23:06
This is resolved by the version bump in #7026 and should be available when 1.19.2 is released

**Comment by brophdawg11** [comment] 2023-08-01 23:08
This can also be tested in `1.19.2-pre.0` currently if anyone would like to validate the fix

**Comment by ericallam** [comment] 2023-08-02 13:53
We've had this issue (intermittently on prod only) and we've updated to `1.19.2-pre.0` and are testing it out now. Will update this issue if we continue to experience the Premature close error

**Comment by ericallam** [comment] 2023-08-02 19:07
@brophdawg11 was there really something related to this issue in `1.19.2-pre.1`, and should we upgrade to try it?
