### ISSUE TITLE
@remix-run/architect - Hydration fails on a new project

### ISSUE THREAD

**Issue by dbroadhurst** [remix-run/remix#4352] opened 2022-10-10 16:04 UTC
### What version of Remix are you using?

@remix-run/architect": "^1.7.2",

### Steps to Reproduce

npx create-remix@latest

Select Architect (AWS Lambda)

### Expected Behavior

Sample page runs without errors. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/5667105/194908183-5f9bcfba-1d01-434f-83b4-2b72b6ee0c95.png)

Tried Incognito just incase I have an extension issue but same results in Incognito

**Comment by machour** [comment] 2022-10-10 17:12
Confirmed on my end. One of the main differences is that the LiveReload script doesn't seem to be SSRed.

**Comment by zolzaya** [comment] 2022-10-11 00:42
Same for me

**Comment by zNiik** [comment] 2022-10-13 05:20
Same for me using Remix App Server

**Comment by RobertBroersma** [comment] 2022-10-19 11:33
Try adding `NODE_ENV=development` to your existing or a new `.env` file. 

Explanation can be found in https://github.com/remix-run/remix/issues/1756#issuecomment-1065682371 and the rest of the issue as well!

**Comment by nongc1n** [comment] 2022-10-19 11:58
@RobertBroersma didn't work for me

**Comment by machour** [comment] 2022-10-19 12:11
@dbroadhurst @zolzaya could you give @RobertBroersma comment a try please?

**Comment by nongc1n** [comment] 2022-10-19 12:25
Was having the same issue but now I tried creating a fresh Remix and disable all my chrome extensions and found out whenever I enable Apollo Client Devtools the error occurs even with `NODE_ENV=development`.

**Comment by dbroadhurst** [comment] 2022-10-19 13:19
@machour confirmed adding the NODE_ENV var resolved the issue

**Comment by pacghost** [comment] 2022-10-28 07:10
I was going to do the remix-jokes demo app (using "just the basics") and I also get this error. It is not resolved by doing NODE_ENV=development for me.

**Comment by MichaelDeBoey** [comment] 2022-11-20 21:41
This is probably because one of your browser extensions is injecting code : https://remix.run/docs/pages/gotchas#browser-extensions-injecting-code

**Closed by MichaelDeBoey** 2022-11-20 21:41 UTC
Labels: bug, template:architect

**Comment by thebiltheory** [comment] 2023-02-16 14:09
For me the chrome VPN Express plugin was causing the issues. 
Thanks @MichaelDeBoey
