### ISSUE TITLE
Cloudflare pages with theme-ui `ReferenceError: Buffer is not defined`

### ISSUE THREAD

**Issue by iamskok** [remix-run/remix#4402] opened 2022-10-22 03:19 UTC
### What version of Remix are you using?

1.7.3

### Steps to Reproduce

1. `npx create-remix@latest`
2. `Just the basics`
3. `Cloudflare Pages`
4. Copy over files from [theme-ui example](https://github.com/remix-run/examples/tree/main/theme-ui)
   - `context.tsx`
   -  `createEmotionCache.ts`
   - `entry.client.tsx`
   - `entry.server.tsx`

### Expected Behavior

`yarn dev` and `yarn build` runs without errors and warnings.

### Actual Behavior

[Reproduction repo](https://github.com/iamskok/remix-cloudflare-pages-theme-ui-reproduction)

From what I could observe there seems to be two different issues:

1. Is related to the code that is defined in [`entry.server.tsx`](https://github.com/iamskok/remix-cloudflare-pages-theme-ui-reproduction/blob/main/app/entry.server.tsx).

```
/private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:7412
    var toString3 = Object.prototype.toString, isModern = typeof Buffer.alloc == "function" && typeof Buffer.allocUnsafe == "function" && typeof Buffer.from == "function";
                                                          ^
ReferenceError: Buffer is not defined
    at node_modules/html-tokenize/node_modules/buffer-from/index.js (/private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:7412:59)
    at /private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:10:46
    at node_modules/html-tokenize/index.js (/private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:8231:22)
    at /private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:10:46
    at node_modules/@emotion/server/create-instance/dist/emotion-server-create-instance.cjs.dev.js (/private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:9502:49)
    at /private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:10:46
    at node_modules/@emotion/server/create-instance/dist/emotion-server-create-instance.cjs.js (/private/Users/vladsk/dev/remix-cloudflare-pages/functions/[[path]].js:9606:22)
✘ [ERROR] Miniflare process exited with code 1
```

2. Is related to the code that is defined in [`root.tsx`](https://github.com/iamskok/remix-cloudflare-pages-theme-ui-reproduction/blob/main/app/root.tsx)

```
▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    functions/[[path]].js:12723:15:
      12723 │             }, this),
            │                ~~~~
            ╵                undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    functions/[[path]].js:12909:0:
      12909 │ export {
            ╵ ~~~~~~

▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    functions/[[path]].js:12723:15:
      12723 │             }, this),
            │                ~~~~
            ╵                undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    functions/[[path]].js:12909:0:
      12909 │ export {
            ╵ ~~~~~~

▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    functions/[[path]].js:12723:15:
      12723 │             }, this),
            │                ~~~~
            ╵                undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    functions/[[path]].js:12909:0:
      12909 │ export {
            ╵ ~~~~~~

▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    functions/[[path]].js:12723:15:
      12723 │             }, this),
            │                ~~~~
            ╵                undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    functions/[[path]].js:12909:0:
      12909 │ export {
            ╵ ~~~~~~

▲ [WARNING] Top-level "this" will be replaced with undefined since this file is an ECMAScript module [this-is-undefined-in-esm]

    functions/[[path]].js:12723:15:
      12723 │             }, this),
            │                ~~~~
            ╵                undefined

  This file is considered to be an ECMAScript module because of the "export" keyword here:

    functions/[[path]].js:12909:0:
1 warning(s) when compiling Worker.
1 warning(s) when compiling Worker.
```

`npx envinfo --system --npmPackages '{@theme-ui/core,@remix-run/*}' --binaries --browsers`

```
  System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 54.85 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 102.3.0
    Safari: 16.0
  npmPackages:
    @remix-run/cloudflare: ^1.7.3 => 1.7.3
    @remix-run/cloudflare-pages: ^1.7.3 => 1.7.3
    @remix-run/dev: ^1.7.3 => 1.7.3
    @remix-run/eslint-config: ^1.7.3 => 1.7.3
    @remix-run/react: ^1.7.3 => 1.7.3
    @theme-ui/core: ^0.15.3 => 0.15.3
```

**Comment by machour** [comment] 2022-10-22 11:13
Duplicate of #2813

**Closed by machour** 2022-10-22 11:13 UTC
Labels: bug:unverified

**Comment by iamskok** [comment] 2022-10-23 01:49
And the warning message is a duplicate of #4155
