### ISSUE TITLE
error in website https://remix.run/ Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by masx200** [remix-run/remix#3383] opened 2022-06-05 06:31 UTC
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

<img width="960" alt="image" src="https://user-images.githubusercontent.com/34191203/172038431-75e1550c-2960-4f0b-8034-2058eceb4573.png">

### Expected Behavior

no error

### Actual Behavior

Error
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ys (https://remix.run/build/_shared/chunk-AGZHEPHC.js:7:5603)
    at Yf (https://remix.run/build/_shared/chunk-AGZHEPHC.js:9:3820)
    at L.unstable_runWithPriority (https://remix.run/build/_shared/chunk-AGZHEPHC.js:1:4026)
    at rn (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38448)
    at Ge (https://remix.run/build/_shared/chunk-AGZHEPHC.js:9:1807)
    at yi (https://remix.run/build/_shared/chunk-AGZHEPHC.js:7:11071)
    at https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38670
    at L.unstable_runWithPriority (https://remix.run/build/_shared/chunk-AGZHEPHC.js:1:4026)
    at rn (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38448)
    at Cs (https://remix.run/build/_shared/chunk-AGZHEPHC.js:5:38616)
```

**Comment by machour** [comment] 2022-06-05 07:04
Duplicate of #2943 
Can you please give more information about your OS/browser there ?

**Closed by machour** 2022-06-05 07:04 UTC
Labels: bug:unverified, website

**Comment by masx200** [comment] 2022-06-05 08:03
Google Chrome 版本 102.0.5005.63（正式版本） （64 位）

Microsoft Windows [版本 10.0.22621.1]
