### ISSUE TITLE
The resource […] was preloaded using link preload but not used

### ISSUE THREAD

**Issue by Ryongyon** [remix-run/remix#4257] opened 2022-09-22 09:02 UTC
### What version of Remix are you using?

1.7.2

#### report
[https://github.com/Ryongyon/remix-bug-report](https://github.com/Ryongyon/remix-bug-report "https://github.com/Ryongyon/remix-bug-report")

[![](https://github.com/Ryongyon/remix-bug-report/blob/master/20220922_163409.gif?raw=true)](https://github.com/Ryongyon/remix-bug-report/blob/master/20220922_163409.gif?raw=true)

### Expected Behavior

-

### Actual Behavior

When I click a Link component repeatedly, I notice a warning on the console：
**The resource http://localhost:3000/build/_assets/style-N6AVNUHW.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.**

Strangely, the prefetch attribute is not set on my Link component
I created a minimal example and recorded a GIF to demonstrate the problem

**Comment by Ryongyon** [comment] 2022-09-22 09:04
![](https://camo.githubusercontent.com/d3b6b763e176d3f7376a45fa3f6f5cc19372e7e588fe716c966172f4955f547e/68747470733a2f2f73312e3332383838382e78797a2f323032322f30392f32322f4936724f552e706e67)

I found the same problem with the official sample template. I can get a warning just by clicking the LOGO link

**Comment by Ryongyon** [comment] 2022-09-22 10:51
I found that the problem seems to be related to defining global styles in root.tsx file

**Comment by Ryongyon** [comment] 2022-09-22 11:08
> I found that the problem seems to be related to defining global styles in root.tsx file

When I enter the page I get the network request：
![](https://s1.plumeta.com/i/2022/09/22/vhbeyv.png)

when i click the link jumps to `/a`：
![](https://s1.plumeta.com/i/2022/09/22/vhbavr.png)

`/a` seems to be trying to repeatedly load the global style file

**Comment by Ryongyon** [comment] 2022-09-22 13:57
New clue, I found that when I re-execute `remix dev` command, everything works fine and the warning no longer appears on the website redirect route. However, if the browser is hard refreshed once at this time, the bug will reappear, and a warning will appear every time the website performs a routing jump.

[![](https://github.com/Ryongyon/remix-bug-report/blob/master/20220922_215319.gif?raw=true)](https://github.com/Ryongyon/remix-bug-report/blob/master/20220922_215319.gif?raw=true)

**Comment by jkohlin** [comment] 2022-10-27 16:26
Same here.
I get the same warning for all css files loaded in root.jsx when I click a Link

**Comment by TenkoSpirit** [comment] 2022-10-28 15:51
Yep, happens for me as well.

**Comment by JorisDouvenIlionx** [comment] 2022-12-02 08:40
I am experiencing this too, styles are loaded in `root.tsx` and I see this warning when using a `<Form method="get">` to change URL search params.

**Comment by Ryongyon** [comment] 2022-12-05 14:04
Up to now, the version has been updated to 1.8. The problem is still not fixed, and no official has replied to this

**Comment by KSVarun** [comment] 2022-12-29 10:45
I was facing the same issue, but the problem was with my code. I was importing the same styles in different routes. 
Fixed it by importing the default styles in root.tsx

**Comment by brophdawg11** [comment] 2023-07-06 18:37
I believe this is the same root cause as https://github.com/remix-run/remix/issues/5448 and should also be fixed by #6679 in the next release.

**Closed by brophdawg11** 2023-07-06 18:37 UTC
Labels: feat:routing, bug:unverified, package:css-bundle

**Comment by dkkazmierczak** [comment] 2024-04-15 12:15
This has helped me personally (adding "as: 'style'"):
`{ rel: 'stylesheet', href: GlobalStyle, **as: 'style'** },`

**Comment by vicasas** [comment] 2025-02-12 01:25
I have the same problem here, but with a different file.

> The resource http://localhost:3000/next.svg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally.

<img width="907" alt="Image" src="https://github.com/user-attachments/assets/29cd3279-a940-4941-aee6-cbbacfbb9adf" />
