### ISSUE TITLE
aws error

### ISSUE THREAD

**Issue by emyot** [remix-run/remix#7962] opened 2023-11-10 12:01 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
7:56:00 PM [vite] page reload app/routes/_public.user-cv.tsx
X [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │ ...= require('mock-aws-s3'); 
         ╵              ~~~~~~~~~~~~~   

  You can mark the path "mock-aws-s3"   
  as external to exclude it from the    
  bundle, which will remove this error. 
  You can also surround this "require"  
  call with a try/catch block to handle 
  this failure at run-time instead of   
  bundle-time.

X [ERROR] Could not resolve "nock"      

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │ ... nock = require('nock');
          ╵                    ~~~~~~  

  You can mark the path "nock" as      
  external to exclude it from the      
  bundle, which will remove this error.
  You can also surround this "require" 
  call with a try/catch block to handle
  this failure at run-time instead of  
  bundle-time.
```

### Expected Behavior

I'm a rookie, I don't understand this.

### Actual Behavior

Displaying error during npm run dev

**Comment by pcattori** [comment] 2023-11-15 01:32
@emyot can you share a reproduction? ideally a link to a github repo with this issue (or even better, a stackblitz link), but even a description of the steps you took to arrive at this error would be useful. For example, which template/stack are you using?

**Comment by emyot** [comment] 2023-11-15 03:11
Hi pedro, this is the repo: https://github.com/emyot/remix-v2-testapp.git. I don't know if you can view it since I set it to private. If yes, go ahead and look around at app/components/util/s3.server.ts and app/routes/_public.add.tsx, app/routes/_public.user-cv.tsx.
Thanks.

**Comment by pcattori** [comment] 2024-01-14 14:14
@emyot the repo you shared is private so I cannot access it. Can't find a way to reproduce this, so closing this issue, but happy to reopen if you are able to share a public reproduction

**Closed by pcattori** 2024-01-14 14:14 UTC
Labels: bug:unverified, vite

**Comment by VityaSchel** [comment] 2024-01-22 21:26
Just got the same error

**Comment by VityaSchel** [comment] 2024-01-22 21:28
Turns out it's issue with bcrypt
See here https://github.com/mapbox/node-pre-gyp/issues/661

**Comment by jansedlon** [comment] 2024-01-23 05:59
Also happens with argon2

**Comment by VityaSchel** [comment] 2024-01-23 10:01
> Also happens with argon2

Yes I initially used argon2 and then tried switching to bcrypt
I ended up going with node's native scrypt implementation

**Comment by VityaSchel** [comment] 2024-01-23 10:02
But if you going to use scrypt from crypto, make sure to test parameters. Also you need to generate salt and store it yourself
I decided to go with cost factor (N parameter) equal to 4096, salt 16 bits, 100 rounds (loops of hashing) and 32bit resulted hash
on my mac m1 it takes about 1 second which is a pretty good result
but you should write implementation that takes into account information about hardware to decide N cost and rounds number and store that with hash like argon2 does
