### ISSUE TITLE
Splat Route doesn't handle root index path.

### ISSUE THREAD

**Issue by rossipedia** [remix-run/remix#5841] opened 2023-03-18 02:48 UTC
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix@latest`
2. Rename `app/routes/index.tsx` to `app/routes/$.tsx`
3. `npm run dev`
4. Open http://localhost:3000/

### Expected Behavior

The default index route displays.

### Actual Behavior

Nothing is shown.

See the behavior [here](https://stackblitz.com/edit/remix-run-remix-ch5vc2?file=app/routes/$.tsx)

**Comment by akamfoad** [comment] 2023-03-18 17:38
That is the intended behavior, [**Index Routes**](https://remix.run/docs/en/1.14.3/guides/routing#md-index-routes) routes are a bit special, they share the same URL as their parent route and they render inside the `<Outlet />` that is rendered inside their parent route. 

On the other hand, [**Splat Routes**](https://remix.run/docs/en/1.14.3/guides/routing#md-splats) are last resort for Remix to match if nothing else matches. Remix (React Router really) uses an algorithm that gives each route a rank, routes that rank higher will be given priority to handle a URL.

When route X renders a `<Outlet />` component, Remix will rank the routes nested under route X to find a match for a given URL. Let's say X is the root route.

1. When the URL is the `/`, remix will render the Root route, and for the `<Outlet />` it'll check if the root route has a nested route that is marked as `index` if so it'll render it, otherwise it doesn't render anything on the outlet.
2. If the URL has something after the `/` for example `/games`, Remix will try to find a nested route that matches `games` if there is, it'll render it, otherwise:
3. it'll check for a nested dynamic route, if there is, it'll render that route and pass the `game` string as a parameter, for example `$param.tsx` will get `param=games`, otherwise:
4. If there is no index, and no dynamic route and the URL is not same as parent route's URL, then it'll render the splat route, because splat route as I said, is the last resort, my understanding is, its lowest ranked primitive in React Router (and Remix) router matching algorithm.

See this example, I tried to demonstrate how index and splat are matched https://stackblitz.com/edit/remix-issue-5841

**Comment by rossipedia** [comment] 2023-03-19 00:19
@akamfoad I [was asked to open this issue](https://discord.com/channels/770287896669978684/770287896669978687/1086096713095315488) by a Remix team member, as this behavior doesn't match React Router's handling of the `*` path parameter :)

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/96213/226146891-cf0413fa-1f8f-488f-ad23-ed9cfbaeb91a.png">

**Comment by akamfoad** [comment] 2023-03-19 06:34
@rossipedia I see, I wasn't aware of that.

**Closed** 2023-04-24 21:01 UTC
Labels: bug, awaiting release

**Comment by ryanflorence** [comment] 2023-04-27 20:01
I think we goofed by calling this an issue. I misunderstood in discord that the bug was "splat routes don't work unless a sibling index route is also defined".

But rather, this issue is asking "why doesn't the splat route match the parent URL like an index route?"

In current react router semantics:

- index routes match the parent route
- splat routes match anything *deeper* than the parent route

Given that, I would not expect the remix splat route to match `/`.

In React router, `/` will not match the `*` route:

```jsx
<Route path="/" element={<Root />}>
  <Route path="*" element={<Splat />} />
</Route>
```

You create that router tree in remix with these files:

```jsx
root.tsx
routes/$.tsx
```

If you want the same handling for all routes, you'll need to also have a sibling index route by the splat route to match the parent route.

```jsx
root.tsx
routes/_index.tsx
routes/$.tsx
```

We discussed internally what would happen if we change the root route to be a pathless route:

```tsx
<Route element={<Root />}>
  <Route path="*" element={<Splat />} />
</Route>
```

But this now causes `/` to be a 404, which is very unexpected and also a breaking change for Remix.

There are times where I'd personally like my root.tsx to be able to handle all paths, or have a splat route handle everything that's not defined otherwise (including `/`), but for now you'll just need both an index and splat.

A couple deeper questions:

- should splat routes be able to match their parent path the way index routes do?
- how could we allow Remix to not force the root.tsx file and allow configurations like:

   ```jsx
   <Route path="*" element={<Root />} />

   // or siblings
   <>
     <Route path="/" element={<Root />}>{children}</Route>
     <Route path="*" element={<RootSplat />} />
   </>
   ```

**Comment by brophdawg11** [comment] 2023-04-27 20:02
This change was reverted in #6222

**Comment by jlengstorf** [comment] 2023-04-27 20:21
fwiw I've worked on several apps (including a demo I'm building right now) where everything is intended to happen through a single route

e.g. the `/` route is a default state, and sub-routes are filters, etc. that display a subset of the dataset using the same components (e.g. `/category/burgers`)

it was surprising to me that there was no way to define a "everything goes through here" file

maybe this could be a special opt-in format? `routes/_$.tsx` or something to indicate that it's a catch-all route inclusive of the index?

**Comment by jlengstorf** [comment] 2023-04-27 20:24
for future googlers, this was my workaround, assuming you've got a file structure like this:

```
routes/
  - _index.tsx
  - $.tsx
```

set up `routes/_index.tsx` to do all the logic, and in your `$.tsx` just export all the index pieces, such as:

```tsx
import RouteComponent from './_index';

export { loader } from './_index';

export default RouteComponent;
```

**Comment by brophdawg11** [comment] 2023-04-27 20:32
With `remix.config.js` `routes` you get to do whatever you want!  You can even tag the same file to multiple paths with a unique ID.  So for the "everything" use case, delete your `routes/` dir, stick an `everything.tsx` route file next to `root.tsx`, then add this to your remix config:

```js
  routes: async (defineRoutes) => {
    return defineRoutes((route) => {
      route("/", "everything.tsx", { id: "index" });
      route("*", "everything.tsx", { id: "splat" });
    });
  },
```

**Comment by jlengstorf** [comment] 2023-04-27 20:34
> With `remix.config.js` `routes` you get to do whatever you want!

oh dang! what version did that land in? I'll update my demo

**Comment by brophdawg11** [comment] 2023-04-27 20:39
[`routes`](https://remix.run/docs/en/1.15.0/file-conventions/remix-config#routes) has been there since the beginning (no file convention is going to make everyone happy 😉 ) - but the ability to add a specific ID allowing you to point multiple paths to the same file came in [1.9.0](https://github.com/remix-run/remix/blob/remix%401.9.0/packages/remix-dev/CHANGELOG.md#190)

**Comment by ryanflorence** [comment] 2023-04-27 20:40
v0.1.0, file system routes are whack.
