### ISSUE TITLE
Cloudflare worker: Buffer is not defined

### ISSUE THREAD

**Issue by matrixersp** [remix-run/remix#7223] opened 2023-08-22 09:52 UTC
### What version of Remix are you using?

1.19.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Create a new Remix project using npx create-remix@latest
2. Add the necessary MUI and Cloudflare dependencies and configurations
3. run the app `npm run dev`

repository: https://github.com/matrixersp/remix-with-mui

### Expected Behavior

Should run the Remix app successfully

### Actual Behavior

I get the following error:

```
service core:user:worker: Uncaught ReferenceError: Buffer is not defined
  at regd1tya9jj.js:21735:58 in node_modules/html-tokenize/node_modules/buffer-from/index.js
  at regd1tya9jj.js:82:50
  at regd1tya9jj.js:23774:22 in node_modules/html-tokenize/index.js
  at regd1tya9jj.js:25708:49 in node_modules/@emotion/server/create-instance/dist/emotion-server-create-instance.cjs.dev.js
  at regd1tya9jj.js:82:50
  at regd1tya9jj.js:25810:22 in node_modules/@emotion/server/create-instance/dist/emotion-server-create-instance.cjs.js

  at regd1tya9jj.js:82:50

✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by markdalgleish** [comment] 2023-08-23 00:18
Closing as a duplicate of #2813.

**Closed by markdalgleish** 2023-08-23 00:18 UTC
Labels: adapter:cloudflare-workers, bug:unverified

**Comment by matrixersp** [comment] 2023-08-23 08:27
> @matrixersp Did you add the `nodejs_compat` flag to your `wrangler.toml` file? https://developers.cloudflare.com/workers/runtime-apis/nodejs/buffer
> 
> Another solution would be to import from `node:buffer` instead of just `buffer`

Yes I added `nodejs_compat` mode to `wrangler.toml`, and tried other solutions as well, but neither worked for me

I'm not using node module's buffer in my code, `@emotion/server/create-instance` is using `buffer`
