### ISSUE TITLE
V2 Bug: New `JsonifyObject` type causing union type issues with Typescript

### ISSUE THREAD

**Issue by AjaniBilby** [remix-run/remix#7599] opened 2023-10-06 03:32 UTC
### What version of Remix are you using?

2.0.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

If you have a `loader` or `action` function which can return different object structures the new `JsonifyObject` abstraction type appears to not be properly understood by typescript meaning the code below cannot compile let alone run, even though it was valid in `1.19.*` - and theoretically should be valid code.

`app/routes/test.tsx`
```tsx
import type { ActionFunctionArgs } from "@remix-run/node";
import { useActionData } from "@remix-run/react";
import { json } from "@remix-run/node";

export async function action (args: ActionFunctionArgs) {
	const formData = await args.request.formData();
	const action = formData.get("action")?.toString() || "";

	switch (action) {
		case "a": return json({a: true});
		case "b": return json({b: true});
		default: throw new Response("Unexpected form action", {
			statusText: "Bad request",
			status: 400
		});
	}
};

export default function Index() {
	const actionData = useActionData<typeof action>();
	if (actionData?.a) console.log("It was a");
	if (actionData?.b) console.log("It was B");

	return <div>Hi</div>;
}
```

### Expected Behavior

Typescript should correctly identify the type as effectively
```tsx
const actionData: { a: boolean } | { b: boolean } | undefined;
```
And it indeeed identifying the type to be something close to this:
```tsx
const actionData: JsonifyObject<{
    a: boolean;
}> | JsonifyObject<{
    b: boolean;
}> | undefined
```

### Actual Behavior

```
Line 20: Property 'a' does not exist on type 'JsonifyObject<{ a: boolean; }> | JsonifyObject<{ b: boolean; }>'.
  Property 'a' does not exist on type 'JsonifyObject<{ b: boolean; }>'.ts(2339)

Line 21: Property 'b' does not exist on type 'JsonifyObject<{ a: boolean; }> | JsonifyObject<{ b: boolean; }>'.
  Property 'b' does not exist on type 'JsonifyObject<{ a: boolean; }>'.ts(2339
```

**Comment by AjaniBilby** [comment] 2023-10-06 03:33
For now I'm just slapping `any` everywhere, and then `as`ing into the real types when I used any value from an `actionData` or `loaderData`, but this is creating a lot of bloat syntax and isn't really safe, and defeats the entire point of having a template on those functions.

**Comment by AjaniBilby** [comment] 2023-10-06 04:11
I made a [fork](https://github.com/AjaniBilby/blues-stack/tree/union-type-test) of the [blue-stacks](https://github.com/remix-run/blues-stack) template to ensure it's not something odd about my specific configuration, and it still occurs.

Interestingly there is no error during the `npm run build` process, not when actually loading the page, instead the errors only occurs during `tsc` and in my editor's `lsp`... Which is kind of a problem as I use `tsc` as a CI step to validation of the project before further steps...

**Comment by kiliman** [comment] 2023-10-06 13:08
> Interestingly there is no error during the `npm run build` process, not when actually loading the page, 

`esbuild` _understands_ TypeScript syntax, but does **not** do typechecking.

BTW: I wrote `remix-typedjson` precisely because of this issue. My package includes metadata about the types so your `userLoaderData` gets the actual TS type, and not the `JsonifyObject` wrapper type.

**Comment by grinkus-adapt** [comment] 2023-10-06 13:39
Duplicate of https://github.com/remix-run/remix/issues/7246

**Comment by pcattori** [comment] 2023-10-10 14:03
This is how [Typescript works with non-discriminated unions](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAKwM4IDwBUB8AKAEwEMoiAuRLASgq0QG8AoRRAJwFMoRWljTGAvo0bsAHgAc4rKIiKoAnpEShIsBLOjwweKg2aIANp0QQEBGGqQBeRAFkSACwB0rImAJwAtjsQ5EABicAVkQAfkQAciIIxAoIgCMI4QBIVAB3CwgHRDxTdwstXSZk5Ig5dkQAIiJKig4uHhR0bXpyRChWEHYBKgBuRhKy1ArK+Nq2Tm4kNAQ8eniKDq6e-pKCdmAiEAMoRYdWODTEMHYjgCV2VEkwYbxKgFUTiXZodgJlKU8NS0qAGj0SqlSFxUFgxLsqgAhIjvDgARy6qCgfwGJSRJBAqAoABZ-P5USsBkIBP1GEYZERNAgACIkIiIGxENJECzfLQ6Rh5dBGJwGOAAczwlMstNIoScRConIQ3PYvIFQqpYFFRHF8SoQA), and not a Remix bug.

If you want to narrow the type, you'll need to [use a discriminated field in your union](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAKwM4IDwBUB8AKAEwEMoiAuRLASgq0QG8AoRRAJwFMoRWljTGAvo0bsAHgAc4rKIiKoAnpEShIsBLOjwweKg2aIANp0QQEBGGqQBeRAFkSACwB0rImAJwAtjsQ5EABicAVkQAfkQAciIIxAoIgCMI4QBIVAB3CwgHRDxTdwstXSZk5Ig5dkQAIiJKig4uHhR0bXp4gyIHMiiIgBpZCihWEHYBWVQTBFQoKgBuRhKy1ArK+Nq2Tm4kNAQ8VvbOyMS++IGhkbGJsCnZ+eSCdmAiEAMoAYdWODTEMHYvgCV2KhJFd2HhKgBVH4SdjQdgEZRSTwaSyVPrFEpTEggVBYMSvKoAISI8I4AEdhlNUbdUqQuKgKAAWfz+W4CG7JIQCOaMIwyIiaBAAERIREQNiIaSIFmRWh0jAA9PLLugjE4DHAAOZ4fmWYWkUJOIhUBVKvIq9hqzXagVgPVEA3xY2MGDAa26kVONodMVWGzdXRmuCq9VanVaO2G40ut3hj1e7K+v2JAOTIMWkMxoVxqhAA)

**Closed by pcattori** 2023-10-10 14:03 UTC
Labels: bug:unverified

**Comment by AjaniBilby** [comment] 2023-10-10 23:09
I agree that it's probably a Typescript weirdness issue, but this worked before 2.0, and then updating to 2.0 broke all of my type-checking, and this wasn't even listed as a potential pain point like the changes to file routing, meta functions and the like.

I feel like this change really should have been outlined in the [upgrading to v2](https://remix.run/docs/en/main/start/v2)

Reading #7246 it looks like there is a patch in the works which changes the type information to Typescript can infer the union type correct, am I understanding this correctly? If so I'll live with the pain of `any` everywhere until the patch is finally mainstream.

**Comment by pcattori** [comment] 2023-10-11 02:35
@AjaniBilby unless you were returning plain objects (i.e. without wrapping them in `json(...)`), then the behavior should be the same in v1 as in v2. But if you have a working version of it that uses `json(...)` in v1, I'd love to see it to make sure I'm understanding correctly.

#7246 is about fixing a Remix/`type-fest` bug and is unrelated to accessing properties in a non-discriminated union.

**Comment by AjaniBilby** [comment] 2023-10-11 03:23
There's a whole lot of odd behaviour I'm not able to replicate in a small independent repo I can share, and I don't quite understand why...  
Like:
```ts
type UserList = {
    id: number;
    name: string;
    csv: string;
    visibility: $Enums.VisibilityType;
    ownerID: string;
    createdAt: Date;
    updatedAt: Date;
}; // generated by prisma
const data: JsonifyObject<{
    lists: {
        id: number;
        name: string;
        csv: string;
        visibility: $Enums.VisibilityType;
        ownerID: string;
        createdAt: Date;
        updatedAt: Date;
    }[];
}> // generated my remix.js
const lists = data?.lists as (null | UserList[]);
```
```
Conversion of type 'JsonifyObject<{ id: number; createdAt: Date; updatedAt: Date; name: string; visibility: VisibilityType; csv: string; ownerID: string; }>[]' to type '{ id: number; name: string; csv: string; visibility: VisibilityType; ownerID: string; createdAt: Date; updatedAt: Date; }[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'JsonifyObject<{ id: number; createdAt: Date; updatedAt: Date; name: string; visibility: VisibilityType; csv: string; ownerID: string; }>' is not comparable to type '{ id: number; name: string; csv: string; visibility: VisibilityType; ownerID: string; createdAt: Date; updatedAt: Date; }'.
    Types of property 'id' are incompatible.
      Type 'null' is not comparable to type 'number'.ts(2352)
```
Typescript clearly knows both `.id` properties are a `number` type, but they're still marked as `incompatible`.

**Comment by AjaniBilby** [comment] 2023-10-11 03:47
Also the update to have Jsonify take over as the type of all child objects of a Jsonify object is quite annoying. Because it then means any child object is defined as possibly being null, when actually it's often not.

*i.e. here `dictionaryRef` is actually a `1:m` include from prisma, so they're not null...*
![image](https://github.com/remix-run/remix/assets/11359344/ad90611d-9a94-4e26-843f-90d94ab19de2)  
![image](https://github.com/remix-run/remix/assets/11359344/fd173ee0-b427-4cac-95da-8c70cf5913d9)  
![image](https://github.com/remix-run/remix/assets/11359344/0d74f73a-552a-45d2-bf6e-e2984a561d44)  
`.dictionary.` clearly should not be null

**Comment by pcattori** [comment] 2023-10-11 04:31
Can you share a reproduction in a Typescript playground? For example, trying to replicate your `UserList` example, but the [types are correct for me in this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFYGcIDsC+cBmUIhwDkAAlAKYjAAeAtFAK7oD06EAJuUQFCiSyI4DFOQAyEAIacoAEQkwJ2PAWJlKNek2YUJAYxg9uMAJ5hycAKoioo4CngBeRNziu4wdgC446BiABG5FAA3C5u6BIg5N72UMDoAOahbnC6KABuMTBxicluzMxw6XbA-sAANsAm3gAkAKK+ICgAdABqJWWVJgAqpuR5rhAA7uhBAJIyWTlJYa66OjDk7ACCMN5yiwNCYOzyS6vre6GYodzk1Pzwuhj2cOWS0nBOABQAlE8AfM4AkOXk8MIgpV7N4rEFbLcnAhsBIUHAJOhjNxvhQYAwoOg4KgMM8EEJrMD4JhXtxMNwzhdoPBODgJAxyvAcEx9MAMHAAMIESCjdAwN4-P7wBCAqCE7BOQHiKRBDYSAA8JjMEBwdweQQ+b2RIsJzQ8yIKKTcAD0APzI67oNB-Zr3BLPbV2GAkzBAA).

**Comment by alexanderMontague** [comment] 2023-10-11 22:37
@pcattori I think I've replicated it with `action` as I'm also having an issue with this after upgrading to v2. There were no type errors before upgrading (and I've also tested with the nightly build just released to fix https://github.com/remix-run/remix/issues/7599#:~:text=I%27m%20understanding%20correctly.-,%237246,-is%20about%20fixing). Is this to do with my mix of `redirect` and `json` now? The blues template also does this I believe 

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFYGcIDsA0coFMAmweAxjAL5wBmUEIcA5AAJ4jAAeAtFAK7oD06CPlz0AUKEixEcbilwAZCAENhUACJKYS7LNwBBUsAwatFarQbNcrTj354lpMaJgBPMLjgBVOVHnAUeABeRFE4cLhgfAAuOHRuEAAjXCgAbjCI9CUQXFjAqGB0AHN0iLhiFAA3PJgC4tKIvj44SoDgROAAG2A3WIASAFF4kBQAOgA1No7utwAVd1wG8IgAd3QUgEk1GrqSjPDiBxgCPRhYk0X9mTB8TROzuAv0snTRXDZJeGIMQLhO5VUcBCAAoAJRAgB8oQAkJ1cPBdFBuoFYj4Uv5fiEEBQlCg4Ep0K5RNC8DBuFB0HBUBhgQgZL5kfAyKDRGRRG8PtAvj94I4YEZKSDwUEoQhiXCEQyAg80X5pUDEDi8QSiWVvuhfsMFQBZTQAC1GlH+0GBupgBqgBPwtDBcAAVHAAIwABnBAGoneyysBKMCtUEA07wWKymVSeTKdT0LS0DlzYUirFatxcMyrmyrj6-QkgYGAEzBq5lc00FY4AhEXCkYH0PiUCAQegssoZ72+-2BgDMhdDEXDFKpaGjCBSNCgsQARIklFAJ2mW+ySfCI4OaXTEYy4GmM+9PnBhJQlNxOvBKLxDBg4ABhWiQdboGC2sWw+H4i-oExKBW6Az84yaJQAB43A8CBKDfP90AhMErnVNA4VGf4imBPkBU-AB+UYN2lFloTgiAEKQlD3ww0ZY3hPUE2bCJ8MIiBkNQ-8tEw0doHBJo4AABRoDxYFcBhWKgeh9wgXA8UEeB3nlS8QM8egACkhx9VwAHlEiQKsYFZIA)

<img width="1055" alt="image" src="https://github.com/remix-run/remix/assets/29992628/c4876c79-2a52-483f-b2d3-20b34faad3d0">

**Comment by pcattori** [comment] 2023-10-11 23:31
@alexanderMontague here's a [reproduction of issue without any Remix code](https://www.typescriptlang.org/play?#code/DYUwLgBAlgJhC8EA8AVANAPgBQA8BcEKAlASghhDgFBVgCeADiBAKoDOIATgDJRuSIA3lQijoMAgDsArgFsARlwDcIsZICGskAX6cokgOYqxEAMZsAbjrB7DxsQHoHEC3yjyowKPQIASAKIysmwAdABqbh5e9CiMIPaiAPYA7pJcAJIAIta2Rqqippwg6mAgMACCYASZJfH5ENIMMLUVVRA1pSoAvipUIDgMiZyQpomS-BDAieowXAgQWETkEMIAkKCQ0hycXvwE7Fy8E0JdEOpsZ5J0VKtFYNKckuJYgg3bu5BdRFRdNP2DwzMYwm6lMYCgY3mi2Waw2by4H322yOAhWp3Ol2uJlG40gQXmAFkSgALEIAMymQywRLApM46kkMESsmhACoIABGAAMSwA1JyaCYoGSsPj4OLOUthCYTHcHk9YC82MzwMT9AYCDZpCAvvVfvVhaK5AgJQAmKX1Ey0zgpZ4AcgcZMSiTt3xM+qFIrFEoAzBaZWI5Y9noIuDbOAQAETydScSO6900W7geUh+E7Pifb76-5DSCzMnqaTASBk6SSMEQp4AYWZgzSkjA0Nh4DOlbGHXU81B4LGi3qOOVoBCUwMWB7Vc7AH4QlsEZnvqtB4lh6Px+3JNOQsqtLT1W6xMvV4kxxOOyV1DOw0Mlk4IAAFG1MYZ0CB26+cO0QJkgC6SRKQP0mYQJC9BMG+ABSyqSMKdAAPLyAAViAYI-EAA). Its a consequence of how Typescript works and is not something fixable by Remix.

For more in depth explanation of TS behavior see: https://twitter.com/pcattori/status/1598359344827056131

**Comment by alexanderMontague** [comment] 2023-10-11 23:59
Ahh wow... thank you for the example. Thats too bad, I wonder why things changed once updating to v2... maybe I bumped ts too. Appreciate the explanation!

**Comment by alexanderMontague** [comment] 2023-10-12 01:09
For what its also worth, I've managed to provide typing similar to what was possible before in case anyone comes across this and does now want to type narrow. It didn't really make sense for me to type narrow in every use of the returned loader/action data.

```js
type ActionReturnType = Promise<
  | TypedResponse<{
      errors?: ReturnType<typeof documentValidations>; // value returned from helper function
      success?: boolean;
      bar?: BarType
    }>
  | undefined
>

export async function action({
  request,
  params,
}: ActionFunctionArgs): ActionReturnType {
  // ... formData stuff

  if (_action == "foo") {
    const errors = documentValidations(values);
    if (errors) {
      return json({ errors }, { status: 400 });
    }
  }

  if (_action === "redirect") {
    throw redirect("/bar");
  }

  if (_action === "bar") {
    return json({bar: values.bar});
  }

  if (_action === "baz") {
    return json({success: true});
  }

 // ... etc
}

// ... 

const actionData = useActionData<typeof action>();

console.log(actionData?.errors) // JsonifyObject union, no error
console.log(actionData?.bar) // etc
console.log(actionData?.success)

```

**Comment by AjaniBilby** [comment] 2023-10-12 02:46
I'm beginning to feel like I'm encountering a bug in TS which the previous serialisation happend to not encounter...
![image](https://github.com/remix-run/remix/assets/11359344/d9a8fa83-0dcb-4182-aa44-c31ce7485248)


And I can't seem to replicate it in less complex sandboxes which I could shared ([playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMAyECGATdKAERxhzgF84AzKCEOAIgAEp0RgAPAWimQDsA9GxwBjGIwDcAKFCRYiOACtUEfpRp0GLNhx58h-CASnTpMAJ5h0cAPJQA5nAC8iaQEhgeAFxxUMKGB+BxlPAn4YYGpgQl9-QOC4AB84fmQAG3TQsGQAI3TgUV9ciAh09Bx+UPROMGAoC18SGHRQjFJUXzSQXMJQgDcIURxcgEkiLuQevo88YFQR8p84ErKKqo9RERa8AEEYJtJWj2QwPCO9g7hm44oZaRxUC35RGgFxYDU4AGV6dCIAEIAJXQAEdkOh-AAKACUbk81DgUIAsqQABYAOiglTw9FhcAAfHAAAwYgCccLYMGQUHUaUy93cojU-jg0AclXmpE+-F89icrgQHjCvkYjAANMKvOgIlEYlBRRLhTl8oVfNQcOkMJL3O4anUGl10AB3a5HWE69ztGCdOAARmJxMtg2GYwm9stcwW+XQyw1WvQlq2FR2+yNppuFuFp3Ooau-BNZpasI8FDM7ipNPU7M5C0iahkaek+ug8Eez1e1He+fU6VwBCg+KFTJZ8Bz-C5NZccBwxpwwHgvxA-2BYIh0JhoSiSIAhO3Ozy4TA0XRTQnTSDUJB+BgoYwACzE-cS+FWsjU1AAFRqVwPR6Vuv8pDQvkP+9Tk-TmdpylU-ChzbuPOeY8h+0hFiWCgEBqGTwFWLxdiC-ANk2mytnAsbkK4aBYPWhDNDgAA8ljWBAiJ1vghAErCjLMju8BBAmUDjJM0xQN2mEYsB3JqBiLojOMoTfuoYqFkAA))

**Comment by AjaniBilby** [comment] 2023-10-12 02:49
If I switch to TS 5.0.4 from 5.2.2, then issues go away... This is a TS issue then... 🫡
Thank you for your time

**Comment by kirbysayshi** [comment] 2024-02-28 17:05
In case this helps someone else, I too thought I had a bug with `Jsonify`. But it turned out to be Jsonify accurately representing that `prop: string | undefined` is different than `prop?: string` in terms of the type contract.

The short explanation is that the types accurately represent the following:

```ts
const input = { something: undefined};
const output = JSON.parse(JSON.stringify(input));
console.log('something' in input); // true
console.log('something' in output); // false
```

The longer explanation is in this playground: https://www.typescriptlang.org/play?target=7&module=1&isolatedModules=true&suppressImplicitAnyIndexErrors=true#code/JYWwDg9gTgLgBAbzjAnmApnAUgZwgO2ADMU4BfOIqCEOAIgAEp0RgAPAWigFd8B6HOigA3IV14xQ6PgBNgOGHwBWeQiToBuAFDo2kWIjJatqDHAAKAQwDGAazgBeRFrhxgMgFxwFUYPgDm2q5g1GBYAMoA8gBy0RC2Xj5+-nAAPnC8MuhEfugyQXAhEGFR0ZG2APyJML4B2mTaWkS81pIEcP7oMFZ2ABQAlF64BMQoADw9tgB8zq7MMNxQ+LOubp70bJt0ADQu5PXGzfitwO0yEOE0XQAWyQDqwDDXk71gXpP9K3x8WkZa33AAAbpTLZXIyQFuHBwSxwZgAR24wGYMkKoSEqDgACNuPAAO7AAA2hLg+Ag8CKMm41kwlmW7nQ+EkmOYOG4hPx10ZcBU7V6WU+gl8lkJwAAXnkAHRac6XEA3e6PZ42Wy9TrdFUDfqNawEBRufBgXGORDeK5PZJeUE5fB5CiWaG6-AKbRO-UQXFG+BOCIxSVgSxQQS9X3RSVJAKjXp+L39bVaN0QQnoSWEiD+XoAcjw8otAUzBoNsY0cABNW46ATeqTKbTGez5tu+cLHpgxdLfEoIsEQA
