### ISSUE TITLE
Using pnpm, route content doesn't show

### ISSUE THREAD

**Issue by itsMapleLeaf** [remix-run/remix#147] opened 2021-05-10 04:38 UTC
Reproduction steps:

1. [Install pnpm](https://pnpm.io/installation)
2. Set up a new remix project `pnpm init remix`, say "no" to automatic install
3. Install dependencies: `pnpm install`
4. Run the dev server: `pnpm run dev`

> (technically, only 3. needs to use `pnpm` over `npm`, but consistency 🤷)

This is what shows, just the footer, no route content

![image](https://user-images.githubusercontent.com/19603573/117606352-526e6080-b11f-11eb-8dbf-2cfbdca6bcd4.png)

As suggested with some help from @JNaftali, I tried to change the `"remix"` imports to `"@remix-run/node"` and `"@remix-run/react"` where appropriate, but still ran into the same issue.

I think the solution might be for the `remix` package to declare hard dependencies on the react and node packages

**Comment by tylerbrostrom** [comment] 2021-11-24 21:43
Methinks this be a duplicate of #154.

**Comment by machour** [comment] 2022-03-15 18:02
Tracked in #154

**Closed** 2022-03-17 20:28 UTC
