### ISSUE TITLE
You cannot `useLoaderData` in an errorElement (routeId: root)

### ISSUE THREAD

**Issue by cleytoncarvalho** [remix-run/remix#8951] opened 2024-03-01 00:08 UTC
### Reproduction

- Clone https://github.com/cleytoncarvalho/remix-error/
- Install dependencies, `npm install`
- Run the app, `npm run dev`
- Open http://localhost:5173
- Click the link "Open page with thrown error"

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 65.91 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.asdf/installs/nodejs/20.11.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.11.0/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.22.0 - ~/.asdf/installs/nodejs/20.11.0/bin/pnpm
    bun: 1.0.29 - ~/.asdf/shims/bun
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.8.0 => 2.8.0 
    @remix-run/node: ^2.8.0 => 2.8.0 
    @remix-run/react: ^2.8.0 => 2.8.0 
    @remix-run/serve: ^2.8.0 => 2.8.0 
    vite: ^5.1.0 => 5.1.4
```

### Used Package Manager

npm

### Expected Behavior

Show error in the ErrorBoundary

### Actual Behavior

Page shows "Unexpected Server Error"
Console shows "You cannot `useLoaderData` in an errorElement (routeId: root)"

The error occurs when useLoaderData is used inside Layout export from root.

**Comment by manzano78** [comment] 2024-03-01 05:46
There is a [discussion](https://github.com/remix-run/remix/discussions/8846) which highlights an API lack to correctly use data or error in the new Layout component. It exposes a workaround which could probably help you before an expected cleaner way!

**Comment by brophdawg11** [comment] 2024-03-01 14:40
For now, this is expected behavior and you can use `useRouteLoaderData("root")` to access the root loader data in `Layout`.  The key difference here is that `useLoaderData` is for happy path flows and has a built-in assumption that the loader completed successfully - which is why you cant use it in boundaries because the loader may have thrown and then there wouldn't be any loader data and the typings would be incorrect.

`useRouteLoaderData` is typed with `| undefined` since the route you ask for may or may not be present, so it's safe to use in `Layout` in an error scenario since the types are accurate.

I'm going to close this in favor of the the linked proposal, and if it gets enough traction we can consider adding that API.

**Closed by brophdawg11** 2024-03-01 14:40 UTC
Labels: bug:unverified
